### ISSUE TITLE
Ignore plugin is missing from docs

### ISSUE THREAD

**Issue by glenjamin** [webpack/webpack.js.org#1014]
Webpack v1 docs include a section about [IgnorePlugin](http://webpack.github.io/docs/list-of-plugins.html#ignoreplugin) - although it is a tad cryptic.

There's no equivalent entry in the webpack 2 docs.

It would be good to add this and provide an explanation of what the second argument does that's easier to understand if you aren't familiar with webpack internal terms (or link to an explanation of those terms?).

**Comment by welll** [comment]
@skipjack, does someone need to add thus link at index (`https://github.com/webpack/webpack.js.org/blob/master/content/plugins/index.md), right?

If yes, just create a new `ISSUE` and I could do that.

**Comment by skipjack** [comment]
@welll yea the index is missing a few links/descriptions I think. Feel free to open a a pr and request me as the reviewer. No need to open a new issue...

**Comment by welll** [comment]
@skipjack I couldn't add you as reviewer

https://github.com/webpack/webpack.js.org/pull/1232
