### ISSUE TITLE
Profile Timings Question

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#102]
_From @iliakan on March 25, 2015 18:56_

I compile with `--profile` enabled.

Then `module.profile` stat equals an object like this `{ factory: 19265, dependencies: 166, building: 2288 } }`.

What does it mean? What denotes factory? dependencies? building?

_Copied from original issue: webpack/webpack#915_

**Comment by pksjce** [comment]
_From @sokra on March 25, 2015 21:54_

factory = resolving
building = loaders + parsing
dependencies = time to process dependencies

**Comment by pksjce** [comment]
_From @iliakan on March 25, 2015 21:57_

Can resolving take a lot?

**Comment by pksjce** [comment]
_From @iliakan on March 26, 2015 7:13_

Recently my webpack build became very slow. Like 5 times slower.
I'm trying to discover why.

Resolving paths must be fast, not take 19 seconds.

**Comment by skipjack** [comment]
@bebraw any idea what's involved in this? Maybe we need to add a notes about this in the [CLI profiling section](https://webpack.js.org/api/cli/#profiling) and on the [Module Variables](https://webpack.js.org/api/module-variables) page?

**Comment by bebraw** [comment]
@skipjack Maybe the output has changed since the initial issue. Looks like the timings are more granular now and the page looks good. Let's close this.
