### ISSUE TITLE
404 links in contribute.md

### ISSUE THREAD

**Issue by S-Kaushik** [webpack/webpack.js.org#1030]
Hi, 

The Writers Guide and Development Guide on [this page](https://github.com/webpack/webpack.js.org/blob/master/content/contribute.md) are 404 links.

**Comment by rouzbeh84** [comment]
ah snap, didn't realize this was assigned already. i'll close out #1034

**Comment by skipjack** [comment]
@rouzbeh84 no worries, I'll review your PR shortly. I'm happy to have one less thing to PR today!

**Comment by skipjack** [comment]
Closed by #1035.
