### ISSUE TITLE
Add Left Partner Banner for ag-Grid

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#1033]
* We need to have the attached asset added to the left gutter of the docs page (for desktop). We don't have any plans for mobile yet that provides as eloquent, and so for now we've agreed to not disrupt the delivery of content with the banner on mobile devices. 
* The banner needs to link to https://www.ag-grid.com/?utm_source=webpack&utm_medium=banner&utm_campaign=sponsorship

![banner_ad_vertical 1](https://cloud.githubusercontent.com/assets/3408176/24068202/d3a942e6-0b56-11e7-99d1-0581ce1eff56.png)

@skipjack Pinging you and adding as requested. We are shooting for Monday on this, so if for any reason you don't think you can get to this, that is fine, let me know, and I'll finish any work required for it.

**Comment by skipjack** [comment]
@TheLarkInn starting this now.. so from my understanding we basically want to create fixed ad space in the left gutter that's only displayed on screen sizes large enough to have gutter room. And for now we will just have one hard-coded ad (i.e. the image you displayed above).

I'm going to start it with those as the "reqs" in mind, please correct if I misunderstood anything.
