### ISSUE TITLE
How to make the whole gulp abort when webpack has an error?

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#104]
_From @binarykitchen on February 17, 2015 21:11_

Hello guys

I have the gulp (pseudo)code below. But when an error occurs, i.E. a module couldn't be found due to a wrong path, then the error is shown on gulp BUT the gulp task continues.

What change is required to make the gulp task stop?

Thanks!

```js
var webpackCompiler = webpack({
     ...
  },
  plugins: _.compact([
    ...
});

gulp.task('webpack', function(cb) {
  return webpackCompiler.run(function(err, stats) {
    if (err) {
      throw new gutil.PluginError('webpack', err);
    }
    gutil.log("[webpack]", stats.toString({
      ...
    }));
    return cb();
  });
});
```

_Copied from original issue: webpack/webpack#797_

**Comment by pksjce** [comment]
_From @sirlancelot on February 18, 2015 7:33_

Pass `err` in to `cb`

```javascript
gulp.task('webpack', function(cb) {
  return webpackCompiler.run(function(err, stats) {
    if (err) return cb(err);
    gutil.log("[webpack]", stats.toString({
      ...
    }));
    return cb();
  });
});
```

**Comment by pksjce** [comment]
_From @binarykitchen on February 18, 2015 20:56_

Oh right, thanks man! You might want to add that to the documentation. Because I believe this is better behavior than `throw new gutil.PluginError('webpack', err);`?

**Comment by pksjce** [comment]
_From @jhnns on February 18, 2015 23:58_

Go ahead, the documentation is editable for everyone :)

**Comment by SpaceK33z** [comment]
In #53 usage with Gulp will be documented.
