### ISSUE TITLE
Incorrect comparison guide info for "watch mode"

### ISSUE THREAD

**Issue by veltman** [webpack/webpack.js.org#1049]
The [comparison guide](https://github.com/webpack/webpack.js.org/blob/master/content/guides/comparison.md) says that Rollup doesn't have a watch mode. It does (https://github.com/rollup/rollup-watch).

To mimic the style of the rest of the table (a link to the plugin if it's not built in), I assume that the entries for Browserify and Rollup should read as [watchify](https://github.com/substack/watchify) and [rollup-watch](https://github.com/rollup/rollup-watch) respectively.

**Comment by Aladdin-ADD** [comment]
seems that it is WIP.

**Comment by veltman** [comment]
I guess that's a question for @Rich-Harris, my impression is that it's relatively stable/widely used?

**Comment by Rich-Harris** [comment]
Yeah, it is — we should probably update the README on rollup-watch to reflect that. thanks for the prod
