### ISSUE TITLE
Automatic generated require.ensure() wrapper

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#105]
_From @cowwoc on January 28, 2015 23:52_

Looking at the `require.ensure()` code found at https://github.com/webpack/docs/wiki/code-splitting, is there a tool that will automatically generate a `require.ensure()` wrapper on behalf of the user?

Meaning, given:
```
var a = require("module-a");
var b = require("module-b");
```

the tool would scan for `require()` statements, and generate the following `output.js`:

```
require.ensure(["module-a", "module-b"], function(require) {
    var a = require("module-a");
    var b = require("module-b");
});
```

This way, the end-user codes in terms of simple synchronous `require()` and webpack generates the correct bundles with asynchronous loads under the hood.

_Copied from original issue: webpack/webpack#734_

**Comment by pksjce** [comment]
_From @sirlancelot on January 29, 2015 1:15_

Webpack does it automatically, you can write `require.ensure([], function() { var a = require("module-a") })` and it will work just fine.

**Comment by pksjce** [comment]
_From @cowwoc on January 29, 2015 1:18_

Excellent. Please add this to the documentation (ideally on https://github.com/webpack/docs/wiki/code-splitting).

On a sidenote, is it possible to omit `require.ensure()` altogether and have Webpack add that? In other words, what is the significance of the user adding this code himself/herself? Does it denote something to Webpack?

**Comment by pksjce** [comment]
_From @sirlancelot on January 29, 2015 3:20_

You have to tell webpack where to split the bundle.

**Comment by pksjce** [comment]
_From @cowwoc on January 29, 2015 4:42_

@sirlancelot Okay. Why/when would users want to populate the dependencies array of `require.ensure()` manually (instead of leaving it empty)? Is there a legitimate use-case for doing so?

**Comment by sirlancelot** [comment]
I would imagine pre-populating the `require.ensure` array is for when you have deeply nested/split bundles and you want to tell webpack that certain modules should go in to a certain bundle. You would pre-populate the `require.ensure` array for the same scenarios you would use `require.include`; it just includes it in the bundle without evaluating it.

**Comment by SpaceK33z** [comment]
This would be covered by #3.
