### ISSUE TITLE
Links to examples in menu tree show up as "Example example example"

### ISSUE THREAD

**Issue by dmitriid** [webpack/webpack.js.org#1063]
A picture is worth a thousand words. Found here: https://webpack.js.org/plugins/commons-chunk-plugin/#examples

![](http://dmitriid.com/i/gm2tonbrgm4tinrv.png)

Perhaps something to look out for in #1039

**Comment by skipjack** [comment]
Ah that is bizarre, and it extends the list as you scroll. I'll look into this as soon as I can... assigning to myself but anyone would be welcome to pick it up before me.

**Comment by skipjack** [comment]
#1064 fixed this issue, should be live soon.
