### ISSUE TITLE
Webpack (and docs site) should not accept plugins/loaders without proper docs

### ISSUE THREAD

**Issue by dmitriid** [webpack/webpack.js.org#1076]
Prompted by this tweet: https://twitter.com/kevsmith/status/849062446836985859

----

[dynamic-css-loader](https://webpack.js.org/loaders/dynamic-css-loader/)

> ## Usage
> ### Lorem
> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

----

[bundle-loader](https://webpack.js.org/loaders/bundle-loader/) and [transform-loader](https://webpack.js.org/loaders/transform-loader/)

Usage links to v1 loader usage docs _and_ doesn't explain what it is and what it does. (What's a "typical" brfs example in transform loader?)

----

[coffee-redux-loader](https://webpack.js.org/loaders/coffee-redux-loader/)

No docs (what it does? why?)

----

[exports-loader](https://webpack.js.org/loaders/exports-loader/)

No docs (what it does? why?)

----

and so on and so forth. For many other loaders you can somewhat guess what they do from examples/configs.

**Comment by simon04** [comment]
The plugin/loader docs are 1:1 copies of their READMEs.  The dynamic-css-loader README has been changed in the meantime. For other loaders please PR on their repositories.

**Comment by dmitriid** [comment]
@simon04

You misundersrood the point/purpose of this issue. By including plugins and their documentation on webpack.js.org webpack says: "Hi, world. We officially endorse these plugins and we want you to use them"

- Why are these plugins there?
- Why are they even listed in webpack docs?
- _Shouldn't webpack enforce doc quality before blindly including every plugin in existence?_

Yes, I could definitely rigt PRs for every single plugin ... if I had a single idea what ecen half of them are and what they do. This wouldn't help with some new plugin dumping a Lorem Ipsum into a README and webpack happily including it.

**Comment by dmitriid** [comment]
Oh right. "Dynamic CSS loader readme changed in the meantime" by remaining as bad as it was before. Just so you know

**Comment by simon04** [comment]
We only include projects from `webpack/`, `webpack-contrib/` and a few manually selected others (such as babel-loader).

I got your idea, but neither is the proposal of this ticket's summary realizable (in the scope of webpack.js.org) nor the universal statement "document everything" help to reach that goal.

We're all here to improve things (in the spare time), and going through, commenting, closing issues is one part of it. Thanks.

**Comment by dmitriid** [comment]
This ticket is easily realised: do not accept things to `webpack/` and `webpack-contrib` unless they are properly documented. Where "properly documented" is:

- The goal of the plugin is clearly stated
- Installation steps are provided
- The usage is clearly described
- Options are documented
- There is at least one example

These four steps can be easily deduced at a glance. It took me less than two minutes to discover the problems.

It really is as easy as that. "Lorem ipsum" in Readme? Decline. Empty README? Decline.

>  the universal statement "document everything" help to reach that goal.

So your proposal is:

- document nothing
- blindly include everything that gets into webpack

Something tells me my proposal is orders of magnitude better
