### ISSUE TITLE
More Clarity In Docs Needed on Limitations of Dynamic Imports in Webpack 2

### ISSUE THREAD

**Issue by bdwain** [webpack/webpack.js.org#1083]
[This page in the docs](https://webpack.js.org/guides/code-splitting-import/) only has a quick sentence about how import statements cannot be "fully" dynamic, but can be partly.

>  Keep in mind that import() path cannot be fully dynamic (e.g., import(Math.random())). Rather either completely static (e.g., import('./locale/de.json')) or partially static (e.g., import('./locale/' + language + '.json')).

Ideally the docs would provide details on when and how variable names can be used in import statements.  For example, something like this doesn't work.

```js
export function foo(deps){
  deps.forEach(dep => import(dep).then(doSomething))
}
//usage:
foo(['bar', 'baz']);
```

but this does (according to the docs at least)

```js
import('./locale/' + language + '.json')).
```

it would be helpful if there was more detail about when dynamic import paths are allowed and what parts of them can be dynamic (it seems like the beginning needs to be static?). 

Thanks for the help! I appreciate all of the work you all do on this.

**Comment by bdwain** [comment]
also i'm happy to make the pr to the docs. i just need the questions answered before I can do it. Thanks!

**Comment by simon04** [comment]
The relevant source code is: https://github.com/webpack/webpack/blob/master/lib/dependencies/ContextDependencyHelpers.js

In a PR, please replace `Math.random()` with a more practical code sample.
