### ISSUE TITLE
Building for production guide error

### ISSUE THREAD

**Issue by maasha** [webpack/webpack.js.org#1100]
I am following the guide: https://webpack.js.org/guides/production-build/

The

```
function buildConfig (env) {
  return require('./config/' + env + '.js')(env)
}

module.exports = buildConfig
```

Results in

```
/Users/maasha/install/src/rpncalc/webpack.config.js:2
  return require('./config/' + env + '.js')(env)
                                           ^

TypeError: require(...) is not a function
    at buildConfig (/Users/maasha/install/src/rpncalc/webpack.config.js:2:44)
    at requireConfig (/Users/maasha/install/src/rpncalc/node_modules/webpack/bin/convert-argv.js:102:15)
    at /Users/maasha/install/src/rpncalc/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
    at module.exports (/Users/maasha/install/src/rpncalc/node_modules/webpack/bin/convert-argv.js:107:15)
    at Object.<anonymous> (/Users/maasha/install/src/rpncalc/node_modules/webpack/bin/webpack.js:153:40)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by skipjack** [comment]
Are you passing `--env=dev` and `--env=prod`? Can you log out the what's returned from `require('./config/' + env + './js')`? The guide is expecting this will resolve correctly will return a function in both cases.

That said, I think this guide needs some work and could probably be simplified a bit. For example, the `env` parameter is never used in `dev.js` or `prod.js`.

**Comment by skipjack** [comment]
@bebraw @simon04 do we have example/boilerplate repos backing any of these guides? Maybe something we should try out or encourage going forward. This way people would have something to go off when things break down and we could point them to a working example when something goes wrong. 

However keeping the guide and repo in sync may be tough as well, so I'm not sure this is necessarily the perfect answer either.

**Comment by maasha** [comment]
Ah, sorry, I have wiped the code since I couldn't get it to work. But would `require('./config/' + env + './js')` not cause the same err?

**Comment by skipjack** [comment]
It shouldn't, I don't think if your repository is set up in the same way the guide instructs. Basically that should either resolve to whatever is exported from `./config/dev.js` or `./config/prod.js`. It looks like those weren't coming back at all, or weren't coming back with the right export. The error you saw was because whatever is returned by the `require(...)` wasn't a function, hence the `require(...) is not a function`.

That error isn't saying `require` isn't a function, it's saying whatever is returned by that `require(...)` statement isn't a function so it can't be called with `(env)`. Does that make sense?

**Comment by maasha** [comment]
It vaguely makes sense :o). I think some boilerplate code would be awesome.

**Comment by skipjack** [comment]
Yeah, I hear you. I'll leave this issue open as a stub for improving that guide either by simplifying it a bit or adding a boilerplate somewhere.

**Comment by maasha** [comment]
Cool, getting webpack to work with electron + react has given my headaches. Prowling the internet have left me with a feeling that the available docs, guides, and tutorials are causing lots of confusion (at least for me). Basically, one want to get started with webpack for development. That means starting with webpack-server-dev and not webpack on its own IMHO! Next you want to optimize for production I guess...

**Comment by bebraw** [comment]
> @bebraw @simon04 do we have example/boilerplate repos backing any of these guides? Maybe something we should try out or encourage going forward. This way people would have something to go off when things break down and we could point them to a working example when something goes wrong.

@skipjack No repos. Maintenance-wise it would be the best to generate the repos based on the tutorial code (or vice versa) but that's a harder problem. Otherwise you get a syncing issue (both need to be changed).
