### ISSUE TITLE
Hi I'm an idiot and I failed to find the "caching" section in the docs

### ISSUE THREAD

**Issue by jakearchibald** [webpack/webpack.js.org#1106]
Feel free to "wontfix" this, but when I was looking for the docs I was looking for terms like "revisioning", "versioning", "hashing", "renaming" etc etc.

**Comment by TheLarkInn** [comment]
We should at the least see if theres a way to index those terms against the site search we have. Is that possible @bebraw ?

**Comment by jakearchibald** [comment]
FWIW, I also looked for it in "Building for production" as I thought "Ah yes this is a production-specific action".

**Comment by bebraw** [comment]
@dzello Any thoughts on this?

**Comment by jakearchibald** [comment]
It's totally possible that I'm the only person in the world that wouldn't think of this as "caching".

Within a build system, I figured "caching" might be to internal caching for incremental builds, or something like https://github.com/contra/gulp-cached.

**Comment by dzello** [comment]
_reaches into search toolbox, pulls out synonyms_

This sounds like a job for some [synonyms](https://www.algolia.com/doc/guides/relevance/synonyms/). The DocSearch config supports them directly as you can see [here with Mozilla](https://github.com/algolia/docsearch-configs/blob/eb120290d536908c075b16ef9c08bdb463ce0722/configs/mozilla.json#L136).

Anyone want to take a pass at what they all should be?

**Comment by Munter** [comment]
Content addressable file naming, hashing, revisionig, "revving", consistent file hashing, persistent caching.

People use so many names for this

**Comment by TheLarkInn** [comment]
Alright awesome looks like we have everything equipped to add this feature. I'll share with the masses.

**Comment by dzello** [comment]
The [webpack DocSearch config](https://github.com/algolia/docsearch-configs/commit/c7ccffee1f704069e5033cfcd2c0a7cbe316ec9a) has been updated and deployed. You can use any of those terms now and they'll return caching-related results.

Also, I noticed the Development part of the docs wasn't in the config yet. It's [added now](https://github.com/algolia/docsearch-configs/commit/dcd1b90c0d3403f9c5d06dc7d6d44c59af78f9f7) as well.

**Comment by skipjack** [comment]
Just tested, it seems @dzello's changes have taken effect:

![image](https://cloud.githubusercontent.com/assets/8988697/25154988/ebdfc92a-2460-11e7-8fc0-66efe4491057.png)

Going to close, but feel free to re-open if I missed something.
