### ISSUE TITLE
Plugin/Loader doc pages should have clear, explicit links to their respective repos

### ISSUE THREAD

**Issue by dmitriid** [webpack/webpack.js.org#1107]
In addition to #1076 :

Loaders and plugins are not a part of webpack. And they are not always a part of webpack-contrib. Their documentation pages should have a link to the plugin's/loader's respective Github repo.

_UPDATED_

Explicit is better than implicit. Currently the only ways to get to the respective repos is:

Way 1:
- Hover over "Edit this page"
- Notice that it leads to the correct repo
- Click it
- Click on `Code`/`Issues`/whatever you actually need in the repo

Way2:

- Google the name
- Click first link in search results

This assumes that a person interested in a project's repo will figure out that they have to click "Edit this page" to get to the repo. Which is counterintuitive to say the least.

**Comment by simon04** [comment]
A link already exists: "Edit this page" links to the corresponding GitHub project, more specifically to its README.

**Comment by dmitriid** [comment]
Yes. It's a link to the editing page for the README page. I personally didn't even think on clicking it, because usually I ave no intention to edit a README.

I might want to go the project's Github page and file an issue, for example. Things must be made as explicit as possible.

(On a grumpy note: honestly, what is it with webpack team and clear unobstructed communication?)

**Comment by skipjack** [comment]
I can look into this one.

**Comment by dmitriid** [comment]
Awesome!

**Comment by dmitriid** [comment]
This looks super nice. Awesome!
