### ISSUE TITLE
Sidebar: anchors with links

### ISSUE THREAD

**Issue by simon04** [webpack/webpack.js.org#1126]
Fetched content from `webpack-contrib` plugins/loaders does not show up nicely when a header contains a link, such as https://webpack.js.org/loaders/coffee-loader/#-literate-http-coffeescript-org-literate-

![2017-04-19-124925_1198x947_scrot](https://cloud.githubusercontent.com/assets/782446/25176569/d69a94a2-24fe-11e7-9539-fc5e7ced5a4a.png)

Related: https://github.com/webpack-contrib/bundle-loader/pull/47

**Comment by skipjack** [comment]
@simon04 sure, I can pick this up though I'm a little unsure of what the best fix/behavior would be...

- It seems like it would be hacky to fix this at the component level, probably best in the markdown utility? 
- Also, what should the resulting markup look like? Probably removing them instead of having some double-linking behavior (link within a link), right?

**Comment by simon04** [comment]
Ideally the link text (anchor title) wouldn't contain any markdown syntax. Could this be achieved by editing [the `getAnchors` function](https://github.com/webpack/webpack.js.org/blob/e56f0af/utilities/markdown.js#L110-L117)? A trimming of backticks seems to already be in place.

**Comment by skipjack** [comment]
> Ideally the link text (anchor title) wouldn't contain any markdown syntax.

Yeah, I understand that part -- just wanted to make sure there wasn't an expectation that we would actually turn those into nested `<a>` tags. `getAnchors` should be the right place to do this... I'll get started on this and few of the other UI/UX issues as soon as I have a chance.

**Comment by simon04** [comment]
With https://github.com/webpack-contrib/bundle-loader/pull/47 and similar PRs merged, there's a new similar problem:
![2017-04-23-14-20-35-001](https://cloud.githubusercontent.com/assets/782446/25313518/4521747a-2830-11e7-8efc-2f26a370239e.png)

**Comment by skipjack** [comment]
Ok I guess we can reg ex that out as well.
