### ISSUE TITLE
Create Webpack.config.js file for users to learn from

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#113]
_From @ev1stensberg on March 14, 2016 19:47_

Create A webpack.config file for users to know how to set up a loader from the config and compile from the config.js file. [https://github.com/webpack/webpack/tree/master/examples/code-splitting-bundle-loader]

_Copied from original issue: webpack/webpack#2184_

**Comment by SpaceK33z** [comment]
Closing this issue since that is exactly what we dow now on the [Configuration page](http://webpack.js.org/configuration/).
