### ISSUE TITLE
incomplete css-tutorial?

### ISSUE THREAD

**Issue by TomTasche** [webpack/webpack.js.org#1131]
the tutorial for bundling css with webpack (https://webpack.js.org/guides/code-splitting-css/) does not quite tell you all the steps necessary in my opinion. is it just me and i'm missing the point of the tutorial?

if the point of the tutorial is indeed to bundle css so that it is rendered on the website, i'd like to submit a PR which adds the missing steps (installing and using the style-loader-module). thoughts?

**Comment by skipjack** [comment]
Could you expand on which parts are unclear or the steps you feel are missing?

I just re-read it, and it does look like some things could be elaborated, but it doesn't seem like any code is missing. Either way, we'd love for you to PR any improvements!

**Comment by simon04** [comment]
@TomTasche Has the incompleteness been resolved with https://github.com/webpack/webpack.js.org/pull/1130? If so, let's close this issue.

**Comment by TomTasche** [comment]
#1130 did not add the information i was looking for, but it completed the information that is already available in the tutorial

what the tutorial is missing in my opinion is a mention of style-loader. the last paragraph uses extract-text-webpack-plugin which is fine, but before that it is necessary to use style-loader. otherwise css is merely bundled with javascript, but never applied to the website?

i will come up with a PR as suggested by @skipjack!
