### ISSUE TITLE
Create a .github folder

### ISSUE THREAD

**Issue by yeskunall** [webpack/webpack.js.org#1136]
... and move `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md` inside it.

I mean, all the cool kids are doing it? It also removes clutter in the root directory of the repo, so that's a plus! 👍

Seems fair, right? If so, LMK and I'll make a PR.

**Comment by simon04** [comment]
2 files exchanged for 1 dir is a big improvement :wink: 

https://github.com/webpack/webpack/tree/master/.github also has it, so go ahead :+1:
