### ISSUE TITLE
Create a tutorial on how to set up a boilerplate 

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#114]
_From @ev1stensberg on March 14, 2016 19:52_

Create an offical example of a multiple page App with css loaders, json loaders and so on with detail on walkthrough, for user to understand content from a regular aspect (not that abstract)

_Copied from original issue: webpack/webpack#2185_

**Comment by SpaceK33z** [comment]
Not really sure if we still need this after the "Getting started" page, which will explain the basics. We could also add a link to external blogs on the "Getting started" page for extended tutorials.

**Comment by bebraw** [comment]
Yeah, valid point. Closing.
