### ISSUE TITLE
Maybe, there needs some code analysis direction in wikis or docs.

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#115]
_From @whtoo on March 24, 2016 7:51_

Thanks to your work on webpack.In fact,I'd like to use it and write a bit of loaders.
But when I dig up,I find **the code logic of webpack is so _twisted_**!
Therefore,please give some attention to this issue and write some wikis for introducing
webpack to dev.

_Copied from original issue: webpack/webpack#2227_

**Comment by SpaceK33z** [comment]
I'm going to close this since this issue isn't clear at all. We rewrote the entire docs and have much clearer docs on loaders and the development of loaders / plugins.
