### ISSUE TITLE
Guides(migrating/#complex-options): remove ident

### ISSUE THREAD

**Issue by michael-ciniawsky** [webpack/webpack.js.org#1150]
The `ident` (Complex Options) is obsolete since `webpack >= v2.2.1` and gets automatically added internally by webpack

**Comment by skipjack** [comment]
@michael-ciniawsky were you planning to PR this? If not, I'd be happy to but can you give me a rough idea of your thoughts on how to correct this?

Maybe adding a tip (e.g. `T> ...`) or just blowing away everything about `ident` as anyone who is migrating now should be jumping to the latest version.

**Comment by michael-ciniawsky** [comment]
Go ahead if you have time 😛 I'm not sure what's best, imho remove it enterily from the docs :D

**Comment by skipjack** [comment]
Sounds good, I'll tackle it soon if no one beats me to it.

**Comment by michael-ciniawsky** [comment]
Thx
