### ISSUE TITLE
Basic descriptions for plugins/loaders

### ISSUE THREAD

**Issue by davydog187** [webpack/webpack.js.org#1161]
I really love the documentation improvements that came with the new webpack 2 website. However, I find it frustrating that some of the promoted plugins/loaders on the webpack website do not have simple descriptions of their purpose.

For example, https://github.com/webpack-contrib/worker-loader states 

> Worker loader for Webpack.

What is a Worker Loader? Why might I want it?

There is a lot of implicit knowledge that we're expecting developers to have. This makes it hard and intimidating for new users to start using the platform. My suggestion is to make sure that, at a minimum, all loaders/plugins have a short, easily understandable description of their purpose, such that a layman could make sense of their intended use.

**Comment by skipjack** [comment]
We pull most of the loader and plugin pages in dynamically, so it would be helpful if you could create issues at the repositories themselves (for the loaders/plugins that have vague descriptions).

I agree that some of them are not great, but unless it's a loader in `/content/loaders` (for which there are currently none) or a plugin in `/content/plugins` then these would have to be fixed at the origin. I'll leave this open for a little just in case others want to chime in but it would be great if you could create issues in those repositories.

**Comment by simon04** [comment]
Related: #1076

**Comment by simon04** [comment]
I went through the `webpack-contrib` loaders, checked their READMEs for obvious mistakes or missing loader descriptions, and submitted a bunch of PRs: https://github.com/webpack-contrib/i18n-webpack-plugin/pull/47, https://github.com/webpack-contrib/worker-loader/pull/61, https://github.com/webpack-contrib/coffee-loader/pull/38, https://github.com/webpack-contrib/expose-loader/pull/45, https://github.com/webpack-contrib/raw-loader/pull/28, https://github.com/webpack-contrib/worker-loader/pull/65, https://github.com/webpack-contrib/url-loader/pull/75, https://github.com/webpack-contrib/transform-loader/pull/27, https://github.com/webpack-contrib/transform-loader/pull/28, https://github.com/webpack-contrib/source-map-loader/pull/47, https://github.com/webpack-contrib/sass-loader/pull/444, https://github.com/webpack-contrib/node-loader/pull/9, https://github.com/webpack-contrib/json5-loader/pull/24, https://github.com/webpack-contrib/mocha-loader/pull/59,  https://github.com/webpack-contrib/mocha-loader/pull/60, https://github.com/webpack-contrib/jshint-loader/pull/43, https://github.com/webpack-contrib/file-loader/pull/156.

The same should be done for the plugins and we're done. :smile:

**Comment by skipjack** [comment]
@simon04 is this good to close then or should we leave it open until the rest have been tackled? As you mentioned in the other issue, I think it's hard to tackle these things with this issue here. Creating issues/prs in those repositories is the way to get this knocked out imo. Plus, with the new "Jump to Repository" button, it should be easier to get over there 😉 😉 .

**Comment by simon04** [comment]
Let's keep this open till I (or somebody else) scans the plugin READMEs (once). Afterwards I'm happy to close this issue.

**Comment by skipjack** [comment]
@simon04 any update on this? I'd be happy to help review some of the plugins to push this forward. It looks like most or all of your loader prs have been merged.

**Comment by skipjack** [comment]
Going through the plugins now.
