### ISSUE TITLE
Sponsor/backer icons ↔ links are off by one

### ISSUE THREAD

**Issue by simon04** [webpack/webpack.js.org#1167]
Clicking on the second icon (with dotted border in the screenshot; having id 1 in the URL), I reach the opencollective profile page corresponding to the first icon.

![](https://cloud.githubusercontent.com/assets/782446/25549214/ea91b444-2c70-11e7-927e-ed912dab8e8e.png)

**Comment by skipjack** [comment]
@simon04 can you test #1159 and see if this resolves that issue? (I bet it does)

**Comment by simon04** [comment]
Yes, this issue is fixed with #1159.
