### ISSUE TITLE
proselint not running

### ISSUE THREAD

**Issue by aretecode** [webpack/webpack.js.org#1179]
<img width="321" alt="screen shot 2017-05-01 at 4 34 53 pm" src="https://cloud.githubusercontent.com/assets/4022631/25598820/25571ee4-2e8c-11e7-90c6-61a094547c1a.png">

I've tried installing it locally since it is not listed in the package dependencies, I've tried installing with python as per the proselint site, I've tried installing globally...

```bash
npm i proselint
npm i -g proselint
https://packaging.python.org/installing/#use-pip-for-installing
pip install -U pip setuptools
pip install proselint
```

**Comment by skipjack** [comment]
@aretecode it does need to be installed with pip, not npm. Did you get errors after running those commands? It's a bit hard to tell what's going on without seeing the output... for me, after installing with pip (which is a bit weird in a npm-based project), everything worked fine.

**Comment by aretecode** [comment]
@skipjack got it working, needed a restart
