### ISSUE TITLE
webpack -d devtool default is not overridden in config

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#118]
_From @javascriptjedi on April 11, 2016 19:36_

From the docs it states:

"Note: With the next major version the default for -d will change to cheap-module-eval-source-map"

The behavior I'm seeing is the devtool config is ignored if I run webpack -d, it is honored if I just run webpack. The docs make it sound like cheap-module-eval-source-map is just a default and I would expect the config to be the value used if it is set. This was happening on both beta 4 and 5.

_Copied from original issue: webpack/webpack#2317_

**Comment by pksjce** [comment]
_From @sokra on April 13, 2016 7:26_

CLI options override the configuration options. So `-d` overrides `devtool: ...`.

`--devtool eval` overrides `-d`.

**Comment by SpaceK33z** [comment]
The new docs no longer have this note and clarify this more clearly in the [Shortcuts page](http://webpack.js.org/api/cli/#shortcuts).
