### ISSUE TITLE
You can't upload any file to http://webpack.github.io/analyse/

### ISSUE THREAD

**Issue by LordMalkev** [webpack/webpack.js.org#1180]
Simply as that. No upload button or any type of submit.

Chrome  57.0.2987.133 (64-bit)
MacOS Sierra 10.12.3 (16D30)

**Comment by skipjack** [comment]
@LordMalkev thanks for pointing this out. However the analyze tool isn't managed from this repository (although at some point it may be hosted here). Please move this issue to [that repo](https://github.com/webpack/analyse).
