### ISSUE TITLE
Dev Server Build Failure: Module "support-sponsors.json"

### ISSUE THREAD

**Issue by chrisVillanueva** [webpack/webpack.js.org#1182]
I updated to current master.  When I ran "npm start" to build a local dev server, the documentation site did not load on port 3000.  It's a blank white page.  There is an error in console that states:

Uncaught Error: Cannot find module './support-sponsors.json'.
    at eval (support\-.*\.json$:8)
    at webpackContextResolve (support\-.*\.json$:8)
    at webpackContext (support\-.*\.json$:5)
    at Support.render (support.jsx:45)
    at eval (ReactCompositeComponent.js:796)
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext 

Does anyone else have this issue? I ran "npm cache clean", "npm install", then "npm start" to ensure I have the latest packages on my local.

Screenshot:
![webpack-js-fail](https://cloud.githubusercontent.com/assets/1554280/25647696/54217b96-2f92-11e7-8732-041d721155c6.png)

**Comment by skipjack** [comment]
These files are auto-generated during the build, similar to some of the loader/plugin content. Run an `npm run fetch` to generate these files. I'll add this to our `start` script as well to avoid any confusion.

**Comment by chrisVillanueva** [comment]
Thanks for the fix
