### ISSUE TITLE
The markdown table is parsed unexpectedly in css-loader documentation page

### ISSUE THREAD

**Issue by Alex1990** [webpack/webpack.js.org#1187]
In the "Options" section of the [css-loader](https://webpack.js.org/loaders/css-loader/#options) documentation.

![image](https://cloud.githubusercontent.com/assets/3141679/25673218/26e8d57a-3069-11e7-8f2d-16ce788984a9.png)

**Comment by skipjack** [comment]
@NejcZdovc can you look into this?

**Comment by NejcZdovc** [comment]
@skipjack problem here is that we are not escaping `|` correctly, that's why new column is added.

This is a markdown from `css-loader` repo:
![image](https://cloud.githubusercontent.com/assets/9574457/25693974/71529356-30ac-11e7-83d2-ca2c81ae9162.png)


As you can see `{Boolean\|Object}` is in there.

**Comment by skipjack** [comment]
Hmmm after looking at the markdown utility I don't see where the parsing fails. Are we manually parsing each table line somewhere?

**Comment by NejcZdovc** [comment]
For table we have a custom handler and it starts here https://github.com/webpack/webpack.js.org/blob/master/utilities/markdown.js#L102. Thing is that this is parsed and handled by markdown util, we just add some wrappers around it.

**Comment by skipjack** [comment]
> Thing is that this is parsed and handled by markdown util, we just add some wrappers around it.

Yea that's what I noticed when going through it as well. It doesn't seem like we're manually calling `.split(' | ')` or anything similar anywhere. I wonder if this was broken by something else were doing like the reference links.

**Comment by NejcZdovc** [comment]
maybe it's bug in markdown?

**Comment by skipjack** [comment]
I don't think so because is parsed correctly [in github](https://github.com/webpack-contrib/css-loader). Maybe in marked but I doubt it, seeing as the reference link issue is definitely caused by our customizations. 

I really want to move to markdown-to-react-components but don't have the time yet to do the port (I think it'd take a decent amount of effort).

**Comment by skipjack** [comment]
Not pretty, but I came up with a temp solution. I'll PR it tonight.

After digging into it a bit more I'm still unsure as to what we're doing that's breaking this and other stuff (like reference links). I tried commenting some bits out, but nothing seem to fix the odd behaviors. This could be something that just an issue in marked, the only way to find out would be to test a similar table using marked without any customizations.

**Comment by Alex1990** [comment]
Okay, I find it is a marked's bug https://github.com/chjj/marked/issues/595. And, I use the latest marked to test it.

**Comment by Alex1990** [comment]
Should we use `<code>{Object&verbar;Boolean}</code>` which is parsed rightly by github and marked?

**Comment by skipjack** [comment]
> Okay, I find it is a marked's bug chjj/marked#595. And, I use the 0.3.6(latest) marked to test it.

@Alex1990 awesome thanks for digging into that. Unfortunately, reading into that issue doesn't give me much hope that it'll get fixed. I think we just need to switch our markdown parsing process.

> Should we use <code>{Object&verbar;Boolean}</code> which is parsed rightly by github and marked?

The content for that page is actually from another repository. I think it'd be tough to enforce people not to use things that are supported by GFM. We probably need to make sure that when we do update our markdown processing that we fully support GFM if possible.

I do have a fix for the meantime I'll add PR for shortly.
