### ISSUE TITLE
Korean Version

### ISSUE THREAD

**Issue by Lutece** [webpack/webpack.js.org#1189]
Hello, I would like to translate this page in Korean.
I would like to ask if I can translate in Korean.

I created a repository that named webpack-korea.
I connected the repository to Travis and completed it for my local environment.

I'm waiting for your answer.

**Comment by skipjack** [comment]
Awesome! We already have a [chinese version](https://doc.webpack-china.org/) maintained by @lcxfs1991 and recently added a dropdown for languages in the main site. Once you get something solid going we could add a link in the languages dropdown:

![image](https://cloud.githubusercontent.com/assets/8988697/25713580/3083374c-30c3-11e7-9908-875ed3be890b.png)

Also, just so you are aware, we are considering some tools to make internationalization/translation easier, see #295.

@bebraw feel free to elaborate or add anything. From my standpoint, this would be fine as long as it's maintained in a separate repo.

**Comment by bebraw** [comment]
It's alright.

**Comment by skipjack** [comment]
@Lutece can you share a link to your repo? If anyone creates issues over here re korean translation, I'll send them over to your repository. Also, you may want to get some ideas from @lcxfs1991 as their chinese repository is already pretty far along. He can discuss our `translation` branch a bit, which may be useful to you as well.

**Comment by Lutece** [comment]
this is korean repo link :) - https://github.com/webpack-korea/webpack.js.org 

Should i use Locki when i translate webpack.org?

Could you please explain how to proceed with the translation?

**Comment by lcxfs1991** [comment]
Hi Lutece, I am willing to help.

Locki is needed more work to be integrated into the main repo.

You can take a look at branch [translate](https://github.com/webpack/webpack.js.org/tree/translation). You can arrange friends to help translate first.  Any questions you can raise issue here or directly contact me via Twitter Message. 

https://twitter.com/lcxfs1991

**Comment by skipjack** [comment]
> Should I use Locki when I translate webpack.org?

Not yet, as @lcxfs1991 said, the Locki setup probably won't be for a bit. Just wanted you to be aware, and might be worth subscribing to the issue (#295).

> Could you please explain how to proceed with the translation?

What you proposed, as in maintaining a separate repo, would be fine for now. Past that, I would discuss with @lcxfs1991. I'll leave this issue open for a few more days in case you'd like to discuss more here. Also, I may add a translation section to the readme with links to each of your repositories.

**Comment by skipjack** [comment]
Closing this, but I will add a translation/internationalization section to the readme with links to both repos. And, once the korean version is significantly built out, we'll add a link to wherever you decide to host it.

**Comment by Lutece** [comment]
@lcxfs1991 @skipjack Thank you for answering me.
I started to translate to Korean, so when I finished translate, I'll inform you.

I'll be back to here soon!

**Comment by lcxfs1991** [comment]
@Lutece  Good luck man. It'd better ask more friends to join you.

**Comment by mojosoeun** [comment]
@Lutece Hi, Lutece. I want to contribute korean translation project! Could I join the project?

**Comment by Lutece** [comment]
@mojosoeun Sure! I sent you an email for the invitation and i made a slack channel for webpack-korea. if you want to talk to me any time, please join the slack channel

**Comment by mojosoeun** [comment]
@Lutece OO Thank you :)

**Comment by Lutece** [comment]
I have a few question about Webpack version.

Translation branch is still version 2.3.3 and my repository is watching translation branch. so my version is 2.3.3 too, how can I change version 2.3.3 to version 3.0.0?

Do I need to update to 3.0.0 after I finish 2.3.3 version?

**Comment by skipjack** [comment]
Hmmm so what do you mean by:

> Translation branch is still version 2.3.3

Do you mean the version number in the sidebar:

![image](https://user-images.githubusercontent.com/8988697/27444881-c27c2b74-5745-11e7-963d-e0a1a7e7be95.png)

That's dynamic now so if you update your fork it should basically always be on the latest version. One of you could also PR an update to the translation branch if it's behind. @lcxfs1991 @bebraw could probably give you slightly better advice since I'm still not exactly sure what the translation workflow is.

You could also keep your fork a little behind and wait for things to stabilize a bit before updating -- meaning things are still changing quite rapidly (for example all the guides cleanup in #1258) so you might end up having to update the translations a lot.
