### ISSUE TITLE
webpack watch doesn't work with  cifs  share  windows folder

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#119]
_From @hellolwq on April 18, 2016 1:23_

development enviroment under linux,use cifs  share  windows folder,webpack watch does not work.

_Copied from original issue: webpack/webpack#2351_

**Comment by pksjce** [comment]
_From @sokra on April 20, 2016 21:13_

Yeah the normal watching doesn't work on shares. You need to use the polling mode on shares...

**Comment by SpaceK33z** [comment]
Closing this since I've documented this in #204 and added examples of when watching does not work.
