### ISSUE TITLE
API - Module resolution

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#12]
[Stub](https://github.com/webpack/webpack.io/blob/develop/content/api/module-resolution.md).

Feel free to comment here if you have ideas on what this guide should cover. Link to potential resources too.

**Comment by bebraw** [comment]
Great starting point at https://webpack.github.io/docs/resolving.html . Copy over to the docs and go from there.

**Comment by ClementVidal** [comment]
Hi, I'd like to contribute to this page.
Appart from copy/pasting/formatting the above page, where can i get webpack2 specific informations ?
If the only way to go is to explore the code base, can you please direct me to a starting point for this topic ?
Thank you !

**Comment by bebraw** [comment]
@ClementVidal Great! You can find the new resolution options [here](https://gist.github.com/sokra/27b24881210b56bbaff7#resolving-options). So you would have to port that over. 👍

**Comment by ClementVidal** [comment]
@bebraw Thanks, Were can i ask for questions (if any) regarding that topics ? Directly in this issue ? Or is there a slack/gitter channel for that ?

**Comment by bebraw** [comment]
@ClementVidal You should have mail. Thanks. 👍

**Comment by pksjce** [comment]
Is there anything more to be done on the issue?

**Comment by bebraw** [comment]
Yeah, looks like this one is safe to close. Thanks!
