### ISSUE TITLE
Pragma style with eval-source-map devtool does not follow documentation

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#120]
_From @keirlawson on January 8, 2016 10:14_

Documentation states that the pragma style for source maps defaults to #, yet I'm finding with Webpack 1.12.10 with devtool set to eval-source-map, the pragma style seems to default to @, causing Firefox to complain:

`Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead`

_Copied from original issue: webpack/webpack#1865_

**Comment by pksjce** [comment]
_From @sokra on January 8, 2016 16:23_

> Documentation states that the pragma style for source maps defaults to #

Propably already updated for webpack 2...

You can specify: `devtool: "#eval-source-map"`

**Comment by pksjce** [comment]
_From @cageygee3 on March 30, 2016 19:5_

I'm also seeing this. Adding a hash to the front of the `devtool` setting string does fix the problem, but indicates that the documentation is wrong about the default.

**Comment by pksjce** [comment]
_From @irnc on May 4, 2016 14:47_

I updated documentation to clarify defaults for each major version. Change could be seen at https://github.com/webpack/docs/wiki/configuration/_compare/207d9e5b0e8d69b1bdd15675e1fb5a40ab29457c...3c4be00157ddad325e3aa52e2d99a01accfcb6b2

@sokra Could you please review and publish that change?

**Comment by SpaceK33z** [comment]
Tested this, and webpack v2 uses `#` as default, which is correct.
