### ISSUE TITLE
No Dash Docset available 

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#121]
_From @likeabbas on May 19, 2016 23:9_

This isn't _that_ high priority but it would be wonderful if the docset could be ported to Dash :) 

https://kapeli.com/docsets

_Copied from original issue: webpack/webpack#2521_

**Comment by pksjce** [comment]
_From @TheLarkInn on May 21, 2016 0:43_

@bebraw I think one we restructure the initial documentation this could be a future down the road.

**Comment by bebraw** [comment]
@pksjce Do you want to give it a go with the current docs? Curious about the results.

**Comment by pksjce** [comment]
Sure! Sounds interesting.

**Comment by silvenon** [comment]
[Here it is](https://github.com/silvenon/webpack-docset)! Now I just have to get it submitted to Dash…

**Comment by silvenon** [comment]
Kapeli/Dash-User-Contributions#1175

**Comment by bebraw** [comment]
Thanks. 👍
