### ISSUE TITLE
how to use pure nodejs to achieve Hot Module Replacement?

### ISSUE THREAD

**Issue by anlexN** [webpack/webpack.js.org#1216]
hopefully, who can tell me how to use pure nodejs to achieve Hot Module Replacement?

**Comment by skipjack** [comment]
Even when [using the node api](https://webpack.js.org/api/node/#webpack-), you still pass a configuration object. So my guess is that you'd simply pass the internal `webpack.HotModuleReplacementPlugin()`. This is mentioned in the [devServer configuration](https://webpack.js.org/configuration/dev-server/#devserver-hot) docs but we still don't have a page for the plugin itself.

@webpack/contributor-team @webpack/documentation-team anyone interested in adding what I think would be a short page in plugins for the `HotModuleReplacementPlugin`?

**Comment by skipjack** [comment]
Completely forgot about #86... closing in favor of that issue. @anlexN please follow that thread, I'll try to help to push it forward.
