### ISSUE TITLE
Webpack 2 + System.import: default export has to be read with .default

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#122]
_From @Kovensky on March 15, 2016 7:12_

Snippet demonstrating the issue:

```js
// test.js
export default class Test {}

// index.js (with proper runtime available)
System.import('./test').then(Test => {
  new Test() // error! must use new Test.default()
})
```

The following code gets generated in webpack's chunk containing `test.js`:
```js
/* harmony default export */ exports["default"] = Test;
```

This behaves differently from when you use `import Test from './test'`, as when you use such a static import you can then call `new Test()` instead of having to call `new Test.default()`.

I also considered this might be an issue with babel transforms, but as it is getting emitted as a `/* harmony default export */`, I don't believe babel is transforming the export. I am using the `es2015-webpack` preset to preserve harmony imports/exports.

Not sure if this a webpack 2 bug or just a  documentation issue.

_Copied from original issue: webpack/webpack#2188_

**Comment by pksjce** [comment]
_From @Kovensky on March 15, 2016 7:24_

Hm, I just noticed that this basically has the same behavior as `import * as Test from './test'`. In this case, I would still have to access `Test.default` to get at the default export.

Thus, I suppose this is only a documentation (or expectation) issue.

**Comment by pksjce** [comment]
_From @helloyou2012 on March 17, 2016 9:4_

@Kovensky ,  I use this plugin to solve this problem: https://github.com/59naga/babel-plugin-add-module-exports

**Comment by pksjce** [comment]
_From @sokra on March 30, 2016 17:31_

> Not sure if this a webpack 2 bug or just a documentation issue.

> Thus, I suppose this is only a documentation (or expectation) issue.

Yep, working as intended.

**Comment by pksjce** [comment]
_From @sokra on March 30, 2016 17:32_

> @Kovensky , I use this plugin to solve this problem: https://github.com/59naga/babel-plugin-add-module-exports

I don't recommend this. babel had good reasons for no longer doing so.

**Comment by pksjce** [comment]
_From @hkrutzer on May 31, 2016 23:18_

Take a look at https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0

**Comment by SpaceK33z** [comment]
Closing since @TheLarkInn documented this in #213.

**Comment by souptown** [comment]
@SpaceK33z The PR you reference when closing this says you can freely mix ES6, AMD, CommonJS.

Webpack 2.2.0-rc.3 (correctly?) breaks the case of mixing CommonJS `module.exports = function (){}` and ES6 `import foo from ...`.

In this case `foo` will be undefined because `module.exports.default` was not set.

I'm unsure now if this is a webpack 2 bug or a documentation error.

**Comment by Kovensky** [comment]
@souptown both. Your code is supposed to crash with ReferenceError instead :)

The node interop spec says that ES modules _do not_ have either a `module` or `exports` "global".

**Comment by ssylvia** [comment]
So if I reading this thread right, when using the following syntax to import an es6 module, I will always need to execute the default method instead of just calling the module directly?

```js
import('path/myModule').then((module) => {
  module.defualt();
});
```

**Comment by Kovensky** [comment]
that is only if your module _has_ a default export to begin with.
