### ISSUE TITLE
webpack.js.org vs. webpack.github.io (2 vs 1?)

### ISSUE THREAD

**Issue by jm3** [webpack/webpack.js.org#1239]
Apologies if this has been answered before, but I didn't see it in the open or closed issues — what's the difference between the two webpack home pages / sites, and why are there two?

I know there are two versions of webpack, 1 and 2, but https://webpack.js.org, which i assume is the "main" site, doesn't prominently mention versions, and https://webpack.github.io, the other site, prominently mentions BOTH versions. If it were the case that one site for for v1 and the other was for v2, wouldn't it make more sense to clarify, "webpack 1" or "webpack 2" somewhere plainly?

I don't mean to waste time with a silly question, I just have both sites in my browser history and I'm not entirely sure why. Happy to submit PRs to add some clarifying text, but I would rather ask first before trampling around. :)

**Comment by skipjack** [comment]
This site is for documenting webpack 2 and any future versions (we may even have a major version dropdown at some point to toggle between the documentation for version 2 and above). The old docs do have a pretty clear warning on most pages:

![image](https://cloud.githubusercontent.com/assets/8988697/26401986/67d5c406-4056-11e7-84bb-82d0003c1d4a.png)

and these docs do state the current documented version in the sidebar (though sometimes the img shield takes some time to load):

![image](https://cloud.githubusercontent.com/assets/8988697/26401972/49606b20-4056-11e7-8364-ff65127ef6a4.png)

I'll keep this in mind though next time we make updates to the index page to clarify that a bit more. Closing as I think this answers your question, but feel free to comment or re-open if it didn't.

**Comment by jm3** [comment]
One reason to consider changes is that Google ranks the old, `github.io` webpack site higher than the "new" webpack 2 `.js.org` site:

<img width="681" alt="old vs new" src="https://cloud.githubusercontent.com/assets/12213/26412854/f519ce36-405e-11e7-90ed-0c45a7cae126.png">

**Comment by skipjack** [comment]
> One reason to consider changes is that Google ranks the old, github.io webpack site higher than the "new" webpack 2 .js.org site

Yeah I've noticed this as well. I figured that was caused more by the fact people had been using and linking to the old version for a longer time but you mean doing something like "Webpack 2 | Page Name" or even "Webpack | Page Name" would help?

**Comment by RinkAttendant6** [comment]
Is it possible to merge the two sites and have a version dropdown similar to https://getbootstrap.com/ (Bootstrap) or Zend Framework (https://framework.zend.com/manual/2.4/en/index.html)? If so then the old site can be changed to redirect to the new site.

I'm just getting started with Webpack and need to refer to the docs quite often... it's frustrating to land on the old site frequently as there are so many links to it, especially since it's high-ranking on Google as @jm3 pointed out.

**Comment by skipjack** [comment]
> Is it possible to merge the two sites and have a version dropdown similar to...

This would be great, and is something we definitely want to do for future releases but would take a significant amount of work to accomplish for v1. Even if we had a system set up to archive content at the latest major and switch content using a dropdown, we'd still have to port all the old content to the same general structure of this site and then archive it. This may not be too bad but I'm not sure the effort would be worthwhile as I think the vast majority of users are now off v1.

I do think a redirecting any traffic  to `webpack.github.io` to the new site and taking down the actual `webpack.github.io` site is warranted. Unless there is some way for owners of sites to push google to drop a site's page ranking (which I'm not aware of).

Taking down the old site was suggested a little while back but @bebraw pointed out that it would break a lot of links it throughout other sites. Personally I think a redirect to the new site would be fine and we could just point people to the old docs repo/wiki for webpack 1 documentation. This decision would be up to the @webpack/core-team though. They would know better how frequently webpack 1 and the old site are still used.

**Comment by skipjack** [comment]
Btw we do have a TODO for archiving versions of content in #1525:

> Mark releases (synced with main package) and archive them (#176, #1017).

This would likely follow a similar flow to lodash where the last version of each major is archived and accessible via a dropdown. If someone wanted to propose an approach and submit a PR, we would definitely help facilitate. Otherwise, we'll try to get to it after some other infrastructure work is completed.
