### ISSUE TITLE
Docs need to force https. Disqus tracks both separately.

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#124]
_From @k-funk on July 11, 2016 19:13_

Bug:
Current behavior: Different Disqus comments depending on usage of http/https. 
Reproduce: visit both links, view Disqus comments

* https://webpack.github.io/docs/usage-with-gulp.html
* http://webpack.github.io/docs/usage-with-gulp.html

_Copied from original issue: webpack/webpack#2758_

**Comment by SpaceK33z** [comment]
With the new docs this is still relevant, but not very important. I still would like to move to https if possible. Also allows us to use http/2, which is nice.

**Comment by bebraw** [comment]
@indus Any thoughts on this? Can js.org be forced to https somehow?

**Comment by indus** [comment]
It could - but -  only when i force everybody to https (and thats not what i want; it would propably break other pages).

I would suggest [this](https://coderabbi.github.io/posts/force-https-with-github-pages/) solution. Looks a bit hackish but works great. And when JavaScript is disabled in a browser, there would be no Disqus anyway, or am I wrong?

**Comment by indus** [comment]
Forget about my last post. Its 2016 and enforcing SSL is a good thing. This only affects all requester that opted-in to use Cloudflares "Universal SSL" and all that requested after it became default, all others can still use http. I think that is the cleanest solution not only for your project.

So you should now notice enforced https when you serve your page.

**Comment by bebraw** [comment]
Great work. Closing.

**Comment by k-funk** [comment]
Is this deployed/fixed on the live site? The http link i posted still doesn't redirect to the https version.

**Comment by SpaceK33z** [comment]
@k-funk, this is the repo for the new docs website for webpack v2. It was also an issue on the new website, which is fixed now.
