### ISSUE TITLE
Add webpackMode() api documentation for import()

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#1243]
1. Check the existing issues to see if you can find something matching to your request.
2. If you didn't find a relevant issue, go ahead and open a new one. It's better to make small typo fixes and such directly as pull requests.

As of https://github.com/webpack/webpack/releases/tag/v2.6.0 there is a new "comment based" API called `webpackMode()`. We need to add this information to our documentation as part of the `import()` or code-splitting sections etc. The purpose of these additions are to support eventually getting rid of require.ensure(), but have a way to still emulate its multiple behaviors around the limited specification of `import()`.

**Comment by skipjack** [comment]
There's already a pr open for this -- #1231

**Comment by TheLarkInn** [comment]
Ahhh sorry I'll close as dupe!! Thank you

**Comment by skipjack** [comment]
No worries, just merged the PR (#1231)!
