### ISSUE TITLE
compiler watchOptions are ignored in compiler.watch

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#125]
_From @DarkPark on January 29, 2016 9:12_

I have a compiler with watch options:

```js
var compiler = webpack({
    ...
    watchOptions: { ... }
    ...
});
```

then I start watching:

```js
compiler.watch(watchOptions, function ( error, stats ) {
    // why I should put watchOptions here again?
    // they are already set for compiler as described in documentation
});
```

it would be nice to be able to just start watching as it has all the necessary info:

```js
compiler.watch(function ( error, stats ) {
    ...
});
```

or even without callback as I may not need error/stats info:

```js
compiler.watch();
```

_Copied from original issue: webpack/webpack#1951_

**Comment by pksjce** [comment]
_From @sokra on January 30, 2016 8:53_

You don't need the `watchOptions` in the configuration. You only need to provide it in the watch call.

`watchOptions` in configuration is only used by the CLI. Just like the `devServer` key which is only used by the dev server CLI.

**Comment by pksjce** [comment]
_From @DarkPark on January 30, 2016 9:17_

@sokra quote from documentation:
"(only used when using CLI or simple node.js API)"
and I exactly use it in simple node.js API.

From architectural point of view maybe it's reasonable to split page configuration to a couple of config files.

**Comment by pksjce** [comment]
_From @sokra on January 30, 2016 10:52_

yep thanks, I changed the documentation.

**Comment by pksjce** [comment]
_From @DarkPark on January 30, 2016 12:23_

It is still confusing.
The whole page https://webpack.github.io/docs/configuration.html is clearly about the single configuration object passed to webpack.
It's rather strange to describe some options among compiler options but forbid to use these options for compiler.

**Comment by SpaceK33z** [comment]
I think with the new docs in #204 this has been made pretty clear. At the top, it specifies how you can pass webpack-dev-server or webpack-dev-middleware options. `watchOptions` is also correctly documented there.
