### ISSUE TITLE
Is source-map-loader necessary for the typescript example?

### ISSUE THREAD

**Issue by johnnyreilly** [webpack/webpack.js.org#1257]
In the webpack / typescript documentation [it says](https://github.com/webpack/webpack.js.org/blob/master/content/guides/webpack-and-typescript.md#enabling-source-maps) that the `source-map-loader` is necessary for sourcemaps to work.  I don't believe it is (I've been happily debugging TypeScript with sourcemaps and webpack for about 2 years now).  I was just curious if I was missing anything?  As far as I know this section:

```
 module: {
   rules: [
     {
       enforce: 'pre',
       test: /\.js$/,
       loader: "source-map-loader"
     },
     {
       enforce: 'pre',
       test: /\.tsx?$/,
       use: "source-map-loader"
     }
   ]
 },
```

Isn't necessary at all. 

You just need `"sourceMap": true` in the `tsconfig.json` and `devtool: 'inline-source-map'` in the `webpack.config.js`.  

I just wanted to know if there was anything else `source-map-loader` brings to the party?  AFAIK this isn't required...

**Comment by skipjack** [comment]
Related #969

**Comment by skipjack** [comment]
Can you take a look at the changes in #969 and let me know if the guide is valid so we can push it forward?

**Comment by johnnyreilly** [comment]
The changes in #969 look valid to me - I don't think source-map-loader is required.

**Comment by donaldpipowitch** [comment]
I followed the guide, but run Babel after TypeScript  and it looks I can only get the source map for my code *after* TypeScript run.

E.g. I have a file like this (`foo.tsx`):

```
import React from 'react';
import { NameComponent, ImageTestComponent } from 'some-module';

/**
 * This is our app component.
 */
export const AppComponent = () => (
  <div>
    <NameComponent a={1} b={2} name="foo" />
    <ImageTestComponent />
    {
      process.env.NODE_ENV === 'production'
        ? <p>Production Build</p>
        : <p>Dev Build</p>
    }
  </div>
);
console.log('test');
```

`'test'` is logged correctly to the console and it shows `foo.tsx:9` (correct name, wrong line). Clicking on `foo.tsx` shows this file:

```
import React from 'react';
import { NameComponent, ImageTestComponent } from 'some-module';
/**
 * This is our app component.
 */
export var AppComponent = function AppComponent() {
    return React.createElement("div", null, React.createElement(NameComponent, { a: 1, b: 2, name: "foo" }), React.createElement(ImageTestComponent, null), process.env.NODE_ENV === 'production' ? React.createElement("p", null, "Production Build") : React.createElement("p", null, "Dev Build"));
};
console.log('test');


//////////////////
// WEBPACK FOOTER
// ./src/app.tsx
// module id = 84
// module chunks = 0
```

(Here is the `console.log` on line 9.)

Any idea why?

**Comment by johnnyreilly** [comment]
Do you have these set correctly?

> You just need `"sourceMap": true` in the tsconfig.json and `devtool: 'inline-source-map'` in the webpack.config.js.

**Comment by donaldpipowitch** [comment]
Well you _can_ check out our setup, but it's quite big. We have a similar tool like `create-react-app` called [`ws` (linked to v2 branch)](https://github.com/Mercateo/ws/tree/v2). It also contains examples.

The webpack config for an single page app is created [here](https://github.com/Mercateo/ws/blob/v2/src/lib/webpack/spa.ts).

Already cloned ts-loader earlier today, because of the examples 😄 Will try out react-babel-karma-gulp.

**Comment by johnnyreilly** [comment]
Great - thanks for reporting back. Be great to hear what the difference is (if you find it)

**Comment by johnnyreilly** [comment]
BTW you might find the fork-ts-checker-webpack-plugin / happypack examples useful if you'd like faster build times. I'm planning to blog about these but haven't got round to it yet

**Comment by donaldpipowitch** [comment]
Found the bug https://github.com/Va1/string-replace-loader/pull/28.

**Comment by johnnyreilly** [comment]
Great work!
