### ISSUE TITLE
Guides - Correct Example in Code Splitting

### ISSUE THREAD

**Issue by jkrems** [webpack/webpack.js.org#1274]
Section of the website: https://webpack.js.org/guides/code-splitting-async/#dynamic-import-import-

I'm not sure if it's by design but the moment example, as written, is not supposed to work with the "real" dynamic import:

```js
function determineDate() {
  import('moment').then(function(moment) {
    console.log(moment().format());
  }).catch(function(err) {
    console.log('Failed to load moment', err);
  });
}
```

According to the spec, `import(specified)`...

> ...returns a promise for the module namespace object of the requested module

And that namespace object will never be a callable function. So the example should read something like this to be spec-compliant:

```js
function determineDate() {
  import('moment').then(function(moment) {
    console.log(moment.unix(moment.now() / 1000).format());
  }).catch(function(err) {
    console.log('Failed to load moment', err);
  });
}
```

It's still cheating, technically, but it's at least *possible* within the spec. Alternatively:

```js
function determineDate() {
  import('moment').then(function(moment) {
    console.log(moment.default().format());
  }).catch(function(err) {
    console.log('Failed to load moment', err);
  });
}
```

But this might be even more confusing because I don't think that's how webpack implemented it..?

**Comment by skipjack** [comment]
Ah good catch -- yes it is the `module` that is returned so `module.default` I think would have to be referenced first. I'm not sure how this works with other types of modules but definitely for ES6 this is how `import()` works. Would you be interested in submitting a pr to resolve this? (while it is slightly hacky, your `moment.default().format()` is correct)

**Comment by jkrems** [comment]
I can try it out but I don't really have a project with webpack set up right now (so I don't think I would get around to it today).

**Comment by skipjack** [comment]
No problem, I'll pr this correction shortly.

**Comment by skipjack** [comment]
@jkrems hey so I actually tested this out before updating the documentation:

![image](https://user-images.githubusercontent.com/8988697/27257804-d790edb0-53b2-11e7-9e54-2a470dc2398b.png)

and in the console:

![image](https://user-images.githubusercontent.com/8988697/27257807-e5a34d26-53b2-11e7-8c93-1cc54c3e9d33.png)

The key here is that it depends on how the library or module is written and exports itself. Other libraries, like [marksy](https://github.com/cerebral/marksy) for example and custom ES6 modules do follow the spec and when `import(...)` is used the `module` is what the promise resolves to, as you described. But as you can  see above, for `moment` at least, the docs are correct. If you think something should be changed about the implementation, I would create an issue over at the main repo.
