### ISSUE TITLE
Config - Clarify Aliasing Example

### ISSUE THREAD

**Issue by iTob191** [webpack/webpack.js.org#1282]
https://webpack.js.org/configuration/resolve/#resolve-alias:

> ```js
> alias: {
>   xyz$: path.resolve(__dirname, 'path/to/file.js')
> }
> ```
> 
> which would yield these results:
> 
> ```js
> [...]
> import Test2 from 'xyz/file.js'; // Error, /path/to/file.js/file.js is invalid
> ```

I'm not sure if I really got how the trailing `$` works, but if so, I think the explanation for `import Test2 from 'xyz/file.js'` is wrong. As I understand it, `'xyz/file.js'` is not an exact match for the alias `xyz$`, so webpack does not even consider this alias for resolving and therefore never even tries to find `/path/to/file.js/file.js`. Is that correct?

If yes, I would prefer:

```js
alias: {
  xyz$: '/path/to/file.js'
}
```
```js
import Test1 from 'xyz'; // Exact match, so /path/to/file.js is imported
import Test2 from 'xyz/file.js'; // Not an exact match, so normal module resolution takes place
```
I use the complete path (instead of `path.resolve(...)`) in the alias definition to clearly identify the file in the comment of the second code block.

**Comment by skipjack** [comment]
I believe you are correct `xyz$` should only match `import Test1 from 'xyz';` and not throw an error for the second one. However, I would leave the `path.resolve(...)` in as developers will have to include the full path through their whole file system, not just the path within their directory (i.e. `/Users/Me/Desktop/Project/Test/path/to/file.js` not just `/path/to/file.js`). @bebraw do you agree?

**Comment by bebraw** [comment]
@skipjack Yup, that's the way the match works.

**Comment by skipjack** [comment]
@iTob191 so if you'd be interested in submitting a pr with this change you mentioned:

```js
import Test1 from 'xyz'; // Exact match, so /path/to/file.js is imported
import Test2 from 'xyz/file.js'; // Not an exact match, so normal module resolution takes place
```

That would be great.
