### ISSUE TITLE
Dev - Link Usage in Headers

### ISSUE THREAD

**Issue by stof** [webpack/webpack.js.org#1306]
The DllPlugin doc puts links inside a heading. this breaks the navigation on the left:
![webpack_dll_doc](https://user-images.githubusercontent.com/439401/27294558-3988adb0-551a-11e7-8008-ede8f70cf4a2.png)

**Comment by skipjack** [comment]
@stof thanks for reporting this. I thought we had something in place to deal with that but obviously something went wrong here.
