### ISSUE TITLE
Config - Auxiliary Comments for UMD Builds

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#132]
_From @TheLarkInn on June 9, 2016 5:53_

This is a reminder/placeholder to add documentation for https://github.com/webpack/webpack/pull/2113

Can assign to me or PR's welcome. 
- [ ] Add documentation on githubio page
- [ ] Add examples in examples page
- [ ] Add to wiki

_Copied from original issue: webpack/webpack#2623_

**Comment by skipjack** [comment]
See webpack/webpack#2113 where @TheLarkInn has already provided the details for the `auxiliaryComment` property with `output` configuration.
