### ISSUE TITLE
Webpack vote pack styling broken due to CSS 404

### ISSUE THREAD

**Issue by edmorley** [webpack/webpack.js.org#1326]
The vote page (https://webpack.js.org/vote/) is currently displaying unstyled since the CSS file referenced within 404s:
```
$ curl -sSf https://webpack.js.org/vote/ | grep '.css" rel="stylesheet"'
      <link href="/fa26aaea11cbddeb377b.css" rel="stylesheet">
$ curl -sSf https://webpack.js.org/fa26aaea11cbddeb377b.css
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by edmorley** [comment]
Strangely the file does exist on the gh-pages branch:
https://github.com/webpack/webpack.js.org/blob/gh-pages/fa26aaea11cbddeb377b.css

I'm presuming varnish has cached the 404 having raced with the deploy or something:
```
$ curl -I https://webpack.js.org/fa26aaea11cbddeb377b.css
HTTP/1.1 404 Not Found
...
Via: 1.1 varnish
X-Served-By: cache-lcy1147-LCY
X-Cache: HIT
X-Cache-Hits: 66
X-Timer: S1497978242.045070,VS0,VE0
Server: cloudflare-nginx
```

**Comment by skipjack** [comment]
I'm seeing the page load fine even after an "Empty Cache and Hard Reload"... are you still seeing the issue or was it only for a moment?

**Comment by edmorley** [comment]
The page was consistently broken before, but now works.

Looks like there was another deploy in the meantime that changed the hash, and thus busted the cache, fixing the issue:
```
$ curl -sSf https://webpack.js.org/vote/ | grep '.css" rel="stylesheet"'
      <link href="/e56afcdd06ae67effc28.css" rel="stylesheet">
```

**Comment by skipjack** [comment]
Weird, yeah we've run into this once before when a lot of builds were triggered at once. I'm also seeing a lot of pending builds -- assumably because Travis imposes some sort of limiting on builds per day or something?

> I'm presuming varnish has cached the 404 having raced with the deploy or something:

Is varnish the tool webpack uses for caching sites deployed via `gh-pages`? Your description of the issue makes perfect sense. Is there anything we can do besides spacing out merges a bit better? @bebraw thoughts?

**Comment by edmorley** [comment]
Varnish is unrelated to webpack. The response headers referenced cloudflare & fastly (both CDNs) as well as Varnish (a caching reverse proxy, see [here](https://varnish-cache.org/)) - seems like there are multiple layers between webpack.js.org and the gh-pages backing the site.

As for Travis - I was seeing delays on jobs on other repos today too - looks like they had a bit of a backlog earlier:
https://www.traviscistatus.com/

Thank you for your help!

**Comment by skipjack** [comment]
Related #845 #709 #1237

@edmorley no problem, thank you for the detailed report. Seeing as it's fixed now I'm going to close as we have some higher priority things to tackle. This definitely isn't the first time it's happened (see related issues above), but if it's just a caching issue I'm not really sure what we can do to resolve this. If somebody has ideas or a plan, please feel free to re-open. If it happens again, I will probably leave the issue open a bit longer to discuss if there's any potential if fixes.

**Comment by bebraw** [comment]
I think the only real solution would be to push the site to something more robust like Netlify. That would also improve build speeds but would require someone's time to set up.
