### ISSUE TITLE
Issue with absolute path resolved as relative

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#135]
_From @hackfaq on July 15, 2016 8:59_

Hello, I have found that issue #109  is not resolved.

Have expirienced the same problem as author of #109 , please update docs for resolve.alias, as path with "/.../ not works as relative.

_Copied from original issue: webpack/webpack#2773_

**Comment by SpaceK33z** [comment]
This is [documented now clearly](http://webpack.js.org/configuration/resolve/#resolve-alias).
