### ISSUE TITLE
Consider renaming the "support" page

### ISSUE THREAD

**Issue by probablyup** [webpack/webpack.js.org#1365]
Generally when visiting a website, "support" as a single word is where an end-user would go to find help information. The naming is a little confusing and I think people might overlook it for its purpose: to explain and drive income for the project.

Some alternate title ideas:

- Support Webpack (basically just adding a subject so it's more obvious what the page is about)
- Contribute (my favored one - not as monetarily driven and encourages community involvement)
- Donate
- Get Involved
- Become a Backer

**Comment by skipjack** [comment]
I agree and I think "Contribute" is best as well. I added a TODO in #1380 and will address soon with some other content re-organization.
