### ISSUE TITLE
Comparison is hard to read

### ISSUE THREAD

**Issue by futagoza** [webpack/webpack.js.org#1367]
I was tring to read the [comparison page](https://webpack.js.org/comparison/), but the table displaying the comparison is forced to a percentage of the page, while theres open room on the left and right sides.

I check the [source file](https://github.com/webpack/webpack.js.org/blob/master/content/comparison.md) for the page and it seem's the size of the table here is also limited, but only because of GitHub's page layout.

Is this the same for the website page? If so, can you consider making a slight change to the layout so that the comparison table is readable.

**Comment by skipjack** [comment]
I agree -- we really need 2 layouts: one with the sidebar and one without. This can be used for multiple other pages as well that don't fit into any specific section (rendering the sidebar useless). I'm about to make a meta issue that will detail a high-level plan to address this and a variety of other things.

**Comment by skipjack** [comment]
Noted this in #1380 -- will work on addressing this as soon as possible. It would be made a bit easier by a port but I have a rough idea on how we might achieve this sooner than that as well.

**Comment by futagoza** [comment]
@skipjack thanks
