### ISSUE TITLE
ProvidePlugin loads the module onto that module.

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#137]
_From @dashed on November 15, 2014 20:27_

For example, I'm using the following config:

```js
// config
new webpack.ProvidePlugin({
    'regeneratorRuntime': 'regenerator/runtime'
});
```
To load https://github.com/facebook/regenerator/blob/master/runtime.js for variable `regeneratorRuntime`. But the variable is also referenced in the file `runtime.js`. 

It doesn't seem desirable to be loading the same module onto itself, if it happens to be using the same variable that `ProvidePlugin` is detecting.

_Copied from original issue: webpack/webpack#586_

**Comment by pksjce** [comment]
_From @jhnns on November 17, 2014 14:57_

Maybe you shouldn't use the `ProvidePlugin` but make `regeneratorRuntime` global in an alias.

**Comment by pksjce** [comment]
_From @sokra on November 18, 2014 6:57_

You could use `imports?regeneratorRuntime=>undefined` on `regenerator/runtime`.

**Comment by pksjce** [comment]
_From @dashed on November 18, 2014 13:32_

@jhnns Thanks for the suggestion. I don't think that would work.

@sokra Oh man thanks! I've been struggling to figure this out. Works perfectly.

I'm guessing this is a nofix/wontfix then? One would need to be familiar with the `imports-loader` loader to hack around this type of behaviour.

**Comment by pksjce** [comment]
_From @jhnns on November 18, 2014 14:56_

The `imports`- and `exports`-loader are indispensable for compatibility issues.

**Comment by SpaceK33z** [comment]
This would be covered by #13, so closing.
