### ISSUE TITLE
Plugins - Document WatchIgnorePlugin

### ISSUE THREAD

**Issue by NicBright** [webpack/webpack.js.org#1378]
The WatchIgnorePlugin is not documented. Is it deprecated?

**Comment by skipjack** [comment]
@sokra @webpack/documentation-team any thoughts? It looks like it hasn't been updated in months but it's a pretty simple plugin so I'd say try it out. There is something in the old documentation [here](https://github.com/webpack/docs/wiki/list-of-plugins#watchignoreplugin).
