### ISSUE TITLE
Does "usage with gulp" article needs update?

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#138]
_From @kamlekar on April 6, 2016 6:45_

Hi,

I was reading this [article](https://webpack.github.io/docs/usage-with-gulp.html) where there is no mention of `gulp-webpack` plugin. It is kind of confusing of what exactly I should use. I think the article needs update mentioning whether or not to use `gulp-webpack` plugin.

_Copied from original issue: webpack/webpack#2283_

**Comment by pksjce** [comment]
_From @sokra on April 10, 2016 22:25_

yes, feel free to update it.

**Comment by pksjce** [comment]
_From @kamlekar on April 11, 2016 4:51_

@sokra I don't think I am the right guy to update it as I just started using webpack with gulp,  I don't have much knowledge on it.

**Comment by SpaceK33z** [comment]
This will be fixed with #53.
