### ISSUE TITLE
Plugins - Add HashedModuleIdsPlugin and NamedModulesPlugin

### ISSUE THREAD

**Issue by shaodahong** [webpack/webpack.js.org#1384]
[Plugins](https://webpack.js.org/plugins/) page I didn't see the introduction of `HashedModuleIdsPlugin` or `NamedModulesPlugin`. But [deterministic-hashes](https://webpack.js.org/guides/caching/#deterministic-hashes) is mentioned. Whether you need to create a new session or page

**Comment by skipjack** [comment]
Would you be interested in submitting a PR to add documentation for these?

**Comment by shaodahong** [comment]
@skipjack PR in https://github.com/webpack/webpack.js.org/pull/1392
