### ISSUE TITLE
Guides - Add Image or Analyze Link to Code Splitting

### ISSUE THREAD

**Issue by shaodahong** [webpack/webpack.js.org#1385]
Code Splitting page example is already very good, but do we need a more intuitive view to help us understand?

We use [webpack-bundle-analyzer](https://github.com/th0r/webpack-bundle-analyzer) to help us more intuitively

Use it we can get such a view：
![wx20170707-103804](https://user-images.githubusercontent.com/14831261/27940934-66b57d92-6300-11e7-8c41-117d51649d08.png)

**Comment by skipjack** [comment]
Hmmm I think we would be open to PR that mentions the webpack-bundle-analyzer or one of the other similar tools... are you suggesting adding an image to the guide?

**Comment by shaodahong** [comment]
@skipjack Yes, this will be better to see the  Code Splitting

**Comment by skipjack** [comment]
Hmmmm @TheDutchCoder what do you think? 

Personally I actually like some other bundle analyzers more and I think maybe keeping it simple within the guide (i.e. not adding any extra images) would be better. However what I do think would be good is linking to some bundle analyzers so people can try them out themselves.

**Comment by TheDutchCoder** [comment]
@skipjack I agree. I understand that visuals help, but I feel like the guides will get too cluttered.

It also would be more logical to have images like these in the documentation. The guides are really a "how to" sort of thing.

I also agree that we could link to bundle analyzers, they're very useful.

**Comment by shaodahong** [comment]
I think the image helps to understand, so that we clearly see each file contains dependencies, and I also agree that we could link to bundle analyzers, they're very useful.

**Comment by skipjack** [comment]
Yea once mermaid, or something similar, is in place (#469) a small graph to illustrate this should be an easy add.

**Comment by skipjack** [comment]
I'm going to submit a PR with links to analyzers shortly.
