### ISSUE TITLE
Release - Document Version 3.1.0

### ISSUE THREAD

**Issue by simon04** [webpack/webpack.js.org#1388]
Document changes according to https://github.com/webpack/webpack/releases/tag/v3.1.0

- [x] Allow different library names for UMD
- [x] Support for passing a defined identifier as this in a IIFE
- [x] Use the new resolve performance option cacheWithContext: false by default when it's safe
- [x] Support array of functions as configuration
- [ ] add sortModules to Chunk which is required in extract-text-plugin to support webpack 3

**Comment by simon04** [comment]
> add sortModules to Chunk which is required in extract-text-plugin to support webpack 3

See https://github.com/webpack/webpack/pull/5225. We do not have an API doc for the `Chunk` class. The immediate effect of this is a bugfix. Nothing to be done for this item?

**Comment by simon04** [comment]
> Support for passing a defined identifier as this in a IIFE

The PR https://github.com/webpack/webpack/pull/5076 classifies this a bugfix. So we can skip a documentation update?

**Comment by skipjack** [comment]
@simon04 yep I agree on webpack/webpack#5076 (just looked over that pr) and the other. It seems that they're both just classified as bug fixes. However, I'll keep the missing `Chunk` class doc in mind. The __API__ section definitely needs the most help/attention/review of this whole site. Still working my way through the backlog but I'm hopeful start cleaning that up soon. I think we'll have some other help coming on soon as well.

I'll close but, if you feel there's still something that needs to be addressed, feel free to re-open.
