### ISSUE TITLE
pre-pwa: refactor naming convention for react components

### ISSUE THREAD

**Issue by hulkish** [webpack/webpack.js.org#1395]
So, I've been talking to @TheLarkInn regarding converting webpack.js.org to be a PWA. So, this is the first of a few tasks I'm creating to lay out a plan towards that direction.

Measuring by the [current usage of react](https://github.com/webpack/webpack.js.org/tree/master/components); I'd like to refactor the naming convention of the components to use Pascal case.

For example, this is the current convention:
- `components/dropdown/dropdown.jsx`
- `components/dropdown/dropdown-style.scss`

With the proposed convention this would like:
- `components/Dropdown/Dropdown.jsx`
- `components/Dropdown/Dropdown.scss`

**Comment by skipjack** [comment]
@hulkish saw your slack message, but didn't get a chance to reply as I've been sick the last few days -- would you mind merging these four issues to one meta issue with a checklist with the four points? We can then link PRs within the checklist and mark things done as they are completed. Also, as mentioned on #1380, I would really like the issues to be mostly content-related.

Re the proposed naming convention, I'm fine with that change. How is that related to making the site a PWA though?

**Comment by skipjack** [comment]
Also we should make sure we stay in sync as we port the site -- I'm not sure if switching to gatsby or phenomic tackles or conflicts with certain parts of this.

**Comment by hulkish** [comment]
@slipjack i dont think switching to gatsy or phenomic will conflict with what i have in mind - since i am primarily focused on the react + webpack.config.js areas of the app.

Regarding the naming convention pwa dependency question.. It doesn't necessarily need to be so in order to convert to a PWA - but I figure it's a change made much easier before the actual conversion.

**Comment by Dean-Coakley** [comment]
I'd like to PR this but I'm not so knowledgeable to be honest.

It should be very simple, right?

**Comment by hulkish** [comment]
@Dean-Coakley Yea, it's pretty straight forward.. just be sure to update the import paths with the changes as well. Ex:
```js
import Dropdown from './components/Dropdown/Dropdown';
```

**Comment by Dean-Coakley** [comment]
@hulkish navigation-bar -> NavigationBar ?

**Comment by hulkish** [comment]
`NavigationBar`

**Comment by Dean-Coakley** [comment]
@hulkish Sorry for more questions but: 
Would I be correct in saying: 

`import Sidebar from '../Sidebar/Sidebar';` will import the `.jsx`
and `import '../Sidebar/Sidebar';` will import the `.scss` ?

Secondly, `Organization/projects.json` and `Support/support-additional.json` should not be renamed.

**Comment by hulkish** [comment]
yes for jsx(an assumed extension). No for scss (not an assumed extension)

**Comment by hulkish** [comment]
moving this to https://github.com/webpack/webpack.js.org/issues/1400
