### ISSUE TITLE
pwa: Add jest & create snapshot tests for existing components

### ISSUE THREAD

**Issue by hulkish** [webpack/webpack.js.org#1397]
description TBD

**Comment by TheLarkInn** [comment]
Hey @hulkish, @jorybraun is a first time contributor to FOSS and expressed some desire to tackle (a part of) this. 

This is a really larger task but I think there's more than enough incremental issues we could break this down into? 

Personally my jest experience is pretty limited so I'll yield to both of your expertise into determining the right way to separate the work out. 

Thoughts? Discuss away!! 🤗

**Comment by hulkish** [comment]
I think it could be convenient if @Jorybraun and i could share the same fork and pr for this. I'll setup the tooling and create the first few tests as a direction?

**Comment by Jorybraun** [comment]
Yes that sounds great! 

I have spent the last month creating snapshot tests for Vue components at work, but there isn't a senior frontend dev currently to provide feedback. So I think this is a great opportunity for growth :).

**Comment by hulkish** [comment]
Ok cool. So, just as a heads up I really just have in mind to create very simple snapshot tests. Explained here https://facebook.github.io/jest/docs/snapshot-testing.html

**Comment by Jorybraun** [comment]
ok @hulkish sounds great! 

So you'll be creating the fork, will we create a test directory or should we create folders and keep the tests with their relative components?

**Comment by hulkish** [comment]
Yep.

**Comment by Jorybraun** [comment]
I guess ill wait and see 💯

**Comment by hulkish** [comment]
It will be a couple hours, going to see if i can time it so that it comes after https://github.com/webpack/webpack.js.org/issues/1397

**Comment by Jorybraun** [comment]
Great, I will most likely be starting on it tonight or tomorrow, so no rush 👍

**Comment by hulkish** [comment]
moving this to https://github.com/webpack/webpack.js.org/issues/1400
