### ISSUE TITLE
API - Using Preloaded Assets with the Compiler

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#141]
_From @danschumann on March 11, 2015 14:0_

I have all my files in memory, for various reasons I won't get into ( maybe one is because I wrote a loading module `loaddir` and tend to use it ), but part of it is re-using code on the front end and back end.

My loaded files look like this (`asObject: true`):

```
require('loaddir')({path: './scripts', asObject: true }).then(function(directory) {
  /* directory == {
     'file1': 'console.log("file1");',
     'subDirectory': {
         'file2': 'console.log("subDir/file2");',
     },
  } */
});
```

or, my loaded files look like this (`asObject: false`)

```
require('loaddir')({path: './scripts' }).then(function(directory) {
  /* directory == {
    'file1': 'console.log("file1");',
    'subDirectory/file2': 'console.log("subDir/file2");',
  } */
});
```

How do I give a manifest like this to webpack, telling it "Hey webpack, I already loaded everything, can you just compile using this data plz?"

_Copied from original issue: webpack/webpack#874_

**Comment by pksjce** [comment]
_From @sokra on March 13, 2015 13:44_

You can provide a custom `inputFileSystem` to the `Compiler` instance.

**Comment by pksjce** [comment]
_From @danschumann on March 16, 2015 17:29_

Is it documented anywhere?  Or, what structure does it need to be in?

**Comment by skipjack** [comment]
@sorka can you give a little more detail on `inputFileSystem` (e.g. how/where it's passed and used)? Seems like we could just add the docs to [this page](https://webpack.js.org/api/plugins/compiler/#components/sidebar/sidebar.jsx).

**Comment by skipjack** [comment]
This [section](https://webpack.js.org/api/loaders/#this-fs) seems to be the only one that mentions it so far. Related discussion here as well: webpack/webpack#1562.

It also seems to be somewhat related to the [webpack/enhanced-resolve](https://github.com/webpack/enhanced-resolve) repository and the `**InputFileSystem.js` modules offered there.

**Comment by sokra** [comment]
You can set the `compiler.inputFileSystem` in the `Compiler`'s `enviroment` hook.

This should be an object with these methods:

```
mkdirp(path, callback)
readFile(path, callback) // only Buffer variant needed
readdir(path, callback)
stat(path, callback)
```

**Comment by skipjack** [comment]
@sokra so I do see the `environment` event listed in the [compiler events table](https://webpack.js.org/api/plugins/compiler/#event-hooks) but it says no params are passed to the callback -- is that wrong and it's set like so?

``` js
MyCompiler.plugin("environment", function(compiler) {
    compiler.inputFileSystem = {
         mkdirp(path, callback) { ... },
         readFile(path, callback) { ... },
         readdir(path, callback) { ... },
         stat(path, callback) { ... }
    }
});
```

or differently? Also it seems maybe we should recommend people use or at least take a look at the `***InputFileSystem` files in `enhanced-resolve`?

**Comment by sokra** [comment]
I recommend using `memory-fs` for you own in memory filesystem.

**Comment by skipjack** [comment]
Ok will do -- is that usage example I showed correct or incorrect though?

**Comment by skipjack** [comment]
Related: webpack/webpack#1562

**Comment by skipjack** [comment]
Hmmm I found what looks like a good example here: christianalfoni/webpack-bin#106
