### ISSUE TITLE
Error: Config did not export an object

### ISSUE THREAD

**Issue by shaodahong** [webpack/webpack.js.org#1414]
node -v
`v6.11.0`

webpack -v
`3.2.0`

I fork this project, and today to upgrade the global webpack to 3.2.0, but when `webpack -v` output `Config did not export an object`. In other projects is good

**Comment by skipjack** [comment]
You shouldn't be using the global version of webpack. See the [README](https://github.com/webpack/webpack.js.org/blob/master/README.md) in this repo -- all you need to run the project is `npm install && npm start`. Also -- just an FYI -- this project uses another build tool called antwar in combination with webpack so we don't use the webpack CLI directly to start the dev server or build process.

**Comment by skipjack** [comment]
Also, if you were just confused about why we're on an earlier version of webpack, you can see #980 which attempts to fix that problem but is blocked by a few issues atm.

**Comment by shaodahong** [comment]
@skipjack I understand the problem, just think when the `webpack -v` such a prompt is very strange

**Comment by skipjack** [comment]
Yeah I was wondering that too when I read your comment. If that is still an issue I would create a ticket on the main repo... this one is specifically for docs not bugs.
