### ISSUE TITLE
Concepts - Introduction page should use less technical language

### ISSUE THREAD

**Issue by tanyagray** [webpack/webpack.js.org#1416]
The [introduction page](https://webpack.js.org/concepts/) uses language which is likely unfamiliar to someone new to modules and bundling. It also could do with some front-loading of important info in each section.

Some examples of technical language:

- "dependencies" should be initially referred to as "input files and libraries"
- "bundle" should be referred to as "output file"
- the concept of a "dependency graph" could possibly be addressed in less technical terms

Examples of front-loading important info:

- "The _entry_ describes the file that webpack should process first. There may be more than one entry file."
- "The _output_ describes the file which should be produced by webpack. There is generally one output file produced for each entry."
- "A _loader_ describes how files of a certain type should be processed."
- "A _plugin_ adds custom functionality to the webpack bundling process."

**Comment by TheDutchCoder** [comment]
I think it would be great to reword this page so that it's more beginner friendly.

I can take a stab at it if you like!

**Comment by skipjack** [comment]
@TheDutchCoder you still interested in looking into this one? I saw you already had a related branch open... #1386 wouldn't be nearly as bad as #1258 if you have any time to get the ball rolling on it. The sections already fairly well organized, I think just a quick review and maybe some sorting should do the job.

@tanyagray are you still interested in working on the _Concepts_ section as well?

I'm going to keep trying to hit the few other content-related ones that are left and then really try to dig into the dev cleanup work so it would be great if someone could take the lead on the _Concepts_ work.

**Comment by TheDutchCoder** [comment]
@skipjack Yeah sorry, life's a bit hectic right now with the little one coming, but I think I can make some time to finish this up.

I'll take a look at the other ones as well when I'm working on this one.

**Comment by TheDutchCoder** [comment]
I created a PR for this, so if you can take a look and provide some feedback, then that would be awesome!

https://github.com/webpack/webpack.js.org/pull/1673
