### ISSUE TITLE
Which Webpack version is the current documentation for?

### ISSUE THREAD

**Issue by chrisbroome** [webpack/webpack.js.org#1420]
Webpack release [v2.7.0](https://github.com/webpack/webpack/releases/tag/v2.7.0) come out after release [v3.2.0](https://github.com/webpack/webpack/releases/tag/v3.2.0). Consequently the "release version" badge now shows `v2.7.0`.

You can see it here on the left-hand side: https://webpack.js.org/concepts/

So I have 2 questions:
1. Which version of the documentation is actually deployed to [webpack.js.org](https://webpack.js.org)?
2. Is it possible to support multiple versions of the documentation at the same time? (maybe via a url path?)

Thanks!

**Comment by skipjack** [comment]
> 1. Which version of the documentation is actually deployed to webpack.js.org?

It intends to document the latest (v3.2.0). We need to fix the sidebar.

cc @simon04 

> 2. Is it possible to support multiple versions of the documentation at the same time? (maybe via a url path?)

We've discussed this (#176, #1017) but need to get some other things in order such as synchronizing releases in some manner with the main repo. Hopefully this will be a thing at some point.

**Comment by chrisbroome** [comment]
Awesome. Great to know! Thanks.
