### ISSUE TITLE
Sourcemaps contain invalid source webpack/bootstrap

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#143]
_From @frapontillo on November 27, 2015 8:0_

When generating external sourcemaps (`'source-map'`), the resulting map files has, as first element in the `sources` array, something like `"webpack:///webpack/bootstrap 170846d63e93fb4a12c6"`.
This causes the impossibility to further reprocess the sourcemaps with other tools, as it introduces an invalid file that doesn't exist on the file system.

Is this something that can be fixed?
Thanks.

_Copied from original issue: webpack/webpack#1676_

**Comment by SpaceK33z** [comment]
Hm this is not really a documentation issue, so not sure why it has been moved.

@frapontillo, do you still have this problem. It's been almost a year ;p.

**Comment by SpaceK33z** [comment]
Closing this in favor of webpack/webpack/issues/3165

**Comment by liz282907** [comment]
i ran into the same problem...

**Comment by djskinner** [comment]
For any future travelers, this StackOverflow answer offers some explanation of why this entry appears: https://stackoverflow.com/a/45068039/120497
