### ISSUE TITLE
"stay in the same language in pre and post loaders"?

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#144]
_From @dwiyatci on April 2, 2016 22:10_

I'm about to create my first custom Webpack loader, but I'm not sure I understand well what the [loaders doc](http://webpack.github.io/docs/loaders.html#recommendations) stated:

> It is recommended to **stay in the same language in pre and post loaders**.

Hasn't the non-JS to JS transformation already happened before post-loaders kick in? So, what's "stay in the same language" supposed to mean there?

_Copied from original issue: webpack/webpack#2272_

**Comment by pksjce** [comment]
_From @dwiyatci on May 3, 2016 20:5_

🆙

**Comment by SpaceK33z** [comment]
The new docs are being rewritten, and there aren't any pre and post loaders anymore, so closing this.
