### ISSUE TITLE
Guides - Hot Module Replacement

### ISSUE THREAD

**Issue by maheshpec** [webpack/webpack.js.org#1463]
Hello,

While going through the [hot module replacement guide](https://webpack.js.org/guides/hot-module-replacement/#gotchas), I noticed a snippet line did not have + sign indicating that its a new statement.

**What is the current behavior?**
[HMR guide page's _Gotcha_ section](https://webpack.js.org/guides/hot-module-replacement/#gotchas) has a code snippet. This code snippet introduces a `let element = component();` statement. Its not present in the _Enabling HMR_ section. However, it does not have a + sign to indicate that its a new statement.

**What is the expected behavior?**
The `let element = component();` statement should be treated as a new statement by having a + in front of it and highlighting it in green.

Thank you

**Comment by skipjack** [comment]
@maheshpec I'm going to close and quote your comment in #1461 as that one mentions this error as well. That way we can keep the discussion in one place. I think we may be able to update your PR with one or two other fixes to resolve these issues for good 👍
