### ISSUE TITLE
CLA IP Policy

### ISSUE THREAD

**Issue by maheshpec** [webpack/webpack.js.org#1470]
Hi,

**What happens now?**
The [CLA agreement](https://cla.js.foundation/webpack/webpack.js.org) doesn't seem to link to the IP Policy correctly. It shows 
```
 [JS Foundation IP Policy]({{ site.url }}{{ site.baseurl }}/pdf/ip-policy.pdf).
```

**What should happen?**
The CLA agreement should link to the correct IP policy. Googling shows this IP Policy -> [JS Foundation](https://js.foundation/wp-content/uploads/sites/33/2017/03/JS-Foundation-IP-Policy.pdf)

Could you guys please fix it? :)

**Comment by skipjack** [comment]
Thank you for reporting this. The CLA document actually isn't stored at this repo as far as I know. I think this issue maybe should be moved elsewhere.

@d3viant0ne do you typically manage this? Should I move this issue to a webpack-contrib repo like [this one](https://github.com/webpack-contrib/organization) or [this one](https://github.com/webpack-contrib/webpack-defaults)?

cc @webpack/core-team

**Comment by d3viant0ne** [comment]
The CLA & it's associated bot is a service provided & hosted by the JSFoundation.

**Comment by skipjack** [comment]
Ok so then it looks like maybe I need to move this issue [here](https://github.com/JSFoundation/cla-assistant/issues) then? Will do so momentarily, but if there's a better place let me know.

**Comment by skipjack** [comment]
Moved to JSFoundation/cla-assistant#7
