### ISSUE TITLE
Inform --optimize-minimize is not required for tree shaking

### ISSUE THREAD

**Issue by esbenp** [webpack/webpack.js.org#1473]
There seems to be some confusion as to when tree shaking occurs (ie what configuration is necessary). Ref #1331 https://github.com/webpack/webpack/issues/4713#issuecomment-317601066 

Correct me if I am wrong but it seems multiple separate parts of webpack is responsible for different parts of tree shaking? Anywho, following https://github.com/webpack/webpack/issues/4713#issuecomment-317601066 I thought it might be a good idea to note in the documentation that `--optimize-minimize` is not required for tree shaking to occur.

I have added an initial PR #1474 . This is not meant as a final solution but more of an opener for a discussion of how to explain that `--optimize-minimize` is not only way to tree shaking but a production config is.

**Comment by skipjack** [comment]
Ok so as you touched on in webpack/webpack#4713, I believe tree shaking is basically enabled via a combination of:

- Using webpack's built-in support for ES6 module syntax
- Including the `UglifyJsPlugin` (either via `--optimize-minimize` or manually in a production configuration).

I'll take a look at your PR momentarily but that's one of the last guides left to rewrite, see #1258 -- [this comment](https://github.com/webpack/webpack.js.org/issues/1258#issuecomment-312139191) in particular. My preference would be to add a small note for now, as you did in your PR, and then continue this discussion in #1258 or #1331 so we can try to resolve this confusion for good in the rewrite.

**Comment by skipjack** [comment]
Also, thanks to @TheDutchCoder, we now have [a home](https://github.com/TheDutchCoder/webpack-guides-code-examples) for small examples that back each guide. We can do the same for tree shaking so we have a single place to discuss and test things.

Note that we aren't linking to those yet from the guides themselves but probably will start doing so soon, once #1258 is finished and we have time to make sure everything is in sync.

**Comment by esbenp** [comment]
I think that is a good path for this. Thanks for taking your time to clarify the roadmap for the guides
