### ISSUE TITLE
Unexpected behaviour during error handling

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#148]
_From @s-panferov on July 8, 2015 14:42_

I am the author of https://github.com/s-panferov/awesome-typescript-loader and I have a problem with my async loader:

Pseudo-code:

```
let callback = this.async();

/* inside promise handler */
try {
    callback(null, result.text, sourceMap);
} catch(e) {
    console.error('Caught', e)
    // I'm here! What I need to do in that case?  
}
```

Console output:

```
Caught { [ModuleParseError: Module parse failed: /Users/panferov-s/Workspace/arui/node_modules/react-hot-loader/index.js!/Users/panferov-s/Workspace/awesome-typescript-loader/dist/index.js?compiler=ntypescript&rewriteImports=arui&module=commonjs!/Users/panferov-s/Workspace/arui/src/popup/common/popup.ts Line 112: Unexpected token ,
You may need an appropriate loader to handle this file type.
|             || nextAttachment !== attachment) {
|             this.setState({
|                 attachment: ,
|                 targetAttachment: ,
]             });

/** stripped */
```

Versions:

```
    "webpack": "^1.10.1",
    "webpack-dev-server": "^1.10.1"
```

The big problem here is that compilation freezes in webpack-dev-server

_Copied from original issue: webpack/webpack#1232_

**Comment by pksjce** [comment]
_From @shama on July 14, 2015 21:59_

It is because you're informing the loader that it is async. Which means it will wait for you to call `callback()` to continue. Upon an error, you're not calling the `callback()` so it hangs waiting for it.

The 1st argument of the callback is for errors: `callback(err)` instead of `null`. Although it is likely you can just remove that `try catch` and let webpack deal with the error though.

**Comment by pksjce** [comment]
_From @s-panferov on July 15, 2015 7:56_

@shama 	you don't understand the problem. I **call** the callback, but **the call throws an exception** that takes place in some other loader or inside webpack core (e.g. if syntax error is in the file) and the error propagates inside my loader (I can catch it with try-catch or with Bluebird's catch handler). But I can't call the callback another one time with this error, because it throws an exception (callback was already called) in that case!

If I leave the error as-is, Bluebird thows an Unhandled exception error.

In each case webpack freezes and I don't know what to do.

**Comment by pksjce** [comment]
_From @shama on July 15, 2015 15:25_

Ah you're right sorry. Could you post a full stack trace or even better an example repo that duplicates the issue so I can take a look? Thanks!

**Comment by pksjce** [comment]
_From @s-panferov on July 15, 2015 16:45_

@shama, ok, I'll try to provide some example.

**Comment by pksjce** [comment]
_From @s-panferov on July 18, 2015 9:39_

I was because `bail: true` was written in my config file. 

So I have to write https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/index.ts#L357-L362 inside my async loader. The problem is solved, but I thing that the behaviour of the `callback` function in bail mode must be documented somewhere.

**Comment by pksjce** [comment]
_From @shama on July 18, 2015 15:2_

@s-panferov Oh nice find! The documentation is openly editable to anyone. Would you mind adding a note about it here http://webpack.github.io/docs/configuration.html#bail? Thanks!

**Comment by pksjce** [comment]
_From @bebraw on November 14, 2015 18:5_

@s-panferov Can you look at that documentation bit so we can get this closed?

**Comment by skipjack** [comment]
[Same section under discussion on webpack.js.org](https://webpack.js.org/configuration/other-options/#bail) -- editable [here](https://github.com/webpack/webpack.js.org/blob/master/content/configuration/other-options.md).

**Comment by bebraw** [comment]
Let's close.
