### ISSUE TITLE
output.libraryTarget is undocumented

### ISSUE THREAD

**Issue by emulbreh** [webpack/webpack.js.org#1480]
[Targets](https://webpack.js.org/concepts/targets/) mentions `output.libraryTarget` and links to [Output](https://webpack.js.org/concepts/output/), which doesn't contain any information about that property.

**Comment by skipjack** [comment]
Thanks for reporting this but I have good news for you! It is documented, just not on the __Concepts__ page. See [this section](https://webpack.js.org/configuration/output/#output-librarytarget) of the __Configuration__ `output` page.

**Comment by skipjack** [comment]
We should do better at the separation between __Concepts__ and __Configuration__ (or other sections of the docs). I think this can be addressed in #1386 and each __Concepts__ page should probably end with some links to other sections of the documentation.

cc @tanyagray @TheLarkInn
