### ISSUE TITLE
Compiler watch mode needs example(s)

### ISSUE THREAD

**Issue by alex-r-bigelow** [webpack/webpack.js.org#1493]
The documentation outlines ["two flavors of execution,"](https://webpack.js.org/api/plugins/compiler/#watching) but doesn't say anything about how to choose one mode or the other, or provide relevant examples of each.

**Comment by skipjack** [comment]
Essentially, watch mode is used in development, when you want to keep rebuilding every time a change is made, and normal compilations are used for production. I think maybe mentioning that and linking to the development/production guides from there would resolve this issue.

I don't think we add full-on examples on that page as it's really more of a reference page than a guide.

**Comment by jennings** [comment]
@alex-r-bigelow Would [this change](https://github.com/webpack/webpack.js.org/pull/1495/files) clarify the documentation? I added links to the [Node API](https://webpack.js.org/api/node/#watching) and the [CLI watch options](https://webpack.js.org/api/cli/#watch-options) so the reader can see how watch mode is invoked.

**Comment by alex-r-bigelow** [comment]
This is good, but it's still not super clear how to enable watch mode. Of course `webpack-dev-server --watch` works—and documentation about that exists everywhere—but it's not clear how to do that from inside Node. From this documentation, my initial guess would be to do something like:

```
import {Compiler} from 'webpack';
const compiler = new Compiler();
compiler.options = {
  watch: true
};
```

... but that's probably wrong (if it's right, it's not documented). Or maybe I'm misunderstanding what Compiler is for in the first place?

**Comment by jennings** [comment]
[This page has the Node API documentation](https://webpack.js.org/api/node/#watching) and does mention the `.watch()` method on a Compiler instance.

```javascript
const webpack = require("webpack");
const compiler = webpack({
  // Configuration Object
});
const watching = compiler.watch({
  /* watchOptions */
}, (err, stats) => {
  // Print watch/build result here...
  console.log(stats);
});
```

The audience for [the documentation page we're discussing](https://webpack.js.org/api/plugins/compiler/) seems to be those writing a webpack plugin. If I understand it correctly, plugin writers don't need to create a Compiler or invoke it; the Compiler will call the plugin's `apply()` method, passing itself in as the first argument.

However, if a plugin is interesting in knowing whether the compiler is running in "run" or "watch" mode, it can subscribe to the "watch-run", "watch-close", and "invalid" events. These events appear to only be emitted while running in watch mode.

**Comment by alex-r-bigelow** [comment]
Ah, that makes sense... I *am* misunderstanding what Compiler is for in the first place. The use case that brought me to this page was trying to run two development servers on the same port, and I was trying to wrap my head around the fuzzy line between the Compiler and [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware).

I eventually figured it out just by setting up an express server to proxy independent `webpack-dev-server` instances running on different ports.
