### ISSUE TITLE
Guide - Get started

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#15]
[Stub](https://github.com/webpack/webpack.io/blob/develop/content/get-started.md).

Feel free to comment here if you have ideas on what this guide should cover. Link to potential resources too.

---

To quote @logaretm from #29:

Maybe it should cover:
* What is Webpack? (in a small paragraph)
* Establishing Mindset (JavaScript file as entry point) or how it works at its highest levels, some colleagues had issues understanding how it works since they were using gulp.
* Files and Loaders (in two or three lines).

Then move on to a small example:
* Installation.
* Basic html page with an entry point, that just logs something or manipulates an element using jQuery.
* Bundling the JS files.
* Extracting chunks (like vendor) with CommonsChunk plugin.
* Adding CSS (css loader and style loader).
* Adding static resources like an image (file/url loader).
* Optimization (Uglify, Clean).
* HMR.

probably that would be somewhat enough to get used to most of Webpack concepts at a high level. I'm not sure if its too short or a bit long.

Probably some short version of [this post](https://blog.madewithlove.be/post/webpack-your-bags/).

**Comment by Awk34** [comment]
Note: Apparently the ['What is webpack?'](http://webpack.github.io/docs/what-is-webpack.html) section of the current 'Getting Started' is confusing to many. Maybe it needs to be simplified *even more* from where it is now?

**Comment by bebraw** [comment]
Yeah. That's a valid point.

I took a historical approach in my [intro chapter to webpack](http://survivejs.com/webpack/webpack-compared/). Maybe a similar idea would work here so you get the context before digging into webpack itself. If you don't understand the past, it's hard to appreciate the ideas.

**Comment by Awk34** [comment]
@bebraw Nice article! I think that is spot on. Many people don't understand what Webpack is meant for.

**Comment by bebraw** [comment]
I'm thinking a structure like this would work:

1. Bit of history for context (adapt from above and link if someone wants to read more).
2. Basic features of webpack. This would be a good place to link elsewhere in the documentation and show how the bits go together (loaders, plugins, entries, output) on a basic level.
3. Brief comparison to show what tool to use and when. This shows webpack in context and highlights alternatives. For some usage a simpler tool like rollup could be completely enough. And this gives a better idea of how Grunt, Gulp, and such fit in.

Actually now that I think of it, we probably want a 5-10 minute intro to webpack. The current documentation has something. It would be a technical sibling to this first one and would show the basic concepts in practice.

**Comment by bebraw** [comment]
FYI, I added [a stub for 10 minute introduction](https://github.com/webpack/webpack.io/issues/29).

**Comment by pksjce** [comment]
I would like to pick this up. Looks like its not been taken by anyone yet.

**Comment by bebraw** [comment]
@pksjce Sure, do a quick draft at first of the planned structure so we can avoid a bit of effort. 👍
