### ISSUE TITLE
Wrong proxy documentation

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#150]
_From @0x80 on March 8, 2016 11:25_

In the current documentation it is suggested that you configure the proxy using a path as key. I could only get it to work when you pass it an array of objects like this:

```javascript
proxy: [{
      path: new RegExp('/api/(.*)'),
      rewrite: rewriteUrl('/api/$1'),
      target: 'http://localhost:9000/'
    }],
```

_Copied from original issue: webpack/webpack#2152_

**Comment by pksjce** [comment]
_From @sokra on March 9, 2016 7:34_

You can edit the documentation with the button on the top right corner.

**Comment by SpaceK33z** [comment]
This has been fixed a while ago, the v1 docs are correct, and v2 also.
