### ISSUE TITLE
API - Resolver documentation confusing

### ISSUE THREAD

**Issue by 43081j** [webpack/webpack.js.org#1505]
Regarding [this page](https://webpack.js.org/api/plugins/resolver/).

I noticed webpack allows plugins in the `resolve` config ([`resolve.plugins`](https://webpack.js.org/configuration/resolve/#resolve-plugins)). So I assumed these kind of plugins are defined as per the documentation found [here](https://webpack.js.org/api/plugins/resolver/).

However, this page gives absolutely no information at all about creating a "resolver" or how to go about implementing one. It mentions what methods a resolver has access to and should use, but not how to create one.

It would be of great use if there was at least a linked example, or the boilerplate of such a plugin.

Edit: Removed second issue, as it was a scoping problem on my end.

**Comment by 43081j** [comment]
Another example is that the same page specifies `resolve` takes `(string, string)`. But in actual fact it seems to receive `(object, function)`. 

Presumably the second parameter is a callback and the first is some sort of object representing what the docs think are in it?

**Comment by skipjack** [comment]
This seems pretty related to #1458 and @mlcohen's [description of resolvers](https://github.com/webpack/webpack.js.org/issues/1458#issuecomment-330445790) and the [enhanced-resolve](https://github.com/webpack/enhanced-resolve) package. @mlcohen I've dug into this a bit more the over the last day or two and here's what I think we should do:

- [ ] Submit a PR to the `enhanced-resolve` package's README with some of your write up.
- [ ] Add another section called "Utilities", similar to loaders and plugins, and dynamically pull in all utility README's as page (similar to what we do for plugins and loaders).
- [ ] Break the [Resolver](https://webpack.js.org/api/plugins/resolver/) page out of the "API > Plugins" section to a single page or group (i.e. API > Resolvers > [multiple pages] or simply API > Resolvers (single page).

What do you all think about this approach? @43081j in the meantime I would recommend reading @mlcohen's detailed comment and checking out the `enhanced-resolve` package as that's really what's used to create resolvers.

**Comment by skipjack** [comment]
Created an issue over at webpack/enhanced-resolve#133 and rewrote the `resolvers` page on the next branch in #1754 to make things a little more clear and offset much of the actual documentation to the package's README to avoid duplication.

We can look into creating that __Utilities__ section later on.
