### ISSUE TITLE
Plugins - Test Option in the SourceMapDevToolPlugin

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#151]
_From @awong-dev on February 20, 2016 0:30_

This makes handling jsx annoying, especially in Karma.  See
  https://github.com/webpack/karma-webpack/issues/104

_Copied from original issue: webpack/webpack#2078_

**Comment by pksjce** [comment]
_From @af7 on March 15, 2016 9:30_

+1

**Comment by pksjce** [comment]
_From @bebraw on August 29, 2016 7:15_

As mentioned in the linked issue, the problem is at https://github.com/webpack/webpack/blob/5b5775f9e2fc73fea46629f2d6a3ed7a1f8424d3/lib/SourceMapDevToolPlugin.js#L35 . By the looks of it you should pass custom `test` that includes `jsx` somehow.

**Comment by anvish** [comment]
Workaround: 
```
config.set({
...
        webpack: {
            ...
            plugins: [
                new webpack.SourceMapDevToolPlugin({
                    test: /\.(js|css|jsx|ts|tsx)($|\?)/i,
                }),
            ],
        },
...
```

**Comment by idiotWu** [comment]
Same for `.ts|.tsx` too. It took me a whole day to figure out the problem 😢

**Comment by jroitgrund** [comment]
Thank you so much for this @anvish

**Comment by viankakrisna** [comment]
@anvish where do you place your code?

**Comment by skipjack** [comment]
The `test` option is documented now on the [`SourceMapDevToolPlugin` page](https://webpack.js.org/plugins/source-map-dev-tool-plugin/). @bebraw do you think there's left to do for this one?

**Comment by bebraw** [comment]
Time to close.
