### ISSUE TITLE
Unexplained Code Change in Caching Guide

### ISSUE THREAD

**Issue by trautlein** [webpack/webpack.js.org#1512]
On the [caching guide page](https://webpack.js.org/guides/caching/) there is a change in the code that isn't noted or explained. The example goes from using `[chunkhash]` to `[contenthash]` without an explanation. The diff's in the documentation also don't show that this code has changed. I'm not sure why the change in the code occurs so I thought I would report it here.

The change happens inside the [extracting boilerplate section](https://webpack.js.org/guides/caching/#extracting-boilerplate).

**Comment by skipjack** [comment]
This is a mistake. It should be chunkhash everywhere. I thought this was fixed recently but maybe not all instances. Would you like to submit a PR?

**Comment by trautlein** [comment]
Totally would have but it looks like you beat me to it! Thanks for maintaining this docs so well!

**Comment by skipjack** [comment]
No problem, yeah it was a quick fix..
