### ISSUE TITLE
DllReferencePlugin doesn't explain string form for 'manifest' parameter

### ISSUE THREAD

**Issue by bijanvakili** [webpack/webpack.js.org#1513]
The `manifest` parameter for `DllReferencePlugin` also supports the ability to pass a string (as an absolute path) rather than an object.   The logic is implementation [here](https://github.com/webpack/webpack/blob/master/lib/DllReferencePlugin.js#L27).

This has been supported since [this commit](https://github.com/webpack/webpack/commit/530fad43b418dbf78c484eda78b5b22fba086ee9).

The documentation should clearly indicate that the `manifest` parameter can also be specified as an absolute path string.

**Comment by skipjack** [comment]
Thanks for pointing this out. Would you be interested in submitting a PR to resolve this issue?
