### ISSUE TITLE
Comparison - Talk About webpack vs SystemJS 

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#152]
_From @TheLarkInn on July 1, 2016 12:47_

**I'm submitting a feature request**

**Webpack version:**
1.10.x/2.x

There has been a lot of community confusion in regards to SystemJS and Webpack. This issue is a stub to add some documentation talking about the difference between a module bundler and a module loader and how they perform 2 different things.

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**

**Expected/desired behavior:**
- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
- **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...] 

_Copied from original issue: webpack/webpack#2727_

**Comment by pksjce** [comment]
_From @jackfranklin on July 1, 2016 16:6_

👍 awesome stuff - pinging @guybedford who is the authority here rather than me.

I think we can take some inspiration from Guy's talk yesterday at PolyConf which talked through the reasons and motivations behind jspm / SystemJS, which I think will clarify to a lot of users where and how Webpack/SystemJS differ.

I don't think it matters if this lives on the jspm or webpack site, as long as one links to the other.

**Comment by pksjce** [comment]
_From @sokra on July 8, 2016 8:40_

https://github.com/webpack/webpack.io/blob/develop/content/concepts/compared-to-other-systems.md

**Comment by pksjce** [comment]
_From @TheLarkInn on July 8, 2016 12:25_

Although it's clear to me we need just a paragraph or so differentiating a bundler and loader.

**Comment by skipjack** [comment]
The current comparison lives [here](https://github.com/webpack/webpack.js.org/blob/master/content/guides/comparison.md) in case anyone was wondering. It doesn't seem that SystemJS is mentioned anywhere there so maybe adding a column would be good.

> Although it's clear to me we need just a paragraph or so differentiating a bundler and loader.

@TheLarkInn yeah it seems maybe this could go somewhere in concepts as it's a bit more general? Or maybe a section or two under the comparison table would work as well...

Out in the wild (for reference):

https://engineering.velocityapp.com/webpack-vs-browersify-vs-systemjs-for-spas-95b349a41fa0
https://stackoverflow.com/questions/38263406/what-are-differences-between-systemjs-and-webpack
