### ISSUE TITLE
webpack-dev-server changeOrigin option?

### ISSUE THREAD

**Issue by blueshirts** [webpack/webpack.js.org#1521]
It seems like changeOrigin is a valid option for the webpack-dev-server proxy settings though I don't see it documented anywhere.

https://webpack.js.org/configuration/dev-server/

Should this be documented?  I am unsure what it's exact purpose is.

**Comment by skipjack** [comment]
So where/how did you find that `changeOrigin` is a valid option?

**Comment by skipjack** [comment]
`webpack-dev-server` passes the `proxy` options to the [`http-proxy-middleware`](https://github.com/chimurai/http-proxy-middleware) which is linked to and documented in the proxy section of the dev-server page:

https://webpack.js.org/configuration/dev-server#proxy

The `changeOrigin` option is documented in the other package in their README. If it's not documented well enough, I would open an issue over there. Also, if you want to highlight the relationship between the two packages a bit more then feel free to submit a PR here as well but we shouldn't re-document all options (i.e. linking out is the right way to go so we don't duplicate existing documentation).

**Comment by blueshirts** [comment]
I saw the changeOrigin option in one of the examples in the old webpack documentation.

https://webpack.github.io/docs/webpack-dev-server.html#proxying-local-virtual-hosts

**Comment by blueshirts** [comment]
I found that it was a valid option b/c my proxy would not work without it.  I initially did not see the link you mentioned, thanks for the insight.

**Comment by skipjack** [comment]
Ah ok... yeah like I said if you wanted to submit a PR here I'd be happy to review but imo there's plenty of docs on the `proxy` option already and the link to `http-proxy-middleware` is good. Like I said if anything, I think the link should be highlighted more so that it's as clear as possible that these options are actually handled by another package.

Thanks for highlighting this though and definitely feel free to submit a PR. I'll keep my eyes out for anyone mentioning something similar (which would definitely indicate that link should be highlighted).

**Comment by ebuildy** [comment]
``changeOrigin`` is a very important option, as you can see in http-proxy code source, it's change the host header, could be necessary according the targeted server configuration.

```
if (options.changeOrigin) {
    outgoing.headers.host =
      required(outgoing.port, options[forward || 'target'].protocol) && !hasPort(outgoing.host)
        ? outgoing.host + ':' + outgoing.port
        : outgoing.host;
  }
```

**Comment by littlee** [comment]
I also think `changeOrigin` should be documented, the "documentation" link in webpack-dev-server's github repo is https://webpack.js.org/configuration/dev-server/#devserver, which jump to webpack documentation.
![image](https://user-images.githubusercontent.com/7534668/46196319-4b60fe00-c339-11e8-97c5-e99bbd821ae4.png)

But I can't find anything about "changeOrigin" there.
![image](https://user-images.githubusercontent.com/7534668/46196382-7d726000-c339-11e8-98cc-7670f2d36c07.png)

**Comment by Yiidiir** [comment]
Seems like `changeOrigin` is sent to `option.changeOrigin` of [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware), which is deprecated based on their [README.md](https://github.com/chimurai/http-proxy-middleware/blob/master/README.md)
[DEPRECATED!](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAmAAAAAtCAYAAAAJMtdLAAAPJElEQVR4nO2d728UdR7H/WPmyTRhVsjaZGtoI42SciWuIj2tkYQIoYFKXQhIyTXtiYnUM7ZXobZwnJazRL3d3F5sSpreeWo0AS4QGiwc+AAfYB+VBwJrtz7gfQ9mZnfmO9/5td2d/dH3K/k86O7M99d8Zz7v/Xw/8+0TIIQQQgghkfJEtRtACCGEELLeoAAjhBBCCIkYCjBCCCGEkIihACOEEEIIiRgKMEIIIYSQiKEAI4QQQgiJGAowQgghhJCIoQAjhBBCCIkYCjBCCCGEkIihACOEEEIIiRgKMEJIQ/L48WPkV1eR+/VXPHz0iEajldFyuRzyq6vVvs3rGgowQkhDsvrbb1V3UjRaoxtFWOlQgBFCGpJcLld150SjNbo9yuWqfavXLRRghJCGpNqOiUZbL0ZKgwKM1BHLmDncCiXWiT9dqnZbSK1TbadEo60Xk5NFr6qhY/R6pPd9ebiOkc7Kt71uBNjCaBKKmkIWABbG0KFqUBxmfG9DnwSOY/vMI/WBFr+3D7z8mGIZZlUpSZs09DobhWxfsOP0ficxsuBfj73tLm3uHMOCRxucfTeOs5xXPZYx89YWNG18GR9VvzE1gX4NhflhoM8d+byKFq+HWeUedNV2SjTaejE5FGB+1IcAWxhDh9XJiH+bHxsOxz5o+iRwd0KSgTYEXvEz2cUwhJ1VhGVTLiJQ7IvkwmZTkoudRa+aRIfXRHAZiyATKNsnEZEFwWrtRzST0c5dfPn2Ljyb6Pcez3VO9ALsEv66pwuJl0+HEOTrVYDdxIcvaFBemMCNqrfF2a5Ds9VuR62Pf61ev9qzaPDz5eWkgQTYLw8e4J13h7Gp+Wkoqoae3j7cu/dz4PMXRpN2oeAqOmCIIOt3JQgws85C1MflYmRT9siQrwALOYHM8r3KLbsAK54bWlyWFTOCF2Wd9Uf0AswQ6KEioo0pwGaOaNg+frMOHXg9CDBj7AqR+WOYKbWMBhVg/vMvOosGCrCS6OntcyxzbWp+OuDZ+kDYBt1LgDkGrjQBZhccQUSaeI4Tx/E+ZPvsy4nSPlREgEHSl2CT/+GNv2Pg1Q48GdOv84ZEFw5MfoMloRylcwxXrpzB61uaoagamp7agaOZW8gX+iRfXpYJjvxP/8bEwS7EN2pGWR14eTCDWyv2sVDUFDK3MjiaTKDJqHNgrtgy6fioSYxcuYKJvc9hg6pBiSXQ+Za1bLM/b2NicIfeb3NMH/6ALwZ34Zmn4nofNrYiefAMvl4CgDzmj7dCUTW8OHnb7InxWSt6s7M42a5BUfdh+r6lUfc/x+sxDcrOM7jjMh4mUgG28hO+mnwTyYQ+7kosgWdeHULmVr54zNI3tvHckOjCB5cgX/ruHMOC71JDSAEm1mObo+LSuvv9tp4cYDirdQFmCJ8jFwuf3RjfWbNCqFpWS/NPjuAzCr7KnhYk9avi95Jnj/W5Zk+nEZ+H4jND8rwUfE7HaLYxBNi9ez+75ip9PPWpfwELY+gQH7KeAkwUFhWKgBkXzFaupwALqaiFPrqKt0oJMEe5/uXlr46hM6ZB2fg8DoyeR/r8GA78rhmKGkfn6DVdXJmCpW0r2jZ3YWAyjanRN7F1owZFbUX/fB64fw0X05PY36ZBUV/BUDqNdPpb/AiJ4FjKojehQYltwY7Bs0inz2KgawuaVA3xvqwh/MwbsBXxLc/j6GQak4NdiKsalFgPPrsv749eVzva2rcgOXjW0h8N8ePz9v6oGuJ9GfxkCrOVaxhJxqGozdh6cAxT6fMYOfg8NqgampJjuLYCYGUe/QkNSnMK2fsozKlN+zNYAnB5eCsUVcPu6eVCm5Y/70GTGsfrny9b2hhUgC0h29cKRY0j0TWEyXQak4PdSMQ0KIkUsksAcBtnu+NQYtuwb/Q80unzGNm/DaksgB+/RTp9Ai+qGpS2gxhPp5G+eA3L5RRgjnmXRa+Qr2ktx5YbKhDIyUsjLKZAuYhDhe934sNFixiQPdNEwSD5vBz1B7bZY7b2FZ21Wb61Dc7yZ46spX1i/3Szij5b+VZxNXtMEvGyi8Yb4zuxffymbZytYiT8+Nvb531+ma5PiRZ0/rmPj0SAzx5zCFzX67MmASb8aBJXrEQfujCGXp9gisOPScq0nuN4Zkh8uSno6l6AXbr8X1cB9udTH/kXIC7zAb4CzL5kKU/CLw62+y9w8Ri3ZHbxPFnkxjOK5dYHax1uffYRYF4J9p4CzMg/s5brffwyPtsbh6JuxYnvLNGUlTkcbdagxFLIrpjl6sJq4k7xsPzccWxSNWw6Pi+03+5cRcGhi5Q4dk9bI1m3MbHTepxZlrVteWT74lDUFvTPQ4p5ExYjVJb+NA9gvjBOGsRIlS6UNLS98x2Ko5HH3LEWKGocvVn90+WZI4irGtqG5zC9Jw6l+Q1kzK7cOaOLnT0XsGyM8fQeDUrzccyt2NvoZYU5d+k9tKkamvZcgHW07ky+YpkbM0jFNChtQ/jqYbHdeUfEr0JLkF4/YmTPAo8fWH7iy+GwC06m6JxtDlnioPwiEDfGd7o6cP/6BdEnFRJe4stNFLj0T3DgDrEUon0zR6yCwNlf+/f2v936ah3vgrAw27Q4ge2S/nqV5dW+INdvTdenDOY1/7zHx1+AeV2ftQow+71qv/+9V4kk97osQOMXLBB8ptyvNcgS5C8PHrg6hvl/feVfQAkCrJQImL1t8hCm/Ve637KlvJ5gF1Qm1lzOjywCJsnFs2E47m0juCarp1CWiwNfyaBH1aAkT2PR0n5vAfYDTiU1KOobyKzAhj36Iy/LL0dKHl3KI7Nfg6K+hFOL7v2ZORyHom7H+1fFQlOCEF5CZn8LlFgcTWoLejJWaWSKWkPc3b+A3aqGTcfmCqJOb2MLOnvewuEjdtubbLH1b/HUS1BUDT0Zi0AGir9M+7IA8vj+5DY0qZqxZDqGL288tBxc6Ryw4v3otzThthxh4uq8Fiew3RFhuYhDXg7K9v0aBVgp9UsiFKU655LKt33vd77ze/s4OMfSOiZuzt4hwGztlZTpI6Dc2xf+/HDXxxo5Cx5lCi3AXMfHr/3e12dtAszHt1oCJs57WuLLPXYE8ExrEH6cO+tqEAEGAJl//NMxOEf7/xDs5NACTBzQEnPA/I6RiS2fHDDvCJJYjltEI+hybBlywIRxr6gAu3sOv7dFe2pVgN3F2W5rxGutAszY20zVoKitSM0s2w43I4O7p5exPL0PiroVJy17oIVZggwmwAAgj+XrX2LkoJHTpraiN2sKw6iS8IsPYtuv4yD3j4Gr85I6S6tTqrAAK6X+UA7eL8crQPmLE9juKhDCRlCECJOsbLUYUQocAQsQcapkBGwtArkc5ivAXMfHp/0+16eyAsx6rCjEXASY57NI8uy3tWMdCDAAuHnrf3jn3WH09Pbh46lP8cuDB8FODCnAnCHMCgmwUt4UdLyh6XKYmzCShXArIsACrrXbMIVJEu9ftS5BfoPBNuuymeFYY/tgXTVcmt6nL9kNX7a1328Jcv54CxRH5GgJU7s0FJc51yLAhOXNpQvYHdOgtL+Hy5axEufo3b+8pouHD67ZliC//mM7FLUFR+f0T5eyKcRVDR0fXMCJdg1K4ghmbDlp8+hv1tC09zRGurVC8r3beFhx9G9+QF/mNXLMCl2a2o3iUutDPLQEvPI3x/Vl0O5zuOvRXz9c95ILkk5gnhfyTVxX51VKBEpyTu1GwNwFRTABITk/VARMzB8TI1ryaJV3X/WokduSaUkCzLV9fufXSQSsVAHmd30k5nLXly7ArM8Nr9Usn+eH9HuJAHPbjqlhBFjJBE7Cd9u2oFICDE5BFMBBuDr9wj5g3u11iKByCzBHhCZ4efn5IT2h25GE34zuT8w8KlOAxbHhuV6MnLckgttEmZHvpMbRfvgspgZOYwYSwXFnCt0bNUkSfhyJQTNRPogAMzZ5jb2EU9bcADWOpo1GQvrkEHZsjguizG1JdR4Dm+VJ+Btem9JFlPkCQfu7+H4FyM8PIK5qiB+egTUOdnl4q7FEKeSjycbDtX8AcBufvKa/FCEm4TdtHsK8IZBTm7sxMJlGOp3G5GF9OTI+aKYLfIcTbXpUrHv4PEaHpwK8BQmXZXv5jxhHwmxhbCV77+E6RvrkYjCMQJHlODlyoASHFuTNvKA5YH71e4kS2RYNeg6Q25JREAds/d6oJ3D7LuKQz7YR3jlFen3u47NWAebfviDXr9oRMK/55zc+tvE3I14eOWB+Jie8AFsYTXnkHXsEQoTnb7bPfNaL/tT0BWLiv08SfsDgSVhqX4C5ql6fNV/hfL/k+JIEGMwLZZTltnQoihyPbRa83upCoQ7LRAiZhG89V57A7VZ3sG0olr4+gwM7WvUtG9Q4nnx2FwbM7SUs5SidI5jN9KPzKV3QPJnsxxe2XCMgf/VcYZuKDVtO4j+QC478rYzP1hdhBNg2DF+yjk8S78/at644+sUPKLbUIyIkbOdg3x7DyP1SW9CbNeXWkp6ILy5Fmsn4kjc2w29DcQsZ160xAOASxi1j6dzSA1iaGypet71/w93Avxad96I8j9JyjEvSvV/+F+D3FqQQhbA5MskbckHepBOWtBz3liMK5F3/WgRYwQlb6gj1FpztDcqd+HB2AttDCETpm3q2/vuNsdf4BIvweNXv3T6/82tDgLnPvwAC1bbMeAwzi9brG+YeKLcAE/I8Pf7bjNdLcu75X0mMZCXtEJ47vVnZy0HrUoCFyJ0ilaNsG7GWtoRVDbzETaQYAsyafE/8Watjq919smrcpG8kilE1tq+RjJRGXQgw33VeUmHKmZBIARYW/VehsUcaCUzpDoUCbE0m2wLDZZsItq8xjJRGfQgwBFiaIxWjvP+MmwIsKP/55D2MGDlaYuI88ad0h0IBtlZzLvHVlrip9fbVm5HSqBsBRhoFCrBw9Tejde85fed8EopcLld1x0SjNbo9yuWqfavXLRRghJCGJL+6WnXnRKM1uuVXV6t9q9ctFGCEkIaFIoxGq4w9yuWwks/j8ePH1b7N6xYKMEIIIYSQiKEAI4QQQgiJGAowQgghhJCIoQAjhBBCCIkYCjBCCCGEkIihACOEEEIIiRgKMEIIIYSQiKEAI4QQQgiJGAowQgghhJCIoQAjhBBCCIkYCjBCCCGEkIihACOEEEIIiZj/A+3OG70O5kDDAAAAAElFTkSuQmCC)

**Comment by ucanuupnocannobb** [comment]
> 那么你在哪里/如何发现这`changeOrigin`是一个有效的选择？

hello
