### ISSUE TITLE
Dev - Eliminate FOIT

### ISSUE THREAD

**Issue by jeremenichelli** [webpack/webpack.js.org#1536]
Currently the site experiences FOIT _(Flash Of Invisible Text)_, which hits critically in speed index and critical rendering path.

I suggest using system fonts until font is ready and caching Google Fonts stylesheet on Web Storage for future visits. I wrote about this solution some time ago: https://jeremenichelli.github.io/2016/05/font-loading-strategy-static-generated-sites/

I would be glad to tackle this issue and other perf improvements on the site but I don't know if I'll have the time so I'm opening this issue in case someone grabs it first.

Reference: WebPageTest video https://www.webpagetest.org/video/view.php?id=170822_56_71cdab6b373bdf426e921032cc97f012.1.0

**Comment by skipjack** [comment]
@jeremenichelli thanks for bringing this up. I thought we did have some fallbacks set up at least for certain elements but if you'd like to improve on this or fix any missing ones that would be fantastic.

**Comment by skipjack** [comment]
Also moved to #1400. If you elaborate on exactly which fonts don't already have fallbacks I may pick this up. As you mentioned, it should be a fairly quick fix.
