### ISSUE TITLE
Dev - Move icons to SVG images

### ISSUE THREAD

**Issue by jeremenichelli** [webpack/webpack.js.org#1545]
I was on a slow internet connection and discover the icons come from a font which adds **tofu**
boxes, delays content showing and makes FOIT worse.

We should definitely move to SVG, something that will also improve visuals on 1x pixel density screens.

I think that this, plus https://github.com/webpack/webpack.js.org/issues/1536 plus a better hosting server (something I've seen in the issues) will have a big positive impact in content serving.

**Comment by skipjack** [comment]
Can you be a bit more specific about which icons aren't SVGs? Most of our [assets](https://github.com/webpack/webpack.js.org/tree/master/src/assets) already are as far as I can tell.

**Comment by jeremenichelli** [comment]
Sorry for not being as clear as I should 🙏  I catched icon fonts in the desktop header to be more specific, even when SVG files are used on the background, they are still fonts.

My suggestion is inlining them, a react component would work for sure.

**Comment by skipjack** [comment]
@jeremenichelli no problem, yes I understand now. I think we may want to use react components for easier customization which may take a little thought. I might add this, and #1536, into the one of the other dev checklists ( #1525 or #1400 ) as our goal right now is to continue keeping the focus on cleaning up the content of the site. That said, you should feel free to start digging into these things and submitting PRs. I'd be happy to help push this and the other forward.

**Comment by skipjack** [comment]
Moved to #1400.

@jeremenichelli seeing as both you and @pierreneter seem interested in helping to tackle dev improvements (specifically performance and pwa it seems) I'll be inviting you both as collaborators and also to our slack channel. Looking forward to working with you both!
