### ISSUE TITLE
Dev - Should Support Files be Ignored?

### ISSUE THREAD

**Issue by jeremenichelli** [webpack/webpack.js.org#1554]
I just did a _clean clone_, run `npm install`, then `npm start` and these two files appeared as added:

- `src/components/Support/support-backers.json`
- `src/components/Support/support-sponsors.json`

Should they be added to `.gitignore`?

**Comment by skipjack** [comment]
They should be and it looks like they already are:

https://github.com/webpack/webpack.js.org/blob/master/.gitignore#L5-L7

However I'm seeing the same issue.

**Comment by jeremenichelli** [comment]
Yeap, they are. Super weird. Don't know if it's cached or an encoding discrepancy.

**Comment by skipjack** [comment]
Fixed in #1555 ... will merge as soon as the build passes.

**Comment by skipjack** [comment]
Just some git weirdness left over from the restructuring.

**Comment by skipjack** [comment]
I also simplified the `.gitignore` a bit. I think we may want to follow some paradigm for all our "generated" files. Maybe prefix them with an underscore or two so we can just ignore a simple pattern (e.g. `__backers.json` and in `.gitignore` => `__*`).

**Comment by jeremenichelli** [comment]
Yeah, I was about to suggest something like that, or `__fetched__` prefix, to be more obvious about them.

**Comment by skipjack** [comment]
Sounds good. Feel free to dig into that if you have time.

cc @pierreneter
