### ISSUE TITLE
Dev - Code Block Alignment on Home Page

### ISSUE THREAD

**Issue by jezmck** [webpack/webpack.js.org#1559]
![This image](https://pbs.twimg.com/media/DIZWCgCXgAErw6p.jpg)
demonstrates a minor alignment issue on the code blocks on the homepage, visible only when the blocks go over two columns.

**Comment by pierreneter** [comment]
Thank you for reporting this issue, fixing it is part of what I'm doing in PR: #980, we are actively working to finish as soon as possible and merge it.
