### ISSUE TITLE
Update Travis for new repo name.

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#159]
It appeared CI is failing with the new repo name. Can't find the repo/project, etc.

**Comment by TheLarkInn** [comment]
@bebraw do I have access to modify travis?

**Comment by bebraw** [comment]
@TheLarkInn You would have to ask Tobias for rights. I don't know how it works out with Travis.

**Comment by TheLarkInn** [comment]
Looks like this is happening now correctly, I think it was just a stale testt.
