### ISSUE TITLE
Translation -  Arabic and Turkish 

### ISSUE THREAD

**Issue by AhmedAbdulrahman** [webpack/webpack.js.org#1593]
Hi, I would like to contribute to webpack documentation for translation into the following languages?

- [ ] Arabic
- [ ] Turkish

What I have done so far:

1. Fork the repo
2. Clone it
3. Run the following commands:
- `npm install` 
- `npm run build` 
- `npm start `
- `npm run fetch`

4. Created new branch for translation in my fork.

Any other things?
Thanks!

Screen Capture
![screenshot-localhost-3000-2017-09-13-15-39-33](https://user-images.githubusercontent.com/10485129/30380410-d989dfd8-9899-11e7-8578-6e2f0b0c0916.png)

**Comment by skipjack** [comment]
Awesome, glad you're interested in tackling this! So we do have a potential long-term plan for making translation easier in #295. However this is likely still a ways off. Here's how we handle it now:

- Fork the repository (as you've already done)
- Translate the content
- Rebase on the existing `translation` branch we've created in the main repository

@lcxfs1991 @Lutece could you elaborate on the steps above and correct me if I got anything wrong? (I wouldn't mind knowing a bit more about the current workflow myself as I may be able to add more content to _Translation_ section in our README). @AhmedAbdulrahman these are two of our maintainers for other translated forks so they should be able to help you more than I can.

Once we hear from them, I'll close this out. However, @AhmedAbdulrahman you should ping me once you have something ready to go so we can add a link to these new translations in our banner.

**Comment by Lutece** [comment]
@AhmedAbdulrahman 

Hi :) I'm korean who is translating the 'Webpack Docs' into Korean 
I succeeded in connecting the domain temporarily by referring to the blog post by @lcxfs1991. 
This is the URL of the post.

https://medium.com/@lcxfs1991/deploy-using-travis-ci-and-github-webhook-eba67b3ab6ac

@lcxfs1991 Thanks for writing this post :)

**Comment by skipjack** [comment]
cc @dear-lizhihua (I know you work on some translation stuff as well)

@Lutece @dear-lizhihua @lcxfs1991 are any of you in our slack channels yet? I think it might make sense for us to create an `#i18n` channel so we have a place to discuss things offline when necessary. @AhmedAbdulrahman I think we'd be happy to add you there as well. @TheLarkInn what do you think?

@AhmedAbdulrahman also you should be able to take `npm run fetch` out of your command list above. That command is run automatically by `npm start` and `npm build` already.

**Comment by Lutece** [comment]
@skipjack Hello :)  
I'm not joined in `Slack channel` of webpack yet, How can i do join in there?

**Comment by skipjack** [comment]
@Lutece we will add you, I just have to talk to someone with permissions first.

@AhmedAbdulrahman I'm going to close as I'm not sure what else we can add here. Feel free to keep discussing though and I'll work on getting you all invited to slack. Were there any other questions you had?

**Comment by dear-lizhihua** [comment]
@AhmedAbdulrahman @skipjack 
we use `translation` branch to update third-party loaders and plugins.
So you should merge `translation` branch to your `xxx` branch, you won't need `npm run fetch` to get `loaders/*.md` and `plugins/*.md`, because we do it at  `translation` branch.

![image](https://user-images.githubusercontent.com/15142680/30467899-7867bbd4-99ad-11e7-88e2-682b1ec95518.png)
![image](https://user-images.githubusercontent.com/15142680/30467909-85806014-99ad-11e7-9640-51640be9caa0.png)

**Comment by dear-lizhihua** [comment]
like this:
```
master                                  translation
(not loaders/*.md & not plugins/*.md)   (loaders/*.md & plugins/*.md)
      |                                        |
          \                                /
             \                         /
                 \                 /
                       |
                       |
               cn (or your branch)
```

**Comment by dear-lizhihua** [comment]
![image](https://user-images.githubusercontent.com/15142680/30468096-c6108e78-99ae-11e7-8c7e-5e2edf9ee752.png)

we split `src/scripts/fetch.sh`, like `copy`, `fetch` and `fetch-logo`:
`copy`: copy `./src/content/loaders/` to `./generated/loaders`
`fetch`: we `npm run fetch` at `translation` branch
`fetch-logo`: `node ./src/scripts/fetch_supporters.js` & `node ./src/scripts/fetch_starter_kits.js`

**Comment by skipjack** [comment]
@dear-lizhihua can you send me your email address so we can invite you to our slack channel? Feel free to pm me on gitter if you don't want to share here.

**Comment by dear-lizhihua** [comment]
OK, my email is 275091674@qq.com.
