### ISSUE TITLE
Dev - Issue with Remote Content Parsing

### ISSUE THREAD

**Issue by sapegin** [webpack/webpack.js.org#1600]
[Here](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/):

![image 2017-09-18 at 2 11 38 pm](https://user-images.githubusercontent.com/70067/30541358-5783aaf6-9c7b-11e7-87ef-006be22d5b02.png)

Not sure where it should be fixed: in their readme or in the site engine somewhere.

**Comment by skipjack** [comment]
Thanks for reporting this @sapegin. This is one of those instances that would likely be fixed by switching to `remark` and simplifying/externalizing our parsing process. For the time being though I think it can be fixed by tweaking the README, I saw something similar recently. I'll look into it.
