### ISSUE TITLE
Simple fix to resolve reloading issue

### ISSUE THREAD

**Issue by chagwood** [webpack/webpack.js.org#1605]
If you follow your guide up to the section on webpack-dev-server, everything is great. But I came in after having already pieced my webpack.config.js file together. I could not for the life of my get the page to reload after updating a project asset. Webpack would re-compile but the page would not reload. After spending a while trying to figure it out, I discovered that if you are not requiring('path') and using path.resolve(__dirname, 'dist') for your output, the reload will not work. This might help some others if you note that on your documentation (or maybe using path is something most newbies know and I'm just the exception). This could also resolve some more inexperienced users' issues with the reload not working. See my screenshots for a before/after of the simple change to get the reloading working.

Before:
![before](https://user-images.githubusercontent.com/7561533/30789989-0d6ad998-a177-11e7-8868-db47e4cf1262.png)

After:
![after](https://user-images.githubusercontent.com/7561533/30789990-1154e97c-a177-11e7-8169-187a25167b38.png)

**Comment by skipjack** [comment]
@chagwood I get what you're saying but I'm not sure how you're suggesting we update the guide...

The [hot module replacement guide](https://webpack.js.org/guides/hot-module-replacement/) already includes usage `output.path` in every example. Almost all, if not all, the other guides include it as well. Are you just suggesting that we highlight that it's usage more?

**Comment by chagwood** [comment]
In the example it may include it, but I think it should be noted that if you're not using output.path, the automatic page reload won't occur. 

webpack-dev-server would still recompile, but the changes would only be visible with a manual refresh of the page. I was only using output.filename with a relative path which worked fine with everything else I was doing with webpack. So on the surface it appeared everything was working except the refreshing. I was trying hot, inline, etc - nothing quite got me there. 

If I would have followed the guide I wouldn't have had a problem, but I was coming into the documentation trying to get the automatic reloading to work. Not start my webpack.config.js from scratch. Little did I know not using output.path would have caused me hours of headache. 

I think a little footnote in your guide under/in the section about adding the devServer portion to the module.exports would be beneficial is all (ex: "Ensure you are including output.path otherwise automatic reloading won't work"). 

But like I said, you may think that this isn't something worth mentioning. I just wanted to put in a comment in case someone else could be saved from such a headache over something so small. 

Great product and thanks for the quick response!

**Comment by skipjack** [comment]
> I think a little footnote in your guide under/in the section about adding the devServer portion to the module.exports would be beneficial is all (ex: "Ensure you are including output.path otherwise automatic reloading won't work").

Yeah I'd be fine with that and I'd suggest using our special warning syntax, e.g.

``` md
W> Ensure you are including output.path otherwise automatic reloading won't work
```

Feel free to PR that change if you have time.
