### ISSUE TITLE
Fix build issues on CI

### ISSUE THREAD

**Issue by sokra** [webpack/webpack.js.org#166]

**Comment by sokra** [comment]
@bebraw could you take a look?

**Comment by bebraw** [comment]
Sure. Most likely updating Antwar to a newer version will fix it once it's good enough. I'll do the styling fix while at it too.

**Comment by bebraw** [comment]
Updated. It should build now. I can see the CI expects to deploy from `master` branch. The script gets triggered when you push to `develop`, though. I think we might want to add a check against that and run the deploy script *only* when you push to `master`.

**Comment by bebraw** [comment]
And fixed. There were some nasty `^`s around so it tried to install wrong version.

**Comment by sokra** [comment]
awesome
