### ISSUE TITLE
Styling Updates

### ISSUE THREAD

**Issue by gregvenech** [webpack/webpack.js.org#168]
I'm going to start working on a PR soon to work on...

- [x] Markdown styling and typography
- [x] Playing with PrismJS themes and possibly customizing our own
- [x] Adding a few icons
- [ ] Start working on breakpoints/responsiveness
- [x] Make the minimum height of the application the height of the screen
- [x] Better tip styling (i.e. these... `?>`, `W>`, `T>`)

If anyone has noticed any issues with the styling or has a request please let me know so I can try to address it along with these other updates.

**Comment by sokra** [comment]
Responsive size, mobile devices.

Footer should be on bottom of page, even if there is only very few content.

**Comment by gregvenech** [comment]
@sokra yea I can definitely start addressing breakpoints on this update. 

Just updated the list above.

**Comment by gregvenech** [comment]
Creating a new issue (and soon a PR) for breakpoints.
