### ISSUE TITLE
Document webpack-hot-middleware

### ISSUE THREAD

**Issue by f-w** [webpack/webpack.js.org#1682]
In [HMR guides for Node.js API](https://webpack.js.org/guides/hot-module-replacement/#via-the-node-js-api), code example uses webpack-dev-server. But typically in such case there is a reason to use an existing Node.js web server other than webpack-dev-server, which is what webpack-dev-middleware is designed for. I think it makes more sense to document how to enable HMR in webpack-dev-middleware, for example by using [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware).

**Comment by skipjack** [comment]
I'd recommend adding this as a tip. We want to keep the guides fairly simple and I think fleshing out a whole section on this would convolute the guide a bit as `webpack-dev-server` works fine for most users (especially the more amateur users that these guides are directed toward).

How about something like this using our custom blockquote syntax for tips (i.e. `T>`):

``` md
T> If you're using `webpack-dev-middleware`, check out the [`webpack-hot-middleware`](https://github.com/glenjamin/webpack-hot-middleware) package to enable HMR on your custom dev server.
```
