### ISSUE TITLE
Plugins - IgnorePlugin Docs Are Sparse

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpack/webpack.js.org#1695]
https://webpack.js.org/plugins/ignore-plugin/

There's only one example. Can we get more, such as for using global React+ReactDOM+ReactDOMServer?

**Comment by skipjack** [comment]
You're right that it isn't a very long page but the [plugin](https://github.com/webpack/webpack/blob/24ef6ea1b56b358caeb4b07476a909f4f86c2d8a/lib/IgnorePlugin.js) itself is under 100 lines including comments and usage is pretty straightforward, all parameters are documented, and a simple example is given so I'm not really sure this is an issue. That said, you'd be welcome to submit a PR to add another example if it provides a different use case than what's there now (e.g. ignoring globals).

**Comment by skipjack** [comment]
Btw, I'm not sure ignoring globals is a common use case for this plugin. It ignores module requests, e.g. `import` or `require`. I think [`externals`](https://webpack.js.org/configuration/externals) is more commonly used for what you're referring to.
