### ISSUE TITLE
Guides - Entry Array when Authoring Libraries

### ISSUE THREAD

**Issue by LeBenLeBen** [webpack/webpack.js.org#1703]
I used the [Authoring Libraries](https://webpack.js.org/guides/author-libraries/) guide to export a library today. I got stuck for quite a long time understanding why my library would export nothing and this was caused by my entry point looking like this:

```
entry: {
  common: [
    './assets/scripts/common.js',
    './assets/scss/common.scss'
  ],
},
```

The compiler didn’t throw any error but the resulting library was just an empty object. I was wondering if this would be worth mentioning as a warning in the guide?

It’s not really clear for me why this doesn’t work in that specific case, so I would be happy to get some help to write an explanation if you think that’s the way to go.

**Comment by rouzbeh84** [comment]
This may be oversimplifying it but would something like whats below work?

```
entry: {
  common: {
    scripts: './assets/scripts/common.js',
    styles'./assets/scss/common.scss'
  },
},
```

**Comment by skipjack** [comment]
> The compiler didn’t throw any error but the resulting library was just an empty object. I was wondering if this would be worth mentioning as a warning in the guide?

We should mention it both in the guide and the configuration docs.

> It’s not really clear for me why this doesn’t work in that specific case, so I would be happy to get some help to write an explanation if you think that’s the way to go.

The problem with an array is that it's not clear what the default export should be. As @rouzbeh84 pointed out, an object might work along with the syntax specified here: webpack/webpack#221. It looks like [`libraryExport`](https://webpack.js.org/configuration/output/#output-libraryexport) may be an option as well.

That said, in your case I actually think the best option is a single entry point and then use the [`ExtractTextWebpackPlugin`](https://webpack.js.org/plugins/extract-text-webpack-plugin/) to create a separate `.css` file.

**Comment by skipjack** [comment]
I found something related but still nothing that indicates support for arrays:

https://github.com/webpack/webpack/tree/master/examples/multi-part-library

My guess is that with entry arrays, webpack will correctly build a bundle containing all the code but none of that code will be exposed correctly. I'm not seeing any syntax for `library` or `libraryExport` that would allow exposing the individual modules in an `entry` array. 

I tested this out though and got slightly different results. I tweaked the example (see the link above) to use `entry: [ './alpha.js', './beta.js' ]` and then wrote a simple Node script to log out the contents of the library. What seemed to be exported in this case was actually the export from the __last module__ in the array. In this case:

``` js
let Library = require('MyLibrary.main.js') // Yields "beta"
import Library from 'MyLibrary.main.js' // Also would be equal to "beta"
```

In any case, the _Authoring Libraries_ should at least mention the other types of `entry` configurations, link to the multi-part example, and note/link to the `libraryExport` docs. @LeBenLeBen hope this helps, feel free to submit a PR. If not, I'll submit one when I have a chance.

**Comment by DominicTobias** [comment]
> What seemed to be exported in this case was actually the export from the **last module** in the array. In this case:

I wish this was the case, I'm using 4.26.0 and it's still nothing when I do `['style.less', './src/index.js']`. I need the CSS file to have the same name and I export other CSS files in entry too.

Thinking I may have to give the CSS entry different name and rename with a plugin.
