### ISSUE TITLE
Missing .css asset on deployed page

### ISSUE THREAD

**Issue by hswolff** [webpack/webpack.js.org#1723]
Howdy! Seems the website is missing a .css asset which is causing a broken page.

Currently looks like this: 
![image](https://user-images.githubusercontent.com/322576/33500444-ce956aca-d6a6-11e7-82ee-676124c3c582.png)

Let me know how else I can help!

**Comment by hhsnopek** [comment]
The asset: `https://webpack.js.org/acd2001274306f1e8b40.css` is not resolving. The hash/filename is updated here: bf53cc0

Note: The missing file is present - [gh-pages/acd2001274306f1e8b40.css](https://github.com/webpack/webpack.js.org/blob/gh-pages/acd2001274306f1e8b40.css)

**Comment by skipjack** [comment]
Thanks for alerting us. We are aware of this issue but it's somewhat unavoidable in our current build/deployment process. See the following TODO in #1525:

> Consider a better hosting/deployment setup like Netlify (e.g. #845).

It happens occasionally when updates are being deployed. Try the site again -- I just tried and it loaded fine (even after emptying the cache). Sorry I don't have a better answer but we're aware of the issue and are cleaning up the infrastructure supporting the site bit by bit.

> Let me know how else I can help!

If someone wanted to dig into a port to netlify, we'd definitely help facilitate.

**Comment by hswolff** [comment]
No worries, appreciate the followup.

FYI I just tried the site again, including clearing my cache, and still see the same issue.

Perhaps it needs a re-deploy to kick it back into a working state?

**Comment by skipjack** [comment]
> FYI I just tried the site again, including clearing my cache, and still see the same issue.

Hmmm weird, I'll test this out more over the weekend. I'm definitely seeing all 200s in chrome's network tab. Can you try with another browser to make sure it's not a caching issue?

![image](https://user-images.githubusercontent.com/8988697/33501809-f139fbf4-d6ab-11e7-8acf-b2052ac83ec6.png)

**Comment by hswolff** [comment]
Just tried Firefox, same thing.

![image](https://user-images.githubusercontent.com/322576/33501938-4b272344-d6ac-11e7-9b73-e90e1d234c33.png)

Also co-workers see it at a different internet connection.

FYI this is out of NYC area.

**Comment by hswolff** [comment]
....and it appears to be working now. Thank you for your patience!

**Comment by hhsnopek** [comment]
@skipjack https://webpack-js-org.netlify.com/
All that needs to happen is pointing DNS at Netlify and giving access to users 😄

**Comment by skipjack** [comment]
> ....and it appears to be working now. Thank you for your patience!

Haha yea I think the main issue is that it takes some time for the new content to be distributed through GitHub's CDN or something.

> All that needs to happen is pointing DNS at Netlify and give access to contributors...

Awesome, thanks for the email and for setting that up. I'll take a look at it more this weekend and discuss with the other maintainers. Someone had mentioned it previously as a more scalable alternative but I hadn't had time to dig into it.
