### ISSUE TITLE
Config - Clarify Externals Documentation

### ISSUE THREAD

**Issue by cpxPratik** [webpack/webpack.js.org#1726]
In the documentation `externals` configuration option [here](https://webpack.js.org/configuration/externals/),  giving only example of `jquery` was confusing. For example, I thought to exclude 'vue-i18n'  package, i need to specify as `'vue-i18n': 'VueI18n'` while consumer app importing with `import VueI18n from 'vue-i18n'`. But actually  correct property-value pair turned out to be `'vue-i18n': 'vue-i18n'` after trying different variation.

May be documentation should have said explicitly like- in the context of global variable, you should give variable name as value but if it is module or another npm package you should give module name as value. Reading doc now, I dont get confuse about it. But while reading for first time, readers may get confused like me.

**Comment by skipjack** [comment]
I see what you mean and I've run into this as well. I'm submitting a PR which, aside from some general formatting cleanup, elaborates on the __string__ documentation to make it clear that the property name is the externalized module and the value is what's used to retrieve the global variable.
