### ISSUE TITLE
Add refactored logo + new font

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack.js.org#173]
@bebraw @gregvenech I've refactored the current logo, you can find it [here](https://github.com/webpack/media). I've replaced the gradients with solid colors, refactored the shape of the cubes and changed the font. I think, the new logo works better with small sizes, because now the icon has a recognizable shape and the font has a strong character (can you say that in English? At least in German it makes sense 😁).

I would prefer to keep it flat for now because imho there are other priorities. But I'm totally open to experiment with unobtrusive animations and very very light gradients. We can easily add them later.

My vision for the new brand design is to keep it very minimalistic, with a lots of whitespace. I haven't found the time to experiment with fonts, but I suggest to use the [logo font for the headlines](http://geomanist.com/). If you have any questions regarding the font, you can ask @TheLarkInn. Please do not commit any font files to the repo, we need to sort out the licensing stuff first.

Since the used logo font is rather heavy, we could also use thick black/light blue strokes as separators or graphical elements.

I'm away on holiday for the next 2 weeks, so I won't be able to give feedback. But I'm really curious about your thoughts :)

**Comment by gregvenech** [comment]
> ...because now the icon has a recognizable shape and the font has a strong character (can you say that in English? At least in German it makes sense 😁 ).

Haha yea I get what mean.

> I would prefer to keep it flat for now because imho there are other priorities. But I'm totally open to experiment with unobtrusive animations and very very light gradients. We can easily add them later.

That's fine, I believe @bebraw still has some work to do on antwar before we can add scripts easily use the `<interactive>` feature anyway (see [this issue](https://github.com/antwarjs/antwar/issues/103)).

> Please do not commit any font files to the repo, we need to sort out the licensing stuff first.

I'm about to make another big push to get the styling of this repo in good shape, see [this issue](https://github.com/webpack/webpack.js.org/issues/168). If you guys get licensing sorted out soon, i can add it to that list and hit it soon. If not we can always add it later.

Aside from the Logo and font, would you like me to port the existing mockups over to that repo? I can at least start incorporating the new and font there. (There's a few other things I wanted to fix anyway)

**Comment by jhnns** [comment]
> I'm about to make another big push to get the styling of this repo in good shape, see this issue. If you guys get licensing sorted out soon, i can add it to that list and hit it soon. If not we can always add it later.

No, I just meant that if we push any content to the repo, we must make sure that our license does not conflict with the other license. And if it does conflict, we must explicitly exclude these files from the license.

Speaking about the license, I just saw that we don't have any? @bebraw 

> Aside from the Logo and font, would you like me to port the existing mockups over to that repo? I can at least start incorporating the new and font there. (There's a few other things I wanted to fix anyway)

Where do you want to put the mockups? In case you wanted to put it into the media repo, I'm not sure. I thought that this repository is meant to be an up-to-date reference for "production-ready" files. I think it's fine that these mockups are under your namespace.

**Comment by gregvenech** [comment]
@jhnns ah ok. I thought you might have been trying to centralize all the design assets in one repo.

**Comment by gregvenech** [comment]
@bebraw let me know once the license is there and I can work on getting this done.

**Comment by bebraw** [comment]
@jhnns I think we may have to wait @jhnns on that. I'll bring this up in the next meeting. Vacations are going to delay this. 😢

**Comment by gregvenech** [comment]
Yea no rush. Just trying to knock the issues out that I can.

**Comment by bebraw** [comment]
Ok, cool.

**Comment by jhnns** [comment]
I've added the license for our logo (https://github.com/webpack/media/pull/3).

Now when we add the new logo and the geomanist font to the repository, we need to make sure that these are excluded from the docs license.

**Comment by gregvenech** [comment]
@jhnns I've added the font (in regular and and medium) as well as the images in #225. The license is the last thing and then we can close this.

**Comment by jhnns** [comment]
Awesome, thank you @skipjack :)
