### ISSUE TITLE
Config - TypeScript Setup Failing in Configuration Languages

### ISSUE THREAD

**Issue by youta1119** [webpack/webpack.js.org#1735]
Need Update how to write the webpack configuration with typescript. Current configuration is wrong.
ts-node dosenot  support the module syntax of other than commonjs module. 
So, if module in compilerOptions in tsconfig.json is not commonjs, webpack getting error. like this.

```bash
(function (exports, require, module, __filename, __dirname) { import * as path from "path";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Module.m._compile (/Users/hogefuga/webpack-config-with-typescript/node_modules/ts-node/src/index.ts:392:23)

```
https://webpack.js.org/configuration/configuration-languages/#typescript

**Comment by skipjack** [comment]
@youta1119 thanks for reporting this. If you know what the fix is please submit a PR.

cc @dmitriid

**Comment by dmitriid** [comment]
I haven't worked wit ts-node, but I wonder if it silently compiles TypeScript to JavaScript and then executes it in node.js.

Since node.js doesn't support `import ...` constructs, it's possible that you need to do the following:

In your `tsconfig.json` add/change the following: 

- remove `module` setting, if it's there. Or change it to "CommonJS"
- add/change: 

```
"target": "ES5"
```

I can't check it right now, but this may work

**Comment by youta1119** [comment]
@skipjack I was send pull request at #1734

**Comment by skipjack** [comment]
@youta1119 great, I'll take a look at it tonight.

@dmitriid thanks for the quick response. If you have time to review that PR, I'd appreciate it.

**Comment by akopchinskiy** [comment]
> I haven't worked wit ts-node, but I wonder if it silently compiles TypeScript to JavaScript and then executes it in node.js.
> 
> Since node.js doesn't support `import ...` constructs, it's possible that you need to do the following:
> 
> In your `tsconfig.json` add/change the following:
> 
> * remove `module` setting, if it's there. Or change it to "CommonJS"
> * add/change:
> 
> ```
> "target": "ES5"
> ```
> I can't check it right now, but this may work

What if I need `module: 'es6'` ?
