### ISSUE TITLE
Guides - Inline vs Extracted CSS in Asset Management

### ISSUE THREAD

**Issue by slurps-mad-rips** [webpack/webpack.js.org#1741]
I'm fairly new to webpack (and frontend development in general). I had read in the Asset Management section of the guide that `css-loader` and `style-loader` are needed for using CSS, and was surprised to learn that they are then placed into the `bundle.js` file (or similar). I later asked @TheLarkInn during a twitch stream as to why this is the case. I was informed that webpack doesn't actually require this, but it wasn't mentioned anywhere in the guide that I could easily see (at least during the initial tutorial steps).

I'd really like to see a section added to the guide on when (and why) to inline your CSS files into any bundled file as well as when (and, again, why) not to.

**Comment by skipjack** [comment]
There is a small note about at the end of that section:

![image](https://user-images.githubusercontent.com/8988697/34027400-728bf9ae-e12a-11e7-97b5-399179c2428d.png)

That links to the `ExtractTextPlugin` which has a good tutorial and notes that:

> you can also split your CSS for better load times in production.

To answer your question though, it basically comes down to _development_ vs. _production_. Inlining the CSS on a per module basis works better with hot module replacement and requires less configuration. In short, those are the reasons people typically use it in _development_. In _production_ however, you gain some benefit in terms of load time and caching by extracting all stylesheets into one or more `.css` files that are loaded in parallel with your bundles.

> I'd really like to see a section added to the guide on when (and why) to inline your CSS files into any bundled file as well as when (and, again, why) not to.

If you'd be willing to submit a PR, that would be fantastic. I would recommend adding a short section to the __Production__ guide and maybe adding a little bit more description to __Asset Management__ along with a link to the new __Production__ section.
