### ISSUE TITLE
Bug - Blurry SVG Text on Firefox 57.0.2 (64-bit) Win10

### ISSUE THREAD

**Issue by duncanawoods** [webpack/webpack.js.org#1752]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/2480457/34077967-2a48b4b8-e308-11e7-9d1e-9d5d15dfa3c1.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Legible text.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Site: https://webpack.js.org
Browser: Firefox 57.0.2 (64-bit)
OS: Win10

**Comment by skipjack** [comment]
I also tried zooming in and out to see if that was the cause but it still seemed crisp at all levels.

**Comment by duncanawoods** [comment]
Extra info:
* opening just the svg file in Firefox shows the same text rendering problem
* 100% zoom - expanding window (stretching svg) does not improve it
* error in console - opencollective.com - Failed to load resource: the server responded with a status of 403()
* disabling uBlockorigin, ghostery does not change appearance
* Looks fine in Chrome
* Looks fine Inkscape
* Edge has some different artefacts - text is getting clipped:

![image](https://user-images.githubusercontent.com/2480457/34093595-ff680aaa-e3c0-11e7-9d60-76e76146f825.png)

**Comment by pierreneter** [comment]
@skipjack Confirmed for this issue is exist on Windows

**Comment by pierreneter** [comment]
- The more straightforward way is to convert this background to `png` format files with a maximum width of `1024px` and use `img srcset` if needed.
- Or we can re-export that `svg` file from the original file so that it retains the text and font and does not convert it to a path. (I do not know about this possible or not?!)

**Comment by pierreneter** [comment]
@skipjack I can't find the original file at https://github.com/webpack/media and https://github.com/skipjack/webpack-design to try to do the option 2.
But I vote for option 1.

**Comment by skipjack** [comment]
@duncanawoods thanks for the additional details and @pierreneter thanks for digging into it and confirming.

> The more straightforward way is to convert this background to `png` format files with a maximum width of `1024px` and use `img srcset` if needed.

Yeah I think there was a reason we used an SVG in the first place, probably for size and I think it typically renders a bit crisper as a vector but looking at the file again I see what @duncanawoods means re the filters.

> I can't find the original file at https://github.com/webpack/media and https://github.com/skipjack/webpack-design to try to do the option 2.

Yeah I'm not sure I have it either. It was created by @pastelsky (ping!) who might be able to help. I also search around a bit and see if I can find the link I got to the original. Some of the weird styling might have been caused by running it through a compressor.

**Comment by skipjack** [comment]
Weird tested it out on Firefox 57 on Windows 10 in BrowserStack and couldn't replicate:

![image](https://user-images.githubusercontent.com/8988697/34314298-245f7d98-e740-11e7-8288-d64a62b53b53.png)

@pierreneter in terms of those two options I think maybe I can just rebuild the SVG in sketch so we have a stable copy. Then we can be a little more careful when minimizing to prevent any oddities such as this one.

**Comment by skipjack** [comment]
Ok rebuilt and cleaned things up a little while I was at it. The following zip contains the `.sketch` file as well as an exported `.svg`...

[visualization.zip](https://github.com/webpack/webpack.js.org/files/1583911/visualization.zip)

Can you both take a look and 🙏  test to see if it looks any better?

**Comment by pierreneter** [comment]
I think `BrowserStack` don't directly interact with the native device that is a reason why you can't reproduce it. New `svg` file in this zip work ok. But we need the font: `Quicksand-Medium, Quicksand` for this work.

**Comment by pierreneter** [comment]
And `Avenir-Heavy, Avenir`

**Comment by pierreneter** [comment]
Or simply use our current font on the web for this `svg` file

**Comment by skipjack** [comment]
Yep my bad, tried to match the the previous one but forgot that with text nodes we'd actually have to include the font. Will update and post a new zip momentarily.

**Comment by skipjack** [comment]
Here you go (fixed some casing issues as well):

[updated-viz.zip](https://github.com/webpack/webpack.js.org/files/1584642/updated-viz.zip)

Everything in there is now "Source Sans Pro" which should already be loaded by the site.

**Comment by duncanawoods** [comment]
We need an html file to host it in to give feedback. I used this:

```
<!DOCTYPE html>
<html>
<head>
<link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:400,600|Source+Sans+Pro:400,400i,500,600" rel="stylesheet">
</head>
<body>
<img src="visualization.svg">
<img src="bf093af83ee5548ff10fef24927b7cd2.svg">
</body>
</html>
```

Differences include size, margins, colour of boxes and it doesn't look like its picking up the font but does look the same as in Chrome!

![image](https://user-images.githubusercontent.com/2480457/34352993-951079ea-ea1d-11e7-9e07-831061afc798.png)

**Comment by duncanawoods** [comment]
btw something unrelated but when I return to the webpack homepage after being away for some duration... the spinning cube catches up with all the spins it has missed since the tab has not had focus i.e. it goes nuts for a while.

**Comment by skipjack** [comment]
> It doesn't look like its picking up the font (could be my fault) but does look the same as in Chrome!

Ok I'll make sure to double check it when testing #1762.

> btw something unrelated but when I return to the webpack homepage after being away for some duration... the spinning cube catches up with all the spins it has missed since the tab has not had focus i.e. it goes nuts for a while.

Haha yeah I'm aware of this minor bug with the cube. I wasn't sure how to fix that when I initially wrote the `Cube` component but maybe clearing the `timeout` on `blur` of the whole window and resetting it on focus would resolve that. Not a high priority in my opinion but I gladly welcome a pull request if you wanted to play around with it.
