### ISSUE TITLE
Dev - Archive Versions

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#176]
The build should copy earlier version below `archives` or so. This would allow us to maintain documentation for older versions online with minimal effort.

Apparently `add` option of [gh-pages](https://www.npmjs.com/package/gh-pages) should be enough for this. More info: https://github.com/tschaub/gh-pages/issues/93 .

**Comment by sokra** [comment]
or a git submodule to itself in an earlier version ^^

**Comment by skipjack** [comment]
This would definitely be cool but I think should only be done for major releases (at most maybe the most recent minors as well). This requires that the docs are fully up to date and I think something like what we were discussing at the end of #1017 could work. I think once the backlog is done we can re-open that pr and discuss this a bit more. IMHO synchronizing tagged releases with the tool itself would be best, though we can still update the site continually on merge to master.

**Comment by skipjack** [comment]
Noted in #1380 -- let's track there as this has been stagnant and will probably be more of a long term thing.
