### ISSUE TITLE
Questions about translation

### ISSUE THREAD

**Issue by Lutece** [webpack/webpack.js.org#1772]
In the `docs`, it was confirmed that the loader contents and plugin contents are created in the 'generated' folder through the script(init:generated & .antwar.config.js) . During this process, I found that the content(loaders and plugins content in generated folder) was deleted and re-created. I do not know how to proceed with the translation of `loader` and` plugin`.

**Comment by lcxfs1991** [comment]
Please refer to this branch.
https://github.com/webpack/webpack.js.org/tree/translation

**Comment by lcxfs1991** [comment]
webpack-china has solid practise on translating webpack docs.

**Comment by Lutece** [comment]
Thanks! @lcxfs1991 👍
