### ISSUE TITLE
The docs is too huge to load and maintain

### ISSUE THREAD

**Issue by lcxfs1991** [webpack/webpack.js.org#1786]
![image](https://user-images.githubusercontent.com/3348398/34907081-1ab0599a-f8b4-11e7-8352-9c6220f5da03.png)

![image](https://user-images.githubusercontent.com/3348398/34906933-b484390e-f8b1-11e7-93a6-309f94f2b040.png)

I think it is due to recent change. But it would be better to reduce bundle size. Otherwise, it is a pressure for developers with slow network to load the doc site.

**Comment by lcxfs1991** [comment]
I also spot some unuseful code in some pages:

![image](https://user-images.githubusercontent.com/3348398/34912236-eb882b94-f916-11e7-8f5d-ae579449ded6.png)

![image](https://user-images.githubusercontent.com/3348398/34912238-f6101270-f916-11e7-85cd-6d8fe487e369.png)

**Comment by lcxfs1991** [comment]
what's you guys opinions? @skipjack @TheLarkInn

**Comment by skipjack** [comment]
I'm not able to replicate:

![image](https://user-images.githubusercontent.com/8988697/34913179-0b00d938-f8c4-11e7-941e-659a4ebd9d51.png)

What branch are you on and what page of the site are you on? The `rebuild` branch isn't complete so large build sizes are to be expected. In the screenshot I shared above one of the bundles is slightly too big but there's already mention of that in #1525 and will should be addressed by the `rebuild`. Closing but feel free to share more details and I'll take another look.

**Comment by skipjack** [comment]
On the chinese site, I am able to replicate however:

![image](https://user-images.githubusercontent.com/8988697/34913215-e94799f2-f8c4-11e7-984c-d3f9ff18fc60.png)

Did someone alter the webpack or antwar config over on that repo? Maybe `react` and `react-dom` aren't being replaced by `preact` in production? We don't officially support the other forks so this issue might make sense over there... I'm not sure how much time I'll have to help debug but you may be able to grab some other help from our slack channel or @bebraw (author of `antwar`).
