### ISSUE TITLE
Translation to pt-BR

### ISSUE THREAD

**Issue by PlayMa256** [webpack/webpack.js.org#1799]
Hello,
I do want to contribute translating the docs into pt-BR, altough i've been looking into some open issues about internationalization and there are some discussions regarding tools to make it easier, but these discussions seems to still open.

So, i would like to know, since i could not find any folder reference to any localization, do i simply:
- fork
- translate
- open PR?

Thanks.

**Comment by skipjack** [comment]
Hey @PlayMa256, we'd love for you to add a portuguese translation. At some point, we may support translations in this repository but for now you would:

- Take a look at the translation branch and talk to @lcxfs1991 @Lutece @dear-lizhihua.
- Fork the repository and host it on a new domain (e.g. `webpack-portuguese.com`).
- Ping us once you're further along and we can add an option to our languages dropdown.
- Issues and PRs should be managed on the other repository (at least for now).

The people I mentioned above have all done a lot of translation work in the past and should be able to point you in the right direction. You can subscribe to #295 if you want to stay up to date with our support for translation (probably still a ways off). Closing, but feel free to continue the convo if you have any other questions.

**Comment by skipjack** [comment]
I'd also recommend you take a look at all the previous translation/i18n discussions if you haven't already:

https://github.com/webpack/webpack.js.org/issues?utf8=%E2%9C%93&q=label%3AInternationalization+

You may find more info there on how to get started.

**Comment by PlayMa256** [comment]
Thank you for the feedback.
