### ISSUE TITLE
`import()` dynamic path

### ISSUE THREAD

**Issue by catamphetamine** [webpack/webpack.js.org#1806]
On the `import()` docs page one example is provided: `import(./locale/${language}.json)`.
The doc says that it "will cause every .json file in the ./locale directory to be bundled into the new chunk".
And what about a more complex example, like `import(./pages/HomePage.${language}.json)`?

**Comment by skipjack** [comment]
> And what about a more complex example, like `import(./pages/HomePage.${language}.json)`?

Then every possible file that the template string could evaluate to would be included. In this case, it might be something like:

- `HomePage.en.json`
- `HomePage.fr.json`
- `HomePage.cn.json`

And so on. As per #1699 we should expand this discussion a bit. Please continue the discussion there.
