### ISSUE TITLE
Set up 404 checker

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#181]
1. Generate RSS (antwar rss plugin).
2. Run build with RSS.
3. Run hyperlink against the build.

**Comment by bebraw** [comment]
Made some progress on this. Waiting for https://github.com/Munter/hyperlink/issues/104 and https://github.com/Munter/hyperlink/issues/105 to be resolved. After that we are good to go with link checking.

**Comment by Munter** [comment]
Hyperlink 2.5.0 should have what you need now

**Comment by bebraw** [comment]
Yeah, working great. Just setting this up. 👍
