### ISSUE TITLE
Translation - Spanish Support

### ISSUE THREAD

**Issue by andres-uris** [webpack/webpack.js.org#1813]
Hello world!

I want to know if there a Spanish version of the documentation where I can contribute on it.

**Comment by skipjack** [comment]
Hey @andres-uris. There isn't a spanish translation yet that I'm aware of. Until we figure out #295, all translations are managed on forks of this repo and hosted on separate domains. Please talk to @dear-lizhihua, @lcxfs1991, and @Lutece for more info as they maintain the Chinese and Korean versions iirc. They've built out a process for doing this using the `translation` branch.

Once you have a fork ready to go, we can link to it from our language dropdown. Hope you go forward with it! Closing, but feel free to continue the conversation and/or ping me directly if you need any additional info.
