### ISSUE TITLE
Plugins - Document CommonsChunkPlugin() Defaults

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#1822]
- [ ] Check the current issues to ensure you aren't creating a duplicate.
- [ ] Consider making small typo fixes and such directly as pull requests.
- [ ] For the voting application, go to https://github.com/webpack-contrib/voting-app.
- [ ] For loader/plugin docs, consider opening an issue in the corresponding repository.
- [ ] No existing issue? Go ahead and open a new one.
- __Remove these instructions from your PR as they are for your eyes only.__

**Comment by skipjack** [comment]
Isn't the `CommonsChunkPlugin` removed in `v4`?

**Comment by EugeneHlushko** [comment]
Yes, this is redundant
