### ISSUE TITLE
Landing - Link to Webpack 1 Docs

### ISSUE THREAD

**Issue by s1iqbal** [webpack/webpack.js.org#1823]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Regarding <a>https://github.com/webpack/webpack/issues/6390</a>

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Google legacy webpack 1
2. End up on a page similar to https://webpack.github.io/docs/using-plugins 
![image](https://user-images.githubusercontent.com/23174030/35840898-f08336e0-0ac6-11e8-811a-e877e5084130.png)
3. Redirects to the webpack 2 docs

When I google for a problem in a legacy webpack 1 setup, I might end up on pages like this: https://webpack.github.io/docs/using-plugins, which currently shows nothing but

**Solution**

<--Finished -->
 TO DO: Should redirect to the proper webpack 1.0 documentation when referring to the link.
👍 Added links to webpack 1 docs in wiki in support section of README in webpack/webpack repo

👍  TODO: open issue in webpack/webpack.js.org to explore the right location to link back to wiki from new docs page. 

The location for the proper documentation for webpack 1.0 is located in webpack.wiki commit tree.

![image](https://user-images.githubusercontent.com/23174030/35841340-6d1f0394-0ac9-11e8-862f-a7157e3f6bfd.png)

The SHA of this commit can be copied and can be served after a link to view the state on that commit day.

The latest commit for webpack 1.0 documentation was on January, 15, 2013.
The SHA for that commit is ef63d78c66cae3657520884787e5efcf6e4e1d5b

The link can be applied such as https://github.com/webpack/webpack/wiki/Function/ef63d78c66cae3657520884787e5efcf6e4e1d5b

Below is the required edit for README.md

If you're just getting started, take a look at [our new docs and concepts page](https://webpack.js.org/concepts/). This has a high level overview that is great for beginners!!

If you are looking for webpack 1.0 docs, please look at these:
[Loader-specification](https://github.com/webpack/webpack/wiki/Loader-Specification/), 
[Tutorial](https://github.com/webpack/webpack/wiki/Tutorial/1037ac5c91937d130fb0a153b5a7e857b59b093e), 
[Plugins](https://github.com/webpack/webpack/wiki/Plugins/8f90c0b8caa6892ab80add5a40fae5c7b14a87a1),
[Functions](https://github.com/webpack/webpack/wiki/Function/ef63d78c66cae3657520884787e5efcf6e4e1d5b).

**Comment by skipjack** [comment]
I think the following link to the old wiki would be a better place to link to:

https://github.com/webpack/docs/wiki/contents

Feel free to submit a PR to add a brief sentence to our landing page, as such:

> Looking for webpack 1 documentation? Please check out the old [wiki](https://github.com/webpack/docs/wiki/contents), but note that this version is no longer supported.

**Comment by s1iqbal** [comment]
I will get to it by this week.

**Comment by EugeneHlushko** [comment]
@s1iqbal still planning to put up a PR?

**Comment by BeniCheni** [comment]
Hi dear maintainer(s), gave this issue an attempt by the [webpack/webpack #7286 PR](https://github.com/webpack/webpack/pull/7286). Looking forward to your review feedback. Thanks in advance!

Posted a simple question about the necessity of updating the same content of _Webpack 1_ wiki reference in the [landing page](https://github.com/webpack/webpack.js.org/blob/master/src/content/index.md) mentioned in previous comment. Will look out the guidance about the question as well. 🙏

**Comment by BeniCheni** [comment]
Hello, @s1iqbal (original issue creator) & deal maintainer(s),

[webpack/webpack #7286 PR](https://github.com/webpack/webpack/pull/7286) has been merged to add a brief description & a link to Webpack 1 "Old" Wiki in the [Support Section](https://github.com/webpack/webpack/blob/master/README.md#support) of the [_webpack/webpack_ README](https://github.com/webpack/webpack/blob/master/README.md).

> Looking for webpack 1 docs? Please check out the old wiki, but note that this deprecated version is no longer supported.

It seems efficient enough to address this open issue here @ _webpack/webpack.js.org_. I'm not familiar with the issue closing process. Would you like to confirm the [_webpack/webpack_ README](https://github.com/webpack/webpack/blob/master/README.md), and see if we can work toward the closing of this open issue?

P.S.: Think it'd be a good idea to reach the "_acceptable_" solution to bring this open issue to a "_close_" status, to aim to have a "_clean cycle_" to refer to the related, merged [PR](https://github.com/webpack/webpack/pull/7286). If there is anything you'd like to advise me to help further, I'm happy to help. Thanks.

**Comment by EugeneHlushko** [comment]
This is pretty much resolved, thanks @BeniCheni 

If anyone feels different please re-open
