### ISSUE TITLE
Responsiveness - Create Breakpoints

### ISSUE THREAD

**Issue by gregvenech** [webpack/webpack.js.org#183]
Need to play around with the [design](https://github.com/gregvenech/webpack-design) a bit, maybe create a mockup for mobile devices, and then update the css.

- [x] Add mobile mockup
- [x] Update screen sizes in `_vars.scss` if necessary
- [x] Create `styles/_breakpoints.scss` and begin!

Note that I only added a mockup for mobile screens, everything in between the largest screen size and mobile I think we can just wing for now as it's a pretty simple site.

**Comment by oliverturner** [comment]
@gregvenech so, prompted by @SurviveJS on Twitter, stepping up to offer any help I can on this. Let me know!

**Comment by gregvenech** [comment]
@oliverturner awesome, yea definitely. Planning to get at least a rough mockup going for mobile done this weekend so we have something to work off. If you have any suggestions re design feel free to take a look at the [design repo](/gregvenech/webpack-design).

**Comment by montogeek** [comment]
I want to help too!

**Comment by gregvenech** [comment]
@oliverturner added a rough draft of the mobile version [here](/gregvenech/webpack-design). It has a few layer comps (normal, search, and sidebar) but to start we can ignore search. I also added a small high-level checklist that we can add to above. Feel free to open a PR whenever if you want to start working on it. 

@montogeek sure, let's give @oliverturner a chance to start it and then enumerate the tasks and divide and conquer when necessary.

I'll add some screenshots to this thread tomorrow just in case either of you don't have photoshop.

**Comment by montogeek** [comment]
@gregvenech I have Photoshop :)

**Comment by oliverturner** [comment]
@gregvenech please do add those screenshots: it's been a while since I let Photoshop pollute my machines ;)

**Comment by gregvenech** [comment]
@montogeek great! Feel free to poke around that design repo if you're interested and let me know if you have any suggestions.

> it's been a while since I let Photoshop pollute my machines ;)

@oliverturner jeez, I didn't know there was such anti photoshop sentiment out there 😁  ! Just out of curiosity what's your preference, sketch?

Threw together a quick demo with each comp:

![mobile-demo](https://cloud.githubusercontent.com/assets/8988697/18818224/0d66b5e2-8342-11e6-960b-fb30c90d0bd5.png)

As you can see the search one is barely started but I think we can definitely work on the other two and the medium size screens. Once the screen narrows to the largest size in _screens.scss we should probably go to 100% width and then make any tweaks necessary to keep the site looking good, hiding the Sidebar somewhere around 960px. 

Thanks again for taking this on, it should free me up to get more work done on the search design/implementation (in the larger screens as well), as well as playing around more with the landing page. The landing page (Splash) is another thing I wouldn't worry about too much yet as it's likely to change a bit. 

Let me know your thoughts.

**Comment by oliverturner** [comment]
@gregvenech yep: Sketch is my new jam. Was never a PS fan: Fireworks always seemed the more intuitive and flexible option (showing my age I know...)

Thanks for posting the comps :)

**Comment by oliverturner** [comment]
I have a few questions that would possibly be better hashed out in a quick chat than via GH issues... is there a chance you'd be free to catch up?

**Comment by gregvenech** [comment]
Haha, yea no problem pm me on gitter. I should be on in 45 min or so.

**Comment by oliverturner** [comment]
@gregvenech pinged you :)

**Comment by gregvenech** [comment]
Closing via @oliverturner's #203. There's still some tweaks to be made but these can be opened as separate issues/PRs.
