### ISSUE TITLE
Guides - Author Libraries text finishes abruptly

### ISSUE THREAD

**Issue by davidjb** [webpack/webpack.js.org#1832]
At https://github.com/webpack/webpack.js.org/blame/master/src/content/guides/author-libraries.md#L310 the text reads:

> The module property should point to a script that utilizes ES2015 module syntax but no other syntax features that aren't yet supported by browsers or node. This enables 

and that's it, ending abruptly.  What's missing?

**Comment by skipjack** [comment]
Good catch... I believe it's supposed say something like:

> ... This enables webpack to parse the module syntax itself, allowing for lighter bundles via [tree shaking](https://webpack.js.org/guides/author-libraries/) if you aren't using the full library.

Would you be willing to submit a PR with that fix?

**Comment by davidjb** [comment]
@skipjack Done, thanks for the text.  I adjusted the link to "tree shaking" to point at the Tree Shaking guide (https://webpack.js.org/guides/tree-shaking/) as the link was originally to the same Authoring Libraries article.
