### ISSUE TITLE
Plugins - 404 in CommonsChunkPlugin

### ISSUE THREAD

**Issue by stowball** [webpack/webpack.js.org#1834]
The final 2 example links (Multiple Common Chunks & Multiple Common Chunks) in https://webpack.js.org/plugins/commons-chunk-plugin/ 404

**Comment by montogeek** [comment]
That plugin was removed for the upcoming version of webpack, a new option `optimization.runtimeChunk` replaces it.

You can find more documentation about it here https://github.com/webpack/webpack/blob/798eaa834af59835eedbd01ea9e2f4a6175ae9a1/examples/chunkhash/README.md#L3

**Comment by skipjack** [comment]
@montogeek could you submit a PR that simply repoints these links to an older blob of the repo that still contains those examples?

**Comment by montogeek** [comment]
@skipjack will do
