### ISSUE TITLE
Set up search for the site

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#184]
Algolia would work.

I'm opening this based on Twitter discussion.

**Comment by dzello** [comment]
Great! Per the comment on Twitter, what thoughts did you have in mind for the design?

**Comment by bebraw** [comment]
@dzello Mostly fine. The structure of the site is completely different now, though, so that might affect your side. The search control needs a good location. Maybe header? See http://webpack.js.org/ .

**Comment by dzello** [comment]
Ok, good to know. If the new content structure is different that's ok, I will have to make some config changes but should be mostly painless. From clicking around on the new site it looks like some content isn't there yet. Should I hold off on trying to index it until there's more there?

The header is good for location, that's what we did on the React docs.

**Comment by bebraw** [comment]
You can index it, but it's correct it won't yield a lot of results yet. But then, I assume you index it regularly so going with the new structure can't hurt.

**Comment by dzello** [comment]
Right, once the config is live we re-index every 24 hours to pick up any changes. I will play with indexing the new site and see where I get. Any ideas for timeline on having all the new content up?

**Comment by bebraw** [comment]
All content - months.

Minimum will take less. There's a [target](https://github.com/webpack/webpack.js.org/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Webpack+2+-+Documentation+MVP%22) for that.

**Comment by dzello** [comment]
Sounds good, no problem to get new indexing configuration done by then.

In the meantime, for the sake of asking, do you think it's worth deploying search for the existing docs since the PR is ready to go? I don't want to make extra work but one upside of deploying for the existing docs is that we'll have more data to improve search for V2.

**Comment by bebraw** [comment]
@dzello Yeah, getting the search on the old site could be worthwhile. Just poked about that so we get a decision made.

**Comment by sokra** [comment]
google custom search can work too...

**Comment by dzello** [comment]
The Google custom search UX isn't great for docs. No autocomplete, irrelevant suggested searches, clumsy modal dialog for displaying results. Also there's ads and you have to pay to remove them.

**Comment by jhnns** [comment]
If a documentation site uses google custom search, I'm instantly annoyed ^^. I don't like the results.

**Comment by SpaceK33z** [comment]
@dzello, are you still interested in adding search for this repo? We'd love it if you could do a PR :).

**Comment by dzello** [comment]
@SpaceK33z yes, I will start getting that together :)

**Comment by bebraw** [comment]
@dzello Could you provide us the api key + webpack id for Algolia API? It should be straight-forward to set up after that once you have indexing going (just did integration of my own).

**Comment by dzello** [comment]
@bebraw Yes, will provide once I have indexing going. In the meantime for development or testing you could use the DocSearch index for the existing site. App Id: `bh4d9od16a`, API Key: `93950c6eda05068a6f0649e4a7f7546e`, Index name: `webpack`.

**Comment by skipjack** [comment]
@bebraw @dzello Started working on a branch to add the interface bits (e.g. a togglable input in the Navigation bar) for you to hook into, haven't it pushed it yet by I should be able to open a PR for that sometime tonight or tomorrow.

**Comment by dzello** [comment]
Good to know @skipjack, thanks!

**Comment by SpaceK33z** [comment]
Fixed with PR #284.
