### ISSUE TITLE
Contribute - Donate Link Broken in Production

### ISSUE THREAD

**Issue by drKnoxy** [webpack/webpack.js.org#1843]
The link around the image on the `/contribute/` is broken.
It seems to work fine when you run `npm start` but not when you run `npm run build`.

I was going to try and help but the custom lexer implementation for finding markdown in html was a little tough for me to understand.
FYI multi-line html blocks work as expected in the marked lexer.

Anyway, the bit of code that is leading to the bug `webpack.js.org/src/utilities/markdown.js@handleHTML`
Each html tag gets split and parsed by `parseContent` which means that each individual start/end tag is wrapped in a `<p>`.
I believe the regression was introduced in 5d7534e661d

I didn't dig into why the issue doesn't crop up on development builds.
But I did hit a github rate limit trying to work this issue, it seems fetch.sh is doing some work ?

**Comment by montogeek** [comment]
Will take a loot at this one

**Comment by EugeneHlushko** [comment]
@montogeek this is not the case anymore right? we can just close?

**Comment by montogeek** [comment]
It is working now.
