### ISSUE TITLE
Guides - Incorrect Diff in "Code Splitting"?

### ISSUE THREAD

**Issue by xmoyKing** [webpack/webpack.js.org#1851]
Should it show the diff on code section of [code-splitting/#dynamic-imports](https://webpack.js.org/guides/code-splitting/#dynamic-imports) ?

screenshot like blow:

![tim 20180224100716](https://user-images.githubusercontent.com/4265421/36624475-b94572aa-194a-11e8-8dc3-88726298c1b3.png)

**Comment by montogeek** [comment]
@xmoyKing What is missing in that page?

**Comment by xmoyKing** [comment]
It's not about missing something in this code section.

The question I want to know that are the diff labels and change logs of the code deliberate

or are these labels unnecessary?

PS: may be the question I asked is confusing.

**Comment by xmoyKing** [comment]
May be the question I asked is confusing. 

What I mean is that are these diff code (or change logs) deliberate.  I thought they're incorrect (unnecessary) before.

**Comment by montogeek** [comment]
Yes, they are deliberate there for guiding purposes. It is a way to show the user that is following the guide what should be deleted and what should be updated in each step.

**Comment by xmoyKing** [comment]
I see, Thanks a lot. : )
