### ISSUE TITLE
Update the Configuration section with webpack v4 configuration

### ISSUE THREAD

**Issue by jeremenichelli** [webpack/webpack.js.org#1869]
In the Configuration section we still have old config snippets and we also are not reflecting the fact that webopack is now cero config out of the box.

Some content might also need to be change so it's compatible with the new webpack default behavior.

**Comment by EugeneHlushko** [comment]
Hi @jeremenichelli 

I can take this if u hadn't started yet. Please feel free to assign at me at will

**Comment by EugeneHlushko** [comment]
this specific bit can be close i guess? @jeremenichelli @montogeek
