### ISSUE TITLE
Prevent warnings for optional modules

### ISSUE THREAD

**Issue by janjaap** [webpack/webpack.js.org#1876]
I'm working on an application (for which the configuration is based on ejected create-react-app) that imports configuration files to construct the app's global configuration object. Some of the files that can be imported, are optional. I've wrapped the inclusion commands for those files in a try-catch block, but Webpack still throws a warning and when `CI=true`, turns them into errors. Note that I'm using aliases for modules.

This is (a snippet of) my code:
```javascript
let cfg;

try {
    // required configuration files
    const globals = require('module-alias/cfg/globals.json');
    const routes = require('module-alias/cfg/routes.json');

    cfg = { globals, routes };
} catch (e) {
    if (process.env.NODE_ENV !== 'test') {
        throw new Error(e);
    }

    // test env, use appropriate config
    cfg = require('./testConfig');
}

try {
    // optional configuration file
    const theme = require('module-alias/cfg/theme.json');
    cfg.theme = theme;
} catch (e) {
    // no theme, continue
}

export default cfg;
```

The error that is thrown by Webpack is `Module not found: Can't resolve 'module-alias/cfg/theme.json' in '<folder-path>'` where `<folder-path>` is the path of the script trying to require the missing module. 

How can I prevent Webpack from generating warnings for configuration files that are optional?

**Comment by janjaap** [comment]
Using `react-dev-utils`' `formatWebpackMessages` function I managed to filter out warnings that I wanted to suppress, but I'm not sure if this is the way to go.

Code:
```javascript
const optionalModules = [
    'module-alias/cfg/theme.json',
];

const messages = formatWebpackMessages(stats.toJson({ warningsFilter: (warning) => {
    const isModuleNotFoundError = warning.includes('Module not found');
    const shouldBeIgnored = optionalModules.some(ignorePattern => warning.includes(ignorePattern));
    return isModuleNotFoundError && shouldBeIgnored;
} }, false));
```

**Comment by montogeek** [comment]
This issue belongs to webpack main repo, this repository is about its website documentation and documentation.

**Comment by TheDutchCoder** [comment]
Yes please take this up in the webpack repo :)
