### ISSUE TITLE
Ctrl+F awareness

### ISSUE THREAD

**Issue by arcanis** [webpack/webpack.js.org#188]
The current documentation works really well with in-page search tools, since every configuration option is on the same page. The new website breaks this by splitting every option inside multiple pages. It's a good idea from a discovery viewpoint, but when looking for help about a particular option, it makes it quite harder to find the right place. Maybe a page should be setup with a link for each different option. Something like:

> [resolve](http://example.org/resolve)
[resolve.root](http://example.org/resolve#root)
[resolve.module](http://example.org/resolve#module)
[resolve.fallback](http://example.org/resolve#fallback)
[output](http://example.org/output)
[output.path](http://example.org/output#path)
[output.filename](http://example.org/output#filename)
[output.publicPath](http://example.org/output#publicPath)
...

**Comment by sokra** [comment]
We could add it to the bottom of this page: http://webpack.js.org/configuration/

Do you want to send a PR?

## List of all options

(For easy Ctrl+F 😄 )

* [resolve](http://example.org/resolve)
* [resolve.root](http://example.org/resolve#root)
* [resolve.module](http://example.org/resolve#module)
* [resolve.fallback](http://example.org/resolve#fallback)
* [output](http://example.org/output)
* [output.path](http://example.org/output#path)
* [output.filename](http://example.org/output#filename)
* [output.publicPath](http://example.org/output#publicPath)

**Comment by gregvenech** [comment]
What do you guys think about hijacking the CMD / CTRL + F behavior and piping it to our own search bar? See #184 and [this issue](/gregvenech/webpack-design/issues/1). Working on finishing mockups for search on large and small screens, based off @patelsky's original concept.

**Comment by bebraw** [comment]
Worth a go.

**Comment by dzello** [comment]
As long as the search bar is nice and visible at the top I don't think we would have to hijack the keyboard, which would mean less surprises for new documentation visitors :)

The [React documentation](https://facebook.github.io) is likewise separated out onto a number of smaller pages, but we've seen that visitors are able to find what they're looking from with the search box, since all pages are collected by the DocSearch crawler into one index. No additional content or navigation required.

**Comment by gregvenech** [comment]
@dzello yea I guess my main point is that having a prominent search bar should resolve this issue whether we hijack the behavior or not.

**Comment by SpaceK33z** [comment]
So as discussed above, a prominent search bar is the way to go. This will be done in #184. Closing this in favor of #184.

Feel free to re-open if you think I have closed this too fast, but I really think it's not worth the extreme hacks we would need to do to get ctrl + f working "properly", and using the search bar is just as fast.
