### ISSUE TITLE
American vs British English?

### ISSUE THREAD

**Issue by kswedberg** [webpack/webpack.js.org#1882]
I started looking through the v4 documentation to fix some typos and clean up some punctuation/style/grammar issues, and I noticed that some spellings switch between the American variant and the British variant of a word. For example I see both "optimize/optimization" and "optimise/optimisation" used. 

Does this project have a preferred standard spelling for such words? From a cursory glance, it looks to me like American English spellings are used more frequently ("color" vs "colour"; "visualize" vs "visualise" etc.). Of course, I wouldn't change the spelling when it refers to the name of a tool, such as webpack's "analyse tool." Otherwise, however, I think some spelling consistency could help with readability. 

Project maintainers, please let me know if and how you'd like me to proceed with such spelling edits.

Thanks.

**Comment by montogeek** [comment]
I am rather new to the repository, but I would say that USA English should be used. @ChrisChinchilla could know better

**Comment by TheDutchCoder** [comment]
I'd vote for US English, as that's also the language used in JavaScript itself and probably the best "common ground".

**Comment by kswedberg** [comment]
Thanks for the replies, @montogeek and @TheDutchCoder . I'd vote for US English, as well, but as an outsider with zero contributions to the repo so far, I thought it would be undiplomatic of me to forge ahead without at least raising the question. 

@montogeek , would you like me to wait until we hear from @ChrisChinchilla ? Or shall I just submit a  pull request and let him and others weigh in on that?

**Comment by montogeek** [comment]
A PR would be a good start :)

**Comment by montogeek** [comment]
@kswedberg Still interested? Cheers!

**Comment by kswedberg** [comment]
@montogeek  Oh wow. Totally fell off my radar. This week is crazy for me, but I'll set myself a reminder to look at it next week. Cool?

**Comment by montogeek** [comment]
@kswedberg Whenever you can, thanks!

**Comment by kswedberg** [comment]
Pretty sure I and others have already taken care of the inconsistencies I noted above (e.g. in PR #3165) except for one I just noticed. Just created a PR for that one: https://github.com/webpack/webpack.js.org/pull/3303

Feel free to close this issue whenever you want. Also, I'm happy to proofread/edit anything at all if there's a need.

**Comment by EugeneHlushko** [comment]
Thanks, closing in this case
