### ISSUE TITLE
Documentation: Update CLI arguments

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack.js.org#1910]
We've got some new arguments in the CLI, which would need need to be shown in the documentation. Is there anyone that would do that? Have a look at  the arugments [here](https://github.com/webpack/webpack-cli/blob/master/bin/config-yargs.js) and [here](https://github.com/webpack/webpack-cli/blob/master/bin/webpack.js).

**Comment by montogeek** [comment]
I will

**Comment by montogeek** [comment]
Also https://github.com/webpack/webpack-cli/issues/361#issuecomment-374915440

**Comment by DanielRuf** [comment]
Is this still relevant?

**Comment by alexander-akait** [comment]
I think we can close it, resolved
