### ISSUE TITLE
Broken image on website

### ISSUE THREAD

**Issue by augbog** [webpack/webpack.js.org#1924]
Looks like the image is no longer available for this person's image

`https://opencollective.com/proxy/images/?src=https%3A%2F%2Fimages.githubusercontent.com%2Fandrewvieyra&height=96`

<img width="422" alt="screen shot 2018-03-17 at 6 21 29 pm" src="https://user-images.githubusercontent.com/2054339/37561623-3cbb859a-2a10-11e8-86f4-ecd4f810d30a.png">

**Comment by Youngestdev** [comment]
Probably he's changed it or he's no more part of open collective or a manual error.

**Comment by montogeek** [comment]
We added an `onError` handle to deal with broken images (https://github.com/webpack/webpack.js.org/pull/1846), but for some reason it is not working in the website, it works locally

**Comment by EugeneHlushko** [comment]
@montogeek i suspect its an issue with preact's `onError`

**Comment by EugeneHlushko** [comment]
Maybe it makes sense to update react to 16 and stop aliasing?

**Comment by developit** [comment]
Looks like this isn't actually being rendered on the client. Since it's just SSR, there's no event attached to those images at all.

**Comment by montogeek** [comment]
@EugeneHlushko It would be nice to have.

**Comment by augbog** [comment]
If it helps, I don't consistently see it because I imagine it only happens to opencollective related images so if it needs to be prioritized for later then that's fine. As of right now I don't see the issue anymore.

I don't think it makes sense to close the issue if it is an actual issue though but I leave that up to you :)

**Comment by EugeneHlushko** [comment]
I'm trying to fix this by not rendering the images during "SSR" render pass, but only clientside, means html will be up and events will be bound on time. you can check it here @augbog https://github.com/webpack/webpack.js.org/pull/2026/files#diff-9f531bc074d3219cdba0c558ba8350aeR98
CC @developit

**Comment by Munter** [comment]
Another improvement could be to style the images to their known width and height, so they don't break the layout of missing or make the layout jump while they are loading
