### ISSUE TITLE
Compiler page is not found.

### ISSUE THREAD

**Issue by RonanQuigley** [webpack/webpack.js.org#1931]
Currently if you open up https://webpack.js.org/api/compiler/ the page returns the following: 

![capture](https://user-images.githubusercontent.com/33596237/37650963-73a29b96-2c2e-11e8-892d-77a110ea89b6.JPG)

Any chance of a fix? I'm resorting to using a cached version at present.

**Comment by montogeek** [comment]
Use https://webpack.js.org/api/compiler-hooks/, we are updating broken links

**Comment by RonanQuigley** [comment]
Got it, thanks!
