### ISSUE TITLE
[Dependency: Guides] - Create "Migrating" section and move content from Guides

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#1933]
Dependency for #1859 

Goal: As a user I would like to be able to easily find (starting from the homepage), how to upgrade to the latest version of webpack.

- [ ] Create a new Section called "Migrate", it's creation should be at the same tier as "Guides"
  - [ ] The url to access this page should be `webpack.js.org/migrate`
- [ ] Move existing Migrating (v1 => v2/3) Guide and place it inside of new `Migrating` section under 
  - [ ] This page's url should be `webpack.js.org/migrate/3`

**Comment by onstash** [comment]
How about we add a link "Migration" section in the home page in this "It's that simple" section? Or probably something similar? Please let me know your thoughts on this. @TheLarkInn 😅 

<img width="1182" alt="screen shot 2018-03-21 at 22 42 09" src="https://user-images.githubusercontent.com/4272832/37725561-3c9276f4-2d59-11e8-8e64-3c39f607e924.png">

**Comment by TheLarkInn** [comment]
We can link to it from that page certainly, but this is just scoped to creating the section itself, and moving the existing guide to the new section location, and then with the PR that @sokra lands with #1939, then we can move that also into this section.

**Comment by EugeneHlushko** [comment]
@montogeek can you assign this on me, will implement over this weekend

**Comment by EugeneHlushko** [comment]
@TheLarkInn pls see PR open for any additions
