### ISSUE TITLE
[Dependency: Guides] - Add v4 Migration Guide

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#1934]
Dependency for #1859 

Goal: As a user looking to upgrade to webpack 4, I would like step by step instructions for any changes I need to make from my v3 configuration to update to webpack 4

MVP
========================
- [ ] Create new v4 Migration guide and place in "Migrating" section.
- [ ] The url should be `webpack.js.org/migrate/4`
- [ ] The migration guide should be formatted in the same way as the v3 migration guide (diff style)
- [ ] For loaders and plugins, link to new Plugin and Loader reference implementation docs

**Comment by onstash** [comment]
Hey Sean and the rest of the amazing contributors of Webpack! I would like to give back to the webpack community by contributing to the migration guide from v3 to v4 but I'm not sure where to start. Could you please help me get started with that? Thank you. :)

**Comment by dhruvdutt** [comment]
Hey @onstash. :wave: 
One of the best places to look for v4 changes is [this release note](https://github.com/webpack/webpack/releases/tag/v4.0.0).
I'd also recommend reading our [medium blog's](https://medium.com/webpack) latest blogs as well as looking over [v4 docs](https://webpack.js.org).
Welcome aboard. :shipit:

**Comment by TheLarkInn** [comment]
@onstash It looks like @sokra started a PR that you could review!!! What might be a great intro into the repo is https://github.com/webpack/webpack.js.org/issues/1933 which will let you get familiar with how the content is laid out in the source. How does that sound?

**Comment by onstash** [comment]
@dhruvdutt Thank you for listing those links. It actually helped me get started with the migration docs. :)

@TheLarkInn Ah. I just raised a PR that had a skeletal version of the migration docs. It's alright. Is it possible to contribute in a different way with respect to documentation?

**Comment by dhruvdutt** [comment]
@onstash, There are opportunities for everybody to contribute to webpack. :)

There are some minor issues in v4 docs PR #1856 which we haven't addressed yet. You can see the review comments to resolve them.
Also, take a look at the open issues with [Help Wanted](https://github.com/webpack/webpack.js.org/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Help+Wanted%22) label.

**Comment by nickbae91** [comment]
@onstash @TheLarkInn  I lack a bit of expertise to make good sense of the docs, which has prevented me from upgrading (barely got the webpack to do what I need ><). So props to you for driving this initiative! Will look forward to what's coming 👏👏👏

**Comment by lloydjatkinson** [comment]
Any updates? With 4 being the recommended and advertised version, a migration could is really needed for users of webpack 3...

**Comment by Piyushaa7** [comment]
I stumbled upon issue #1934 - "[Dependency: Guides] - Add v4 Migration Guide," and I'm eager to contribute to the Webpack community by working on this.

I'm particularly interested in creating a migration guide from v3 to v4. I'm ready to dive in, but I could use some guidance on where to start.  @dhruvdutt , could you please help me get started on this issue? I'm excited about the opportunity to contribute and make the migration process smoother for our users.

**Comment by snitin315** [comment]
Thanks for your interest, but I believe this has been resolved. Here is the migration guide -https://webpack.js.org/migrate/4/

Also, we are on webpack v5 now, hence closing this issue.
