### ISSUE TITLE
Section for optimization is missing under webpack.js.org/configuration/#options

### ISSUE THREAD

**Issue by Legends** [webpack/webpack.js.org#1938]
Section for `optimization` is missing in [https://webpack.js.org/configuration/#options](https://webpack.js.org/configuration/#options).

Has to be added.

**Comment by EugeneHlushko** [comment]
There is a page under concepts/mode, maybe that should be moved under configuration section?

**Comment by Legends** [comment]
I mean [optimization](https://medium.com/webpack/webpack-4-code-splitting-chunk-graph-and-the-splitchunks-optimization-be739a861366).

**Comment by EugeneHlushko** [comment]
Oh my bad, misread that one 👍

**Comment by tanhauhau** [comment]
i believe this is now added ? https://webpack.js.org/configuration/optimization/

**Comment by chenxsan** [comment]
> i believe this is now added ? https://webpack.js.org/configuration/optimization/

Seems so, thanks for heads-up
