### ISSUE TITLE
ExtractTextWebpackPlugin should be removed from v4.2.0 docs

### ISSUE THREAD

**Issue by janswee** [webpack/webpack.js.org#1945]
ExtractTextWebpackPlugin is not supported up to webpack >= v4.0.0

See issues thread: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/749

Please cleanup Webpack 4.2.0 Asset Management, Code Splitting, and Production guides. This is causing a lot of confusion.

Delete here: https://webpack.js.org/plugins/extract-text-webpack-plugin/
and here: https://webpack.js.org/guides/asset-management/
and here: https://webpack.js.org/guides/production/#split-css

Please refer users to https://github.com/webpack-contrib/mini-css-extract-plugin instead.

**Comment by montogeek** [comment]
Send a PR

**Comment by EugeneHlushko** [comment]
@janswee if u need help or dont have time i can put up a PR this weekend

**Comment by EugeneHlushko** [comment]
@montogeek pls assign on me for transparency, picking it up

**Comment by EugeneHlushko** [comment]
I am closing this one for now as #2028 was merged in already.

I did not remove ETWP and did not push a redirect from it to `mini-css-extract-plugin` as it is still a working plugin and its use case is being revisited in next major release. I have filed a PR to ETWP to say that it shouldnt be used for css in webpack 4 +
webpack-contrib/extract-text-webpack-plugin#777
