### ISSUE TITLE
Concepts - Mode: Add missing differences between production and development

### ISSUE THREAD

**Issue by edmorley** [webpack/webpack.js.org#1947]
From:
https://github.com/webpack/webpack.js.org/pull/1856#discussion_r173507062

The `production` mode enables a few more plugins than currently listed, eg `FlagIncludedChunksPlugin`, `OccurrenceOrderPlugin`, `SideEffectsFlagPlugin`, `FlagDependencyUsagePlugin`:
https://github.com/webpack/webpack/blob/4f399322ad1922ae7bafdeea1c4d83bf9c9851a7/lib/WebpackOptionsDefaulter.js#L192-L207
https://github.com/webpack/webpack/blob/fde018300aa52262c384e937c408d5dd97d62951/lib/WebpackOptionsApply.js#L307-L318

And `development` mode also enables `NamedChunksPlugin`.

Page in question:
https://github.com/webpack/webpack.js.org/blob/master/src/content/concepts/mode.md

**Comment by EugeneHlushko** [comment]
please close this one @montogeek

**Comment by edmorley** [comment]
@EugeneHlushko why was this closed?
The issue still applies to `master` and `next`.

**Comment by EugeneHlushko** [comment]
Hmm you are right, my mistake here @edmorley 
Will fix this asap

**Comment by mike3run** [comment]
This has been added properly on text but not on the code-diff that appears below
