### ISSUE TITLE
Consider simpler tagline

### ISSUE THREAD

**Issue by athyuttamre** [webpack/webpack.js.org#195]
While "webpack transforms your modules into production-ready bundles and assets" is accurate, I don't think it simply communicates what Webpack is or what use case it solves for.

One suggestion could be "webpack is a modern build tool for web applications", and we could expand more with a bullet point list or a grid of prominent features. (Think dependency graph, loaders and plugins, etc.)

Thoughts? Other ideas for taglines?

**Comment by TheLarkInn** [comment]
I think this is a great start. 

Why don't you update your issue with a few bulleted phrases that may capture a couple variations.

**Comment by skipjack** [comment]
Closing this as we recently simplified the tagline to "Who said front-end code can't be modular?".
