### ISSUE TITLE
What color theme is used for the webpack docs? 

### ISSUE THREAD

**Issue by FrozenHearth** [webpack/webpack.js.org#1952]
Really love the color theme used for the docs. I'm interested in knowing what it is.

![fontcolor](https://user-images.githubusercontent.com/27160715/37878336-19005c86-3085-11e8-9011-08d5f25fc5d6.PNG)

**Comment by montogeek** [comment]
A custom one https://github.com/webpack/webpack.js.org/blob/master/src/styles/prism-theme.scss
