### ISSUE TITLE
Documentation: talk about using webpack with TypeScript

### ISSUE THREAD

**Issue by athyuttamre** [webpack/webpack.js.org#196]
There is a large TypeScript community out there (especially with release of Angular 2.) It would be cool to have a page directed at creating a nice TS build with loader recommendations, best practices for performance, how to get typed CSS working (using [typed-css-modules-loader](https://github.com/olegstepura/typed-css-modules-loader) for example), and so on.

**Comment by krisimmig** [comment]
There is this [page](https://webpack.js.org/guides/webpack-and-typescript/), but if you follow the standard install procedure and don´t use the **@beta** tag to install webpack, this config for typescript doesn´t work. It would be nice to have a hint to which version of webpack is used for the example.

**Comment by skipjack** [comment]
> There is this [page](https://webpack.js.org/guides/webpack-and-typescript/), but if you follow the standard install procedure and don´t use the **@beta** tag to install webpack, this config for typescript doesn´t work.

That should be fixed now as the latest release is on 2.4.1. Re [that guide](https://webpack.js.org/guides/webpack-and-typescript/) are either of you interested in reviewing and/or updating it? I personally don't use typescript and I'm not sure if any of the other @webpack/documentation-team does either. Would be great to have someone who uses typescript with webpack on a daily basis review and edit it.

**Comment by athyuttamre** [comment]
I no longer use it on a day to day basis either. I'm certain there are many people who do use both products. If there's a broader platform to ask for contributors, we could find someone.

**Comment by skipjack** [comment]
> If there's a broader platform to ask for contributors, we could find someone.

Ah, good idea. I'll ping our gitter and slack channels now.

**Comment by skipjack** [comment]
Ok so there's one pr open (#969) and some others have gone in recently regarding typescript. I think this is safe to close now but please re-open with details on what needs to be added/changed if I'm missing something.
