### ISSUE TITLE
Documentation site styles not found, site broken.

### ISSUE THREAD

**Issue by NafaaBout** [webpack/webpack.js.org#1965]
The webpack documentation site styles are broken. Here what I get when I visit it.

![getting started page](https://user-images.githubusercontent.com/1812732/37963638-d020c0a4-31b6-11e8-98cc-ff1a8de8c221.png)

**Comment by montogeek** [comment]
Thanks for your report, could you please tell us:
Which browser?
Which OS?
Are you using an adblocker?

**Comment by jc231321** [comment]
Same for me. disabling adblock didn't help. The homepage itself is broken as well for example.  I get this in the console:
`[Error] Failed to load resource: the server responded with a status of 400 () (images, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (images, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (images, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (images, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (images, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (images, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (images, line 0)
[Error] Failed to load resource: the server responded with a status of 403 () (images, line 0)
[Error] Failed to load resource: the server responded with a status of 400 () (images, line 0)
[Error] Failed to load resource: the server responded with a status of 400 () (images, line 0)`

**Comment by montogeek** [comment]
@jc231321 Could you please post a screenshot from the Console logs?

**Comment by jc231321** [comment]
<img width="1436" alt="screen shot 2018-04-05 at 10 46 03" src="https://user-images.githubusercontent.com/23641681/38355931-99f2095c-38be-11e8-8ab4-38d6b7e070bf.png">
thanks for looking into it

**Comment by jc231321** [comment]
The same in Chrome console:
<img width="1431" alt="screen shot 2018-04-05 at 10 48 08" src="https://user-images.githubusercontent.com/23641681/38356042-ef758660-38be-11e8-8e89-386f9a1bca31.png">

**Comment by jc231321** [comment]
More info here:
<img width="1435" alt="screen shot 2018-04-05 at 10 49 46" src="https://user-images.githubusercontent.com/23641681/38356105-1e024dba-38bf-11e8-9bca-231bb320db9c.png">

**Comment by jc231321** [comment]
looks like some cloudflare IP got banned or something. I'm based in czech repubic (europe).

**Comment by montogeek** [comment]
@jc231321 Thanks, could you please open Network tab in Chrome, search for the CSS request and show Headers tab content, like this:
![image](https://user-images.githubusercontent.com/1002461/38356144-3c8fc3ac-38bf-11e8-9528-7658067cf524.png)

**Comment by montogeek** [comment]
We have no control over OpenCollective responses. We could fix our CSS request.

**Comment by jc231321** [comment]
<img width="1440" alt="screen shot 2018-04-05 at 10 53 22" src="https://user-images.githubusercontent.com/23641681/38356304-ab4037a0-38bf-11e8-82d5-56acdf1fb4f6.png">
<img width="1440" alt="screen shot 2018-04-05 at 10 53 33" src="https://user-images.githubusercontent.com/23641681/38356309-aec205ca-38bf-11e8-8ea4-f029bee4a8ec.png">

**Comment by montogeek** [comment]
Thanks, Can you please hard reload the page or try in Incognito mode or even in a different browser?

If it fails in Incognito mode, Could you please submit the same screenshot?

Thank you

**Comment by jc231321** [comment]
After clearing cache:
<img width="1552" alt="screen shot 2018-04-05 at 10 55 04" src="https://user-images.githubusercontent.com/23641681/38356376-dcc97228-38bf-11e8-91cd-6b7033c80e5a.png">
<img width="1440" alt="screen shot 2018-04-05 at 10 53 22" src="https://user-images.githubusercontent.com/23641681/38356377-ddec5616-38bf-11e8-978f-c5dcde7b9fae.png">

**Comment by jc231321** [comment]
Just tried incognito mode as well and I see the same thing

**Comment by montogeek** [comment]
Thanks, I will investigate this, first time I see it, sorry.

**Comment by jc231321** [comment]
Clearing all site data (incl cookies, etc) didn't help. Just tried that now as well. Thanks for looking.

**Comment by jc231321** [comment]
no problem. If you need further tests feel free to ask, thanks.

**Comment by jc231321** [comment]
I get:
![screen shot 2018-04-05 at 11 00 52](https://user-images.githubusercontent.com/23641681/38356695-b388b4ea-38c0-11e8-8353-7f0858ca1dd6.png)

**Comment by jc231321** [comment]
In the console I see the response comes from cloudflare. This really looks like some proxy cache issue.

**Comment by montogeek** [comment]
Yeah, I guess you can see its src code (https://github.com/webpack/webpack.js.org/blob/gh-pages/5741b873d63bd283fa34.css)

It is definitely something out of our hands, it was updated 34 mins ago, maybe you haven't received it, yet.

I am in Germany, it works here

**Comment by jc231321** [comment]
Yep, I see the code from this link. I have some colleagues from Karlsruhe, I can ask them to look as well.

**Comment by jc231321** [comment]
Colleague in Karlsruhe confirms it looks fine for him. Another colleague in czech republic confirms it's broken for her as well.

**Comment by montogeek** [comment]
@jc231321 It used to work fine for you in the past?

**Comment by jc231321** [comment]
@montogeek yes

**Comment by montogeek** [comment]
It is updated daily, I wonder if redeploy them would fix it

**Comment by CorwinCZ** [comment]
Broken for me too, same behavior as @jc231321 is describing.

**Comment by jc231321** [comment]
Can you please try? I could use having access to the documentation. Thanks a lot :)

**Comment by montogeek** [comment]
You can always clone the repo and run `yarn start`

**Comment by jc231321** [comment]
ah, looks like I've downloaded the wrong zip file then.

**Comment by montogeek** [comment]
How are you cloning it? run
1. `git clone https://github.com/webpack/webpack.js.org.git`
2. `yarn install`
3. `yarn start`
4. Open http://localhost:3000 in your browser

More info: https://github.com/webpack/webpack.js.org/blob/master/.github/CONTRIBUTING.md

**Comment by jc231321** [comment]
sorry, my fault trying to save some time. Yep, yarn install and yarn start worked for me. Good to know that this is possible in the future.

**Comment by jc231321** [comment]
Also the redeploy helped. The site is back up for me, thanks for resolving 👍

**Comment by dylmye** [comment]
Getting the same issue here - adding a query string fixes it too. Can anyone else repro? Chrome/FFX in the UK

**Comment by dylmye** [comment]
@EugeneHlushko seems all good here now - perhaps it's just a cdn delay after the branch is updated. Sorry to bump an old thread!
