### ISSUE TITLE
The docs build is broken due to invalid json response from opencollective

### ISSUE THREAD

**Issue by Munter** [webpack/webpack.js.org#1975]
The Travis build of the docs is failing due to invalid responses from the opencollective API during the supporters fetching stage.

Example: https://travis-ci.org/webpack/webpack.js.org/builds/360812190

Related issue: https://github.com/opencollective/opencollective-api/issues/1205

**Comment by montogeek** [comment]
@TheLarkInn It is mandatory to show backers in the homepage? We could fail silently to these errors and don't show them.

**Comment by montogeek** [comment]
Fixed: https://github.com/opencollective/opencollective-api/issues/1205#issuecomment-377960686
