### ISSUE TITLE
Add twitter card metadata

### ISSUE THREAD

**Issue by jeremenichelli** [webpack/webpack.js.org#1984]
I think we could easily introduce some metadata to display better content when docs are shared on twitter, nothing big but a nice to have I guess.

**Comment by montogeek** [comment]
Definitely, always nice to have.

**Comment by EugeneHlushko** [comment]
@jeremenichelli hi man, i hope you dont mind i've put up a PR for this as it was kinda stalled for a while (last action 5th of April)

**Comment by EugeneHlushko** [comment]
in rebuild now 🎉
