### ISSUE TITLE
--build-delimiter to add to the cli options 

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack.js.org#1987]
We recently added `--build-delimiter`

https://github.com/webpack/webpack-cli/blob/master/bin/webpack.js#L207-L210

I can make a PR to add it to the documentation but I would like to know which section we should add it to.

**Comment by kbgar24** [comment]
Is there any way to to access/config this --build-delimiter options from webpack.config.js file? I would like the output to be a variable available there, so just using --build-delimiter from the CLI isn't ideal.
