### ISSUE TITLE
Rule.type not documented ?

### ISSUE THREAD

**Issue by unilynx** [webpack/webpack.js.org#1994]
https://webpack.js.org/configuration/module/#module-rules does not seem to document that there is a 'type' option. Is this intentional (ie illadvised or deprecated?) or just missing ?

I needed to add `type: 'javascript/auto'` as documented here: https://stackoverflow.com/questions/49187802/how-to-disable-loader-in-webpack-4 to suppress the now-builtin json-loader from interfering with '.lang.json' extensions we were using ourselves. So that option still seems pretty useful, especially when transitioning from webpack 2 to 4

**Comment by nerdkid93** [comment]
Is there someone on the webpack team who can give a good explanation of what the `type` property does?I can make a PR but the only thing I'd feel comfortable doing is basically copying the text from the `RuleSetRule` schema.

**Comment by montogeek** [comment]
@nerdkid93 That works, it is better than nothing :)

**Comment by nerdkid93** [comment]
@montogeek any chance I could get a review from you for #2541?
