### ISSUE TITLE
No mention of the deprecation of in the Migration Notes extract-text-webpack-plugin

### ISSUE THREAD

**Issue by Bezilon** [webpack/webpack.js.org#2001]
Hi, there's a lack of mentioning that `extract-text-webpack-plugin` was deprecated in here for example. 
https://webpack.js.org/guides/migrating/#extracttextplugin-extract

I started running into issues because I couldn't find adequate info on this until someone responded to a stack trace of mine.

Please mention this in the appropriate places.

**Comment by montogeek** [comment]
Related #1859

**Comment by EugeneHlushko** [comment]
PR merged, change will be visible in docs after re-deploy
