### ISSUE TITLE
Questions about resolvers

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#201]

**Comment by TheLarkInn** [comment]
Stub

**Comment by sebastiandeutsch** [comment]
@sokra if "raw-file" considered a hook and "before-raw-file" considered an phase of the hook. What exactly is an action?

**Comment by sebastiandeutsch** [comment]
@sokra What would be the best way to model the "happy-path" of my graph? Currently there are some ifs and elses in the factory but I think the best way to educate the people is by just displaying the defaults in the graph.

**Comment by sebastiandeutsch** [comment]
@sokra would it make sense to document the existing plugins by having an example input and output?

E.g. ParsePlugin usually listens to the "resolve" hook and emits a "parsed-resolve". The request is parsed and enriched by additional information like

```
query: "",
module: false,
directory: false,
file: false
```

**Comment by SpaceK33z** [comment]
What is exactly the purpose of this issue? To answer the questions above? There are quite some docs now about resolvers.

**Comment by sebastiandeutsch** [comment]
@SpaceK33z I think you can close it. All questions regarding wording and functionality has been resolved.

**Comment by SpaceK33z** [comment]
All right!
