### ISSUE TITLE
Split Chunks Plugin documentation presumes a lot of prior knowledge about now-deprecated Common Chunks

### ISSUE THREAD

**Issue by jonnybot0** [webpack/webpack.js.org#2013]
Sparked by this Twitter thread:
https://twitter.com/TheLarkInn/status/983569227352178689?s=19

The SplitChunksPlugin is the replacement for the CommonsChunkPlugin. The [documentation for SplitChunks](https://webpack.js.org/plugins/split-chunks-plugin/) assumes a fairly deep amount of understanding about chunking. For new users getting started with webpack 4 or later, this is a bit annoying. The SplitChunks docs should be similar in progression to the [CommonChunksPlugin](https://webpack.js.org/plugins/commons-chunk-plugin/) docs, which explain the specific problems they're trying to solve and why. Also, pages that reference the CommonChunksPlugin like the [Code Splitting guide](https://webpack.js.org/guides/code-splitting/) should probably be updated to point users to the SplitChunksPlugin if they're on 4.0+.

[This person's notes](https://gist.github.com/gricard/e8057f7de1029f9036a990af95c62ba8) helped me figure out important, basic things (like, putting the splitChunks config inside the optimize: block), which weren't clear from the docs to a newbie like me.

**Comment by EugeneHlushko** [comment]
Hi @jonnybot0 
The migration guide is progressing very slowly, we did split up migration section into pages and now starting on the migration guide v3->v4 itself

Although as a quick help could you clarify what could be better on [splitChunks](https://webpack.js.org/plugins/split-chunks-plugin/#optimization-splitchunks) page? Because titles already say `optimization.splitChunks`.

Maybe examples should have full module to be clearer like that:
```
// webpack.config.js
module.exports = {
  ...
  optimization: {
    splitChunks: {...}
  }
}
```

**Comment by parit** [comment]
Hi @EugeneHlushko , 

I completely agree with @jonnybot0 .. documentation seems to be all over the place right now. For starters could we please list all the options/flags/properties available for splitChunks plugin? In one blog post I read there is a test property for cacheGroups.common but not sure if there is an exclude one too or not...

**Comment by jonnybot0** [comment]
I think having the full module would be helpful. If you're _new_ to webpack, you aren't going to intuit from the title where the splitchunks configuration should go. Show it in context. People go to docs trying to solve, "How do I..." type of problems when they're ready for the next step in their build, so providing an example with the context matters.
