### ISSUE TITLE
mini-css-extract-plugin is missing from plugins

### ISSUE THREAD

**Issue by Munter** [webpack/webpack.js.org#2016]
less-loader is linking to https://github.com/webpack-contrib/mini-css-extract-plugin which is rewritten to `/plugins/mini-css-extract-plugin` by `fetch.sh`

I think mini-css-extract-plugin isn't downloaded as part of the documentation because it doesn't match the `webpack-plugin` pattern

**Comment by EugeneHlushko** [comment]
This is already fixed in #2028
