### ISSUE TITLE
Build time is insufferably long

### ISSUE THREAD

**Issue by Munter** [webpack/webpack.js.org#2018]
This is my laptop building the documentation site:

![image](https://user-images.githubusercontent.com/331790/38588038-18772e10-3d24-11e8-89ce-38737f446bec.png)

This total resource consumption has been going on for around 20 minutes now.

Further more I see the build times tripling in travis:

![image](https://user-images.githubusercontent.com/331790/38588108-6154e776-3d24-11e8-86db-287d68d98399.png)

It looks like https://github.com/webpack/webpack.js.org/commit/b45b73e1a4f3d600f006fec5cc95de20aa9b7382 introduced a major performance regression

**Comment by montogeek** [comment]
Build times have been always big, that's one of the reasons we are rebuilding it on `rebuild` branch.

**Comment by montogeek** [comment]
This regression is bad, now it takes 8 mins to build it on my Mac, it used to take up to 3 mins :/
@EugeneHlushko @bebraw Any idea what could be causing this?

**Comment by EugeneHlushko** [comment]
Will profile this in evening asap

**Comment by bebraw** [comment]
@montogeek I sped up Antwar considerably a while ago (webpack 4 upgrade and other tuning). I don't know which version or setup your are using, though.

**Comment by montogeek** [comment]
@bebraw 0.28.3 https://github.com/webpack/webpack.js.org/blob/master/package.json#L44

**Comment by bebraw** [comment]
@montogeek Ok, hard to say without profiling. There are some optimizations I could do but I don't have time.

**Comment by EugeneHlushko** [comment]
BTW it did not look worse than original locally when i tested it initially, didn't expect to grow the build time with this PR. Maybe there is an extra iteration going on? 17min => 35 min looks very very bad

**Comment by EugeneHlushko** [comment]
the 44 min was probably due to change of packages cached vs not cached somewhere under .../.npm/cache/ next builds are very close 2x vs 3x of first build with updated packages and wp4

**Comment by EugeneHlushko** [comment]
Can we set node to ^8.9.0 here ? https://travis-ci.org/webpack/webpack.js.org/jobs/364985003/config

**Comment by jeremenichelli** [comment]
I was about to mention the Node version. We can check locally first if everything works as expected from a fresh install, and it everything looks good, then change it.

**Comment by EugeneHlushko** [comment]
i cannot check until tonight, if anyone willing to give it a shot before that pls do

**Comment by montogeek** [comment]
I have Node 8.10, still takes 8 minutes

**Comment by skipjack** [comment]
@EugeneHlushko @montogeek @jeremenichelli I'm fine with whatever you all want to use in terms of the latest node engine. On `rebuild`, I'm using the latest stable version of node and the pure webpack build using the `SSGPlugin` amounts to ~30s (and there's probably more opportunities for optimizations).

At this point, `rebuild` is getting much closer as @montogeek has helped to tackle a few of the remaining things. I updated `react-banner` yesterday (an abstraction of our `Navigation` component) which means I can finish the much simpler `Navigation` component on that branch. I'm going to spend some time on that this saturday and, if I have any remaining time, try to tackle another item from the list of TODOs.

Sorry if I'm sidetracking this conversation, but I just thought it's worth mentioning that we might be a week or two away from merging `rebuild` (especially if others keep helping). Maybe I'll open a PR soon if it hasn't been done already.

**Comment by EugeneHlushko** [comment]
I am looking at TODO list now and may help with things. Would be nice to get invite to slack @skipjack we had pinged Sean with @montogeek multiple times but he seems to ignore those notifications :D

**Comment by skipjack** [comment]
@EugeneHlushko actually I can invite you to slack myself, feel free to share your email here, send it to me privately on gitter or send me an email (use the one on my profile).

**Comment by Munter** [comment]
This is fixed on the  `rebuild` branch
