### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by renzhentaxi** [webpack/webpack.js.org#2019]
On some pages  the "concepts|configuration|api..." menu is missing. I don't think this is intentional but I might be wrong. 

![screenshot from 2018-04-10 23 57 30](https://user-images.githubusercontent.com/6445762/38595779-92a7d756-3d1b-11e8-89ac-26ab7f674563.png)

![screenshot from 2018-04-11 00 00 58](https://user-images.githubusercontent.com/6445762/38595780-92b3979e-3d1b-11e8-936b-9c8e41f4b620.png)

**Comment by EugeneHlushko** [comment]
doesn't look right indeed, guess it needs a fix

**Comment by montogeek** [comment]
@renzhentaxi Please tell us which browser and also post Console errors, if any.

**Comment by EugeneHlushko** [comment]
I am able to reproduce too on latest chrome, land on documentation the menu is missing, switch on left-hand side to any subsequent section and menu appears
