### ISSUE TITLE
css loader page bug

### ISSUE THREAD

**Issue by renzhentaxi** [webpack/webpack.js.org#2023]
when you click on one of the options on this page: https://webpack.js.org/loaders/css-loader/. 

![1](https://user-images.githubusercontent.com/6445762/38619927-4b66b7ae-3d6b-11e8-8877-768ccb1a07f3.PNG)

it takes u to the actual md file at https://raw.githubusercontent.com/webpack-contrib/css-loader/master/README.md#root.
![2](https://user-images.githubusercontent.com/6445762/38619931-4e29e42a-3d6b-11e8-9676-e095dbb781dc.PNG)

My chrome version
Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by montogeek** [comment]
@Munter I think this is related to your change

**Comment by Munter** [comment]
I have a fix in #2017

Can't do anything from my phone right now
