### ISSUE TITLE
Out-of-date documentation leads to broken build

### ISSUE THREAD

**Issue by thejohnfreeman** [webpack/webpack.js.org#2027]
I didn't spend much time searching, but couldn't find if this was a duplicate.

- [The issue.](https://github.com/webpack/webpack/issues/6858)
- [The out-of-date docs](https://webpack.js.org/guides/production/#setup), specifically these lines:
```diff
+ const common = require('./webpack.common.js');
```
- [The fix](https://github.com/webpack/webpack/issues/6858#issuecomment-378430698), specifically changing to this line:
```diff
+ const common = require('./webpack.common.js')();
```

**Comment by montogeek** [comment]
webpack [accepts](https://webpack.js.org/configuration/configuration-types/) configuration objects or a function which returns a configuration object, if `webpack.common.js` returns a function, you have to call it: `()` at the end.

In the docs, it returns an object, hence you don't have to call it.

**Comment by thejohnfreeman** [comment]
I see, then perhaps `webpack-merge` should call the function if it is passed one.
