### ISSUE TITLE
Linebreaks showing on home

### ISSUE THREAD

**Issue by eric-blue** [webpack/webpack.js.org#2031]
`/n` line break characters showing on home page of [webpack.js.org](webpack.js.org)

<img width="1028" alt="screen shot 2018-04-12 at 12 56 42 pm" src="https://user-images.githubusercontent.com/19786312/38700867-3f786046-3e51-11e8-8641-443a1092311e.png">

**Comment by montogeek** [comment]
@EugeneHlushko @munter Any idea about this?

**Comment by Munter** [comment]
I think https://github.com/webpack/webpack.js.org/pull/2026 might be causing this. But I'm so unfamiliar with the build system that I can't be sure. After the build times regressed it's impossible for me to build the docs on my home machine any more, so I can't bisect it.

I do note that the supporters are also not showing, which is what gets me thinging of https://github.com/webpack/webpack.js.org/pull/2026

**Comment by montogeek** [comment]
Fixed in https://github.com/webpack/webpack.js.org/pull/2033, would take ~1h to be deployed.

**Comment by montogeek** [comment]
Fixed, thanks for you report.
