### ISSUE TITLE
Document [contenthash]

### ISSUE THREAD

**Issue by edmorley** [webpack/webpack.js.org#2055]
Hi!

Support for a new `[contenthash]` template parameter was added in webpack/webpack/pull/6839, however it's not yet documented on any of:
https://webpack.js.org/configuration/output/#output-filename
https://webpack.js.org/guides/caching/#output-filenames

**Comment by FadySamirSadek** [comment]
I will pick this one up

**Comment by FadySamirSadek** [comment]
#2085
