### ISSUE TITLE
webpack-serve not documented

### ISSUE THREAD

**Issue by ferrao** [webpack/webpack.js.org#2069]
The `webpack-dev-server` repo clearly states:

> Please note that webpack-dev-server is presently in a maintenance-only mode and will not be accepting any additional features in the near term.
> Use webpack-serve for a fast alternative. Use webpack-dev-server if you need to test on old browsers.

I do not need to test on old browsers, so the choice seems obvious to me. But for some reason, I find no mention of `webpack-serve` on the docs. 

Which project should I currently use on my frontend javascript development with Webpack 4? `webpack-dev-server` or `webpack-serve`?

**Comment by montogeek** [comment]
@shellscape ping!

**Comment by shellscape** [comment]
The `webpack-serve` README is and will always be up to date. I'm positive the docs project would accept a PR syncing the README here, but I have no current plans to submit that as the project already had solid documentation.

**Comment by ferrao** [comment]
I agree that the project is well documented, but the documentation style at `webpack.js.org` is at another level with its concepts, configuration, guides and api sections.

But my main problem is not on how to use any of the two.  My problem is that as a webpack user I am confused and do not know what is the recommended way to go. It seems these are my choices:

`webpack-dev-server` - README says development stopped and hints at the `webpack-serve` alternative, but all examples/guides on the webpack.js.org site still use it.

`webpack-serve` - README says this module is still green and should be considered unstable. I gave it a try and I believe I have experienced this greeness already... 

So I do not think it is too much to ask the webpack team which one is it?

**Comment by maciej-gurban** [comment]
For people stumbling here from Google, it looks that `webpack-dev-server` is back in the game and is currently being actively developed again. The `webpack-serve` project has been archived.

**Comment by EugeneHlushko** [comment]
Under which search query @maciej-gurban ?

**Comment by EugeneHlushko** [comment]
webpack-dev-server's readme and on webpack.js.org doesn't have deprecation notices anymore. Should we just close this? CC @montogeek

**Comment by evilebottnawi** [comment]
webpack-serve is deprecated, please use webpack-dev-server
