### ISSUE TITLE
Broken Slideout Icon on Mobile

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#208]
My bad for merging this one into master without testing. Leaving here to track. Haven't looked at larger viewports.

Cc @gregvenech

**Comment by oliverturner** [comment]
It looks like the React JS isn't being loaded

**Comment by bebraw** [comment]
Yeah, we would need `Interactive` wrapper (on today's program) for that kind of bits since it relies on JavaScript.

**Comment by oliverturner** [comment]
@bebraw is that an antwar-specific thing? If needed I can hack in a quick `:target` hack that would fix it without js...

**Comment by bebraw** [comment]
@oliverturner Yeah, it's something I need to implement. Another way would be to go through jQuery and attach a custom script through the existing template.

**Comment by oliverturner** [comment]
At this point the best solution is the quickest solution ;)

**Comment by gregvenech** [comment]
@TheLarkInn yea sorry I was asleep when you asked if my PR was safe to merge. I should have mentioned the toggling functionality only worked on the dev server. There are also some styling tweaks that still need to be made to get it into a more presentable state (in mobile and normal). 

@bebraw @oliverturner yea obviously the preact solution would be best but yea we could also use vanilla js (if we can include scripts) or some css trickery to get the interactive bits to work in the meantime.

**Comment by TheLarkInn** [comment]
I believe @bebraw just finished the interactive bits

**Comment by bebraw** [comment]
Yeah, we should try a deploy.

**Comment by bebraw** [comment]
Works now (flashing during nav can be handled separately, limitation of the approach for now).
