### ISSUE TITLE
Documentation lacks information about optimization.minimizer option

### ISSUE THREAD

**Issue by Maximaximum** [webpack/webpack.js.org#2081]
The only place I could find information about `optimization.minimizer` option was on https://webpack.js.org/plugins/mini-css-extract-plugin/#minimizing-for-production page.

Because the page header says `MiniCssExtractPlugin`, I skipped that altogether, as I'm interested in setting options for `UglifyJSPlugin` which, in my case, is used only for JS minification, **NOT CSS**.

Generally speaking, I think it would be great if the documentation contained a separate section describing the `optimization` config options.

**Comment by montogeek** [comment]
Please, before submitting issues use search before, there is a PR for it already: https://github.com/webpack/webpack.js.org/pull/2053

**Comment by Maximaximum** [comment]
Oops, sorry for that. Thanks for the merge :smiley:
