### ISSUE TITLE
Getting started guide: confusion between main.js vs bundle.js

### ISSUE THREAD

**Issue by grantm** [webpack/webpack.js.org#2094]
Just working my way through https://webpack.js.org/guides/getting-started/ . 

Paragraph 2 of #modules talks about dist/bundle.js, but I think if I've followed the instructions correctly that should say dist/main.js

The next section uses a config file that specifies dist/bundle.js as the output, but there's no mention of changing dist/index.html to point to it instead of dist/main.js

**Comment by tdondich** [comment]
Confirmed as an issue.  This should instead be referencing the output bundle of main.js.

Great catch @grantm !
