### ISSUE TITLE
Single page or PDF version of the doc ?

### ISSUE THREAD

**Issue by alfredking1988** [webpack/webpack.js.org#2105]
Hi, the current doc is very good. It would be even better if they can be printed.

Is it possible to have the pdf version or single page version of doc ?

Just like the Node.js offical doc, it does provide a [view on single page](https://nodejs.org/dist/latest-v8.x/docs/api/all.html) link, so it can be printed easily.

Thanks

**Comment by jeffin143** [comment]
@montogeek @EugeneHlushko don't we have that feature now ?

**Comment by chenxsan** [comment]
Closed as we should have button to print the whole section as pdf.
