### ISSUE TITLE
webpack.js.org/src/content/concepts/mode.md does not define precendence

### ISSUE THREAD

**Issue by klick-barakgall** [webpack/webpack.js.org#2141]
Hey maybe it's defined elsewhere but if so I think it bears repeating in this section of the documentation.

It says that we can define the `mode` entry to dictate the mode to webpack, and that we can also define it in the command line using `--mode=` flag.

However it doesn't say which will be in effect if both the command line and webpack.config.js entry are defined.

Also does anyone know which wins? I assume command line will override config as it is more immediate, but I don't want to assume.

**Comment by EugeneHlushko** [comment]
cc @ev1stensberg

**Comment by ev1stensberg** [comment]
Let me check & update the docs
