### ISSUE TITLE
Fix linter: throw on broken formatting in code examples

### ISSUE THREAD

**Issue by byzyk** [webpack/webpack.js.org#2151]
Code examples formatting seem to be broken in some places (eg. #2150 #2111 etc). 

I suggest linter could attempt to fix code formatting automatically or at least throw during CI.

**Comment by jeremenichelli** [comment]
I think is worth, though it's true that some examples will not be valid js, like for example the one in configuration index page. Basically this requires an audit on how many places we have this situation and if it's worth re-writing those examples to some other format that will allow linting inside markdown articles.

I kinda feel it's a little overkill.

**Comment by byzyk** [comment]
There were around 250 invalid code issues last time I checked, but most of them are easy to fix. Same as the example above, you just wrap code chunk with `module.exports` declaration and you're good to go. We don't have to rewrite all code examples completely, so it won't affect the content. On the other hand, it will make docs look more consistent and user-friendly. I should be able to submit a PR in a couple of days

**Comment by jeremenichelli** [comment]
That would be awesome @byzyk, tag me as a reviewer :)

**Comment by skipjack** [comment]
Note that we did have this functionality before and decided to move away from it. If we do add this again I recommend using a different eslintrc file as the requirements for example code should be much less stringent than the actual code that powers the site.

**Comment by byzyk** [comment]
@skipjack thanks for sharing your concern. The way I implemented it is through ESLint `overrides` property which allows us to define rules specifically for `.md` files, thus not affecting actual source files.

**Comment by skipjack** [comment]
Yeah that makes sense. As long as it’s possible to delineate the two in certain ways.
