### ISSUE TITLE
Suggestion: Feedback System?

### ISSUE THREAD

**Issue by Legends** [webpack/webpack.js.org#2175]
Is it possible to establish a Feedback System for webpack.js.org?
Like [here](https://docs.microsoft.com/en-us/dotnet/api/system.uri.tostring?view=netframework-4.7.2#feedback) for example?

We have many contributors with different perceptions and explain things from their point of view, which is sometimes too high-level for beginners.

With such a system we could easier spot issues in the documentation of webpack. The usera could leave feedback for a certain page/section, instead of opening an issue or an issue could be opened through the feedback system by the maintainers/contributors.

For example, there is a part where `reuseExistingChunk` is mentioned in the docs. And the user could give feedback like: Wtf, does `reuseExistingChunk` do?
So if several users complain about the same thing, we would know that there is an issue with this part in the docs.

Just a suggestion....

**Comment by montogeek** [comment]
I like it, no sure if worth it.

**Comment by EugeneHlushko** [comment]
I am not sure its worth it, webpack doesn't have FT contributors for monitoring and answering to such feedback outside of github.com
Even if we spend time implementing it and defining a useful process for it.

webpack is an open source tool for developers to use free of charge. It would be good that if users (read: developers) after finding a lacking piece of documentation would:
- file an issue and wait for someone to pick it up
- file an issue and try to do resolve it yourself (preferable option in open source world, which means understanding the feature from playing with source code and chatting in gitter/slack/gh issue) via pull request

**Comment by Legends** [comment]
I assume, that most **new** users don't open issues for webpack.js.org. They try it out like depicted, it works or it doesn't work... giving up... switching to something else.. and you wouldn't know.
Feeback would be easy (click button and comment) and if the docs are fine, there shouldn't be much work otherwise something is wrong, right !? :-)

Of course, if the overhead of implementing and maintaining is is bigger than the gains, then probably not.
Closing this for now...

If someone has a suggestion how to easily implement this, feel free to reopen the thread...

**Comment by montogeek** [comment]
Today I realize we could to this:
Implement a Medium-like selection that would allow the user to select a part of text, then write some feedback and it would get posted as an issue on GitHub.

**Comment by montogeek** [comment]
For example:
https://github.com/webpack/webpack.js.org/issues/new?title=%22new%20issue%22&body=%22my%20description%22

**Comment by Legends** [comment]
Can you point me to a Medium like selection section, I want to take a look... I only know this "clap" thing :-)

The only problem I see with your suggestion is, that it can create double, triple... threads for the same issue.
Feedback could be given in repect to a certain section, if the user clicks feedback, then the feedback app should check for open issues regarding this section.
If issues already exist, tell the user to first check if one of them not already covers his issue (show list of links with active issues for this section which he can choose from), otherwise she/he can create a new issue.

**Comment by montogeek** [comment]
https://camo.githubusercontent.com/1a028beccc7fdebeaee6d1c02f778956fd3e5ae1/68747470733a2f2f6d6178617274323530312e6769746875622e696f2f73686172652d746869732f6578616d706c652e676966

https://github.com/MaxArt2501/share-this

Your related issues idea is implemented by this extension https://github.com/sindresorhus/refined-github

Maybe one day it would be part of GitHub, one can dream :D

**Comment by EugeneHlushko** [comment]
yep i like that 👍

**Comment by Legends** [comment]
Yes, `share-this` in combination with [Avoid opening duplicate issues](https://user-images.githubusercontent.com/29176678/37566899-85953e6e-2abf-11e8-9f0e-52d18c87bbe3.gif) would be fantastic.

As I am not a github geek rather noob, but is there an api available for this `prevent duplicate` feature?

**Comment by montogeek** [comment]
@Legends Probably not, but we can check refined github extension to see what it does

**Comment by Legends** [comment]
I have downloaded the source code of the chrome extension, thanks for the link.
But now I see, that you have built the docs using React.... 
I've no clue about React, soooo... if someone wants to implement this in the future, feel free to do it :-)

Over and out :D
