### ISSUE TITLE
The Module configuration interface does not document defaultRules

### ISSUE THREAD

**Issue by thw0rted** [webpack/webpack.js.org#2176]
The [docs for Module options](https://webpack.js.org/configuration/module/) make no mention of the `defaultRules` option.  I only know it exists at all because of [this super-obscure fix](https://github.com/webpack/webpack/issues/6725#issuecomment-372182505); I have no idea how or why that works because the option being used isn't documented at all.

Once the docs are updated, I can add the option to `@types/webpack`... would be nice to stop VS Code / Salsa from bitching at me.

**Comment by snitin315** [comment]
This has been now added https://webpack.js.org/configuration/module/#moduledefaultrules
