### ISSUE TITLE
Raw markdown appearing on some loader pages.

### ISSUE THREAD

**Issue by mikegreiling** [webpack/webpack.js.org#2178]
Some raw markdown tags are appearing on a few webpack loader pages, like [raw-loader](https://webpack.js.org/loaders/raw-loader/) and [file-loader](https://webpack.js.org/loaders/file-loader/).  These appear to be links to build/stat badges from the GitHub readme.

<img width="729" src="https://user-images.githubusercontent.com/812328/40332777-f4a59226-5d1a-11e8-8c64-588677d9938c.png">

**Comment by EugeneHlushko** [comment]
this might be ok on `rebuild` branch, needs confirmation

**Comment by budmc29** [comment]
Any updates on this?

I can take at stab at trying to fix this, if it's still an issue.

**Comment by EugeneHlushko** [comment]
i think its not, did you try `rebuild` branch?

**Comment by budmc29** [comment]
@EugeneHlushko Looks like this issue is fixed in the `rebuild` branch.

**Comment by montogeek** [comment]
@budmc29 It is.
