### ISSUE TITLE
404 on plugins list page

### ISSUE THREAD

**Issue by warpdesign** [webpack/webpack.js.org#2185]
On the [plugins](https://webpack.js.org/plugins/) the link to [NoEmitOnErrorsPlugin](https://webpack.js.org/plugins/no-emit-on-errors-plugin) is broken.

I had a look at the [source code] (https://github.com/webpack/webpack.js.org/tree/master/src/content/plugins) to fix it myself but couldn't find the related file: is it missing?

**Comment by warpdesign** [comment]
Seems like it was accidentaly removed here #2112

**Comment by EugeneHlushko** [comment]
Yeap that link needs update, will fix 👍

**Comment by EugeneHlushko** [comment]
Thanks mate, PR is up @warpdesign @montogeek
