### ISSUE TITLE
Recommendations from chapter "Extracting Boilerplate" do not work for webpack 4

### ISSUE THREAD

**Issue by in19farkt** [webpack/webpack.js.org#2204]
For webpack 3 it works, but after updating to version 4 I get the error `"Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead"`. And I can't find in the documentation how it doing in version 4.

**Comment by EugeneHlushko** [comment]
@montogeek there are no PRs on that files recently? i am missing github feature (search PRs that touch xxx file)... I will take on this if not
