### ISSUE TITLE
The search icon should automatically focus the search input

### ISSUE THREAD

**Issue by mikegreiling** [webpack/webpack.js.org#2208]
This is a minor nitpick, but it would save me a click and I reference the webpack documentation often enough for this to be a nuisance.

When you click the search (magnifying glass) icon at the top of the page, it does not highlight the search input that appears.  So I need to click on the icon, then click on the input field, and then start typing my query.  It would be nice if that second click were not necessary 😄

**Comment by montogeek** [comment]
What is your browser?
What is your operating system?
What scripts blocker extensions are you using?

Because it works on latest Firefox, Chrome, Edge, Internet Explorer and Brave on Windows.

**Comment by mikegreiling** [comment]
Sorry I should have mentioned, I'm using Safari 😆 

I suppose that's my problem then.  Still, it would be nice to get a fix for that browser.

**Comment by montogeek** [comment]
Safari on Windows or OSX?

**Comment by mikegreiling** [comment]
macOS 10.13.4
Safari 11.1

**Comment by tryzniak** [comment]
Turns out it's a safari "feature", check out [here](https://caniuse.com/#search=autofocus) and [here](https://medium.com/@brunn/autofocus-in-ios-safari-458215514a5f). Safari won't let to focus input neither with `autofocus` attribute nor programmatically like `document.querySelector("input").autofocus = true`. 

Looks like this issue can be closed.

**Comment by mikegreiling** [comment]
@tryzniak I am reporting this issue in regards to macOS Safari, _not_ iOS.

Also is there anything stopping us from just attaching an event handler to the `click` event of the icon and then focusing the input from there?  It’s more code than, `autofocus="true"`, but it’s not _that_ cumbersome

**Comment by tryzniak** [comment]
@mikegreiling I only tested on MacOS Safari 11.1.
But it looks to me like your approach has already been implemented, [check this out](https://github.com/webpack/webpack.js.org/blob/95fed9f37a71b6c5fcf25623156b487c8f11bc04/src/components/Navigation/Navigation.jsx#L161). Safari is super stubborn about not letting inputs to focus without user interaction.

**Comment by mikegreiling** [comment]
one would think clicking on a button on the page constitutes “user interaction” 🤔

**Comment by chenxsan** [comment]
Closing as it's not valid anymore.
