### ISSUE TITLE
Clarification/grammar - concepts-loaders

### ISSUE THREAD

**Issue by Legends** [webpack/webpack.js.org#2210]
[Section-concepts-loaders](https://webpack.js.org/concepts/loaders/#loader-features)
Didn't get the bolded part, perhaps it could be rephrased or made more clear??

> Loaders can be chained. They are applied in a pipeline to the resource. A chain of loaders are executed in reverse order. The first loader in a chain of loaders returns a value to the next. **At the end loader, webpack expects JavaScript to be returned.**

What means: At the end loader..?
Should it mean, Webpack expects JavaScript to be returned by the last loader in the chain?

**Comment by montogeek** [comment]
Yes, send a PR
