### ISSUE TITLE
output.chunkFilename out of date regarding defaults and [name] replacement

### ISSUE THREAD

**Issue by edmorley** [webpack/webpack.js.org#2221]
In this section:
https://webpack.js.org/configuration/output/#output-chunkfilename

It currently says:
> By default [id].js is used or a value inferred from output.filename ([name] is replaced with [id] or [id]. is prepended).

From code inspection this doesn't appear to be correct:
https://github.com/webpack/webpack/blob/e2fe2009d9f2b26a8d751ea89e184d6ec96e37d7/lib/WebpackOptionsDefaulter.js#L91-L104

For example:
* If `filename` is set to its default value, then `chunkfilename` is set to the same value, rather than `[id].js`.
* Usages of `[name]` are not replaced by `[id]`

**Comment by montogeek** [comment]
Send a PR

**Comment by edmorley** [comment]
Hi! Thank you for the reply.

Just as a bit of feedback (mainly for other PRs where issue authors may not be as used to the webpack project) - the wording "Send a PR" can come across as a bit abrupt. The kind of phrasing that I've seen used to good effect in open source projects (Mozilla's or otherwise) is something like:

"Thank you for the issue. We're pretty swamped with XYZ at the moment (/this project is only volunteer run...), so if you'd have a chance to open a PR for this issue, this we'd really appreciate it. `<link to contribution guide etc>`"

**Comment by EugeneHlushko** [comment]
Very nice, didn't know there are saved replies in github :) thank you mate
