### ISSUE TITLE
output.libraryExport and import

### ISSUE THREAD

**Issue by Wikiki** [webpack/webpack.js.org#2246]
Hi,

I need some help please, I'm trying to biuld a library that could be used both by ES5 and ES6 javascript source. I mean I want to be able to directly call my library in script file and also able to use import to use it.

I have the following output configuration:
```javascript
output: {
          filename: config.javascript.output.filename + '.js',
          library: config.javascript.output.name,
          libraryTarget: config.javascript.output.format,
          libraryExport: 'default'
},
```

but when doing
```javascript
import MyLibrary from 'myLibrary';
```
 I get the following error <code>SyntaxError: import not found: default</code>

And if I remove the <code>libraryExport: 'default'</code> then I'm not able to use it like following anymore:
```html
<script type="text/javascript" src="myLibrary.js"></script>
<script>
  new MyLibrary;
</script>

How can I handle that ?
```

**Comment by montogeek** [comment]
Please use Stackoverflow for questions, this repository is only for webpack documentation issues,
Also, check this issue for more info https://github.com/webpack/webpack/issues/3929.
