### ISSUE TITLE
Configuration options "stats" missing in docs

### ISSUE THREAD

**Issue by danez** [webpack/webpack.js.org#226]
I cannot seem to find any documentation about the stats option which seems to be valid according to the error message:

```
Warning: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'failOnError'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
```

**Comment by bebraw** [comment]
Sounds like your configuration has an extra property. Getting rid of that `failOnError` field might fix it.

That said, these fields need to be documented.

**Comment by danez** [comment]
Yes I copied the error from webpack/grunt-webpack#81. Because i wanted to figure out what this option is doing, because if webpack is now printing the stats on it's own, when this option is set, I could remove the stats printing in the grunt plugin. But even after looking at the source I have no idea what it is doing. :D

**Comment by SpaceK33z** [comment]
I documented it [here](https://webpack.js.org/configuration/dev-server/#devserver-stats-) for dev-server, but it seems to be also valid for webpack.

**Comment by SpaceK33z** [comment]
Discussed with @bebraw: we'll move the current docs for `stats` in dev-server to a separate page, and refer to it from dev-server.
