### ISSUE TITLE
AutomaticPrefetchPlugin not documented

### ISSUE THREAD

**Issue by Legends** [webpack/webpack.js.org#2267]
I cannot see the AutomaticPrefetchPlugin under [plugins](https://webpack.js.org/plugins/prefetch-plugin/).
If it is very similar to the `PrefetchPlugin` we can add it there, create a separate menu entry and deep link it...

**Comment by EugeneHlushko** [comment]
@sokra by looking at plugin code it seems that it will do prefetch to all `NormalModule`s after compilation was done, can you provide any additional context/info we might add to docs for that?

**Comment by sokra** [comment]
prefetch comes with two meanings in webpack:

* (web) prefetch: adding a prefetch `<link>` tag.
* (build) prefetch: discovering a module in the graph earlier to start building these module (and dependencies) earlier (in parallel).

This is about (build) prefetch. The PrefetchPlugin discovers a single module earlier. The AutomaticPrefetchPlugin discovers all modules from the previous compilation earlier when watching.

May or may not have a performance benefit. I guess it's not that important considering that the incremental build times are pretty fast anyway.
