### ISSUE TITLE
ConstPlugin - Internal plugins

### ISSUE THREAD

**Issue by Legends** [webpack/webpack.js.org#2275]
I saw this [wiki-page ](https://github.com/webpack/docs/wiki/internal-webpack-plugins) which describes internal plugins.
Could this page be enriched with infos and added to the official docs?

What does [ConstPlugin ](https://github.com/webpack/docs/wiki/internal-webpack-plugins#constplugin)actually do?
The wiki says:

>  Try to evaluate expressions in if(...) and replace it with true/false.

But this [issue ](https://github.com/webpack/webpack/issues/7519 )says that it should also remove dead branches....?

I thought `treeshaking` is done by the `UglifyJsPlugin`?
Does it mean that `ConstPlugin` does it too?

**Comment by EugeneHlushko** [comment]
This is not exactly tree shaking but dead branches elimination. The source code has good comments on the strategy, but i would suggest adding this to the /plugins/const-plugin page. If you wish to file a PR please do, otherwise ping me here and i'll pick this one up @Legends

**Comment by Legends** [comment]
Dead branches = unreachable code, like `if(false){....}`?
Treeshaking = removing unused exports of imported modules.

Not sure, but I would put it under 
`Plugins-> Internal `  // internal plugins
and
`Plugins-> External ` // other plugins

 It's more interesting perhaps for webpack devs, than standard webpack users...

@EugeneHlushko It's yours, pick it up.

**Comment by EugeneHlushko** [comment]
Okay i will CC you in PR when something is up
