### ISSUE TITLE
Valid configuration syntax/ordering?

### ISSUE THREAD

**Issue by timdorr** [webpack/webpack.js.org#228]
In examples throughout [the Concepts section of the docs](https://github.com/webpack/webpack.js.org/blob/master/content/concepts/index.md), this kind of pattern is used:
```js
module.exports = config;

const config = {
  entry: './path/to/my/entry/file.js'
};
```

However, this appears to be invalid because the `config` variable is referenced for the export before it is defined. The result is errors like this (under Node 6.x):
```sh
ReferenceError: config is not defined
    at Object.<anonymous> (/Users/timdorr/src/conf.js:1:80)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at repl:1:14
    at sigintHandlersWrap (vm.js:22:35)
```
A `var` works without errors, but returns `undefined`, as it doesn't have a temporal dead zone like `const`/`let` do.

It should be a simple fix to move those exports to the bottom.

**Comment by tizmagik** [comment]
I'd like to take this, if that's cool? I should be able to get a PR out tonight.

**Comment by SpaceK33z** [comment]
@tizmagik, sure!

**Comment by tizmagik** [comment]
Would you prefer:

```js
module.exports = {
  // ...
}
```

Or

```js
const config = {
  // ...
}

module.exports = config;
```

**Comment by timdorr** [comment]
I think just `const config = {...` might be best, as you don't have to prescribe a module system, or even bring it up every time. Perhaps just once at the beginning to establish that you're building a config object and it needs to be exported as a module. But after that is established, no need to include it every time.
