### ISSUE TITLE
Document plugin `context` / `context.reportProgress` usage

### ISSUE THREAD

**Issue by elliottsj** [webpack/webpack.js.org#2289]
Following up on https://github.com/webpack/webpack/pull/7442, it would be useful to have some documentation for plugin authors on the `reportProgress` function, and more generally, the `context` object that's available when tapping into a hook with `context: true`.

I'd like to make a PR for this; would https://webpack.js.org/api/plugins/ be the best place to add this documentation?

**Comment by montogeek** [comment]
@elliottsj Yes, that would be very welcome

**Comment by jeffin143** [comment]
This seems done :) @montogeek
