### ISSUE TITLE
Further reading and Module Identifiers sections in Caching guide are out of date 

### ISSUE THREAD

**Issue by kasperpeulen** [webpack/webpack.js.org#2296]
See:
https://webpack.js.org/guides/caching/#conclusion

All the links talk about webpack 2 or webpack 3.

**Comment by kasperpeulen** [comment]
Module identifiers is also out of date. It uses CommonsChunkPlugin in the configuration:
https://webpack.js.org/guides/caching/#module-identifiers

**Comment by EugeneHlushko** [comment]
Yeap this needs a good cleanup and update, up for a pr or should i grab it @kasperpeulen

**Comment by kasperpeulen** [comment]
@EugeneHlushko I don't think I'm the good candidate for the PR, because I don't have much knowledge on this topic.

The reason I post this is because I was searching for more "Further Reading" on this topic and I could not find it, I could just remove "Further Reading" section of course.

About the Module Identifiers, would removing the CommonsChunkPlugin references and replacing it with a webpack 4 configuration using optimization.splitChuncks be sufficient?

**Comment by EugeneHlushko** [comment]
Yes i already did that for `Extracting boilerplate` section above so you could take that as a reference. Also you would need to re-run the demo project with latest webpack after you've up with configs and update output log(s). I would also ask to state at least one sentence why each of the item is getting deleted in the PR so everyone could have an idea without investigation. If you feel more comfortable with just removing the outdated referenced read pelase do so and i can follow up with the section refactor in other PR.

**Comment by afontcu** [comment]
Hi! I'm willing to help, and this looks like a good first issue!

To recap, after I downloaded and ran the demo project in local, i should:

1. Rerun the latest webpack and update the logs.
2. Remove the outdated references
3. In the PR, justify why things are getting removed.
4. anything else?


Thanks 😄

**Comment by stavalfi** [comment]
Does it mean that Module Identifiers are no longer part of webpack?
