### ISSUE TITLE
yarn build  --> 100% CPU + RAM usage goes towards its limits

### ISSUE THREAD

**Issue by Legends** [webpack/webpack.js.org#2321]
When I try to build the `webpack.js.org` project I get 100% CPU usage constantly and RAM is rising.
My lap is not the slowest Win10 x64, 16GB RAM and 8 x i7 cores.

```
git clone https://github.com/webpack/webpack.js.org.git
yarn // install the deps
Open Git Bash --> yarn build   // the build starts
```
I have to quit the `build` during execution otherwise my lap gets non-responsive and I do have to do a hard-reboot.

In task manager I can also see several dozens of `node.exe` processes running, count is rising...

![image](https://user-images.githubusercontent.com/966368/42134702-51e6a9e8-7d41-11e8-828f-6c0f0983dbb5.png)

**Comment by Legends** [comment]
No, I didn't want to contribute currently.

But this is not a really clever solution. After 5 builds the lifetime of my CPU`s decreases by 50% haha :D
I mean, if my laptop gets unresponsive, it cannot be good. During the build above I was able to do some screenshots and kill the relevant processes.

Is there an alternative? Or do I have to accept 100% CPU usage when doing `yarn build`?

P.S.: What is the grand `rebuild` ?

**Comment by montogeek** [comment]
@Legends You can change this parameter: https://github.com/webpack/webpack.js.org/blob/master/antwar.config.js#L5, but it would make it even slower but will only whatever you pass as number.

Rebuild: https://github.com/webpack/webpack.js.org/pull/2039

**Comment by Legends** [comment]
I set it to:
` maximumWorkers: 1,` but no much success.

After every "Finished writing pages" it again jumps to 100%.

I see it's getting handled, I hope that the grand rebuild takes this issue into account..

**Comment by dhruvdutt** [comment]
@Legends Any way to contact you? Can you please email me at dhruvdutt.jadhav@gmail.com
