### ISSUE TITLE
Drop "it's that simple"

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#2378]
Let's switch up the header to something that might leave a first timer feeling frustrated if they didn't end up getting webpack working on the first try. 

This is something I had brought to me as a small but really impactful change! Some suggestions:

* Let's dive in/deeper!!!
* <Open for suggestions>

**Comment by EugeneHlushko** [comment]
Suggest changing it to `Next steps: `

**Comment by rouzbeh84** [comment]
<details>
  <summary>Before beginning, prepare carefully. (cicero)
</summary>
  <img src="https://dha4w82d62smt.cloudfront.net/items/3D2b1A3M412D2p272J2W/Image%202018-07-24%20at%2011.17.02%20PM.png?X-CloudApp-Visitor-Id=2881526&v=c1a8a05c" />
</details>
---
<details>
  <summary>The beginning is always today. (mary shelley)
</summary>
  <img src="https://dha4w82d62smt.cloudfront.net/items/1J2R2F093Y0h2l3S0j43/Image%202018-07-24%20at%2011.13.54%20PM.png?X-CloudApp-Visitor-Id=2881526&v=4c534149" />
</details>
---
<details>
  <summary>The beginning is the most important part of the work. (plato)
</summary>
  <img src="https://dha4w82d62smt.cloudfront.net/items/1a3p1E36050x1e1q1u0K/Image%202018-07-24%20at%2011.12.02%20PM.png?X-CloudApp-Visitor-Id=2881526&v=ca53c08d" />
</details>
---
<details>
  <summary>Awesome isn't it? Lets dive in! (Fernando Montoya)
</summary>
  <img src="https://dha4w82d62smt.cloudfront.net/items/280B1s461Z0v2P0z0z3R/Image%202018-07-24%20at%2011.25.07%20PM.png?X-CloudApp-Visitor-Id=2881526&v=178ea3da" />
</details>
---
<details>
  <summary>First step is always the hardest (proverb)
</summary>
  <img src="https://dha4w82d62smt.cloudfront.net/items/280B1s461Z0v2P0z0z3R/Image%202018-07-24%20at%2011.25.07%20PM.png?X-CloudApp-Visitor-Id=2881526&v=178ea3da" />
</details>

**Comment by TheLarkInn** [comment]
These are all super awesome folks. I'm pretty proud of the variety here. I'm going to get some external opinions also!!!

**Comment by TheLarkInn** [comment]
I really love then Fernando Montoya reference. Haha there's my official vote for now.

**Comment by anshumanv** [comment]
> I really love then Fernando Montoya reference. Haha there's my official vote for now.

Sounds good to me too, @EugeneHlushko @montogeek thoughts?

**Comment by EugeneHlushko** [comment]
Yeah i guess `Awesome isn't it? Lets dive in!`

Has to be `Let's` though. Will up a PR
