### ISSUE TITLE
Custom compress/minified functionalities for javascript packages.

### ISSUE THREAD

**Issue by D19cannon** [webpack/webpack.js.org#2379]
Hi guys! I am having some trouble for the last 2 days with webpack. 

For my project I tried to use the "development" and "production" mode which resulted in a problem in my code.

My packages look basically like this:

`var myPackage = (function () {
  test: funtion(){
    ....
  }
})`

However, whenever I run development or production the bundle looks like this:

`(function(modules) { ...`

// webpackBootstrap
	// The module cache
`var installedModules = {}; ...`

// The require function
`function __webpack_require__(moduleId) {
...`
(function(module, exports) {
`var myPackage = (function () {
  test: funtion(){
    ....
  }
})`
}
})`

It's two layers deep (encapsulated/hoisted) in which my entire package is not readable.

Is there a way that when I bundle my files to prevent this from happening?

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.

**Comment by D19cannon** [comment]
@montogeek May I issue it as  feature so that webpack is able to handle:
`var myPackage = (function () {....}(this)`

It seems like a useful feature?
