### ISSUE TITLE
Rebuild doesn't work

### ISSUE THREAD

**Issue by montogeek** [webpack/webpack.js.org#2380]
@Legends Following your comment https://github.com/webpack/webpack.js.org/pull/2039#issuecomment-406821825,
Could you please post content of your `./_content.json` file?

**Comment by montogeek** [comment]
Yep, i get the error on Windows too :/

**Comment by Legends** [comment]
`findInContent`  internally flattens the tree and gets passed the filter handler `item => item.url === trimmed` where `trimmed` is `/`.
The function should return `src/content`, but it doesn't.  But if it would, in the next line it would be replaced by `''`., which would result in `entryPath` being an empty string.

The import would then be:

`import(`./content/).then(...`

If I set `entryPath` via the debug console to be an empty string I get:

> .*$:649 Uncaught (in promise) Error: Cannot find module './'.
>     at webpackAsyncContext (.*$:649)
>     at Object.exports.__esModule (index.jsx:31)
>     at __webpack_require__ (bootstrap cfe1c5e423e04985cfca:712)
>     at fn (bootstrap cfe1c5e423e04985cfca:117)
>     at Object.defineProperty.value (index.bundle.js:4361)
>     at __webpack_require__ (bootstrap cfe1c5e423e04985cfca:712)
>     at webpackJsonpCallback (bootstrap cfe1c5e423e04985cfca:25)
>     at index.bundle.js:1

**Comment by montogeek** [comment]
Our past maintainers didn't use Windows, I will solve it :)
