### ISSUE TITLE
Ordering

### ISSUE THREAD

**Issue by NejcZdovc** [webpack/webpack.js.org#239]
I would suggest to order properties alphabetically, because now it's really hard to find what you are looking for when you are looking for a specific property. When you have them ordered alphabetically you can easily spot what you are looking for

For example
https://webpack.js.org/configuration/module/#rule
https://webpack.js.org/configuration/dev-server/#devserver

Current order for dev-server options:

```
devServer.publicPath
devServer.quiet
devServer.noInfo
.....
```

I would change this to:
```
devServer.compress
devServer.contentBase
devServer.hot
```

I can work on this PR if you agree with a change. I would go trough all the pages and apply alphabetically order for the properties.

**Comment by bebraw** [comment]
Sounds like a worthwhile change to me.

Any thoughts @TheLarkInn, @SpaceK33z ?

**Comment by SpaceK33z** [comment]
Jep, good idea!

**Comment by NejcZdovc** [comment]
So, should I start working on this?

**Comment by TheLarkInn** [comment]
Love it lets do it!
