### ISSUE TITLE
Ignore Plugin on Files

### ISSUE THREAD

**Issue by mistrykaran91** [webpack/webpack.js.org#2396]
I'm having an angular app which is quiet big, so I'm lazily loading chunks and just want to ignore few chunks. So, using IgnorePlugin but unable to match the specific folder/directory. Currently my folder structure is src/app/modules/platform, so I want to ignore platform folder in ng-build but unable to achieve it. I', lazily loading that module so the lazy loading code is in src/app/modules/app-routing.module.ts Any help will be appreciated. Thanks in advance.

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
