### ISSUE TITLE
Document stat options (presets + individual fields)

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#240]
Context: `configuration/stats`.

**Comment by SpaceK33z** [comment]
Some more context if anyone wants to work on this:

We want to document the presets and individual fields for the `stats` option a bit more. For the individual fields, explain exactly what each field does. For the presets, explain what fields correspond to it.

This has not been documented before, so you'll need to look into webpack's source code. See [lib/Stats.js](https://github.com/webpack/webpack/blob/master/lib/Stats.js#L738-L778) to get started.

**Comment by bebraw** [comment]
Closed via #234.
