### ISSUE TITLE
Rebuild:bug --> Refresh Vote page

### ISSUE THREAD

**Issue by Legends** [webpack/webpack.js.org#2410]
Happens ins dev and prod build.

Steps to reproduce:

1. Navigate to "Vote" (Main menu) page.
2. Refresh the page (on windows hit `F5` to refresh)
3. In prod build I get a 404, in dev build I get error:
    

> Uncaught TypeError: Cannot read property 'path' of undefined

![image](https://user-images.githubusercontent.com/966368/43419069-3bed27aa-9440-11e8-9b69-ba442992f075.png)

**Comment by Munter** [comment]
This is fixed on the rebuild-hyperlink branch, which is just waiting to be merged once enough maintainers agree

**Comment by Legends** [comment]
Good! Closing...
