### ISSUE TITLE
NotificationBar appears when refreshing page, even it's dismissed

### ISSUE THREAD

**Issue by Legends** [webpack/webpack.js.org#2413]
[Here is a short video](https://drive.google.com/open?id=1-50KD9WhKy9Cks8NzTziDKfY0Xj5FqVq) that demonstrates the issue

**Comment by montogeek** [comment]
Relevant code https://github.com/webpack/webpack.js.org/blob/rebuild/src/components/NotificationBar/NotificationBar.jsx#L7-L14

**Comment by Legends** [comment]
[This part](https://github.com/webpack/webpack.js.org/blob/rebuild/src/components/NotificationBar/NotificationBar.jsx#L68) is responsible for showing/hiding the `MessageBar`.
But your code looks good, wonder why it appears after hitting the refresh button ??
I put a `console.log(barDismissed())` and it always returns `true`, so `MessageBar` shouldn't render at all...

**Comment by montogeek** [comment]
This is a hybrid app (universal), when you hit F5 it is getting a entirely new single HTML from the server, that file contains the notification bar, then it loads the JS, which starts React, React will mount that component then it would access localStorage, all of that takes some time.

**Comment by Legends** [comment]
I just did a fresh `git fetch` now the notificationbar doesn't popup anymore...
Wonder what has changed, because `NotificationBar.jsx` did not!

Caching issue in ` webpack-dev-server` ?
