### ISSUE TITLE
Docs refer to deprecated webpack.optimize.UglifyJsPlugin

### ISSUE THREAD

**Issue by 1j01** [webpack/webpack.js.org#2424]
https://webpack.js.org/configuration/plugins/#plugins

I don't know if there's other stuff that needs to be updated here, or if maybe the documentation's been updated but it's just not published...

**Comment by 1j01** [comment]
The `UglifyJsPlugin` itself isn't, but accessing `webpack.optimize.UglifyJsPlugin` is, because you're supposed to add it as a dependency and pass it to [`optimization.minimizer`](https://webpack.js.org/configuration/optimization/#optimization-minimizer)

**Comment by montogeek** [comment]
Uhmm, using it as a plugin triggers a warning or something?
I think it works just fine as a plugin.

**Comment by michael-ciniawsky** [comment]
`webpack.optimize.UglifyJsPlugin` isn't exposed anymore, one has to explicitly import it since `webpack >= v4.0.0`

```diff
- const UglifyJsPlugin = webpack.optimize.UglifyJsPlugin
+ const UglifyJsPlugin = require('uglifyjs-webpack-plugin')
```

It ships with `webpack` and options can be passed to the 'build-in' plugin via `config.optimization.minimize` removing the need to import it at all in most cases

**Comment by montogeek** [comment]
Please send a PR to this page (https://webpack.js.org/configuration/plugins/#plugins) updating it with your findings.

**Comment by EugeneHlushko** [comment]
You just need to remove it from the plugins https://webpack.js.org/configuration/plugins/#plugins page
It is documented here btw: https://webpack.js.org/configuration/optimization/

**Comment by 1j01** [comment]
Also presumably the `CommonsChunkPlugin` usage should be updated to show `require`ing it, and likely other stuff is outdated. I don't want to work on this; I've never used the `plugins` option, and so I hope someone with at least that qualification can pick this up.

**Comment by EugeneHlushko** [comment]
@1j01 ok, in that case im picking it up
