### ISSUE TITLE
Fix Table Styling (esp. on mobile)

### ISSUE THREAD

**Issue by skipjack** [webpack/webpack.js.org#246]
As mentioned in #244, we need to figure out a way to better handle markdown tables.

I'm pushing a quick fix in 6a95c83 to #225 but if others have better ideas please discuss here.

**Comment by NejcZdovc** [comment]
I would do something like this:

**Desktop:**

![image](https://cloud.githubusercontent.com/assets/9574457/19415594/ef439d80-9374-11e6-9d6b-9189351bba50.png)


**Mobile:**

![image](https://cloud.githubusercontent.com/assets/9574457/19415483/fa35696a-9371-11e6-891f-aa01b67c3378.png)



One thing that can maybe improve table also on desktop. On page we have a lot of tables with very important data (API properties). We lose 260px with a side bar on the side. What if we move it to the top of the page or go full out mobile approach. Also increase max-width of the content to 1200px from 1024px (Users have bigger screens now 24" and 27").

**Navigation top:**

![image](https://cloud.githubusercontent.com/assets/9574457/19415587/bf1e0938-9374-11e6-9f6b-13d47814f977.png)

**Mobile approach: (not sure how to merge it with main navigation): **

![image](https://cloud.githubusercontent.com/assets/9574457/19415610/6ba37828-9375-11e6-9cb7-54b3f656721a.png)

**Comment by pksjce** [comment]
@NejcZdovc - This is the problem table that @skipjack  is trying to fix.
Its a table of how values in `resolve.alias` are resolved in relative and module path requires.
Can you think  of some alternate way to show this data?
<img width="991" alt="screen shot 2016-10-16 at 3 35 59 pm" src="https://cloud.githubusercontent.com/assets/417268/19416753/6d3ea2fc-93b6-11e6-95fe-68a265f1aa79.png">
<img width="1035" alt="screen shot 2016-10-16 at 3 36 08 pm" src="https://cloud.githubusercontent.com/assets/417268/19416752/6d3da94c-93b6-11e6-8092-e42f31ee3ef6.png">

**Comment by NejcZdovc** [comment]
@pksjce My suggestion is that we move side menu out, so that we have a lot more space. Also set max-width to the 1200px from 1024px. For mobile we create alternative table (almost the same HTML as now, just some CSS magic).

### When your screen is bigger then 1200px
![image](https://cloud.githubusercontent.com/assets/9574457/19416858/1ceb9216-939c-11e6-958e-7503d0066b9d.png)


### When is around 850px
![image](https://cloud.githubusercontent.com/assets/9574457/19416863/39a39e4e-939c-11e6-85b1-35e1343aae3e.png)


### Bellow 768px
I would show alternative table as I posted in my previous post. So we change table into alternative table with column name on the left and value on the right.

![image](https://cloud.githubusercontent.com/assets/9574457/19415707/b261d23e-9378-11e6-817d-29ad8c599276.png)

**Comment by NejcZdovc** [comment]
We can playaround with break points when should we move to the alternative table.

**Comment by skipjack** [comment]
> What if we move it to the top of the page or go full out mobile approach. Also increase max-width of the content to 1200px from 1024px (Users have bigger screens now 24" and 27").

Personally I think keeping the Sidebar on the side is better, however we are planning to make it sticky so the user can always navigate despite where they are on the page. Maybe we have one bigger breakpoint than the current `large` one but honestly I think it's fine the way it is right now. For readability I think keeping all content at a max width of about 90 - 95 characters is best (see #191).

I think the showing the donate link on smaller screens isn't a bad idea though. For the tables I was thinking something more along the lines of making the first column fixed or something so they're more approachable on mobile screens (a fixed first column might also help on desktop's for the bigger tables). The only problem with fixing the first column is that we'd have to hack how the html for tables is rendered in the `markdown.js` utility. Here's a [CSS Tricks Article](https://css-tricks.com/responsive-data-tables/) that has a few other approaches including one that doesn't require changing the markup. 

I don't think the tables on desktops are as big of a problem, the scrolling fix I added in fact might be enough for that size viewport. I think we should be careful not to drastically change the layout just to accommodate a few tables. We should also consider whether using a table, especially a long table, is even the best approach in the first place.

**Comment by SpaceK33z** [comment]
> I think it's fine the way it is right now. For readability I think keeping all content at a max width of about 90 - 95 characters is best (see #191).

Agreed completely, this is very [important for readability](https://www.smashingmagazine.com/2014/09/balancing-line-length-font-size-responsive-web-design/).

**Comment by skipjack** [comment]
Related PR - #440. @NejcZdovc look at your "alternative table" suggestion again I realize this is really similar to what the [CSS Tricks Article](https://css-tricks.com/responsive-data-tables/) suggests. That seems like a it would be the best approach for sure.

**Comment by NejcZdovc** [comment]
@skipjack sure I can tackle this, but only in few days, right now I need to finish some things. Is this ok, if not you are more then welcome to take it?

**Comment by skipjack** [comment]
Yep that'd be great, take your time... definitely plenty of other ones I can work on resolving.

**Comment by NejcZdovc** [comment]
Then you can assign this issue to me

**Comment by skipjack** [comment]
Yep, once you accept the collaborator invite I sent, I can assign you.

**Comment by NejcZdovc** [comment]
Accepted, thank you

**Comment by skipjack** [comment]
[Another good roundup](https://css-tricks.com/responsive-data-table-roundup/) of different approaches that I found while reviewing #875. This problem is really tough and even with that whole list there's not one that jumps out to me as particularly elegant or user-friendly. 

@NejcZdovc in the process of looking through #875 and #440 now.
