### ISSUE TITLE
Document this.hot in the loader API

### ISSUE THREAD

**Issue by satazor** [webpack/webpack.js.org#2461]
**Feature to document**

`this.hot` in the loader context, see: https://github.com/webpack/webpack/pull/6228

**Author(s)**

@sokra 

**Additional information**

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org

**Comment by montogeek** [comment]
How is that issue related to `this.hot`?

**Comment by satazor** [comment]
Oops, I linked to the wrong issue. Here's the correct one: https://github.com/webpack/webpack/pull/6228

**Comment by montogeek** [comment]
I see, feel free to send a PR
