### ISSUE TITLE
Mobile Sidebar

### ISSUE THREAD

**Issue by skipjack** [webpack/webpack.js.org#247]
Stub to discuss the best approach and figure out who will finish this off.

**Comment by NejcZdovc** [comment]
1. Align hamburger with a content (add spacing), increase size of it
2. Align logo to the center of the header
3. Increase font size, add more spacing between
4. Add active state for the current page
5. When clicking on link side menu should close
6. Increase clicking area for arrow (increase size of the icon) so it's easier for click on it
7. Remove sliding effect when resizing to mobile screen
8. When on small screen's and if you open some menus (scroll bar appears) header is hidden, so you can see website behind

<img width="528" alt="sidebar1" src="https://cloud.githubusercontent.com/assets/9574457/19415343/0f36cbfa-936e-11e6-962a-c0a21e441186.png">

<img width="529" alt="sidebar1" src="https://cloud.githubusercontent.com/assets/9574457/19415376/eed58a76-936e-11e6-9b6a-0b0b00a2b904.png">

<img width="556" alt="sidebar1" src="https://cloud.githubusercontent.com/assets/9574457/19415381/14676dd6-936f-11e6-9a40-3ac0d010c16e.png">

<img width="564" alt="sidebar1" src="https://cloud.githubusercontent.com/assets/9574457/19415394/531876c4-936f-11e6-94f5-f882cc4a8e55.png">

**Comment by skipjack** [comment]
@NejcZdovc it's completely different now, closer to @KyleAMathews design. I'll add a screenshot soon, but definitely feel free to run it on the dev-server and tell me what you think.

**Comment by NejcZdovc** [comment]
@skipjack I see it now I was working on wrong branch will check out #254.

**Comment by NejcZdovc** [comment]
As I already said in my first comment I would change header to something like this:

![image](https://cloud.githubusercontent.com/assets/9574457/19415666/69d36696-9377-11e6-9ca1-7d85c44db437.png)

Other than that I will wait for the full functionality and then take it for another spin 😃

**Comment by NejcZdovc** [comment]
I would also add donate button on the right side if proposal from #246 will be accepted (mobile first approach).

**Comment by skipjack** [comment]
Yea I think centering the logo on smaller viewports is definitely a good idea.

**Comment by NejcZdovc** [comment]
@bebraw I think this can be closed.
