### ISSUE TITLE
Add open collective banner information

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#248]
Open Collective has a nice [document](https://github.com/OpenCollective/OpenCollective/wiki/Website-banner) for how to add our open collective banner information to the webpage. 

This would probably just live in the bottom of the landing page for now. If we would like to experiment with different badges or things in like the header or footer we could do so, but for now I would just like to have the banner there for visibility as we are getting very close to finishing our milestone.

**Comment by TheLarkInn** [comment]
Looking into this further the script is probably not best suited for our needs. Rather, we should use the html inside that is being used. 

```
          <h1>This is possible thanks to you</h1>
          <h2>This project is possible thanks to our backers and sponsors</h2>
          <object type="image/svg+xml" data="https://opencollective.com/webpack/sponsors.svg"></object><br />
          <object type="image/svg+xml" data="https://opencollective.com/webpack/backers.svg"></object>
```

**Comment by SpaceK33z** [comment]
I agree with your last comment, less external scripts = better :).

**Comment by bebraw** [comment]
Merged the PR, closing.
