### ISSUE TITLE
webpackMode: "lazy-once" not supported by Webpack 4.17.2

### ISSUE THREAD

**Issue by ronenbar** [webpack/webpack.js.org#2490]
The documentation at https://webpack.js.org/api/module-methods/#import- mentions a "lazy-once" mode option but when specifying it such as in:

import( /*webpackChunkName: "moduleB-chunk"*/ /* webpackMode: "lazy-once" */'./moduleB');

webpack reports:

WARNING in ./src/moduleA.js 5:0-88
`webpackMode` expected 'lazy', 'eager' or 'weak', but received: lazy-once.

Isn't "lazy-once" supported?

Webpack version: 4.7.12

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org

**Comment by montogeek** [comment]
Let me check

**Comment by ryadiv** [comment]
Same here

**Comment by EugeneHlushko** [comment]
Looking at code it should be possible to use "lazy-once". Pinged @sokra to have a quick look at this

**Comment by sokra** [comment]
It only makes sense when using an `import()` with expression:

``` js
import(/* webpackMode: "lazy-once" */ `./module${expr}`) // ok
import(/* webpackMode: "lazy-once" */ `./moduleA`) // not ok
```

The different between lazy and lazy-once is that lazy-once loads all possible modules at once, that doesn't make sense when only one module is possible. Use `lazy` instead.

**Comment by sokra** [comment]
See also the note in the documentation

> Note that this only makes sense in the case of a partially dynamic statement, e.g. import(`./locales/${language}.json`), where there are multiple module paths that could potentially be requested.

**Comment by jeffin143** [comment]
@montogeek Since the query was answered and also the information is explicitly mentioned in docs, I guess we should go ahead and close this to just keep the count of issues in check :)
