### ISSUE TITLE
Code snippet in documentation for `writing a plugin` unclear

### ISSUE THREAD

**Issue by franjohn21** [webpack/webpack.js.org#2494]
**Feature to document**
How to write a plugin. [Page on webpack.js.org](https://webpack.js.org/contribute/writing-a-plugin/)

**Author(s)**
@iamakulov @jeremenichelli via https://github.com/webpack/webpack.js.org/pull/2202

**Additional information**
[In the first code snippet](https://github.com/webpack/webpack.js.org/blame/b437543316dc832a780b4530ad282a202833a887/src/content/contribute/writing-a-plugin.md#L28) in the `Writing a Plugin` page, the first argument passed in to the `tap` function is `afterCompile`. It's unclear if this is of significance -- if this hooks into `afterCompile` then why wouldn't the code call `compile.hooks.afterCompile.tap`? In the rest of the code samples on this page, the first argument to the `tap` function appears to the be a descriptive name for the plugin being created.

```js
class MyExampleWebpackPlugin {
  // Define the `apply` method
  apply(compiler) {
    // Specify the event hook to attach to
    compiler.hooks.compile.tapAsync(
      'afterCompile',
      (compilation, callback) => {
        console.log('This is an example plugin!');
        console.log('Here’s the `compilation` object which represents a single build of assets:', compilation);

        // Manipulate the build using the plugin API provided by webpack
        compilation.addModule(/* ... */);

        callback();
      }
    );
  }
}
```

If my understanding is correct then my suggestion would be to change this documentation to: 
```diff
class MyExampleWebpackPlugin {
  // Define the `apply` method
  apply(compiler) {
    // Specify the event hook to attach to
    compiler.hooks.compile.tapAsync(
-     'afterCompile',
+    'MyExampleWebpackPlugin',
      (compilation, callback) => {
        console.log('This is an example plugin!');
        console.log('Here’s the `compilation` object which represents a single build of assets:', compilation);

        // Manipulate the build using the plugin API provided by webpack
        compilation.addModule(/* ... */);

        callback();
      }
    );
  }
}
```

Furthermore adding a blurb somewhere in documentation about the API of the `tap` function would be helpful. From the [tapable docs](https://github.com/webpack/tapable) it's unclear what the significance of the `name` (or any arguments) is. Happy to make these updates myself, just need some guidance on what should change.

**Comment by montogeek** [comment]
Please send a PR

**Comment by franjohn21** [comment]
Pr created https://github.com/webpack/webpack.js.org/pull/2496
