### ISSUE TITLE
API - Configuration

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#25]
[Stub](https://github.com/webpack/webpack.io/blob/develop/content/api/configuration.md).

Feel free to comment here if you have ideas on what this guide should cover. Link to potential resources too.

This is to stub and rewrite the [existing page](http://webpack.github.io/docs/configuration.html)

**Comment by gregvenech** [comment]
Can I take a stab at this one? I already started playing around with this when I was doing the [documentation mockup](https://github.com/webpack/docs/issues/69). Might need a some advice on certain sections but at this point I'm familiar with and have used most of the configuration options...

**Comment by bebraw** [comment]
Sure, that would be great.

**Comment by gregvenech** [comment]
Ok great, I'll start this week.

**Comment by gregvenech** [comment]
@bebraw while working on this section, I noticed that our markdown parser doesn't accept:

 ```
... [link][1] ...

[1]: http://example.com
```

Is this intentional? I find this feature super helpful when adding long external links... it doesn't bother me as much to inline the in-site links.

**Comment by bebraw** [comment]
Yeah. Footnotes aren't a good idea on the web. Hard to lay out, bad UX. It's better to use `T>` and `W>` for secondary information.

**Comment by gregvenech** [comment]
I don't mean actually having the links at the bottom of the page, I just mean separating out long links to make the markdown more readable. What the user sees is unchanged by this, i.e. `[link][1]` and `[link](http://example.com/path/to/my/page)` yield the same result when used in markdown but the first makes paragraphs containing multiple links much easier to read and edit.

**Comment by bebraw** [comment]
Ah, like that. If [marked](https://www.npmjs.com/package/marked) doesn't support that syntax by default, then you'll probably need a syntax extension for that purpose.

**Comment by gregvenech** [comment]
Ok I'll try to look into that.

**Comment by gregvenech** [comment]
Looks like a [bug](https://github.com/chjj/marked/issues/310) which isn't fully addressed yet (although that issue says it was in `0.3.2`).

**Comment by bebraw** [comment]
Time to close this one given there's an entire section on configuration now.
