### ISSUE TITLE
Unable to run `yarn lint` for this repo on Node 10

### ISSUE THREAD

**Issue by edmorley** [webpack/webpack.js.org#2523]
Hi!

Before opening PR #2522, I was hoping to check my changes locally using `yarn lint`.
However trying to install the dependencies under Node 10 failed:

```
webpack.js.org $ yarn
yarn install v1.10.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.10.0"
error Found incompatible module
```

The latest version of [upath](https://github.com/anodynos/upath) supports Node 10, and is in the semver range of the dependency on it in this repo, so I guess `yarn.lock` just needs refreshing?

Fwiw, we've had great results using https://renovatebot.com to automate lockfile refreshing/dependency updates (it's also much less noisy than Greenkeeper and has superior lockfile support).

**Comment by chenxsan** [comment]
Closed as it's no longer valid.
