### ISSUE TITLE
Menu rendering

### ISSUE THREAD

**Issue by NejcZdovc** [webpack/webpack.js.org#256]
Created based on #255.

> Page /configuration/module is quite confusing at first look. Why is header h4 also a link that can be found in the left menu? This happens on other pages as well.

**Comment by NejcZdovc** [comment]
Some other improvements:

- When you click on menu with submenu, submenu should open
- When you switch to other menu (for example from DevServer to DevTool), previous submenu should close

**Comment by NejcZdovc** [comment]
@skipjack Will #254 address this things or should I go for it and also can I add sticky menu as discussed in #246?

**Comment by skipjack** [comment]
#254 is more for the mobile sidebar. Once that one's merged I'd be happy for you to take a stab at finishing off the normal Sidebar component.

I'm about to push some commits to that now so I think we'll have it merged either today or tomorrow.

**Comment by skipjack** [comment]
Closing with merge of #277.
