### ISSUE TITLE
devServer.contentBase can also be a domain or port number

### ISSUE THREAD

**Issue by danez** [webpack/webpack.js.org#257]
Currently the `contentBase` docs only say that `contenBase` should be a path or array of paths, but it can also be a full domain or a port number. At least according to the source-code, not sure if there are plans to remove this.

https://webpack.js.org/configuration/dev-server/#devserver-contentbase
https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L241..L256

**Comment by SpaceK33z** [comment]
Good point. It is still present in the source code, but honestly, I don't even know if it works. I recently removed the feature to use contentBase as a proxy (https://github.com/webpack/webpack-dev-server/issues/582), and I'm not sure yet if we should also remove the feature to use it with a full domain or port number. With the `proxy` option you can do almost the same + it's way more powerful.

It would be very nice if we would have usage statistics :(.

**Comment by SpaceK33z** [comment]
I've officially deprecated the domain and port usages now in https://github.com/webpack/webpack-dev-server/commit/61b46bac419fc496852cb1b94e0b49451631a0e6.

I searched through the commits to find out why this was introduced at all, but apparently this was before the `proxy` option was a thing.

**Comment by danez** [comment]
Nice, then I can also remove it from grunt-webpack now for the upcoming v2

**Comment by SpaceK33z** [comment]
Awesome. I hope not too many people will complain about this. `proxy` does essentially the same and is wayyy more powerful, but it *may* work a bit different in the details. This is a situation where I would really wanted to have usage stats...
