### ISSUE TITLE
Document electron-main (previously electron) and electron-renderer

### ISSUE THREAD

**Issue by rmccue** [webpack/webpack.js.org#258]
Per https://github.com/webpack/webpack/issues/1463 `electron-renderer` is the target to use for the content, but this isn't documented anywhere.

**Comment by TheLarkInn** [comment]
Thank you we should definitely have information on each target. If I point you to the right place in the src would you have interest in documenting it and submitting a PR?

**Comment by rmccue** [comment]
@TheLarkInn Happy to send a PR!

**Comment by TheLarkInn** [comment]
Thanks yes please we would love that!

**Comment by SpaceK33z** [comment]
Closing since there is documentation about `electron-renderer` now.
