### ISSUE TITLE
misleading documentation about `open` in `webpack-dev-server`

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#2610]
**Feature to document**

Add note about `open` option on difference `os` for `webpack-dev-server`. 

Ref: https://github.com/webpack/webpack-dev-server/issues/1337

**Author(s)**

not matter

**Additional information**

Note about it is difference names on difference os https://github.com/sindresorhus/opn#app

**Comment by EugeneHlushko** [comment]
Hi @evilebottnawi ,

Seems like i can add it in my PR here: https://github.com/webpack/webpack.js.org/pull/2609/files#diff-374c60b205ba6f81398769b7fd453e01R623

Basically we wanna add: "The app name is platform dependent. Don't hard code it in reusable modules. For example, Chrome is google chrome on macOS, google-chrome on Linux and chrome on Windows." note right?

**Comment by evilebottnawi** [comment]
Yes

**Comment by EugeneHlushko** [comment]
ok ty for confirming 👍

**Comment by juliankrieger** [comment]
I didn't find it in the docs, but maybe providing a table of names for varying operating systems would be helpful? I couldn't find the correct Paramter name for "Firefox Developer Edition" for example
