### ISSUE TITLE
splitChunks.cacheGroups[x].filename

### ISSUE THREAD

**Issue by sokra** [webpack/webpack.js.org#2611]
**Feature to document**
The `filename` option is missing.

It allows to override the filename when and only when it's an initial chunk. The filename for async chunks can't be set. This will lead to an error.

All placeholders available in `output.filename` are also available here.

Option can also be set globally in `splitChunks.filename`, but this isn't recommended and will very likely lead to an error if `chunks: "initial"` is not set. Avoid setting it globally.

**Author(s)**
sokra

**Additional information**

**Comment by EugeneHlushko** [comment]
sounds clear to me, picking it up

**Comment by EugeneHlushko** [comment]
Its added, pls review @sokra
