### ISSUE TITLE
src/content/configuration/stats.md 

### ISSUE THREAD

**Issue by JasonKleban** [webpack/webpack.js.org#2616]
**Feature to document**

stats configuration - how to extend string-named with specific overrides

**Author(s)**

@SpaceK33z | @sallar | @jungomi | @ldrick | @jasonblanchard | @byzyk | @renjithvk | @Raiondesu | @EugeneHlushko

**Additional information**

My current stats configuration is `stats: 'minimal'` but I want to suppress a certain error without making any other changes.  How can we inherit 'minimal' or whatever and override just one setting?  Alternatively, what stats configurations to those string shortcuts stand for?

**Comment by JasonKleban** [comment]
(Until then, FYI we can find the prebuilt configs in /lib/Stats.js)

**Comment by EugeneHlushko** [comment]
Hi @JasonKleban 

Indeed there is no good way to extend, but i've added the steps to the configuration guide of the stats.

Hope this gets merged as i also find it useful 👍 

See #2618
