### ISSUE TITLE
Update url's to webpack.js.org

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack.js.org#262]
When we release webpack v2 and these new docs, we need to update `https://webpack.github.io` to `https://webpack.js.org` in many places. This issue exists to keep track of those places:
- [x]  [webpack repo](https://github.com/webpack/webpack) description
- [x] webpack core code
- [x] [JS Foundation Projects page](https://js.foundation/projects/)
- [x] [webpack-dev-server readme](https://github.com/webpack/webpack-dev-server)

**Comment by bebraw** [comment]
What if we cheated a bit and added rerouting on the landing page? We can add a link to the new site pointing to http://webpack.github.io/docs/ for legacy users.

**Comment by SpaceK33z** [comment]
Okay, that's a short term solution. Still a bit nicer to actually fix the url though :).

**Comment by montogeek** [comment]
Can I fix this?

**Comment by kborchers** [comment]
@bebraw Moving over here from https://github.com/JSFoundation/js.foundation/pull/20

Is there any reason to not use a project specific domain now that the JS Foundation owns webpackjs.org, would maintain it and could also provide other services around DNS management, DDoS protection, etc.?

**Comment by TheLarkInn** [comment]
@kborchers when the core team meets next week, we will officially vote one this. The due process allows us to document any place that we have used the old link (to change if needed) and setup redirects from our current domain to the new one. Once we have that process we can go through with switching (if thats the direction want/need to take).

**Comment by dmethvin** [comment]
@TheLarkInn I talked to @kborchers and he says the JSF owns webpackjs.org and we could use that. I'm not sure about the long-term goals or stability of js.org.

**Comment by TheLarkInn** [comment]
Could we mirror for now? My only concern is the SEO and indexing we've gotten already will have to start over with a new domain. Unless that is not a concern to the other core team members.

**Comment by bebraw** [comment]
Any chance JSF could buy webpack.com (owned by webpac corporation), webpack.org, or a similar root domain?

**Comment by kborchers** [comment]
@TheLarkInn I don't really have too much concern there but the sooner you switch, the sooner that corrects itself.

@bebraw I will reach out on both but I have never had an org even respond when we have reached out about other domains in the past and if they do, my guess is they will ask an amount we won't be willing/able to pay but I will definitely try and let you know. Even if we can't get one of those, I feel webpackjs.org is much better than webpack.js.org both just as a domain name and in the extra features we could then provide like additional sub-domains if/when needed, additional security like DDoS mitigation, etc.

**Comment by dmethvin** [comment]
Also if you are going to have multiple domains serving the content, make sure there is a `<link rel="canonical" ...>` on the page. https://yoast.com/rel-canonical/

**Comment by simon04** [comment]
webpack core code has been done via https://github.com/webpack/webpack/pull/4224.

**Comment by simon04** [comment]
* webpack-dev-server readme has been done via https://github.com/webpack/webpack-dev-server/commit/cb98dd989ec3b7998f879446a5d2044623967af6
* sent an email for updating https://js.foundation/projects/

**Comment by simon04** [comment]
All done.
