### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack.js.org#263]
@bebraw @TheLarkInn @SpaceK33z What license do we choose for our docs page? If we add a license, we need to make sure that the fonts and the logo are excluded. See #173.

**Comment by bebraw** [comment]
One of the [Creative Commons](https://creativecommons.org/) variants might work. I might pick CC BY myself so people can reuse the content however they like while having to attribute. There are more restrictive options too if you prefer those.

**Comment by SpaceK33z** [comment]
CC BY seems like a good idea, it should not be too restrictive.

**Comment by bebraw** [comment]
Good with CC BY? If so, let's update the readme and add a mention to the site (image + link at the footer would be enough).

**Comment by jhnns** [comment]
Sounds good 👍
