### ISSUE TITLE
Webpack 2 documentation?

### ISSUE THREAD

**Issue by gforcada** [webpack/webpack.js.org#2678]
First of all, thanks a lot for the amazing documentation for webpack, it rocks!! :rocket: 

Due to some plugins that we use that are still not ported to webpack 4, we are stuck with a webpack 2 configuration.

On other projects, we are happily and productively using webpack 4 :+1: but then, when trying to backport some features on the webpack 2 configuration, they either don't work, you have to user another plugin, or the way to configure it is completely different.

Is there any place where one can still find the official webpack 2 documentation? :thinking:

**Comment by EugeneHlushko** [comment]
Hi @gforcada, the same as for v3 docs there is no current web address to view them. The only good way to do it is cloning this repo and checking out some old revision or commit when webpack was at v2 locally, after that, check package.json commands list and find start command.

My best guess is that it should be runnable by:

```
yarn install && yarn run start
```

That potentially will let you browse `localhost:3000`. There is another issue where we are tracking the status of web browsing feature for old revisions e.g. `v3.webpack.js.org` so i am closing this one for now.
