### ISSUE TITLE
style-loader page bug

### ISSUE THREAD

**Issue by ivandevp** [webpack/webpack.js.org#2692]
When reading the docs about `style-loader` there's a heading missing text.

<img width="949" alt="screen shot 2018-12-05 at 7 25 15 am" src="https://user-images.githubusercontent.com/9284690/49516538-79921b00-f85f-11e8-8330-be84451ee056.png">

**Comment by anikethsaha** [comment]
its good to close now as style-loader has updated its docs
cc @montogeek @EugeneHlushko
