### ISSUE TITLE
Better documentation IgnorePlugin

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#2720]
**Feature to document**

IgnorePlugin supports `functions`

**Author(s)**

Don't know

**Additional information**

Based on https://github.com/webpack/webpack/issues/7794

**Comment by iliakan** [comment]
@evilebottnawi thanks, that's actually not a documentation, but a feature change request. I'd send a PR if the change looks good.

**Comment by evilebottnawi** [comment]
@iliakan oh, yes, i am wrong, ssory, very tired

**Comment by iliakan** [comment]
@evilebottnawi I made an issue, thanks. Btw did you get an email from me (Ilya Kantor)?

**Comment by evilebottnawi** [comment]
@iliakan Yes, I see, there are a lot of letters and I sometimes get lost in them, better ping me something in github
