### ISSUE TITLE
Document optimization.chunkIds

### ISSUE THREAD

**Issue by nwoltman** [webpack/webpack.js.org#2724]
**Feature to document**

[`optimization.chunkIds`](https://github.com/webpack/webpack/blob/d5e26f728adb63a1fca080ef728fd627952a921d/schemas/WebpackOptions.json#L406-L409) was introduced in webpack/webpack#7686 and released in [webpack@4.16.0](https://github.com/webpack/webpack/releases/tag/v4.16.0).

**Author(s)**

@sokra 

**Additional information**

`optimization.moduleIds` is already documented, so the documentation for `optimization.chunkIds` will probably be fairly similar.

**Comment by EugeneHlushko** [comment]
Hi @nwoltman 
Thank you for reporting, PR is up and it should be live soon.
