### ISSUE TITLE
Webpack Documenation Error - "Cleaning up the dist folder"

### ISSUE THREAD

**Issue by methodbox** [webpack/webpack.js.org#2738]
OS: Windows 10
Node: 8.10.0
npm: 6.5.0
Webpack: 4.28.1
clean-webpack-plugin: 1.0.0

There is an error in the documentation which will lead to ```clean-webpack-plugin``` not executing the intended behavior.

The documentation is found here: https://webpack.js.org/guides/output-management/#cleaning-up-the-dist-folder

```javascript
...
plugins: [
+     new CleanWebpackPlugin(['dist']),
...
],
```

Using just ```dist``` will  not actually clean the dist folder. Modifying this to ```dist/*``` will do the trick.

**Comment by montogeek** [comment]
Send a PR with its correction please.

**Comment by methodbox** [comment]
I'd definitely like to contribute in some way, but I'm not actually sure how to do that for documentation. Can you clarify and I'd be happy to learn and submit the PR?

**Comment by EugeneHlushko** [comment]
Hi @methodbox 
You would need to fork the repo and then fork from master into a branch e.g. `issues/2738`, after that modify the file with the discussed above contents, commit your change and submit a pull request. If you want i can add such PR and mention you as collaborator to save some time on delivery if you are busy or still not sure how to do it and need time to learn :)

**Comment by methodbox** [comment]
@EugeneHlushko

That would be awesome as a head start, but let me give it a shot first.

Thanks!

**Comment by anshumanv** [comment]
This seems fixed now. ✨

**Comment by jeffin143** [comment]
@montogeek , Done with this too :rocket:
