### ISSUE TITLE
How does System.import() work?

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack.js.org#275]
**Premise**
System.import() allows `webpack` to define split points for code splitting using es6 modules. It is a replacement for `require.ensure()`

**Findings**
- Multiple dependencies cannot be imported using `System.import()` alone. We need to `Promise.all[System.import(), System.import()]`. But as per https://github.com/webpack/webpack/issues/3141, that does not work as expected as well.
- Named chunks are not possible using `System.import()`. `require.ensure()` has a parameter that allows us to name the chunks, hence separating or combining code from other split points in the application. This does not seem to be available with `System.import()`

**Ask**
`System.import()` does not seem to be a perfect replacement and seems to create more problems. Are there workarounds for these issues?

**Comment by SpaceK33z** [comment]
The workaround is to create a new module that contains the modules you want to lazy load.

**Comment by skipjack** [comment]
Maybe this can be merged with the discussion in #589? (or at least tackled in the same PR)

**Comment by pksjce** [comment]
Sure!
