### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by NejcZdovc** [webpack/webpack.js.org#276]
There was new task introduced `init:generated` with [commit](https://github.com/webpack/webpack.js.org/commit/be5ffe93d1fc4cb4691ba8566c39d51c8ebdee9f) . Inside there is `cp `command which is not recognised on windows. For now I executed, what this task should do, by hand.

@bebraw Can you please check it out.

`'cp' is not recognized as an internal or external command, operable program or batch file.`

**Comment by bebraw** [comment]
Fix welcome. I don't have a Windows box to test with.

**Comment by NejcZdovc** [comment]
My suggestion is to use some kind copy cli which can handle environments.

https://www.npmjs.com/package/ncp
https://www.npmjs.com/package/cpy-cli

What do you think?

**Comment by bebraw** [comment]
@NejcZdovc I hooked up ncp so it should work now. `scripts/fetch.sh` is problematic still unless you use something like cygwin. I would welcome a PR that would port that script to pure node.
