### ISSUE TITLE
SplitChunks.name: Specify that setting a specific name merges all chunks in one file

### ISSUE THREAD

**Issue by raulferras** [webpack/webpack.js.org#2763]
**Feature to document**
Based on @sokra comment [here](https://github.com/webpack/webpack/issues/8582#issuecomment-451235164), setting `splitChunks.name` to a string will merge all chunks into a single one.  
This is not documented here: https://github.com/webpack/webpack/issues/8582#issuecomment-451235164

**Author(s)**
?

**Additional information**
The docs document properly other "edge" cases as:

```
If the name matches an entry point name, the entry point will be removed.
```

But it caught me out of guard that setting a name generated one single chunk, so I guess it would be useful to have this case documented too.

**Comment by EugeneHlushko** [comment]
For sure, want to file a PR @raulferras ?
