### ISSUE TITLE
Add "npm install --save-dev webpack" to WebPack installation explanation

### ISSUE THREAD

**Issue by SetTrend** [webpack/webpack.js.org#2794]
The webpack documentation files [`/src/content/guides/installation.md
`](https://github.com/webpack/webpack.js.org/blob/master/src/content/guides/installation.md) and [`/src/content/guides/getting-started.md`](https://github.com/webpack/webpack.js.org/blob/master/src/content/guides/getting-started.md) both claim that it's sufficient to install `webpack-cli`. But that isn't true.

When I install `webpack-cli` only, I get a warning that webpack is missing:

```bat
PS D:\Documents\Visual Studio-Projekte\Web Components> npm install --save-dev webpack-cli

> webpack-cli@3.2.1 postinstall D:\Documents\Visual Studio-Projekte\Web Components\node_modules\webpack-cli
npm WARN webpack-cli@3.2.1 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.
```

**Comment by superburrito** [comment]
Hmm not sure this is an issue, where did you get that impression?

**Comment by SetTrend** [comment]
The reason is subtle, yet present.

This is the headline for using WebPack v4<sup>++</sup>:

`If you're using webpack v4 or later, you'll need to install the CLI.`

To me, that sentence implies:
```
if (webpack.version >= 4) npm("install webpack-cli");
else npm("install webpack")
```

I suggest to add the word "also" to that sentence to make clear that _additional_ (not _alternative_) effort must be taken:

`If you're using webpack v4 or later, you'll **also** need to install the CLI.`

<hr/>

Yet, my second example was wrong. I had misread the sample. Though, I still would tend to improve that page by refraining from using abbreviated syntax in a How To, for two reasons:

* There is no adequate "syntax" highlighting, differentiating the compound elements. So it's hard to discern a compound statement's components when reading.
* It doesn't get clear from the compound statement that actually two packages are getting pulled.

A component How To should not focus on savvy coding. It should rather focus on the true effort necessary to be used. Experts take shortcuts. But beginners need to learn the bare effort first.

That's my personal obvervation, though. (I've been a teacher for some time in the past.)

**Comment by EugeneHlushko** [comment]
Sounds right, want to file a PR @SetTrend ?

**Comment by SetTrend** [comment]
After reading I don't think the issue you've been referring to is related to this issue.

I noticed that [`/src/content/guides/installation.md`](https://github.com/webpack/webpack.js.org/blob/master/src/content/guides/installation.md) has already been updated accordingly.

I'd like to suggest to also amend [`/src/content/guides/getting-started.md`](https://github.com/webpack/webpack.js.org/blob/master/src/content/guides/getting-started.md) by replacing the shortcuts by full statements. Readers switching between many projects and different programming frameworks can more easily grasp the impact of necessary steps when these steps are written separately. Particularly when time is at stake.

I providently created a PR: #2844
