### ISSUE TITLE
Improve documentation for loader order

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#2804]
**Feature to document**

Old docs https://github.com/webpack/docs/wiki/loaders#loader-order

In new docs we don't have information about `!!` and `-!`

**Author(s)**

No matter

**Additional information**

No

**Comment by superburrito** [comment]
Hmm I can look into this

cc @EugeneHlushko

**Comment by EugeneHlushko** [comment]
Go ahead @superburrito

**Comment by EugeneHlushko** [comment]
Open a WIP PR with a mention of this issue so its trackable

**Comment by superburrito** [comment]
@evilebottnawi This info can be found [here](https://webpack.js.org/configuration/module#ruleenforce), but I've tried to make that info more discoverable in [the above PR](https://github.com/webpack/webpack.js.org/pull/2811)
