### ISSUE TITLE
Problem with https://webpack.js.org/assets/icon-square-big.svg

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#2812]
A lot of plugins and loaders use this logo in README. We need return image on this url (asap).

Example: https://github.com/webpack-contrib/css-loader

/cc @montogeek

**Comment by montogeek** [comment]
@evilebottnawi Will fix ASAP. Is that logo in the default template?

**Comment by evilebottnawi** [comment]
@montogeek yep

**Comment by evilebottnawi** [comment]
Link https://raw.githubusercontent.com/webpack-contrib/webpack-defaults/master/templates/README.md

**Comment by montogeek** [comment]
@evilebottnawi Deploying, will be in READMEs around the world in ~4 minutes.

**Comment by montogeek** [comment]
Working now: https://webpack.js.org/assets/icon-square-big.svg

**Comment by montogeek** [comment]
But CSSLoader Readme is still broken, maybe a cache from GitHub?

**Comment by evilebottnawi** [comment]
@montogeek yep, cache, should be refreshed every 2 hours
