### ISSUE TITLE
https://webpack.js.org/api/  style confusing 

### ISSUE THREAD

**Issue by Aladingding** [webpack/webpack.js.org#2815]
The style is confusing when I expanded the two menus in https://webpack.js.org/api/

this bug screenshot
https://files.gitter.im/webpack/webpack/dev/LJX7/thumb/menu.saveimg.savepath20190219111622.jpg

**Comment by montogeek** [comment]
@Aladingding Could you please tell us which menu looks weird? I can't see it in the screenshot.

**Comment by Aladingding** [comment]
@montogeek  if i expend Compiler Hooks menu && Command Line Interface && Introduction the footer's style will be confusing of this page,with 1920*1080 windows 10

**Comment by EugeneHlushko** [comment]
Oh I see so the footer is not pushed down when two are open

**Comment by EugeneHlushko** [comment]
When there is not enough content*
