### ISSUE TITLE
Not able to install it on windows

### ISSUE THREAD

**Issue by abhinavsagar** [webpack/webpack.js.org#2881]
I am on windows 10 64 bit. When i am doing `npm install` i am getting this

`> ttf2woff2@2.0.3 install C:\Users\Win 10\Desktop\github\webpack.js.org\node_modules\ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Win 10\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"`

**Comment by EugeneHlushko** [comment]
Hi @abhinavsagar 
Thanks for reporting, i don't have windows machine at this moment. Will appreciate any help from the community

**Comment by montogeek** [comment]
Could you please try with yarn?

**Comment by EslamHiko** [comment]
@abhinavsagar 
Please try to install python 2 & make sure its path is in the environment paths.
You have already python 3.
Rename python 2 executable from `python.exe` to `python2.exe`.
And try again.

**Comment by montogeek** [comment]
Closed because of inactivity.
