### ISSUE TITLE
UI/UX: Dark Mode

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack.js.org#2893]
Hello Devs,
In the world of developers, there are two types of devs, one on the light side & the rest on the dark side(not that dark side #StarWars :smile: ). Nowadays, many users prefer dark mode, due to this trend many popular products introduced dark mode (Twitter).

As Webpack's website contains docs, there are a lot of users(devs) who would love to read the docs in Dark mode.

Let's discuss :+1:

**Comment by EugeneHlushko** [comment]
While documentation is so far from being up-to-date with features, i find this unnecessary. Maybe others feel different tho. But my call is, invest time and effort into catching up in terms of feature parity vs fancy stuff.

**Comment by pranshuchittora** [comment]
Ya, makes sense. 
Let's take this with least priority.

**Comment by proteriax** [comment]
Would you accept a pull request for this?

**Comment by montogeek** [comment]
@proteriax Sure!
