### ISSUE TITLE
The order of `resolve.extensions` matters, but should not

### ISSUE THREAD

**Issue by justinpombrio** [webpack/webpack.js.org#2899]
# Bug report

**What is the current behavior?**

The order of `resolve.extensions` matters. Specifically, this line of configuration:

    resolve : {extensions: ['.js', '.jsx', '.ts', '.tsx'] }

leads to `.ts` files not being compiled, even if there is a `rule` for Typescript. On the other hand, this line:

    resolve : {extensions: ['.ts', '.tsx', '.js', '.jsx'] }

works, and leads to `.ts` files being compiled.

**If the current behavior is a bug, please provide the steps to reproduce.**

Take a project that is currently setup to use webpack, and change the order of `resolve.extensions` to put the `.ts` extension(s) after the `.js` extension(s). Then notice that the `.ts` files are no longer compiled.

EDIT: Sorry, apparently the order only _sometimes_ matters. I haven't been able to reproduce this with a small example.

**What is the expected behavior?**

Either these two lines should behave identically to each other:

    resolve : {extensions: ['.ts', '.tsx', '.js', '.jsx'] }
    resolve : {extensions: ['.js', '.jsx', '.ts', '.tsx'] }

Or the documentation should be _very clear_ about how and why the order of  `resolve.extensions` matters.

**Other relevant information:**
webpack version:  4.29.6
Node.js version: NA
Operating System: Linux
Additional tools:  typescript

**Comment by EugeneHlushko** [comment]
@justinpombrio wanna send PR or should i?

**Comment by justinpombrio** [comment]
I finally did. https://github.com/webpack/webpack.js.org/pull/2913
