### ISSUE TITLE
Document mistake with TerserWebpackPlugin

### ISSUE THREAD

**Issue by zilong-thu** [webpack/webpack.js.org#2903]
**Feature to document**

The title might be wrong in this page: https://webpack.js.org/plugins/terser-webpack-plugin

**Author(s)**

**Additional information**

![image](https://user-images.githubusercontent.com/5078580/55126030-c53a3e80-5146-11e9-8b4f-78ebca7fe9af.png)

**Comment by montogeek** [comment]
I have a different version:
![image](https://user-images.githubusercontent.com/1002461/55140287-024b0480-5138-11e9-9b2f-444385483c54.png)

Maybe GitHub cache?

**Comment by EugeneHlushko** [comment]
Cannot reproduce too

**Comment by zilong-thu** [comment]
> Maybe GitHub cache?
@montogeek  not quite sure.

> Cannot reproduce too
@EugeneHlushko , I will try to dig deeper next time I run into this problem. 

Thanks guys~~
