### ISSUE TITLE
Dynamic Module Import with its own chunk dependencies

### ISSUE THREAD

**Issue by luispuig** [webpack/webpack.js.org#2907]
I am trying to use `Module Dynamic Import` to create a bundle with an npm package using this is an excellent tutorial: https://webpack.js.org/guides/code-splitting/

But the `npm package` that I want to load dynamically **has its own chunk dependencies**:

![image](https://user-images.githubusercontent.com/24297787/55197905-53004300-51b4-11e9-93f6-b0372ca1e76f.png)

I can see that Webpack created correctly the vendor chunk: 

![image](https://user-images.githubusercontent.com/24297787/55197939-70351180-51b4-11e9-9162-ca2346037ab7.png)

**But the `npm package to import` 's chunks are not re-imported**, so it fails:

![image](https://user-images.githubusercontent.com/24297787/55198032-b4281680-51b4-11e9-8aa2-21bf4064bdf3.png)

I googled a lot but I couldn't find much information about it and, I don't know if it is a bug, misconfiguration or it is not possible.

CONFIG:
```
// my-project/index.js
const initializeLiveAR = await import(/* webpackChunkName: "livear_[index]" */ 'revieve-livear-module'); 
```
```
// webpack.config.js
module.exports = {
  entry: {
    'revieve-sdk': path.resolve(__dirname, config.main_entry),
    demoAR: path.resolve(__dirname, config.demoAR),
    demoPR: path.resolve(__dirname, config.demoPR),
  },
  devtool: 'source-map',
  mode: process.env.NODE_ENV,
  output: {
    path: path.resolve(__dirname, 'build'),
    publicPath: '/',
    filename: '[name].min.js',
    chunkFilename: '[name].chunk.js',
    libraryTarget: 'umd',
  },
  plugins: [
    process.env.ANALYZEBUNDLE ? new BundleAnalyzerPlugin() : function() {},
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
    }),
    new CopyWebpackPlugin([
      { from: 'index.html', to: '.' },
      { from: 'test', to: './test' },
      { from: 'changelog.md', to: '.' },
    ]),
  ],
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
        },
      },
      {
        test: /\.css$/,
        use: [{ loader: 'style-loader' }, { loader: 'css-loader' }],
      },
    ],
  },
};

```

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.

**Comment by luispuig** [comment]
I agree. Thanks and sorry.
