### ISSUE TITLE
Fresh Look: Colors & Fonts

### ISSUE THREAD

**Issue by pastelsky** [webpack/webpack.js.org#291]
As discussed in #285 — discussing this first since it is a perquisite for other changes.
## 1. Colors
<img src="https://cloud.githubusercontent.com/assets/8946207/19899432/21c043bc-a086-11e6-90eb-b0e25d534cea.png" width="350" />

- The blues are picked up from the logo. 
- Cools greys have a slight blue tint and are used in the sidebar, level 2 text etc.
- Neutrals are used as body copy (dark) or body copy background (light)
- Accent color — green  is used in code highlighting to make the code section a stand out a bit — since we use blue shades everywhere else in the rest of the website.

I'm not married to the idea of having green as an accent color, but it seemed to complement the primary colors well (suggestions welcome)

### Code

<img src="https://cloud.githubusercontent.com/assets/8946207/19899871/9f17e81e-a087-11e6-94f3-af6f094b3972.png" width="650" />

## 2. Fonts
The existing design uses a combination of 8 font families / weights / styles including Cabin, Ubuntu Mono, Geomanist and the icon font.

#### Proposed font stack
1) Roboto or Source Sans Pro for body copy and headings (regular/bold/regular italic).
2) System specific monospace font — Monaco (Mac), Menlo (Mac/iOS), Deja Vu Sans (Linux), Consolas (Windows) Droid Mono (Android), fallback to Fira Code. 
The code fonts supplied with OS'es look pretty good and there's little reason to download a new font.
3) Icon font using a subset of material design icons.

This comes out to be a total of 4 font combinations that a user has to download, hence better avoiding FOUT (which can last a good 3-4 seconds for each font style on slower networks)

#### Readability
<img width="1235" alt="screen shot 2016-11-01 at 11 43 39 pm" src="https://cloud.githubusercontent.com/assets/8946207/19901406/105d5dd8-a08d-11e6-97f2-0a8284b4da3e.png">

_Click to enlarge image_ or see [codepen example](http://codepen.io/pastelsky/pen/pEMOdj)

**Comment by bebraw** [comment]
> I'm not married to the idea having green as an accent color, but it seemed to complement the primary colors well.

Green is complement. Have you considered some orange or would that be pushing it?

**Comment by pastelsky** [comment]
@bebraw I did try orange ( which is infact a literal complement of blue), but the warm and cold color combination didn't seem to go to well.

**Comment by skipjack** [comment]
Yea honestly I was thinking maybe we can get away with a blue grey scheme and then a separate one for syntax highlighting. I'm not in love with the current yellow-orange but I'm also not sure if the green is better. What color were you thinking for links?

**Comment by pastelsky** [comment]
Honestly, I'm a little inspired by the green in  [Vue JS docs](https://vuejs.org/guide/#Relation-to-Custom-Elements) a. The link color,  in body copy, is blue with a light blue underline

---

![link](https://cloud.githubusercontent.com/assets/8946207/19903190/af9fb098-a093-11e6-80f3-7279ed6e3d75.png)



.

**Comment by skipjack** [comment]
Actually, seeing it in those docs, I do kind of like the green for links.

**Comment by pastelsky** [comment]
That's cool. What about the typography?

**Comment by skipjack** [comment]
Native fonts for code sound good 👍. Again I'm not sure I'm really sold on changing the base font, if we were to choose one of the others maybe Source Sans Pro but honestly they're all fairly similar. 

If we get rid of Geomanist, we could just use an SVG or PNG for the logo (which I believe @jhnns already mentioned switching back to). However, as suggested by a few people, it's also being used for the headings. @jhnns, what do you think about the fonts?

**Comment by pastelsky** [comment]
Should I go forward and make a PR for the color related changes then?

**Comment by skipjack** [comment]
Yea definitely, once you update the base color scheme in _vars I'll help update the rest of the site.

**Comment by jhnns** [comment]
Sorry for being unresponsive. It's hard to filter the important issues :)

Thx @pastelsky for your work. I like the proposed color scheme 👍 . Especially the green is a nice accent. Where can I find it on the current site?

![bildschirmfoto 2016-11-22 um 17 13 20](https://cloud.githubusercontent.com/assets/781746/20531419/019c52ea-b0d7-11e6-8c65-eb74b354976c.jpg)

I'm not quite happy with the shades, especially dark blue on dark backgrounds is not ideal. We need to ensure that all font colors maintain a [4.5:1 contrast (ideally 7:1 for regular text)](http://webaim.org/resources/contrastchecker/).

---

I agree on simplifying the font stack. 👍 for using a system font for monospaced fonts. We can also use a different font for body text, but I would like to use the Geomanist font for the headlines or decoration stuff.

**Comment by skipjack** [comment]
@jhnns agreed on the syntax highlighting issues. Even the other color, tussock, didn't work very well for links within the code blocks. Personally, I like the darker schemes for syntax highlighting a bit more but maybe going with a lighter one as you, @pastelsky, had in your mockups and picking a new prism theme wouldn't be such a bad idea. We could even customize a theme if someone wants to dig into that 😁

**Comment by jhnns** [comment]
I like dark color themes too :)

**Comment by skipjack** [comment]
Closing as the [_vars.scss partial](https://github.com/webpack/webpack.js.org/blob/master/styles/partials/_vars.scss) has been updated to reflect the new color scheme.
