### ISSUE TITLE
Importing Default using "import" statement not working

### ISSUE THREAD

**Issue by thatguypark** [webpack/webpack.js.org#2916]
Having a hard time understanding the documentation regarding `import` declarations.  The documentation on the website [https://webpack.js.org/api/module-methods/](module methods) makes mention to use imports, referring to MDN's spec, which matches the es6 [http://2ality.com/2014/09/es6-modules-final.html](es6 spec on imports).

In my export file I have...

`export default class_builder(.....)`

Which I am then importing (as per MDN and es6 spec)...

`import MyClass from 'classfile'`

Webpack is then resulting is declaring the MyClass as a Module and not as the default item, which seems contradictory to the MDN and ES6 specs that it refers too. (since one should use `import * as MyModule from 'classfile'` for Module importing.

I understand that the `export default` method is not favored, but have I missed something? was there a change that hasn't been clearly reflected on the website docs?

Using...

- webpack@4.28.4,
- webpack-cli@3.3.0
- babel-core@6.26.3
- babel-loader@7.1.5

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.

**Comment by thatguypark** [comment]
Figured it out today, seems that it was Chrome Inspector was interpreting my import statement as a Module.  After using the good old `console.dir(MyClass)` I got the expected object, so it was Chrome that was misleading me.   It seems that the object was missing the method that was throwing the initial error.   

So happy to close this.
