### ISSUE TITLE
Strange module objects structure source example

### ISSUE THREAD

**Issue by lukasgeiter** [webpack/webpack.js.org#2918]
I noticed that in the structure example for [*Stats Data* > *Module Objects*](https://webpack.js.org/api/stats#module-objects) the `source` property has a strange value:

![image](https://user-images.githubusercontent.com/5907946/55413689-20ff3000-556a-11e9-833c-6ac9584bb4eb.png)

I've stumbled upon this while fixing not escaped backslashes (#2917) but didn't really what the intended value was supposed to be.

**Comment by EugeneHlushko** [comment]
Definitely needs a look, thanks for spotting

**Comment by chenxsan** [comment]
I found it works fine under the latest PrismJS:

![image](https://user-images.githubusercontent.com/1091472/86307016-420c7000-bc48-11ea-88b9-9eb0d9afc997.png)
Might be a problem of [old version PrismJS](https://github.com/webpack/webpack.js.org/blob/master/yarn.lock#L10787).

**Comment by lukasgeiter** [comment]
Looks like it's fixed now.
