### ISSUE TITLE
Cache documention is wrong

### ISSUE THREAD

**Issue by wonnage** [webpack/webpack.js.org#2934]
**Feature to document**

`cache` option in webpack config has incorrect documentation. It states that cache is automatically enabled if the compiler is in watch mode. 

It turns out turning on watch mode doesn't automatically turn on the cache option. It looks like this is actually only the case if `mode` is set to `development`: https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L39

webpack-dev-middleware doesn't automatically enable it either; it puts the compiler in watch mode here: https://github.com/webpack/webpack-dev-middleware/blob/master/index.js#L51

This doesn't affect the cache option in any way. So unless `mode` is development, it looks like you have to explicitly set `cache` to true. 

**Author(s)**

@sokra ?

**Additional information**

N/A

**Comment by wonnage** [comment]
I'm not sure if this is a documentation fix (tell users to use development mode or set it manually), or a code fix (actually default cache to true if watching).

**Comment by EugeneHlushko** [comment]
Hi @wonnage 
Yes this makes sense to correct in docs, very nice finding. Want to file PR or should i take care of that?

**Comment by EugeneHlushko** [comment]
Picked it up, ty again
