### ISSUE TITLE
Can't access https://webpack.js.org/guides/typescript/index.html

### ISSUE THREAD

**Issue by rockmandash** [webpack/webpack.js.org#2938]
Can't access https://webpack.js.org/guides/typescript/index.html

**Comment by montogeek** [comment]
How did you reach that URL?
https://webpack.js.org/guides/typescript/ works

**Comment by rockmandash** [comment]
![image](https://user-images.githubusercontent.com/7580792/56025009-de94da80-5d43-11e9-856d-35c9bf6e2103.png)

**Comment by montogeek** [comment]
Related to https://github.com/webpack/webpack.js.org/issues/2935

**Comment by anshumanv** [comment]
Seems fixed now. 👍
