### ISSUE TITLE
Do you consider Ant-Design?

### ISSUE THREAD

**Issue by yujigali** [webpack/webpack.js.org#2939]
Emmm.... Ant-Design is a very pretty component library, and I think webpack.js.org is not so prerry. Do you consider Ant-Design?

**Comment by anshumanv** [comment]
Using another component library will greatly bloat the pages, I think improving our own SASS would be a better and quicker option to reach any desired UI.

**Comment by anikethsaha** [comment]
I am -1 for this proposal.

cc @montogeek  @EugeneHlushko

**Comment by evilebottnawi** [comment]
Will be great to migrate on https://github.com/facebook/docusaurus

**Comment by montogeek** [comment]
This website doesn't need a component library, but thanks for the recommendation.
