### ISSUE TITLE
Chinese Version

### ISSUE THREAD

**Issue by lcxfs1991** [webpack/webpack.js.org#294]
@bebraw  @TheLarkInn 

Hi, is it a good time to start translate the new doc into Chinese? If yes, I will start working on it with the help of a few friends.

Best regards,

Lee

**Comment by bebraw** [comment]
@lcxfs1991 Hey, I'm waiting for an issue related to that. We might get a specific service to enable this type of work. Stay tuned. I hope we see it in a day or two.

Basically the system would be the same web based one that Node.js uses.

**Comment by lcxfs1991** [comment]
Thx! 

I am from [AlloyTeam](https://github.com/AlloyTeam), Tencent. I have great interest in webpack and spend time on promoting it not only in Tencent but also in China. 

Here are some articles about webpack written by me. I also deliver two publich sharing on Sep. and Oct. respectively. I guess the first article below could be the initial version of the new doc for  _"How to Improve Build Performance"_

[webpack Performance: The Comprehensive Guide (English)](https://github.com/lcxfs1991/blog/issues/15)(https://github.com/lcxfs1991/blog/issues/15)
[How to write a webpack plugin - part1 (Chinese)](https://github.com/lcxfs1991/blog/issues/1)
[webpack performance improvement -- basic part(Chinese)](https://github.com/lcxfs1991/blog/issues/2)
[webpack performance improvement -- react part(Chinese)](https://github.com/lcxfs1991/blog/issues/7)
[Webpack2 -- Generated  Code Analysis On(Chinese)](https://github.com/lcxfs1991/blog/issues/14)

Once the setting is ready, please let me know, We will start working on it. 

Best regards,

Lee

**Comment by lcxfs1991** [comment]
By the way, if the visiting speed for the Chinese version site is slow, we will also provide a free server node near China for the Chinese docs.

**Comment by bebraw** [comment]
@lcxfs1991 #295 is the issue I had in mind. Feel free to check that out.

**Comment by lgh06** [comment]
so,one month passed... any progress? I wanna join.

**Comment by lcxfs1991** [comment]
@lgh06 I have found this translation project so I am wondering whether we should do it officially.

https://webpack.vuefe.cn/index/

**Comment by lgh06** [comment]
Any news? webpack2 is released officially... but the Chinese doc above seems outdated.

**Comment by lcxfs1991** [comment]
@lgh06 hi leo. though it is a bit behind English doc, but we are trying to catch up. I just released a version yesterday, however, it is not a right time to launch officially since we are still reviewing translation work. 

We plan to release another next week till we finish reviewing `guides`.  If you are interested, please join us.

My wechatid: lcxfs1991.

updated doc link:  https://doc.webpack-china.org/

**Comment by skipjack** [comment]
@lcxfs1991 is this safe to close with the chinese site up and running as well as the new link in the banner? #295 is still open for a higher-level discussion about i18n in general.

**Comment by skipjack** [comment]
@lcxfs1991 I'm going to close but feel free to re-open if I missed something.
