### ISSUE TITLE
ui(homepage): Fix file name text alignment

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack.js.org#2951]
In PR #2947, the heading was made to align in the centre which no doubt looks good. Unfortunately now the entire page is centre aligned. 

_Desktop_

![Screenshot from 2019-04-19 15-55-52](https://user-images.githubusercontent.com/32242596/56420545-fe844b00-62bb-11e9-9b6c-0304b2b19e28.png)

_Mobile_

![Screenshot from 2019-04-19 15-56-11](https://user-images.githubusercontent.com/32242596/56420546-02b06880-62bc-11e9-83e9-d8cd4942b01a.png)

### Solution
The idea is to make the file names left aligned, why?
Because in all the webpack docs it left aligned, hence its the standard.

**Comment by EugeneHlushko** [comment]
how did you connect `.splash h2` rule to the filenames? @pranshuchittora
