### ISSUE TITLE
Deploy previews on each PR

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack.js.org#2954]
Can we setup deploy previews on each PR to quickly review the changes? 

Netlify can do this pretty quickly, all we need to do it add the repo on it and it will provide a preview link on each PR.

@EugeneHlushko @montogeek

**Comment by pranshuchittora** [comment]
@anshumanv IMO integrating Netlify is not required.
Because you can achieve something similar to this in VSCode. [Read this](https://code.visualstudio.com/blogs/2018/09/10/introducing-github-pullrequests)

**Comment by EugeneHlushko** [comment]
Just added an integration with netlify, lets see if it works for new PRs outside of my own. For myself looks like its building my own pr now: https://github.com/webpack/webpack.js.org/pull/2955

**Comment by anshumanv** [comment]
> @anshumanv IMO integrating Netlify is not required.
Because you can achieve something similar to this in VSCode. Read this

Too complex in comparison to visiting a link.

> Just added an integration with netlify, lets see if it works for new PRs outside of my own. For myself looks like its building my own pr now: #2955

Build seems to be failing now, looking at the logs! @EugeneHlushko

**Comment by anshumanv** [comment]
@EugeneHlushko what's the build command you're using? I just deployed my fork and seems to work instantly - https://webpack-docs.netlify.com/
![image](https://user-images.githubusercontent.com/21009455/56435640-d403b380-62f6-11e9-93b7-8f5fa525dde2.png)

**Comment by EugeneHlushko** [comment]
It works: https://github.com/webpack/webpack.js.org/pull/2953
Had to fine tune it, ty for suggesting, feel free to close

**Comment by anshumanv** [comment]
Awesome! <3
