### ISSUE TITLE
Host webpack/media logo's on webpack.js.org

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack.js.org#297]
The webpack logo's should be available somewhere on a hosted place. This way we can use the logo in README's etc.

It looks like the path to the logo at the top-left of the website [is a hash](https://webpack.js.org/7291f7007988120cc0b20372736970c2.png), so this is too tricky. Also it should be a SVG version.

We need this feature in relatively short-term for the new loader README's (webpack/webpack/issues/3195).

@skipjack, do you happen to know an easy way to do this?

**Comment by skipjack** [comment]
Yea I can take this up this weekend, already had the update for the logo component in mind after seeing @jhnns comment a while ago, just hadn't gotten around to it.

For this issue, basically we just want a webpack branding page where people can just go download the logo and icon files for easy inclusion anywhere, correct? If so, assign this to me and I'll pick it up this weekend.

**Comment by SpaceK33z** [comment]
Very nice :). Yeah a webpack branding page would be even better, initially I meant purely hosting the files, but a page dedicated to it is much better. https://github.com/webpack/media currently also serves as a branding page, so you might use that.

> already had the update for the logo component in mind after seeing @jhnns comment a while ago

Are you talking about updating the logo + text to be a SVG? That would be nice. Let me know, I can help you test if it looks good on some devices.

**Comment by skipjack** [comment]
> Very nice :). Yeah a webpack branding page would be even better, initially I meant purely hosting the files, but a page dedicated to it is much better. https://github.com/webpack/media currently also serves as a branding page, so you might use that.

Ah good point, yea maybe I'll just link there to start. I need shift things around in the Navigation component as it's starting to get a bit cluttered with the current layout. At the very least I can add a link to the media repo there or in Footer.

> Are you talking about updating the logo + text to be a SVG? That would be nice.

Exactly, I think @jhnns mentioned he'd prefer that as opposed to using geomanist directly.

> Let me know, I can help you test if it looks good on some devices.

Sounds good 👍

**Comment by bebraw** [comment]
Adding `package.json` to `webpack/media` would allow that to be consumed as a npm dependency. That might be a nice way to manage it.

**Comment by skipjack** [comment]
@bebraw that's a good idea, I was thinking maybe via a submodule but maybe sticking with npm for everything is simpler. Maybe we should create another issue to start discussing how we can break parts of this repo out (as we were discussing with the components) and consume other repos like `webpack/media`. 

I'm also interested in what the team's plans are for the analyze tool. Ideally maybe we could have shared repo of components and utilities that this site, the analyze tool, and others all consume for a consistent interface?

**Comment by skipjack** [comment]
Or maybe things like the voting app and analyze tool can be separate SPAs that this site consumes and displays under one of it's routes?

**Comment by SpaceK33z** [comment]
> Or maybe things like the voting app and analyze tool can be separate SPAs that this site consumes and displays under one of it's routes?

Seems like a good idea. If we go that way, it'll probably take a while before the webpack logo's are hosted. Is it possible to temporarily upload the logo's somewhere on the site meanwhile? @michael-ciniawsky needs this for a huge refactoring of README's from webpack repo's.

**Comment by skipjack** [comment]
@SpaceK33z yea should've just created a new issue... done at #301.

> Is it possible to temporarily upload the logo's somewhere on the site meanwhile? @michael-ciniawsky needs this for a huge refactoring of README's from webpack repo's.

Definitely. Still planning to address this today or tomorrow. I'll be opening a PR soon.

**Comment by michael-ciniawsky** [comment]
ping :)

**Comment by skipjack** [comment]
#303 fixed this issue and was merged so I'm closing. @michael-ciniawsky there's a branding link in the footer which will bring you to a page to download the logos or icon although we still may need to do a deployment before it's actually live.

**Comment by michael-ciniawsky** [comment]
Maybe not right here, but is it not possible to host it by simply enable gh-pages in webpack/media? Sure I can download it, but then each loader repo still most enable gh-pages to serve it.

**Comment by michael-ciniawsky** [comment]
sry I misunderstood 'to download' 😛 , thought there is a download link only but got the url
@skipjack thx 👍

**Comment by skipjack** [comment]
@michael-ciniawsky haha no problem. Yea we could definitely create a gh-pages branch to host the branding guidelines page from the media repository or submodule the media repository within all of our other repositories to easily keep dependent repos up to date. Probably a good thing to discuss more in #301.
