### ISSUE TITLE
Add  documentation of sockPort, injectClient, and injectHot

### ISSUE THREAD

**Issue by hiroppy** [webpack/webpack.js.org#2974]
**Feature to document**

Add new options's descriptions of webpack-dev-server.

`sockPort`, `injectClient`, and `injectHot`

**Author(s)**

/cc @evilebottnawi 

**Additional information**

related: https://github.com/webpack/webpack-dev-server/pull/1821

**Comment by EugeneHlushko** [comment]
@hiroppy wanna file a PR or should we pick it up?

**Comment by EugeneHlushko** [comment]
Picking this up:
Lets track progress on checkboxes:
- [] `sockPort`:
- [] `injectClient`:
- [] `injectHot`:

**Comment by hiroppy** [comment]
I missed the message. I'm sorry. Thank you for adding these to the document.

**Comment by EugeneHlushko** [comment]
done, closing

**Comment by IronSean** [comment]
I still have no idea what these do though, even with the documentation

**Comment by lili21** [comment]
I still have no idea what these do though, even with the documentation

**Comment by jpierson** [comment]
Agreed @IronSean. I just ran into an issue getting a library working with webpack-dev-server and ran into the `injectClient` following the thread for https://github.com/webpack/webpack-dev-server/issues/2484. As it turns it, it seems to have fixed the problem I was running into by setting this to `false` but I have no idea why really. Better documentation here would most likely help.
