### ISSUE TITLE
[Feat]: Drop-down to select docs for different version

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack.js.org#2980]
**Description**
As webpack 5 is about to launch in the near future, docs are going to be majorly upgraded. But, there are still people around who want to access the webpack v4 docs.

**Solution**
-  Addition of a drop-down in the Nav. 
- Or Route separation. 
     - `webpack.js.org/v4/*` for webpack v4 docs. 
     - `webpack.js.org/v5/*` for webpack v5 docs. 

_(I prefer dropdown)_

Something just like this. :arrow_down: 
![Screenshot from 2019-04-29 23-55-37](https://user-images.githubusercontent.com/32242596/56920760-b2b67a80-6ae1-11e9-9e42-13c8c52f9333.png)

Let's discuss :+1:

**Comment by montogeek** [comment]
Thanks for the reminder, this is already being discussed, we need to setup the infrastructure for it.

**Comment by EugeneHlushko** [comment]
Closing as duplicate, as soon as we have a go with netlify this will be tracked in separate issue
