### ISSUE TITLE
[UX]: Mobile Sidebar padding should be reduced

### ISSUE THREAD

**Issue by reeversedev** [webpack/webpack.js.org#2989]
I've been exploring the mobile side of sidebar and the look of the first element in the sidebar including the title and close button. There is some unnecessary space from top which can reduced.

Current Look:
![Screenshot 2019-05-03 at 11 43 20 AM](https://user-images.githubusercontent.com/21155917/57122170-8fb5f000-6d99-11e9-9f7c-9c683d7d811b.png)

Improved Look: 
![Screenshot 2019-05-03 at 11 50 57 AM](https://user-images.githubusercontent.com/21155917/57122209-c25fe880-6d99-11e9-9750-9544712746c9.png)

**Comment by EugeneHlushko** [comment]
Improved version looks nice, file a pr please @reeversedev

**Comment by EugeneHlushko** [comment]
Closing via #2989
