### ISSUE TITLE
Document request: futureEmitAssets

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack.js.org#2991]
**Feature to document**
`output.futureEmitAssets`

**Author(s)**
@sokra 

**Additional information**
https://github.com/webpack/webpack/releases/tag/v4.29.0

This is a new feature that helps a lot the performance of the incremental builds. It should be documented.

I looked for closed issues but couldn't find anything

**Comment by EugeneHlushko** [comment]
Will do, thanks for reporting. Wonder why bot didnt pick it up from here: https://github.com/webpack/webpack/pull/8642
