### ISSUE TITLE
Installation page is broken, 404 Not Found

### ISSUE THREAD

**Issue by kevjin** [webpack/webpack.js.org#2992]
### Problem
When I navigate to the webpack installation page:
https://webpack.js.org/guides/installation/index.html
the installation page appears for a quick second, and then **404 Not Found** appears

This link is the top result on Google when I search "webpack installation"
![webpack broken](https://user-images.githubusercontent.com/15851351/57171264-efc78900-6dcf-11e9-8034-63c12858896f.png)

![404 error](https://user-images.githubusercontent.com/15851351/57171287-3ae19c00-6dd0-11e9-9223-73cc69c063fd.png)

I was able to replicate this problem on Chrome, Firefox on PC, and Safari on my iPhone device.

**Comment by kevjin** [comment]
It seems like the link: 
https://webpack.js.org/guides/installation/#root 
works for showing the installation page. But when I am searching up "webpack installation" on google, the top result that pops up is:
https://webpack.js.org/guides/installation/index.html _(which is broken)_
I think instead of having the page show as 404 Not Found, there should be a redirect to the first link

**Comment by EugeneHlushko** [comment]
This seems like a random google issue time to time related to how github pages let google access index.html directly.
Right now it looks like this:
<img width="822" alt="Screen Shot 2019-05-04 at 9 34 07 AM" src="https://user-images.githubusercontent.com/10549495/57175048-044b6600-6e50-11e9-8c1b-9c87589a4c32.png">

**Comment by EugeneHlushko** [comment]
@kevjin can you still reproduce?

**Comment by montogeek** [comment]
We need to know *for real* why this is happening

**Comment by EugeneHlushko** [comment]
I think its github pages allowing crawlers to access files directly

**Comment by EugeneHlushko** [comment]
Can be one of the pages linked to index.html at some point and google kept that in memory.... maybe making a sitemap will help

**Comment by EugeneHlushko** [comment]
We could also add canonical to page without index.html, should work
