### ISSUE TITLE
Unnecessary negative margin for 'Write your Code' and 'Bundle It' section should be removed

### ISSUE THREAD

**Issue by reeversedev** [webpack/webpack.js.org#2993]
While I was inspecting the website on tablet mode. The whole website looks so smooth and easy to navigate but one part on tablet mode looked a little it different and out of consistency. 

I am attaching both the pictures with before and after removing the margin.

Before: 
![Screenshot 2019-05-04 at 11 44 52 AM](https://user-images.githubusercontent.com/21155917/57174843-8775b780-6e62-11e9-9db9-07fad114c7b3.png)

After:
![Screenshot 2019-05-04 at 11 45 08 AM](https://user-images.githubusercontent.com/21155917/57174848-8fcdf280-6e62-11e9-8817-9cbf677f27a8.png)

**Comment by reeversedev** [comment]
@EugeneHlushko What do you think?

**Comment by EugeneHlushko** [comment]
This is a design choice that was made previously, doesn't look like an issue to me

**Comment by reeversedev** [comment]
I agree that this must be a design choice but don't you think removing the margin makes it look better?

**Comment by montogeek** [comment]
Yes, that negative (I think it is called) space looks better

**Comment by reeversedev** [comment]
@montogeek So you like the Before part or the After part?

**Comment by montogeek** [comment]
Yes

**Comment by pranshuchittora** [comment]
IMO the current design shouldn't be changed until & unless content overflow or misbehaves in any resolution.
