### ISSUE TITLE
`resolve.extensions` docs say that `*` is needed to resolve imports with extensions

### ISSUE THREAD

**Issue by jakub-g** [webpack/webpack.js.org#2997]
https://webpack.js.org/configuration/resolve/#resolveextensions says:

> For modules that are imported with their extension, e.g. import SomeFile from './somefile.ext', to be properly resolved, a string containing "*" must be included in the array.

This change landed in https://github.com/webpack/webpack.js.org/commit/c5a12dfeb5da53f839c30649473c7d9aa301e70b around webpack 2

However AFAICT, it is no longer needed - I don't have `'*'` nor `''` in my webpack config and the imports with explicit extensions like `.js` work fine. So I'm wondering if this piece of documentation is still valid? Can someone confirm?

**Comment by EugeneHlushko** [comment]
No i don't think thats necessary anymore, want to fix it @jakub-g or should i?

**Comment by jakub-g** [comment]
Ok opened https://github.com/webpack/webpack.js.org/pull/2998
