### ISSUE TITLE
Writer's guide link in PR template is broken

### ISSUE THREAD

**Issue by furkle** [webpack/webpack.js.org#3005]
The URL in the template to the writer's guide leads to what appears to be a broken redirect (/writers-guide/). The redirect appears as if it *should* occur within https://github.com/webpack/webpack.js.org/blob/3854b237a212d2b5d175651d418d1847ce7069c0/webpack.ssg.js. The actual link, /contribute/writers-guide/, still works correctly.

**Comment by EugeneHlushko** [comment]
Want to file a PR to fix it @furkle or should we pick up?

**Comment by furkle** [comment]
I bundled this fix in (somewhat inadvertently) with another change in #3007. It should maybe receive a rebase given that there's a couple junk commits in there.

**Comment by furkle** [comment]
The referenced pull has been accepted. Closing the issue, feel free to reopen if needed.
