### ISSUE TITLE
Repo Structure - Modularizing and Consuming other Webpack Repos

### ISSUE THREAD

**Issue by skipjack** [webpack/webpack.js.org#301]
Opening a discussion for how we can break parts of this repo out (as we were discussing with the components) and consume other repos like `webpack/media`. 

From #297:

> Adding `package.json` to `webpack/media` would allow that to be consumed as a npm dependency. That might be a nice way to manage it.

@bebraw that's a good idea, I was thinking via a submodule but maybe sticking with npm for everything is simpler... 

I'm also interested in what the team's plans are for the analyze tool. Ideally maybe we could have shared repo of components and utilities that this site, the analyze tool, and others all consume for a consistent interface?

Or maybe things like the voting app and analyze tool can be separate SPAs that this site consumes and displays under one of it's routes?

**Comment by bebraw** [comment]
There's [an effort going on for renewing the analyse tool](https://github.com/webpack/analyse-tool). Integration is going to be interesting. Maybe we could consume it as a dependency (React component) and push it within an `Interactive` container somehow? That would allow us to retain main site navigation and all that.

Any thoughts @Bartekus?

**Comment by Bartekus** [comment]
@bebraw I definitely agree about keeping things modular and the way the current analyze tool is structure should allow the whole component to work as either part of a bigger set or as an individual SPA.
Certainly flexibility, modability and extensibility are the ways of the webpack and as such, they should be our aim too. 
Keeping the webpack brand consistent and coherent to itself is in my opinion a great strategy to take.

**Comment by bebraw** [comment]
@Bartekus Awesome. Good design would make it possible to run it through Electron and so on. Actually wrapping the site within Electron would be feasible (not sure of the exact benefit unless we add some features), but still. 👍

**Comment by Bartekus** [comment]
@bebraw I think the benefit in and of itself would be to push the envelope further and further and to keep trying new ways of utilizing the power that webpack based development affords so that we continue to lead and advance the javascript community.

**Comment by skipjack** [comment]
@bebraw @webpack/documentation-team I'm going to close this for now and try to focus mainly on knocking out documentation tasks for the next month or so. Once we get further along with the actual content, I think we can then take more time to clean everything up. This issue has so many parts to it that I think we should instead create smaller more targeted issues and re-open it once more pieces are in place.

Some notes in the meantime:

- I've already extracted and cleaned up our [banner/navigation][1] component into a separate repo called [react-banner][2]. 
- I think the [sidebar-mobile][3] component could be replaced by an external open source react component like [react-sidebar][4] however we might have to find another that plays better with antwar's interactive feature.
- There are likely some other components like the contributors, gitter button, notification bar etc that can either be extracted or replaced by existing open source react components.
- The [entire voting app][5] can be cleaned up and extracted into a separate repo similar to the discussion of the analyze tool.
- [This package][6] and maybe others could be used to simplify our [bloated markdown utility][7] which has already caused some issues. Related discussion in #178.

Benefits to these changes:

- Simplify this repo and make it's codebase more approachable
- Isolating these pieces makes testing and adjustments easier
- Pushes many UI and non-documentation related issues out to other repositories
- Extracted components can now be used in other sites/applications (webpack tools included)
- And probably a lot more...

As mentioned above, I'm going to try to direct my attention towards finishing the last few [UI issues][8] and then try to start a move to knock out as many documentation issues as possible. If anyone wants to pick up something from the list above, please create a new more targeted issue or PR that we can knock out quickly. Hopefully we'll open this back up in a couple months and start banging away with less high priority docs issues and more time on our hands 👍 .

[1]: https://github.com/webpack/webpack.js.org/tree/master/components/navigation
[2]: https://github.com/skipjack/react-banner
[3]: https://github.com/webpack/webpack.js.org/tree/master/components/sidebar-mobile
[4]: https://github.com/balloob/react-sidebar
[5]: https://github.com/webpack/webpack.js.org/tree/master/components/vote
[6]: https://github.com/christianalfoni/markdown-to-react-components
[7]: https://github.com/webpack/webpack.js.org/blob/master/utilities/markdown.js
[8]: https://github.com/webpack/webpack.js.org/issues?q=is%3Aissue+is%3Aopen+label%3AUI%2FUX
