### ISSUE TITLE
Page scroll remains fixed when navigating

### ISSUE THREAD

**Issue by nveenjain** [webpack/webpack.js.org#3015]
**Feature to document**
When navigating, if I've scrolled to the bottom of one page and navigate to another page, then the new page loads with scroll fixed at the bottom, One has to scroll up to start reading from starting of the page.
To reproduce, scroll down to the bottom in any page, and then click on any link to load another page.

**Author(s)**
N/A

**Additional information**
window.scrollTo(0,0) might save the problem. I'll send a PR.

**Comment by chenxsan** [comment]
I believe it's already fixed.
