### ISSUE TITLE
[build]: build failing

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack.js.org#3017]
**Introduction**
`npm run build` is exiting with status 2.

![Screenshot from 2019-05-12 23-08-37](https://user-images.githubusercontent.com/32242596/57585843-26597e00-750b-11e9-8e18-508f93ec7965.png)

**Expected Output**
It should build successfully.

**Comment by EugeneHlushko** [comment]
We use yarn in this repository

**Comment by montogeek** [comment]
What is triggering that error exactly?

**Comment by EugeneHlushko** [comment]
i think we dont need to keep this discussion or this ends up in package-lock.json which leads to headache when you need to update deps and have both yarn and npm locks

**Comment by EugeneHlushko** [comment]
The error is related to a known issue that sokra was fixing in 4.30.1 4.30.2 4.30.3 where npm hoisted wrong dep IIRC

**Comment by EugeneHlushko** [comment]
https://github.com/webpack/webpack/issues/8656

**Comment by pranshuchittora** [comment]
Thanks @EugeneHlushko executing scripts with`yarn` is working successfully. But why it's behaving weirdly with`npm`.

IMO the workflow with both the package manager should be consistent.

Thanks you.

**Comment by montogeek** [comment]
His 2 previous comments answer the why.
