### ISSUE TITLE
feat(sidebar): drop-down for each section in SideBar (Mobile Devices)

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack.js.org#3032]
**Problem**
As of now all the sections, as well as their subsections, are listed linearly in the sidebar (mobile devices). Which makes it harder to navigate.

![Screenshot from 2019-05-14 23-15-04](https://user-images.githubusercontent.com/32242596/57719831-35bd0080-769e-11e9-89f1-655e8cc8cd00.png)

**Solution**
Addition of dropdown for each section.

Something like this :arrow_down: 

![Screenshot from 2019-05-14 23-15-24](https://user-images.githubusercontent.com/32242596/57719834-36559700-769e-11e9-9a31-e85a7ba451f0.png)

**Comment by montogeek** [comment]
> Addition of dropdown for each section.

That is too much for a mobile site in a sidebar.

Adding some margin left should be enough.
