### ISSUE TITLE
Integrate Prettier

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack.js.org#3040]
* Introduce prettier as a code formatter.
* Integrate with husky to format code pre-commit

Sending a PR with an initial iteration, please use this thread to discuss the config and anything related.

Since we already have eslint, integrating with it.

**Comment by montogeek** [comment]
PR: #3109

**Comment by chenxsan** [comment]
closed via https://github.com/webpack/webpack.js.org/pull/4518
