### ISSUE TITLE
[seach]: clear search button is too close to search button

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack.js.org#3046]
**Description**
The button for clearing search bar is too close to the search button, which leads to false clicks in Mobile devices.

![Screenshot from 2019-05-16 22-07-15](https://user-images.githubusercontent.com/32242596/57871717-99266a00-7827-11e9-9bf1-76a4c8d05997.png)

**Motivation**
Today I encountered a problem in my personal project and wanted to take some reference from the webpack docs. As I was away from my laptop so I decided to read the required docs on my mobile. When I typed the required query in the `navigation-search-bar` and tried to hit the `Search btn`, mistakenly I clicked clear btn `X` as it is too close.

**Comment by hiteshsubnani0128** [comment]
Please this issue to me.

**Comment by pranshuchittora** [comment]
@hiteshsubnani0128 I am happy that you want to work on this issue, unfortunately there's already a PR #3047 against this issue. 

Contrary, there are a lot of issue which you can work upon.

Thank you.
