### ISSUE TITLE
👨‍🔧[node-version]: Newer node version not supported in next branch

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack.js.org#3053]
**Description**
I am using node version `10.12.0` while working on the `next` branch, I am not able to install node_modules.

![Screenshot from 2019-05-19 01-21-54](https://user-images.githubusercontent.com/32242596/57974412-3a9eee80-79d5-11e9-8d46-cbbcbca63052.png)

**How I worked out with this**

![Screenshot from 2019-05-19 01-27-37](https://user-images.githubusercontent.com/32242596/57974415-54403600-79d5-11e9-8349-dd4fb7435c4c.png)

**Expected Behaviour**
Should work with latest node LTS versions (10.x)

**Comment by jeremenichelli** [comment]
I'll take a look at this if nobody grabbed it @EugeneHlushko

**Comment by montogeek** [comment]
Why does it need to work on the latest LTS? That `upath` dependency is a transitive dependency, updating it (if that is even possible) could break something else.

**Comment by EugeneHlushko** [comment]
@pranshuchittora `next` was updated with master few days ago, please re-try

**Comment by EugeneHlushko** [comment]
I am working on `next` and `master` on both macOS and Windows 10 (Yooohooo!) with node 10:
```
PS > node -v
v10.16.0
```

**Comment by EugeneHlushko** [comment]
closing as next is now up to date with master
