### ISSUE TITLE
webpack prefetch  with react Router

### ISSUE THREAD

**Issue by anusm14** [webpack/webpack.js.org#3076]
- [ ] Check the current issues to ensure you aren't creating a duplicate.
- [ ] Consider making small typo fixes and such directly as pull requests.
- [ ] For the voting application, go to https://github.com/webpack-contrib/voting-app.
- [ ] For loader/plugin docs, consider opening an issue in the corresponding repository.
- [ ] No existing issue? Go ahead and open a new one.
- __Remove these instructions from your PR as they are for your eyes only.__

**Comment by anusm14** [comment]
Want to add a prefetch for a component in React Router, but currently its component is and Dynamic Import. Added webpackprefetch= true does not work. Hence want to know what would be the best way to add webpackprefetch= true to React router.

**Current code** - 
 const Schedules = (props: any) => (
    <DynamicRouteImport load={ () => import(/* webpackChunkName: "SchedulesPage" */ /*"./schedules/Schedules") }>
        { (Component: any) => Component === null
        ? <DynamicRouteSpinner />
        : <><Component {...props} /></> }
    </DynamicRouteImport>
);

**react Router**
                    { /* Schedules page */ }
                    <Route exact path={ `${match.url}/schedules` } component={ SCHEDULES } />  } />


**I tried using** 
const SCHEDULES = () =>  import(/* webpackPrefetch: true */ /* webpackChunkName: "SchedulesPage" */ "./schedules/Schedules"); , but that does not create an component. 

Want to know whats the best way to do it.

**Comment by hiroppy** [comment]
Please ask questions on StackOverflow or the webpack Gitter.

https://stackoverflow.com/questions/ask?tags=webpack
https://gitter.im/webpack/webpack

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
