### ISSUE TITLE
Landing page gradient gets banding on lower quality displays (think TN panel)

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#309]
I'm not sure if there's much we can do about that but I would thought to raise an issue. Maybe tweaking the gradient curve a notch would make it less noticeable?

**Comment by skipjack** [comment]
I think this will be moot if we move to the darker background as suggested by @patelsky. Once we update the color scheme I'd be happy to help make these changes.

**Comment by skipjack** [comment]
Leaving this open until the landing page updates get done.

**Comment by pastelsky** [comment]
The banding is because grey is one of the hardest colors for monitors to reproduce correctly. Switching to a different color might help.

**Comment by skipjack** [comment]
Closing as I believe this was fixed by the new background added in #374.
