### ISSUE TITLE
ProgressPlugin Documentation: Many options missing

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack.js.org#3094]
**Feature to document**

ProgressPlugin: https://webpack.js.org/plugins/progress-plugin

Source: https://github.com/webpack/webpack/blob/master/lib/ProgressPlugin.js
Options Schema: https://github.com/webpack/webpack/blob/master/schemas/plugins/ProgressPlugin.json

**Author(s)**

**Additional information**

The documentation includes the case where a `handler` function is passed in, but does not document any of the options when an object is passed into this plugin.

**Comment by EugeneHlushko** [comment]
Hmm looks like we've missed, that. Picking it up
