### ISSUE TITLE
Dev Server Documentation: sockHost option

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack.js.org#3095]
**Feature to document**

`sockHost`: https://github.com/webpack/webpack-dev-server/pull/1858

**Author(s)**

Myself, reviewed by @evilebottnawi @hiroppy 

**Additional information**

`sockHost` is only used by the client of the Dev Server. It is the host that the client connects to. This makes it possible for the server to exist on a different host than the client, allowing the client to know where to remotely connect to.

**Comment by EugeneHlushko** [comment]
Via #3101
