### ISSUE TITLE
Infrastructure - complete plan

### ISSUE THREAD

**Issue by sokra** [webpack/webpack.js.org#31]
The complete plan is:

* For development this is just a normal react application (client-side rendered).
* For production this repo builds into a prerendered site with client-side javascript applied.
  * Why? search engines should be able to index the documentation.
  * How? react-router with async routes, [static-site-generator-webpack-plugin](https://github.com/markdalgleish/static-site-generator-webpack-plugin)/Antwar, entry point per route.
* It's published to the `webpack.github.io` repo. (Best via CI, codeship?)
  * This allows use to override `webpack.github.io/docs` when no `webpack/docs` repo exists. OR we remove the gh-pages branch and use the wiki as old docs.
  * We will rename the `webpack/docs` repo to `webpack/old-docs` once the new documentation ships.
* Server-side elements are added via [gordon](http://gordon.readthedocs.io/en/latest/) with AWS lamdas + api gateway once needed
  * Not needed for the documentation
  * But will be needed to future stuff...

**Comment by bebraw** [comment]
Probably safe to close now that most of the infrastructure is done. We are missing that gordon bit, but that can be discussed later.
