### ISSUE TITLE
There's no way to exit/cancel search after opening the widget

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#310]
Activating search works just great. The problem is that there's no way to exit it once you activate it on the landing page (might apply to other pages too). I would expect "return" on an empty field or "esc" to work. Likely blur should close it too so you can click outside of the field and make it closed.

**Comment by SEAPUNK** [comment]
You can exit it by clicking on the search icon again, from what I've tried, but yeah, that's not very useful.

**Comment by skipjack** [comment]
Yea so as mentioned the only way currently is by clicking the search icon again. I can add a blur handler and maybe a clear button? Would that work?

**Comment by SEAPUNK** [comment]
Does blur get called when switching windows to copy a string?

**Comment by skipjack** [comment]
It gets called on window, not sure if it does on the input.

**Comment by SEAPUNK** [comment]
It looks like it does, at least on Chrome. I think that's fine anyway, since it shouldn't be too much of a hassle, and it's how MDN's search box works.
