### ISSUE TITLE
Document SplitChunksPlugin function parameters

### ISSUE THREAD

**Issue by ryandrew14** [webpack/webpack.js.org#3116]
**Feature to document**

SplitChunksPlugin -- function parameters in functions for `splitChunks.name` and `splitChunks.cacheGroups.{cacheGroup}.test`

#6341 -- introduction of SplitChunksPlugin

**Author(s)**
@sokra 

**Additional information**
These two functions take in parameters `chunks` and `module`, of which there does not seem to be documentation yet on what fields these parameters have. It was really tough for me to use this function even for something simple like a small name change because I didn't know what values I was provided to work with. The `module` and `chunks` arguments are pretty esoteric, and it would be wonderful if people like me and [this guy](https://stackoverflow.com/questions/55717783/any-webpack-splitchunks-name-as-a-function-documentation-other-than-from-the-web/56570774) had a little more to go off of when using these functions.

**Comment by EugeneHlushko** [comment]
Awww i didnt see your PR @ryandrew14

**Comment by ryandrew14** [comment]
@EugeneHlushko Your PR provides the example @montogeek was asking for, but mine provides more information that has proven to be helpful in the actual documentation area. Can we merge both of them?

BTW, thanks for the research, and for a really solid example.

**Comment by montogeek** [comment]
Merge both :)

**Comment by EugeneHlushko** [comment]
Yes i dont see why not, but i left a comment in your PR. Also i am adding `test` example today

**Comment by EugeneHlushko** [comment]
I've had a look at test function example and there isnt much i can add, you can check different properties of module, and chunks but thats about it. i am adding return types to the functions to make it even more obvious
