### ISSUE TITLE
Sidebar - Incorrect active navigation links in sidebar 

### ISSUE THREAD

**Issue by aprilandjan** [webpack/webpack.js.org#3127]
It seems the sidebar in guide page might have incorrect navigation link generated and incorrect active link when page initially opened.

For example, I opened <https://webpack.js.org/guides/development/#using-watch-mode> directly, and get the following:

![image](https://user-images.githubusercontent.com/7011247/59604460-d770bb00-913e-11e9-8ff3-88ddb081613d.png)

Seems that every sidebar menus are shifted by one position.

**Comment by pranshuchittora** [comment]
@aparajita thanks for reporting this issue.
I am able to reproduce this issue.
-> I opened the above link in the incognito, and able to experience the error.
-> The issue might be with the service worker and caching. (Not 100% sure)

**Comment by EugeneHlushko** [comment]
Yup found similar issue earlier, this is SSR pass. Will fix it, think i broke it when released `printable`

**Comment by EugeneHlushko** [comment]
@aprilandjan please check the preview in linked PR, i cannot reproduce anymore

**Comment by aprilandjan** [comment]
@EugeneHlushko Yes the preview link is all good, thanks!
