### ISSUE TITLE
splitChunks.automaticNameMaxLength to be documented

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack.js.org#3133]
__Feature to document__
`splitChunks.automaticNameMaxLength` as per https://github.com/webpack/webpack/releases/tag/v4.35.0

__Author(s)__
@sokra @ryandrew14  

__Additional information__

[ ] I am willing to work on this issue and submit a pull request.

**Comment by ryandrew14** [comment]
I'm actually the author of this feature (here)[https://github.com/webpack/webpack/pull/9285]. I will submit a PR documenting it. Thanks for the issue!

**Comment by EugeneHlushko** [comment]
Thank you @ryandrew14 
Looking forward to the pr
