### ISSUE TITLE
Docs(configuration): Performance>Items link to Node>Items in Sidebar/SidebarItem

### ISSUE THREAD

**Issue by Iyashi** [webpack/webpack.js.org#3138]
Hello brave webpack community,

There are falsy links to configuration items in the Sidebar in the current configuration docs for webpack 4.35.0 under https://webpack.js.org/configuration/

The all the "Performance" SidebarItem's actual link to the "Node" doc items.

As an example:
`Performance > Hints` in Sidebar links to https://webpack.js.org/configuration/node/#nodeconsole whereas it should link to https://webpack.js.org/configuration/performance/#performancehints)
The following screenshot demonstrates exactly that:
(![Performance > Hints link in Sidebar](https://user-images.githubusercontent.com/19608256/59968271-4b440680-9537-11e9-99d8-17f07d775b5f.png) appended):

I was trying to track this down in this repo, but didn't find the issue neither in the Markdown files nor in your documentation build chain.

Maybe one of you who is native to the docs generating is doing a better job than me :/

**Comment by EugeneHlushko** [comment]
Hi @Iyashi 
I think i know what that is, will try to fix

**Comment by Iyashi** [comment]
Nice reaction time! :p

I just noticed, its vice-versa aswell (Node links to Performance, Performance links to Node
AND it only happens on some URLs. If I'm at `Watch and WatchOptions` (https://webpack.js.org/configuration/watch/) both, Performance and Node links are just fine.

**Comment by EugeneHlushko** [comment]
I've found the culprit already, will file a PR soon. Looks like the `printable` page implementation broke it a week ago :(
