### ISSUE TITLE
Concepts Review

### ISSUE THREAD

**Issue by sokra** [webpack/webpack.js.org#314]
I'll review all pages in the concepts section...

* [x] Introduction
* [x] Entry Points
  * [ ] Scenarios > Separate App and Vendor Entries: Consider removing
* [x] Output
  * [ ] Rewrite!
  * [ ] Merge the content with the configuration page
* [ ] Loaders
  * [x] Write content! (Empty)
* [x] Plugins
  * [ ] node.js API should recommend the `plugins` property for plugins
* [ ] Configuration
* [ ] Dependency Graph
* [ ] Module Resolution
* [ ] Modules
* [ ] Targets

**Comment by skipjack** [comment]
@sokra is this still in progress or was it finished in #315 and other subsequent PRs?

**Comment by sokra** [comment]
It was not finished. I had too few time...

**Comment by skipjack** [comment]
@sokra I'm going to close this one as it's a bit dated -- and I think certain things were already tackled in separate prs (like merging output content into the config page). I just started an overarching review of guides with @TheDutchCoder in #1273 (see #1258 as well) and plan to do a heavy review of the other sections once we have much of the backlog complete. I'll definitely ping you and the rest of the team once we start that -- it would be great to have your help to make sure everything is accurate and in sync with the latest release.
