### ISSUE TITLE
Remove printable pages from search entries

### ISSUE THREAD

**Issue by silvenon** [webpack/webpack.js.org#3161]
It seems that just about every search entry is duplicated with a regular page and a printable page. Aside from the confusion that duplicates alone bring, it can also be very confusing to click on a printable page because the print dialog keeps relentlessly popping up and the reader might not have any idea what's happening.

Removing printable pages from search entries would significantly improve viewing the docs.

**Comment by EugeneHlushko** [comment]
Hi @silvenon thats totally on me.
We did not include them into the sitemap but forgot about nofollow on the links and will also add `<meta name="robots" content="noindex,nofollow">`

**Comment by EugeneHlushko** [comment]
Scratch that it already has a nofollow on the links
