### ISSUE TITLE
Potential error in proxy doc

### ISSUE THREAD

**Issue by bard** [webpack/webpack.js.org#3168]
https://webpack.js.org/configuration/dev-server/ says:

```js
module.exports = {
  //...
  devServer: {
    proxy: {
      '/api': 'http://localhost:3000',
      changeOrigin: true
    }
  }
};
```

That doesn't work for me. The following does:

```js
module.exports = {
  //...
  devServer: {
    proxy: {
      '/api': {
        target: 'http://localhost:3000',
        changeOrigin: true
      }
    }
  }
};
```

**Comment by montogeek** [comment]
Please send a PR.

**Comment by bard** [comment]
I would have gladly sent a PR — in fact, I would have sent one right away if certain that this is a bug and not my misunderstanding — but getting assigned work on a project that I didn't opt into joining or othewise made myself available to is, well... unusual.

**Comment by montogeek** [comment]
Sorry

**Comment by EugeneHlushko** [comment]
related pr is merged
