### ISSUE TITLE
Frontpage navigation is broken on iPad Chrome

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#318]
Example:

![img_0045](https://cloud.githubusercontent.com/assets/166921/20139747/f401702e-a687-11e6-8f30-b588aa58ab77.PNG)

**Comment by SpaceK33z** [comment]
I think @skipjack fixed this with #306.

**Comment by skipjack** [comment]
Yea I think this should be fixed but honestly I'm going to simplify the splash page soon and probably remove the `.navigation--transparent` state (which has been the cause of a few issues) once we update the color scheme as I feel it's causing more problems than good. Plus I think the dark background for the visualization will look better and we shouldn't have to customize the navigation state for it.

**Comment by bebraw** [comment]
Ah, ok. Better get faster deployment flow in place. 👍
