### ISSUE TITLE
Bug in Getting Started Guide (easy workaround)

### ISSUE THREAD

**Issue by unixfreak0037** [webpack/webpack.js.org#3182]
# Bug report

**What is the current behavior?**
The Getting Started guide fails at the end of the Creating a Bundle section.

**If the current behavior is a bug, please provide the steps to reproduce.**
Follow the guide as is.

**What is the expected behavior?**
At the end of that section, the browser should display Hello webpack, but instead you get a syntax error in the middle of the minified javascript.

So it looks like there's some kind of compatibility issue between the lodash library and the default minimizer used in production mode (which the guide uses since it's the default mode and it's not specified.) I think the escaped values in lodash/_deburrLetter.js are getting translated into their literal values, and in the process of doing that one of the values ends up missing quotes for some reason and causes a syntax error.

An easy work-around in the guide is to set the mode to development, which is probably fine for the purposes of the guide.

Figured I'd report this for the benefit of people like me who are just getting started with webpack.

**Other relevant information:**
webpack version:  4.35.3
Node.js version: 12.5.0
Operating System: macos (darwin)
Additional tools:

**Comment by unixfreak0037** [comment]
https://webpack.js.org/guides/getting-started/

**Comment by EugeneHlushko** [comment]
Hi @unixfreak0037 
I will look into this tonight, ty for reporting

**Comment by EugeneHlushko** [comment]
Just tested it, could not reproduce. Versions used:
```
  "devDependencies": {
    "webpack": "^4.35.3",
    "webpack-cli": "^3.3.5"
  },
  "dependencies": {
    "lodash": "^4.17.14"
  }
```

**Comment by EugeneHlushko** [comment]
Maybe this is related to Node.js version? I am at `v10.16.0`

**Comment by unixfreak0037** [comment]
Yes, you are correct. I just tested that myself using version 10.16.0 and it worked, switched to version 12.5.0 and got the syntax error.

**Comment by EugeneHlushko** [comment]
Right, if that is a default (did you use brew?), we might want to drop a warning about LTS versions

**Comment by unixfreak0037** [comment]
Yep. Brew on the mac and apt on ubuntu.

**Comment by EugeneHlushko** [comment]
Thank you, that cleard it up

**Comment by nateUX** [comment]
As of now (April 26, 2020) the LTS version is beyond 12.5 as the added disclaimer notes. It is currently 12.16.2. 

No different versions worked for me either. I had to put it in development mode for the page to load properly. 

It tried:
10.16.0
10.16.2
12.16.2
12.15.0
