### ISSUE TITLE
documentation for jsonpFunction 

### ISSUE THREAD

**Issue by petvas** [webpack/webpack.js.org#3186]
## Feature request

**What is the expected behavior?**
Mention `jsonpFunction` in the docs https://webpack.js.org/concepts/output/

**What is motivation or use case for adding/changing the behavior?**
These days webpack is one of the most popular build tool, lots of websites are working with 3rd party companies for marketing / motioning etc... It is possible there are multiple webpack bundle is running on the same site, or some sites has multiple webpack bundle itself. like create react app and traditional js.

**How should this be implemented in your opinion?**
Create a small section in the docs to mention this possible issue and the solution: `jsonpFunction `

**Are you willing to work on this yourself?**
no (English is not my main language)

**Comment by EugeneHlushko** [comment]
Thanks for raising this @petvas 

I guess we can mention this on the concepts section, needs a thought on also expanding the explanation and adding an example here: https://webpack.js.org/configuration/output/#outputjsonpfunction

Or even creating a guide in guides section.

**Comment by EugeneHlushko** [comment]
@montogeek what do you think? Concepts + guide would be my vote, but needs more investigation and putting up an example case.

**Comment by petvas** [comment]
I think guide would be nice too, I read all of it and I had no idea running multiple webpack bundle can cause an issue when chunks are involved. (and error messages are not helping when this issue come up)

**Comment by EugeneHlushko** [comment]
I cannot find a contextually fitting place for the thing, but i was able to improve the output.jsonpFunction doc itself.

**Comment by abelmark** [comment]
I don't see a jsonpFunction section under output for the Webpack 4 docs...
