### ISSUE TITLE
[Writing a Loader / Common Code] Example needed

### ISSUE THREAD

**Issue by ogonkov** [webpack/webpack.js.org#3191]
__Feature to document__

Writing loader [common code](https://webpack.js.org/contribute/writing-a-loader/#common-code). PR not available, commit 06fe82dbcb764273d8dfb8080ab529aeace78845

__Author(s)__

@bebraw 

__Additional information__

It's would be nice to add some examples of creating a runtime file.

It's not clear for me how it supposed to looks like.

[ ] I am willing to work on this issue and submit a pull request.

**Comment by ogonkov** [comment]
I'm guessing that it should be like resolving loader result with imports like:

```
this.async()(null, `
  const runtime = require('./loader-runtime');

  module.exports = function() {
    return runtime('me');
  };
`);
```

**Comment by EugeneHlushko** [comment]
Would be nice if someone who did work on creating a loader would file a PR or contribute on the discussion

**Comment by ogonkov** [comment]
After some experiments, it seems I was right, loader authors should generate `require()` calls in case they need something to use in loader to work. We pack will handle this as usual an bundle it.

Need some confirmation that "Common code" about my thoughts above.

**Comment by jakub-g** [comment]
@ogonkov where should `loader-runtime` to have webpack pick it up correctly? (assuming it's not a separate npm module, but something I want to have in the same repository as the loader?)

**Comment by ogonkov** [comment]
@jakub-g just place it like regular dependency in loader output
