### ISSUE TITLE
invalid documentation for HMR

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#3193]
__Feature to document__

https://webpack.js.org/guides/hot-module-replacement/

__Author(s)__

any

__Additional information__

webpack-dev-server automatically insert `HotModuleReplacementPlugin` plugin when you enable `hot: true`, so need fix docs, thanks

[ ] I am willing to work on this issue and submit a pull request.

**Comment by EugeneHlushko** [comment]
Thanks for reporting man! @evilebottnawi
