### ISSUE TITLE
`require.context` Docs Showing Incorrect Default for `useSubdirectories`

### ISSUE THREAD

**Issue by AaronBeaudoin** [webpack/webpack.js.org#3217]
According to the docs, the default for the `useSubdirectories` parameter to the `require.context` function parsed out by Webpack is `false`, but in my project it seems to default to `true`. I'm using Webpack 4.15.1.

If this is intended it would helpful to at least either note the change and at which version it occurred in the docs, or provide some way to access the docs for previous versions. Both would be even better...

**Edit:** The problem I'm referring to is not in the API docs, but in the "Dependency Management" guide. Sorry for any confusion.

**Comment by EugeneHlushko** [comment]
Cannot seem to find the related source code, @sokra can you help here?
https://webpack.js.org/api/module-methods/#requirecontext

**Comment by AaronBeaudoin** [comment]
Sorry I should clarify... the place in the docs I'm referring to is actually this one:
https://webpack.js.org/guides/dependency-management/#requirecontext

I'm talking about the code block right under the text "The syntax is as follows:". It appears that the signature shown does not match the description on the API page.

I would change the code block from this:
```js
require.context(directory, useSubdirectories = false, regExp = /^\.\//);
```
To this so it matches the API docs:
```js
require.context(directory, includeSubdirs= true, regExp = /^\.\/.*$/, mode = 'sync');
```

**Comment by EugeneHlushko** [comment]
Sure it looks better since also shows the mode

**Comment by dhuang612** [comment]
Hi, 
I would like to take this on

**Comment by EugeneHlushko** [comment]
I think @AaronBeaudoin already has a resolution to this in his previous comment, would you mind filing a PR @AaronBeaudoin ?

**Comment by dhuang612** [comment]
got it thanks for the update

**Comment by EugeneHlushko** [comment]
@dhuang612 looks like @aaronang doesn't have time to do it, still want to grab this?

**Comment by dhuang612** [comment]
yeah I can take it over

**Comment by dhuang612** [comment]
Hey Eugene, 

Sure it was already merged.
PR #3276

**Comment by EugeneHlushko** [comment]
Thank you!
Closing via #3276
