### ISSUE TITLE
[proposal] move awesome-webpack to this repo

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack.js.org#3225]
__Feature to document__

Move https://github.com/webpack-contrib/awesome-webpack repo inside this repo and create page on site for this. Maybe will be great keep file in markdown format for developers which love read information from github.

__Author(s)__

any

__Additional information__

It is allow to us keep information about community loaders/plugins/etc in one place.

[ ] I am willing to work on this issue and submit a pull request.

**Comment by montogeek** [comment]
Sounds good to me, What about its owner/owners?

**Comment by evilebottnawi** [comment]
@montogeek Can you clarify about owners? If you about contributors, i think working through PRs is normal workflow

**Comment by montogeek** [comment]
I mean the owners of that repo

**Comment by evilebottnawi** [comment]
@montogeek oh, no problems with this

**Comment by montogeek** [comment]
What would be the route and its navigation inside the site? That is the starting point.
I think that having a dedicated link in the subnavigation (next to Migrate, Loaders, etc) would be fine.
![image](https://user-images.githubusercontent.com/1002461/62544977-14b11980-b861-11e9-8e6d-ae1596a3d439.png)


But in the other hand, this page will be so abstract regarding content, it has links to a lot of different stuff, some of them already exists in the website, like loaders and plugins section, that information shouldn't be duplicate.

**Comment by evilebottnawi** [comment]
@montogeek 
> I think that having a dedicated link in the subnavigation (next to Migrate, Loaders, etc) would be fine.

How we name page?

> But in the other hand, this page will be so abstract regarding content, it has links to a lot of different stuff, some of them already exists in the website, like loaders and plugins section, that information shouldn't be duplicate.

I will remove duplicate content

**Comment by montogeek** [comment]
> How we name page?

Resources I guess.

**Comment by evilebottnawi** [comment]
:+1: Where i can starts? I want to deprecate this repo as soon as possible to move all docs issue in one repo

**Comment by montogeek** [comment]
By creating a folder and an index.md file in `src/content/resources/index.md`
