### ISSUE TITLE
Feature request: compute [contenthash] after minification instead of before

### ISSUE THREAD

**Issue by thomasjm** [webpack/webpack.js.org#3230]
The documentation says that

> The `[contenthash]` substitution will add a unique hash based on the content of an asset. When the asset's content changes, `[contenthash]` will change as well.

However, the `[contenthash]` does **not** actually match the hash of the file, i.e. the result you would get if you ran `md5sum` or `sha256sum` on the file.

This [StackOverflow answer](https://stackoverflow.com/questions/50224845/why-is-the-contenthash-different-in-webpack) explains why: the `[contenthash]` is computed before minification.

I think it would make more sense to compute the `[contenthash]` *after* minification/any other post-processing steps, or at least provide an option to do so. 

This would have nice properties, such as allowing proxies to validate the integrity of a file just by comparing its hash to the filename.

**Comment by montogeek** [comment]
This is more a feature request to how webpack works than its documentation. cc @sokra

**Comment by thomasjm** [comment]
Oh whoops, I meant for this to go on the main webpack repo. Let me close and move it over there...
