### ISSUE TITLE
Dev Server documentation: transportMode option

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack.js.org#3239]
__Feature to document__

transportMode option: https://github.com/webpack/webpack-dev-server/pull/2116

__Author(s)__

Myself

/cc @evilebottnawi @hiroppy 

__Additional information__

This option allows the user to specify which socket transport mode to use for communication between the dev server and client. It is still an experimental option. Usage:

string:
```
transportMode: 'sockjs'
```
```
transportMode: 'ws'
```

object, with `server` (can be string mode/path or class), `client` (string mode/path) properties:

equivalent to `ws` mode above:
```
transportMode: {
  server: 'ws',
  client: 'ws'
}
```

custom implementation:
```
transportMode: {
  server: require('path/to/custom/server'), // can be path or class (class seen here)
  client: require.resolve('path/to/custom/client') // must be path
}
```

[x] I am willing to work on this issue and submit a pull request.

**Comment by jeffin143** [comment]
@montogeek , This is done and dusted, Let's close this :)
