### ISSUE TITLE
npm run build fails: Cannot find module '<...>/bundleStaticPage.js'

### ISSUE THREAD

**Issue by pastelsky** [webpack/webpack.js.org#324]
I'm trying to setup this repo locally, but I'm not able to start a development server.
After I run `npm run build`, the process exits with the following error:

```shell

> webpack.js.org@0.0.0 build /Users/sk/dev/webpack.js.org
> antwar -b && npm run sitemap && echo webpack.js.org > build/CNAME

2016.11.13.15.38.58 Start building

module.js:457
    throw err;
    ^

Error: Cannot find module '/Users/sk/dev/webpack.js.org/.antwar/build/bundleStaticPage.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /Users/sk/dev/webpack.js.org/node_modules/antwar/build/build.js:34:23
    at Compiler.<anonymous> (/Users/sk/dev/webpack.js.org/node_modules/webpack/lib/Compiler.js:194:14)
    at Compiler.emitRecords (/Users/sk/dev/webpack.js.org/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/Users/sk/dev/webpack.js.org/node_modules/webpack/lib/Compiler.js:187:11)
    at /Users/sk/dev/webpack.js.org/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/Users/sk/dev/webpack.js.org/node_modules/tapable/lib/Tapable.js:60:69)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
```

Node v7.1.0
Mac OS 10.10

**Comment by SpaceK33z** [comment]
I can't reproduce this with a fresh install. Could you try if `rm -rf .antwar` fixes it?

**Comment by bebraw** [comment]
Maybe it has something to do with Node 7. Any chance you could try against Node 6 to see if that makes any difference?

**Comment by pastelsky** [comment]
@bebraw I did try with 6.5.0 too. Same issue. Will try doing `rm -rf .antwar` as @SpaceK33z suggested.

**Comment by bebraw** [comment]
Ok. One fairly scary option is that the recent webpack 1.13.3 broke something. So removing `^` from the deps would be one direction. In any case being stricter about version ranges might not be a bad move.

**Comment by skipjack** [comment]
@pastelsky were you able to resolve this? Sounds similar to some issues we were having early on (see #54). I'm on Node 6.2.2 / Mac OS 10.12 and not seeing any issues.

**Comment by pastelsky** [comment]
I did a `rm -rf` and followed all steps again, and things are working fine now.
Not sure what was causing this error.

**Comment by bebraw** [comment]
Ok, feel free to re-open if you run into it again.
