### ISSUE TITLE
"main" package.json entry mysteriously shows up in guides

### ISSUE THREAD

**Issue by dmwyatt** [webpack/webpack.js.org#3253]
I'm too unfamiliar with webpack to know for sure that this is a docs error, but...maybe?

The [Development guide](https://webpack.js.org/guides/development/) continues on from the [Output Management](https://webpack.js.org/guides/output-management) guide.

The package.json in this guide has the entry `"main": "webpack.config.js",`, but I can't find anywhere in the preceding guides where that line is added. I do not know if this is important.

**Comment by EugeneHlushko** [comment]
Hi @dmwyatt 

It was unsynced indeed, although we dont diff-highlight the packages they weren't really correct, i've fixed it in #3258 

Thank you for reporting!
