### ISSUE TITLE
[Bug] Incorrect url and title in side navigation of guide

### ISSUE THREAD

**Issue by waxter013** [webpack/webpack.js.org#3287]
I found the bug on this page: https://webpack.js.org/guides/asset-management/. 
It looks like the bug occurs for the "Output Management" section and below.

The incorrect "title" and "href" attribute values are set for the sections of the side navigation. The values for the links and their containing list elements are set as the ones for the proceeding section. 

For example, the list and anchor elements under "Output Management" have the values for their respective "title" and "href" attributes set to the values that should be set on the list and anchor elements under the "Development" section. The "Output Management" heading links to the "Development section".

**Comment by waxter013** [comment]
![image](https://user-images.githubusercontent.com/7544238/64889556-3c02bf80-d633-11e9-8d95-4b2a83f645ca.png)

Here's a screenshot. Hovering over "Preparation" shows the title and href values for "Using source maps".

**Comment by superburrito** [comment]
I'll be happy to look into this @EugeneHlushko

**Comment by EugeneHlushko** [comment]
hi @waxter013 thanks for reporting, this was caught once before so i know what is the problem.

@superburrito i have already fixed this last time but seems the key prop was the real culprit, server side render has right links and then during hydration an index based key create confusion for react, i have linked the react issue the last time we fixed it.

**Comment by srishtiBajpai** [comment]
is this issue resolved?
