### ISSUE TITLE
Disable nyan cat test reporter for CI

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack.js.org#330]
As much as I like the nyan cat reporter, it is a living hell when you need to quickly find out which test broke in the CI.

See e.g. this [build failure at Travis](https://travis-ci.org/webpack/webpack.js.org/builds/175563417). It contains **4370 lines of nyan cat particles** my poor browser has to scroll through 🎱 .

So I'd suggest to either disable it for CI, or fully remove it.

**Comment by bebraw** [comment]
It could be conditional on Travis. So you get the default there (separate npm script).

**Comment by sokra** [comment]
I vote for full remove...

**Comment by bebraw** [comment]
Ok, PR welcome.
