### ISSUE TITLE
The TOC of guides documentation page contains wrong links

### ISSUE THREAD

**Issue by yushih** [webpack/webpack.js.org#3308]
# Bug report

**What is the current behavior?**
On the left side of this page, https://webpack.js.org/guides/public-path/ is a TOC, but every entry links to the page corresponding to the previous entry. Also, the wrong TOC entry is expanded.

**If the current behavior is a bug, please provide the steps to reproduce.**

Go to  https://webpack.js.org/guides/public-path/

**What is the expected behavior?**
1. In the TOC, "Public Path" is expanded 
2. The TOC should contain correct links

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by yushih** [comment]
Thank you @evilebottnawi for informing me. Thank you @sokra for transferring the issue. Apologies for raising it in the wrong place.

**Comment by montogeek** [comment]
Seems related to https://github.com/webpack/webpack.js.org/issues/3287#issuecomment-539100251

**Comment by EugeneHlushko** [comment]
Yes, @yushih can you try to reproduce on the preview build of #3287 here? 
https://deploy-preview-3288--webpackjsorg-netlify.netlify.com/

**Comment by jeffin143** [comment]
This is not reproducible anymore, Let's go ahead and close it 

Can you confirm it once @yushih ?
