### ISSUE TITLE
Basic Plugin Architecture plugin name not camelized

### ISSUE THREAD

**Issue by ShootPassSlam** [webpack/webpack.js.org#3321]
__Feature to document__

In [writing-a-plugin](https://github.com/webpack/webpack.js.org/blob/master/src/content/contribute/writing-a-plugin.md) under "Basic Plugin Architecture", the plugin name 'Hello World Plugin', is not camelized. The Plugin documentation states: 

> The first parameter of the tap method of the compiler hook should be a camelized version of the plugin name. It is advisable to use a constant for this so it can be reused in all hooks.

Should this plugin name be changed to 'HelloWorldPlugin'?

__Additional information__

Suggested change: Change the plugin name in [writing-a-plugin](https://github.com/webpack/webpack.js.org/blob/master/src/content/contribute/writing-a-plugin.md) under "Basic Plugin Architecture" from 'Hello World Plugin" to 'HelloWorldPlugin'

[X] I am willing to work on this issue and submit a pull request.

**Comment by anikethsaha** [comment]
> Should this plugin name be changed to 'HelloWorldPlugin'?

Yes 👍
