### ISSUE TITLE
p option not doing what is said in the docs

### ISSUE THREAD

**Issue by trogne** [webpack/webpack.js.org#3330]
If we read current docs, and `webpack --help` (version 4.41.2), we see this : 

"-p   shortcut for --optimize-minimize --define process.env.NODE_ENV="production"  "

This is false.

Running `webpack --optimize-minimize --define process.env.NODE_ENV="production"` have no effect.

In fact, `webpack -p` is equivalent to running `webpack --mode production`.  Now my code is minimized.

Seems that in recent version, webpack does not care about the NODE_ENV value. The "mode" takes over.

**Comment by EugeneHlushko** [comment]
Hi @trogne 
Thanks for reporting, are you willing to correct this in the docs or should we try to resource this change?

**Comment by trogne** [comment]
I prefer you try.  Thanks !     And I'm not 100% sure I'm right.

**Comment by EugeneHlushko** [comment]
Okay, we will pick this up
