### ISSUE TITLE
webpack.js.org redirects through non-encrypted connection

### ISSUE THREAD

**Issue by Munter** [webpack/webpack.js.org#3338]
When visiting a page on `https://webpack.js.org` in a subdirectory while omitting the trailing slash for the directory, an HTTP redirect chain happens that redirects the traffic through an unencrypted connection:

```
$ hyperlink https://webpack.js.org/concepts -i
Guessing --root from input files: https://webpack.js.org/concepts
TAP version 13
# Crawling internal assets
ok 1 load https://webpack.js.org/concepts
not ok 2 mixed-content https://webpack.js.org/concepts --> http://webpack.js.org/concepts/
  ---
    operator: mixed-content
    expected:
      "https://webpack.js.org/concepts --> https://webpack.js.org/concepts/"
    actual:
      "https://webpack.js.org/concepts --> http://webpack.js.org/concepts/"
    at: https://webpack.js.org/concepts (8:1)
  ...
ok 3 load http://webpack.js.org/concepts/
ok 4 load https://webpack.js.org/concepts/
```

The redirect from the URL with no trailing slash redirects to the same URL with a trailing slash, **but on HTTP instead of HTTPS**. From there another redirect sends the browser to the corresponding HTTPS URL.

Since `http://webpack.js.org` redirects to `https://webpack.js.org` I assume that the intention is to keep the visitors connection private at all times. Therefore I see it as a bug that the user gets redirected through a non-private connection for these redirects, with all the downsides to privacy and security that follow.

**Comment by Munter** [comment]
I just tested the same situation with a Github pages repository and I can't recreate the problem. Is it something with the combination of cloudflare and gh-pages?

**Comment by chenxsan** [comment]
This seems to be a bug in Github pages, here's the result of bootstrap site which is hosted on github pages as well:

![CleanShot 2021-07-18 at 12 16 59@2x](https://user-images.githubusercontent.com/1091472/126055503-d0e2595b-ffd7-4d18-ab65-fcca0ed82e25.png)

It's redirected to http version first.

**Comment by alexander-akait** [comment]
Fixed
