### ISSUE TITLE
Question about "plugins/#node-api" - When should this pattern be used?

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack/webpack.js.org#334]
Hi, I currently read the new docs and saw this pattern for the first time ([here](https://webpack.js.org/concepts/plugins/#node-api)):

```
  const webpack = require('webpack'); //to access webpack runtime
  const configuration = require('./webpack.config.js');

  let compiler = webpack(configuration);
  compiler.apply(new webpack.ProgressPlugin());

  compiler.run(function(err, stats) {
    // ...
  });
```

When should anyone ever want to use `compiler.apply(new webpack.ProgressPlugin());`? What are the advantages of this pattern opposite to just do something like `configuration.plugins.push(new webpack.ProgressPlugin()` before calling `webpack(configuration)`? That way you just use the normal `configuration` object and CLI API and Node API behave in the same way. Or am I wrong?

**Comment by sokra** [comment]
Ignore the code snippet. Use the configuration.

On the develop branch there is already a TODO https://github.com/webpack/webpack.js.org/blob/358a966b198618ff2c7d7bbc5b638688e539c378/content/concepts/plugins.md#node-api
