### ISSUE TITLE
webpack Dev Server Invalid Options

### ISSUE THREAD

**Issue by fengxinming** [webpack/webpack.js.org#3374]
incorrect:
```js
devServer: {
  clientLogLevel: 'debug'
}
```

```
webpack Dev Server Invalid Options

options.clientLogLevel should be {String} and equal to one of the allowed values

 [ 'trace', 'debug', 'info', 'warn', 'error', 'silent' ]

(https://webpack.js.org/configuration/dev-server/#devserver-clientloglevel)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

correct:
```js
devServer: {
  clientLogLevel: 'info'
}
```

**Comment by EugeneHlushko** [comment]
Reading the error, `'debug'` option does exist in schema error description, but doesn't pass the validation right?

**Comment by fengxinming** [comment]
@EugeneHlushko it appeared when I used `create-react-app`, you may try it.

**Comment by fengxinming** [comment]
@EugeneHlushko https://github.com/fengxinming/reappear-webpack-config-bug
Please check it

**Comment by EugeneHlushko** [comment]
@hiroppy can you please have a look, i dont see why this is happening

**Comment by rishabh3112** [comment]
@fengxinming this is working for me. Here is a minimal example for this https://github.com/rishabh3112/issues/tree/master/webpackdocs%233374

![image](https://user-images.githubusercontent.com/15812317/70815683-f1d8d800-1df3-11ea-84d6-43cc74db507d.png)

**Comment by fengxinming** [comment]
@rishabh3112 I see but I met this problem from `create-react-app` after ejecting webpack config, I feel like `webpack-dev-server`@latest has fixed this issues.

**Comment by rishabh3112** [comment]
@fengxinming  As you have now ejected the config, try updating the `webpack-dev-server`. It should solve the issue.

**Comment by EugeneHlushko** [comment]
Closing for now

**Comment by husnusetiawan** [comment]
i got same issue after split webpack.config.js with command `expo customize:web `..  i try downgrade webpack-config. and solve 
`yarn add webpack-config@0.12.23`
