### ISSUE TITLE
Invalid Syntax for Splash Page Snippets

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#339]
![image](https://cloud.githubusercontent.com/assets/3408176/20367038/60c9809e-ac13-11e6-9ab3-76198122e348.png)

I believe this needs to be a `default export` rather than regular export.

**Comment by NejcZdovc** [comment]
This issue is the same as #338

**Comment by sokra** [comment]
We should use `import { bar }` because this promotes named imports.

**Comment by SpaceK33z** [comment]
#338 fixed the export, and I fixed the invalid `:` in app.js with #387, so closing.
