### ISSUE TITLE
Common Errors Index

### ISSUE THREAD

**Issue by bishopZ** [webpack/webpack.js.org#34]
Searching for webpack errors on stackoverflow is more difficult than with other libraries because the error messages are often very opaque, and they use common words that are also used by other build systems and libraries.

I would love to write a document like "twenty possible reasons you might get the error 'Module could not be built'".

I envision the page as a list of common error message. Under each one we would catalogue the various reasons why that error might occur.

**Comment by pksjce** [comment]
Have you considered [webpack-validator](https://www.npmjs.com/package/webpack-validator)? It is supposed to statically analyse the config and show possible errors in the build.

**Comment by jhnns** [comment]
I really like this idea. Many confusing error messages and warnings can have simple answers, like:

- Module build failed
- Module not found
- Critical dependencies

However, we should also think about changing the actual error messages. If they can be improved, that's the first step.

**Comment by bishopZ** [comment]
I am on [Webpack Gitter Chat](https://gitter.im/webpack/webpack) right now. There are two people getting the error "Cannot find module." Both have exhausted all troubleshooting options. I have found multiple unanswered stack questions with the same error.

**Comment by skipjack** [comment]
This could be somewhat similar to glossary page @rouzbeh84 is currently working in #1223...

> However, we should also think about changing the actual error messages. If they can be improved, that's the first step.

I think this definitely key. One of the great things about react is the detailed error messages and links from the error message itself to the piece of documentation that relates to it. We could probably link to the index or other places in the docs from these error message.

@bishopZ if you're still interested in submitting a pr for this page I'd be happy to facilitate the process.

**Comment by skipjack** [comment]
I'm going to close as there are now multiple places where actual error messages are mentioned in the parts of the documentation where they apply. Seeing that we have a search bar, I think they are easily discoverable and, if we started linking to bits of the docs in the error messages themselves, I think we'd be in a pretty good place. If people still feel strongly about this and have the time to tackle it I'd be happy to re-open and facilitate however I can.
