### ISSUE TITLE
Plugin name typo?

### ISSUE THREAD

**Issue by MattGoldwater** [webpack/webpack.js.org#3410]
__Feature to document__

Webpack 5 migration guide https://github.com/webpack/webpack.js.org/pull/3361 

__Author(s)__

@EugeneHlushko @montogeek 

__Additional information__

From the guide: "If you are using Yarn's PnP and the pnp-resolver-plugin, we have good news: it is supported by default now. You have to remove it from the configuration."

I can't find the pnp-resolver-plugin. Do you mean to say the [pnp-webpack-plugin](https://github.com/arcanis/pnp-webpack-plugin)?

 #[X] I am willing to work on this issue and submit a pull request.

**Comment by EugeneHlushko** [comment]
Yes when i look at it i think you are right :) Please file a pr
