### ISSUE TITLE
Mismatch information in optimization chapter

### ISSUE THREAD

**Issue by rifler** [webpack/webpack.js.org#3420]
__Feature to document__

https://webpack.js.org/configuration/optimization/#optimizationmoduleids
Doc says that there can be value "deterministic", but webpack@4.41.4 says
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].optimization.moduleIds should be one of these:
   "natural" | "named" | "hashed" | "size" | "total-size" | false
```

Also doc says `To override the default behaviour set optimization.moduleIds to false and use the webpack.ids.DeterministicModuleIdsPlugin`, but
```
TypeError: Cannot read property 'DeterministicModuleIdsPlugin' of undefined
```

__Author(s)__

__Additional information__

to verify webpack version:
```
> cat ./node_modules/webpack/package.json  | grep version
"version": "4.41.4",
```

[ ] I am willing to work on this issue and submit a pull request.

**Comment by snitin315** [comment]
Looking into it.

**Comment by snitin315** [comment]
@rifler this value is implemented for webpack@5 [refer comment].(https://github.com/webpack/webpack/issues/10614#issuecomment-604485934)

I will update the docs accordingly
