### ISSUE TITLE
Error can't commit, failing lint tasks

### ISSUE THREAD

**Issue by niravasher** [webpack/webpack.js.org#3438]
I cannot commit my code, it constantly fails lint tests.
Here is my console
![Screenshot from 2020-01-01 16-08-58](https://user-images.githubusercontent.com/32176296/71640509-7d39e080-2cb1-11ea-835c-f77a8920ae1a.png)
![Screenshot from 2020-01-01 16-09-24](https://user-images.githubusercontent.com/32176296/71640512-86c34880-2cb1-11ea-91cb-bcb90bb4b69d.png)

To solve this I ran the command `npm install --save-dev lint-staged@beta`
I could then successfully commit but this changes package.json file which results in travis CI test fail as in my PR https://github.com/webpack/webpack.js.org/pull/3436 compilation failure on running `npm start`. What should I do?

**Comment by montogeek** [comment]
Please run `git commit -a -m "your message" --no-verify`

**Comment by niravasher** [comment]
Works, thanks @montogeek
