### ISSUE TITLE
Make voting page accessible

### ISSUE THREAD

**Issue by sokra** [webpack/webpack.js.org#3444]
Currently the voting page (https://webpack.js.org/vote/) is unusable with out a mouse. This makes is unusable for some people.

The arrows to vote for the items should be usable with only a keyboard.

**Comment by anshumanv** [comment]
@montogeek have you started working on this? I'd like to pick this up if you haven't started.

**Comment by montogeek** [comment]
@anshumanv Feel free to do it :)

**Comment by anshumanv** [comment]
Sorry for the delay, PR up at - https://github.com/webpack-contrib/voting-app/pull/19

Have just included the vote keys in tab order.

**Comment by anshumanv** [comment]
This has been fixed and can be closed now, @EugeneHlushko @montogeek
