### ISSUE TITLE
Voting page: Make it clear that items are locked

### ISSUE THREAD

**Issue by sokra** [webpack/webpack.js.org#3446]
The `PLACE YOUR VOTE` text on the voting page (https://webpack.js.org/vote/) is a little bit confusing for items that can't be voted on.

Maybe replace the `PLACE YOUR VOTE` text, with `VOTING ENDED` for locked items instead.

**Comment by anshumanv** [comment]
On it.

**Comment by anshumanv** [comment]
PR up - https://github.com/webpack-contrib/voting-app/pull/18

**Comment by jeffin143** [comment]
@montogeek Let's close this since it is done
