### ISSUE TITLE
Document `options.devServer.features`

### ISSUE THREAD

**Issue by Airkro** [webpack/webpack.js.org#3457]
- Operating System: Windows 10
- Node Version: 12.x
- NPM Version: 6.x
- webpack Version: 4.x
- webpack-dev-server Version: 3.10.x
- Browser: Chrome

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

https://github.com/webpack/webpack-dev-server/blob/master/lib/options.json#L80

### Expected Behavior
Document `options.devServer.features` , add `enum` and code example.

### Actual Behavior

Can't find `options.devServer.features` in <https://webpack.js.org/configuration/dev-server/>

**Comment by EugeneHlushko** [comment]
@Airkro not sure i understand the issue, can you provide more details?

**Comment by anikethsaha** [comment]
https://github.com/webpack/webpack-dev-server/blob/master/lib/options.json#L80

seems like its a pending schema. I guess it would be more accurate to submit the issue in dev-server repo.

**Comment by evilebottnawi** [comment]
No need, that option was removed in next version, also it is broken in many cases
