### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Legends** [webpack/webpack.js.org#3465]
__Feature to document__
[Writing a loader](https://webpack.js.org/contribute/writing-a-loader/)

What is the minimum supported version of node we have to support when writing a loader?
I have node v12.13.0 installed.

I can't make the example work following the babel setup in your example:
```
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "node": "4"
        }
      }
    ]
  ]
}

```
I get :
ReferenceError: regeneratorRuntime is not defined
 

What else has to be setup/installed here?

Package.json:
```
{
  "name": "loader-test",
  "version": "1.0.0", 
  "license": "MIT",
  "scripts": {
    "test": "jest"
  },
  "devDependencies": {
    "babel": "^6.23.0",
    "babel-jest": "^24.9.0",
    "babel-preset-env": "^1.7.0",
    "jest": "^24.9.0",
    "loader-utils": "^1.2.3",
    "memory-fs": "^0.5.0",
    "schema-utils": "^2.6.1",
    "webpack": "^4.41.5",
    "webpack-cli": "^3.3.10"
  },
  "dependencies": {}
}
```
@michael-ciniawsky

**Comment by Legends** [comment]
I made it compile using this setting in package.json and converting all import to use `require`

```
 "jest": {
    "verbose": true,
    "testEnvironment": "node"  // <---
  },
```

But what is the setup for using ES6 syntax?

**Comment by anikethsaha** [comment]
Ref any official loader like https://github.com/webpack-contrib/style-loader
They are written in es6

Also better use https://github.com/webpack-contrib/webpack-defaults to setup your webpack loader/plugin project

**Comment by Legends** [comment]
Thanks for the recommendation! 
But adding the `webpack-defaults` does not insert a script command in` package.json`.

> After install a defaults NPM script will be written to the local package.json. To sync a project with webpack-defaults, simply run:
> 
>` npm run defaults`

**Comment by anikethsaha** [comment]
I usually do 

- npm init -y
- npm i --save-dev webpack-default
-  add the webpack default script in the package.json mentioned in the webpack-default docs
- npm run default.

This pretty much works for me. Then I do my own changes on top of that.

**Comment by anikethsaha** [comment]
And if you want to use es6, use `@babel/preset-env` , I saw your package.json and those packages are outdated.
Please update them as well.

**Comment by Legends** [comment]
> add the webpack default script in the package.json mentioned in the webpack-default docs

There is only the readme page, I cannot find any docs?!

So what are the requirements for installing `webpack-default`, nothing is mentioned in the readme, so I assume none.

I will try with a new blank project from scratch.

**Comment by Legends** [comment]
It doesn't work...

**Comment by anikethsaha** [comment]
> It doesn't work...

What doesn't work?

> There is only the readme page, I cannot find any docs?!

I meant readme

**Comment by anikethsaha** [comment]
btw, the package name is  `@webpack-contrib/defaults`.

**Comment by Legends** [comment]
The package only installs, no `default` command is created under scripts in package.json.
The package seems not to create this entry on windows.

I know, there are three different packages

1. webpack-contrib/default
2. webpack-contrib/defaults
3. @webpack-contrib/defaults  <-- this is the correct one

As a workaround I execute it myself:

> In order to make it work on windows 10:
> 
> create and execute the following index.js file:
> 
> ```
> const run = require("@webpack-contrib/defaults/dist");
> run();
> ```

**Comment by anikethsaha** [comment]
the default script is this one

`default : webpack-defaults`

**Comment by Legends** [comment]
One question:

Should there also be a `helpers.js` file generated or should this only be a suggestion:

![image](https://user-images.githubusercontent.com/966368/71933699-12057800-31a3-11ea-968c-8d48d3ce9429.png)


There is no helpers file generated.
