### ISSUE TITLE
docs(watch): watchOptions.ignored documentation is misleading

### ISSUE THREAD

**Issue by logandavis** [webpack/webpack.js.org#3471]
__Feature to document__

watchOptions.ignored: https://webpack.js.org/configuration/watch/#watchoptionsignored

__Author(s)__

From the contributors list in watch.md:
@sokra @skipjack @SpaceK33z @EugeneHlushko @byzyk @spicalous 

__Additional information__

The docs on watchOptions.ignored say this:

> For some systems, watching many file systems can result in a lot of CPU or memory usage. It is possible to exclude a huge folder like node_modules:
```
module.exports = {
  //...
  watchOptions: {
    ignored: /node_modules/
  }
};
```
> It is also possible to have and use multiple anymatch patterns:
```
module.exports = {
  //...
  watchOptions: {
    ignored: ['files/**/*.js', 'node_modules']
  }
};
```
The second array-of-strings entry is very misleading, IMO. From the inclusion of 'node_modules', and the comparison with the RegExp example, I would expect the second configuration to ignore node_modules and all subdirectories, just like the RegExp example does. 

However, from the [anymatch documentation](https://github.com/micromatch/anymatch):
```
anymatch('node_modules', 'node_modules/somelib/index.js'); // false
anymatch('node_modules/**', 'node_modules/somelib/index.js'); // true
```
We can see that the array-of-string example in the watchOptions.ignored documentation will watch the node_modules directory itself, but no children. This isn't something that users want to do very often, practically speaking. 

To avoid confusion, the documentation should be updated to read:
> It is also possible to have and use multiple anymatch patterns:
```
module.exports = {
  //...
  watchOptions: {
    ignored: ['files/**/*.js', 'node_modules/**']
  }
};
```

Thanks for your efforts!

[x] I am willing to work on this issue and submit a pull request.

**Comment by montogeek** [comment]
Feel free to send a PR.

**Comment by vnues** [comment]
must be use regex
