### ISSUE TITLE
Documentation Fix

### ISSUE THREAD

**Issue by maicoqb** [webpack/webpack.js.org#3479]
Hi everybody,

I just found a mistake on documentation, but I don't know how fix it.

Into [Ouptut section](https://webpack.js.org/configuration/output/#outputmodule) of documentation, there is a reference to `output.libraryTarget` as `'module'`, but seems like `'module'` is not a valid option to `output.libraryTarget`.
I try to fix it, but then I realize that I don't know what value I should use there.

https://github.com/webpack/webpack.js.org/blob/master/src/content/configuration/output.md#outputmodule

If for some reason `'module'` is a valid type if we are using `experiments.outputModule`, please let'me know.

Thanks.

**Comment by anikethsaha** [comment]
> Into Ouptut section of documentation, there is a reference to output.libraryTarget as 'module', but seems like 'module' is not a valid option to output.libraryTarget.

I think this is a correct value for `output.libraryTarget` option .

[`refer-this`](https://github.com/webpack/webpack/blob/40074d308f784b0a736177b0aa5582a53e733345/lib/WebpackOptionsDefaulter.js#L274-L276)

**Comment by maicoqb** [comment]
Thansk @anikethsaha
