### ISSUE TITLE
Add how to write links to Writers guide

### ISSUE THREAD

**Issue by montogeek** [webpack/webpack.js.org#3480]
We don't have any guides regarding how to write links, specially internal links in our internal guide, new contributors always assume by default that an absolute URL (https://webpack.js.org/concepts/mode/) should be used, but we use relative links to internal URLs (/concepts/mode/).

Last example: https://github.com/webpack/webpack.js.org/pull/3478

**Comment by EugeneHlushko** [comment]
Great stuff, looking forward

**Comment by jeffin143** [comment]
@montogeek What do you think would be the correct place to add that ?
