### ISSUE TITLE
Webpack includes app unrelated modules to build

### ISSUE THREAD

**Issue by Legends** [webpack/webpack.js.org#3488]
Can we add information to the docs:
Why does webpack include the following packages (target:'web').

Are they needed by the runtime? So this would be good to know.

![image](https://user-images.githubusercontent.com/966368/72472634-3c7bb480-37e5-11ea-8375-e15e17c72d68.png)

**Comment by anikethsaha** [comment]
in which section you are thinking to add this ?

**Comment by Legends** [comment]
Yeah, I had the same thought. But a first thought would be at the end of section `Concepts-->Output`  inside of an light-blue colored attention/info box...
I guess many ask themselves what these modules are for.

**Comment by evilebottnawi** [comment]
You are use node modules in browsers (`require('process')` and etc), maybe we can add it here https://webpack.js.org/configuration/node/, but we remove polyfilling for node modules in webpack@5

**Comment by Legends** [comment]
I don't use any `node` modules in my app, but I use `CommonJS `syntax only in my html template files, I don't know if I can use `import` here in this specific case?

`<link rel="apple-touch-icon" href="${require('../icons/icon.png').default}">`

 Is it possible to use `import` instead of the `require` above?

Aaah, I can set `  node: false,` then I don't have the polyfills for `node `anymore. Thanks @evilebottnawi.

Honestly, as the polyfills are in my output bundle, i would intuitively first look under `Output` or `Concepts-->Output`, but yes it belongs to the [node section](https://webpack.js.org/configuration/node/)...hmmm.

**Comment by Legends** [comment]
@evilebottnawi 
Closing, cause you mentioned 

> but we remove polyfilling for node modules in webpack@5

It's nice to have information..
