### ISSUE TITLE
Develop - Webpack Loader API

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#35]
(Stub probably needed.)

**Story**
As a webpack user and developer, I would like to understand how to create & implement a custom loader using the webpack loader API.

**Scenario**
Given I visit the page: 
- A. I'm presented with clear indication this document contains info on the webpack loader API.
  - What is a loader? (Via link or short description)
  - What arguments can a loader be provide?
  - What is `this`? How does it relate to the loader?
  - How and Why to add support for source mappings.
  - Best practices on writing good loaders (provide examples simple to complex)
    - Writing unit tests for loaders
      - Provide 'boilerplate test suite' for developers that has CI, Coverage, and testing setup.
    - Setting up a loader for publishing on NPM.
  - Loader changes from 1.x to 2.x how to migrate.
- B. I'm provided with link and reference to the webpack Loader 'overview page'

**Comment by TheLarkInn** [comment]
@mxstbr @bebraw thoughts?

**Comment by bebraw** [comment]
Yeah, definitely needed. I added a [site section for API](https://github.com/webpack/webpack.io/tree/antwar/content/api) and pushed bits there.

**Comment by mxstbr** [comment]
Sounds good though I'm not sure the migration should be that prominent, not that many people are going to look for it.

**Comment by bebraw** [comment]
My branch has a separate "how to" for migration so maybe it's best handled there.

**Comment by jackfranklin** [comment]
@TheLarkInn as discussed I'm happy to take a stab at this as a good learning exercise for myself.

My plan of attack is something like:

1. Read through https://webpack.github.io/docs/how-to-write-a-loader.html and try to write my own basic loader
2. Refer to other loaders and dig through them
3. Start documenting the process
4. Push up to GitHub for your review once I have a rough outline.

How does that sound?

**Comment by TheLarkInn** [comment]
Love it!!!

**Comment by bebraw** [comment]
@jackfranklin Any thoughts on this? There's quite a bit of information on loaders now so please review.

**Comment by jackfranklin** [comment]
Hey sorry, as you can tell I didn't make much progress on this. I'd be happy to try to but I don't know when I'll get there. Happy to let someone else have a stab in the mean time. Sorry :

**Comment by DanielaValero** [comment]
Hello guys, I am a new contributor to karma-webpack. The team decided to do a rewrite of the project. I have some time in the upcoming days, and I will be starting to setup some stuff. I did not write a loader in the past, so my starting point will be for sure reading the existing documentation, and setup some skeleton in karma-webpack.

I will check the current documentation for loaders here, plus the one here: https://webpack.github.io/docs/how-to-write-a-loader.html, I will by default review them and provide some updates and or feedback on it. As a new comer, I am the perfect guinea pig. :)

**Comment by SpaceK33z** [comment]
sounds great @DanielaValero!

**Comment by bebraw** [comment]
The old content has been ported to https://webpack.js.org/api/loaders/.

**Comment by skipjack** [comment]
Hmmm was this resolved between the [How to write a loader?](https://webpack.js.org/development/how-to-write-a-loader/) and [Loader API](https://webpack.js.org/api/loaders/) docs?

**Comment by bebraw** [comment]
Yeah, time to close. There are likely some individual topics missing but it's better to open separate issues for those. @DanielaValero, @TheLarkInn please review and set up issues.
