### ISSUE TITLE
Code blocks on homepage

### ISSUE THREAD

**Issue by mxstbr** [webpack/webpack.js.org#350]
The four code blocks on the homepage should be two in one row, instead of wasting a bunch of space:

<img width="1048" alt="screen shot 2016-11-17 at 18 03 09" src="https://cloud.githubusercontent.com/assets/7525670/20396846/3a93f4d0-acf0-11e6-9316-2590a4a96245.png">

Those code blocks could easily fit next to each other instead of having a massive amount of horizontal space, like this:

| Write your code | |
| ------------- | ------------- |
|  import bar from 'foo';       | export function bar()           |
| **Bundle with webpack** | |
| module.exports = {}      | &lt;html&gt; |

**Comment by skipjack** [comment]
Good point, you'd be welcome to PR this if you're interested. Maybe the best way to go would be a flex box and have them at 50% on larger screens and 100% on mobile?

**Comment by mxstbr** [comment]
I tried to do it, but the Markdown + HTML handling didn't work as I expected and I don't have time to dig in further. For somebody who's used to this setup, this should be a five minute operation!

**Comment by skipjack** [comment]
Ok, I can pick this up.
