### ISSUE TITLE
(docs): externals array still referenced

### ISSUE THREAD

**Issue by leibowitz** [webpack/webpack.js.org#3503]
This PR https://github.com/webpack/webpack.js.org/pull/2100 didn't remove all references to array in externals.
https://github.com/webpack/webpack.js.org/blob/2eb1c0e3c355a52a10cc54dba2dab30958fb7758/src/content/configuration/externals.md#array
https://webpack.js.org/configuration/externals/#array
https://github.com/webpack/webpack.js.org/blob/2eb1c0e3c355a52a10cc54dba2dab30958fb7758/src/content/configuration/externals.md#combining-syntaxes
https://webpack.js.org/configuration/externals/#combining-syntaxes
Which is confusing to users, as it seems array is still supported (but doesn't seem to be)

**Comment by snitin315** [comment]
Looking into it.
