### ISSUE TITLE
Add background info on NODE_ENV to "how-to" pages?

### ISSUE THREAD

**Issue by markerikson** [webpack/webpack.js.org#353]
I've read a fair number of articles on Webpack build optimization.  They frequently mention that "`process.env.NODE_ENV` should be set to `"production"`, and you should use DefinePlugin", but rarely mention how those two pieces fit together.

I recently wrote a blog post that was published on Packt, which tries to clarify what `NODE_ENV` is, how it's used in a build process, and why it is important for production:  https://www.packtpub.com/books/content/building-better-bundles-why-processenvnodeenv-matters-optimized-builds .  I thought it might be useful to adapt some of that info for the Webpack docs.

Glancing through the new docs site, it seems like this might be the most relevant place to add in some of that info:  https://webpack.js.org/guides/production-build/ .

**Comment by SpaceK33z** [comment]
Great, a PR is definitely welcome!

**Comment by markerikson** [comment]
Afraid I don't have time to do a docs-specific writeup myself atm, but definitely feel free to use that article as a starting point for fitting the info into the docs.

**Comment by simon04** [comment]
https://webpack.js.org/guides/production-build/ has been updated in #584. Also related and added in the meanwhile: https://webpack.js.org/configuration/environment/
