### ISSUE TITLE
Documentation: Add keyboard shortcut to documentation to toggle sidebar navigation

### ISSUE THREAD

**Issue by plug-n-play** [webpack/webpack.js.org#3538]
## Feature request
In the official documentation, it would be great to add keyboard shortcut which toggles sidebar navigation and helps people like me who get distracted easily from following existing view:
![image](https://user-images.githubusercontent.com/6245927/74553090-9b675180-4f7c-11ea-9441-ecb67b2523fb.png)

to this:

![image](https://user-images.githubusercontent.com/6245927/74553150-bafe7a00-4f7c-11ea-97c1-d43567acf10a.png)

using:
document.querySelector('.sponsors').style.display = 'none'
and
document.querySelector('.sidebar.site__sidebar').style.display = 'none'

**What is the expected behavior?**
Suggested screen-shot added above

**What is motivation or use case for adding/changing the behavior?**
To help people which get distracted easily

**How should this be implemented in your opinion?**
Add a keyboard shortcut in docs to listen to say `Alt+Z` to toggle left navigation

**Are you willing to work on this yourself?**
yes, given some helping hand on my first PR for Webpack

**Comment by anikethsaha** [comment]
did you zoom-out or its the default behavior of showing that sponsor banner.?

**Comment by plug-n-play** [comment]
I did not zoom out, but used only a portion of the screen as screen capture. Here is another full screen capture for comparison:

![image](https://user-images.githubusercontent.com/6245927/74585347-a1534600-5001-11ea-9b86-d5c1cc419119.png)

**Comment by anikethsaha** [comment]
> I did not zoom out, but used only a portion of the screen as screen capture. Here is another full screen capture for comparison:
> 
> ![image](https://user-images.githubusercontent.com/6245927/74585347-a1534600-5001-11ea-9b86-d5c1cc419119.png)

I think the sponsor thing should not be there. !!!!!

even toggling sidebar seems fine enhancement !!

cc @montogeek

**Comment by anshumanv** [comment]
> I think the sponsor thing should not be there. !!!!!

I don't think removing the sponsors is a good idea. Unsure about removing sidebar too.

**Comment by anikethsaha** [comment]
> > I think the sponsor thing should not be there. !!!!!
> 
> I don't think removing the sponsors is a good idea. Unsure about removing sidebar too.

yeah...even I thought about the sponsor and it seems it should be there
and about the toggling, I guess the default will be it will be visible but we can add a toggle.
maybe...even the current is good....

**Comment by plug-n-play** [comment]
The default behaviour can stay as it is. Just a feature enhancement to make the docs more accessible to read. A keyboard shortcut which toggles between existing view and the Medium like, distraction free view.

**Comment by mitchell-frost** [comment]
I am new to open source and github. Can I work on this?

**Comment by montogeek** [comment]
@mitchell-frost Feel free :)

**Comment by chenxsan** [comment]
Closing this as I don't think it's a good idea to hide sidebar navigation.
