### ISSUE TITLE
Links don't scroll to correct position

### ISSUE THREAD

**Issue by SimonSiefke** [webpack/webpack.js.org#3540]
When clicking the anchor links in the sidebar, it doesn't scroll to the correct position

## Current Behaviour 
It scrolls past the heading and past the description (actually it doesn't but it looks like it because the fixed topbar is covering the heading and the description).
![webpack](https://user-images.githubusercontent.com/23744935/74595783-22ccc780-5046-11ea-8551-c3f6900e9254.png)

## Expected Behaviour
It scrolls to the section so that the heading and the description is visible.
![expected](https://user-images.githubusercontent.com/23744935/74595806-5c053780-5046-11ea-9aef-c670f12ff25c.png)

## Possible Solution
According to [Stackoverflow](https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header) a possible solution would be to apply something like `padding-top: 100px; margin-top: -100px;` to every heading. I have found that `100px` works well with a normal topbar and `200px` with a topbar with annoucement.

**Comment by anshumanv** [comment]
This is surely an issue, great catch!

**Comment by anikethsaha** [comment]
> According to Stackoverflow a possible solution would be to apply something like padding-top: 100px; margin-top: -100px;

This style is working as expected. I guess you can submit a PR with this fix. But be sure it is not breaking any other styles !!!
