### ISSUE TITLE
Adding a link to loader template

### ISSUE THREAD

**Issue by gavinhenderson** [webpack/webpack.js.org#3548]
I recently followed the brilliant docs on how to write a loader to create my own loader:
https://webpack.js.org/contribute/writing-a-loader/

I was wondering if I was to create a [GitHub template](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) based on the guide if it would be acceptable to add a link to it within the docs for others to use?

If it is acceptable happy to submit the PR adding the link

**Comment by anikethsaha** [comment]
I guess [this](https://github.com/webpack-contrib/webpack-defaults) might be useful for you 

👍

**Comment by gavinhenderson** [comment]
Yup, even has a link to it in the docs. Thanks 👍
