### ISSUE TITLE
Getting started should pin webpack to a version

### ISSUE THREAD

**Issue by ScriptDevil** [webpack/webpack.js.org#3572]
https://webpack.js.org/guides/getting-started/ (which tracks v5-beta currently) and https://v4.webpack.js.org/guides/getting-started/ have identical installation instructions and so only one of them could be correct. My suggestion would be to either pin versions of webpack in the documentation or bring to the user's attention that the version in the doc may not match the current NPM release of webpack.

Currently - it looks like this
```
mkdir webpack-demo
cd webpack-demo
npm init -y
npm install webpack webpack-cli --save-dev
```

As someone who is getting started with webpack, I followed the instructions in https://webpack.js.org/guides/getting-started/ step-by-step and started hitting issues due to incompatibilities between v5 and v4 since npm installs v4 by default as of today since v5 is still in beta.

Soon, when v5 is in production, the v4 guides will bitrot and for someone following it verbatim.

**Comment by anikethsaha** [comment]
It should be fixed in `v4` docs with this content

```
mkdir webpack-demo
cd webpack-demo
npm init -y
npm install webpack@4.x  webpack-cli@3.x --save-dev
```

cc @EugeneHlushko @montogeek

**Comment by EugeneHlushko** [comment]
@anikethsaha yeah sounds good, you can submit a PR to `webpack-4` branch

**Comment by anikethsaha** [comment]
@anikethsaha is [`webpack-4`](https://github.com/webpack/webpack.js.org/tree/webpack-4) branch source of v4 ?

**Comment by anikethsaha** [comment]
@ScriptDevil do you want to submit the fix at `webpack-4` branch or you want me/others to submit ? as it is reported by you.

> @ScriptDevil do you want to submit the fix at `webpack-4` branch 

We can help you with submitting the PR if you need it.

Thanks,  👍

**Comment by chenxsan** [comment]
closed via https://github.com/webpack/webpack.js.org/pull/3577.
