### ISSUE TITLE
bug: broken link for node.global source  on /configuration/node/#nodeglobal

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack.js.org#3585]
The link for the souce is broken here [https://webpack.js.org/configuration/node/#nodeglobal](https://webpack.js.org/configuration/node/#nodeglobal)

![Screenshot from 2020-02-26 07-41-29](https://user-images.githubusercontent.com/46647141/75305281-b040c080-586b-11ea-8199-411f6bd85f49.png)

Steps to reproduce --

1. Visit [https://webpack.js.org/configuration/node/#nodeglobal](https://webpack.js.org/configuration/node/#nodeglobal)

2. scroll to node.global section.
3. Click on see the source.
4. See Error

![Screenshot from 2020-02-26 07-41-36](https://user-images.githubusercontent.com/46647141/75305358-df573200-586b-11ea-9085-1d534a73872f.png)

**I would like to work on this issue**

**Comment by montogeek** [comment]
It works for me. Maybe cache?

**Comment by snitin315** [comment]
[https://github.com/webpack/webpack/blob/master/buildin/global.js](https://github.com/webpack/webpack/blob/master/buildin/global.js)

**Comment by snitin315** [comment]
> It works for me. Maybe cache?

Can you share screenshot?

**Comment by montogeek** [comment]
I see it now, feel free to send a PR.

**Comment by snitin315** [comment]
@montogeek can you share the correct link?

**Comment by montogeek** [comment]
Should be this one https://nodejs.org/api/globals.html
