### ISSUE TITLE
Code Splitting: multiple entry points object schema not supported

### ISSUE THREAD

**Issue by tpetillot** [webpack/webpack.js.org#3592]
# Bug report

**What is the current behavior?**
> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
>  - configuration.entry should be one of these:
>    function | object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string]

**If the current behavior is a bug, please provide the steps to reproduce.**
- Setup multiple entry points with object schema
`object = { import string | [string], dependOn string | [string], filename string }`
- Run webpack command

**What is the expected behavior?**
Support [documented schema](https://webpack.js.org/guides/code-splitting/).

**Other relevant information:**
Webpack version:  4.41.6
Operating System: MacOS Mojave, Ubuntu 1.18 (Linux 4.15)

**Comment by Mistyyyy** [comment]
![image](https://user-images.githubusercontent.com/37856353/75639058-e914d700-5c69-11ea-893a-d996c9d4fcf0.png)

I thought the version in the tag should be corrected.

**Comment by EugeneHlushko** [comment]
Hi @smelukov pushed a fix for this and unassigned you as there was no PR still
