### ISSUE TITLE
"https://www.webpackjs.com/"  this website can't navigate to the English official website.

### ISSUE THREAD

**Issue by QKflame** [webpack/webpack.js.org#3619]
As the title, it did't work when I clicked the navigate button to the English website。

**Comment by snitin315** [comment]
Actually that's because of the incorrect url , `https://www.webpackjs.com/https://webpack.js.org//`

This needs to be replaced with `https://weboack.js.org/`

I will work on this one

**Comment by snitin315** [comment]
Can anyone tell me where is the code for `https://www.webpackjs.com/` ?

**Comment by EugeneHlushko** [comment]
I am not sure, could be this one? https://github.com/webpack-china/webpack-china-site

**Comment by montogeek** [comment]
It is

**Comment by chenxsan** [comment]
They host the [Chinese version](https://github.com/docschina/webpack.js.org) on https://webpack.docschina.org/, not `webpackjs.com`.

**Comment by momocow** [comment]
FYI, clicking the **edit this page (编辑此页)** button leads me to the https://github.com/docschina/webpack.js.org.

Maybe it'd be better to open an issue there.
