### ISSUE TITLE
Invisible search results

### ISSUE THREAD

**Issue by chenxsan** [webpack/webpack.js.org#3686]
Search results have some unexpected invisible texts:

![image](https://user-images.githubusercontent.com/1091472/79229146-212c4e00-7e95-11ea-93d7-9305a579e778.png)

I can submit a pull request after https://github.com/webpack/webpack.js.org/pull/3682 is merged, or maybe you want me to push fix into that pull request?

**Comment by montogeek** [comment]
Please create a new PR.
