### ISSUE TITLE
"Development" guide maybe broken?

### ISSUE THREAD

**Issue by LowArmour** [webpack/webpack.js.org#3698]
In the "Development" guide: the watch mode (i.e., webpack --watch), having the guide provided plugins (CleanWebpackPlugin and HtmlWebpackPlugin) leads to the deletion of the generated index.html when correcting the error in print.js.

The problem is in "Watch Mode" section of the "Development guide", where it says: "The only downside is that you have to refresh your browser in order to see the changes" -> Well there is nothing to refresh after the incremental build (CleanWebpackPlugin deletes HtmlWebpackPlugin -generated index.html).

I have searched and tried to solve the issue for couple of hours, but to no avail. It is really off-putting for a beginner like me trying to go through each line of the guides, learning the marvelous complexities of webpack, to be face-palmed by such issues.

My webpack config (almost if not identical to the one provided in the guide):
`
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

module.exports = {
  mode: 'development',
  entry: {
    app: './src/index.js',
    print: './src/print.js',
  },
  devtool: 'inline-source-map',
  plugins: [
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      title: 'Development'
    }),
  ],
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },
}
`

my package.json (similar if not identical to the guide):
`
{
  "name": "test-web-app",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack",
    "watch": "webpack --watch"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^3.5.2",
    "file-loader": "^6.0.0",
    "html-webpack-plugin": "^4.2.0",
    "style-loader": "^1.1.4",
    "webpack": "^4.42.1",
    "webpack-cli": "^3.3.11"
  },
  "dependencies": {
    "lodash": "^4.17.15"
  }
}
`

**Comment by EugeneHlushko** [comment]
Hi @LowArmour 
I think i know whats wrong, can you try adding this option to your webpack.config.js when passing a new instance of CleanWebpackPlugin: `cleanAfterEveryBuildPatterns` like so:
```js
new CleanWebpackPlugin({ cleanAfterEveryBuildPatterns: [] }),
```
