### ISSUE TITLE
API - Plugins

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#37]
[Stub](https://github.com/webpack/webpack.io/blob/develop/content/api/plugins.md).

Overview Page: Give Overview of what this section will cover. 
- Explain Schema and Type notation used in guide.
- Tapable
- Compiler instance
- Compilation instance
- Module
  - Module vs ModuleFactory
  - NormalModuleFactory
  - ContextModuleFactory
- NMF instance
- CMF instance
- Maintemplate instance
- Parser instance
- Resolver instance
- Recommended Reading
- Implementing Custom Plugin Hooks (like html-webpack-plugin)

WIP

**Comment by TheLarkInn** [comment]
Can use this to link to individual issues I will create for each of these bullet points.

**Comment by mxstbr** [comment]
> Implementing Custom Plugin Hooks (like html-webpack-plugin)

We use those in Carte Blanche too (@jantimon helped us build it, so that's why :grin:) so I can document that!

**Comment by jantimon** [comment]
Well webpack is very modular - the custom plugin hooks are exactly the same as the "standard" hooks.

**Comment by TheLarkInn** [comment]
@jantimon Exactly. I think one we start educating developers about Tapabale etc. Plugins and how they work will be way easier.

**Comment by jantimon** [comment]
Tapable is very simple - you can just read the source it contains only very small helper functions.

It is similar to event emitter however it allows plugins to queue up and modify the given value.
Unfortunately it doesn't allow to listen to a single event or unbind events.

**Comment by TheLarkInn** [comment]
@jantimon would you be willing to tackle the Tapable page? Like explain how it works, even though it's pretty simple code we want to explain it to somone in a clear and consice way. I was thinking about writing the schema/typescript definition for it as well.

**Comment by jantimon** [comment]
I am on vacation for the next 3 weeks but maybe afterwards.

**Comment by skipjack** [comment]
Closing for the same reason mentioned in #36. Let's open more targeted issues/prs if there's still work left to do.
