### ISSUE TITLE
Development guide has broken 'source map' introduction link

### ISSUE THREAD

**Issue by pushkar100** [webpack/webpack.js.org#3717]
The link explaining what "source maps" are in the **Development** page of the **Guides** documentation is broken.
File: https://github.com/webpack/webpack.js.org/blob/master/src/content/guides/development.md
Broken link: http://blog.teamtreehouse.com/introduction-source-maps

**Comment by jeffin143** [comment]
It does work for me ? can you try from https://webpack.js.org/guides/development/

**Comment by pushkar100** [comment]
Looks like the link was down for only a bit yesterday.
