### ISSUE TITLE
Development config guide: watch section has unnecessary snippet changes

### ISSUE THREAD

**Issue by pushkar100** [webpack/webpack.js.org#3718]
The following code snippet changes (green) are not necessary for the webpack `--watch` example and they reappear in the "Using webpack-dev-server" where they are actually required:

```js
devServer: {
     contentBase: './dist',
}
```

[Document section link](https://webpack.js.org/guides/development/#using-watch-mode)

**Comment by pushkar100** [comment]
I was confused about the snippet example but I think after going through it again, I am quite confident that `devServer` example need not be there while the section is about watch (which comes before introducing webpack dev server)

<img width="622" alt="Screen Shot 2020-05-13 at 9 05 00 PM" src="https://user-images.githubusercontent.com/11087299/81833640-973bd780-955d-11ea-938f-b9cfcf9bb4db.png">

**Comment by EugeneHlushko** [comment]
Hi @pushkar100 
Yes its a mistake, not needed before dev server intro, please remove if willing to commit.

**Comment by pushkar100** [comment]
Hi @EugeneHlushko thank you, I will add a PR soon to remove it

**Comment by pushkar100** [comment]
@EugeneHlushko I have a PR for the issue: https://github.com/webpack/webpack.js.org/pull/3746

**Comment by DanielRuf** [comment]
I think we can close this issue since the PR is merged.

**Comment by pushkar100** [comment]
Thank you for merging the PR.
