### ISSUE TITLE
docs(api):[example error]Command Line Interface--Usage without configuration file

### ISSUE THREAD

**Issue by fankeke007** [webpack/webpack.js.org#3719]
There is an example in docs as follows:

`webpack index=./src/index.js entry2=./src/index2.js -o dist/bundle.js`

This will result in a compile error：

> Conflict: Multiple chunks emit assets to the same filename bundle.js

Remove chunk name or use the same chunk name for each seprated module to get the expected output.

Like this:
`webpack ./src/index.js ./src.index2.js -o dist/bundle.js`
or:
`webpack bundle=./src/index.js bundle=src.index2.js -o dist/[name].js`

**Comment by EugeneHlushko** [comment]
Yes this is outdated example, i will update the doc
