### ISSUE TITLE
Target option documentation is duplicated

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack.js.org#373]
The values for the `target` option are explained twice. In the [Concepts section](https://webpack.js.org/concepts/targets/) and in the [Configuration section](https://webpack.js.org/configuration/target/).

Perhaps we should move the content under the "Options" heading in the Concepts section to the configuration page, since options are not really a concept.

I didn't make a PR for this yet since this would make the Target concept page very empty.

**Comment by TheLarkInn** [comment]
I think there's some validity to maybe have a general overview of what the targets are and then we can link to more information.

**Comment by TheLarkInn** [comment]
Really the docs in concepts are ment to be smaller consumable pages that first time users will come across.
