### ISSUE TITLE
break out fetch-supporters script into its own package?

### ISSUE THREAD

**Issue by boneskull** [webpack/webpack.js.org#3734]
Hi,

Over at [Mocha](/mochajs/mocha) we were wondering how Webpack displays the list of OC sponsors, so I took a look.  We'd like to move to a similar strategy, I think.

It looks as if [src/utilities/fetch-supporters.js](/webpack/webpack.js.org/blob/master/src/utilities/fetch-supporters.js) is generic enough to be applicable to other projects.  

Is this something you'd be interested in publishing as its own module?

I wanted to give you a chance before I, uh, copied the script and published it myself.  😝

**Comment by EugeneHlushko** [comment]
Hi @boneskull,

We had little trouble with the script so no plans to publish it as a package, it required no maintenance so far iirc. Regarding copy-pasting and publishing you should probably check how the code is licensed here and maybe you need to include some disclaimer after copying and publishing as a package
