### ISSUE TITLE
improve documentation about usage node options

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#3740]
__Feature to document__

Improve documentation about usage node options, example:
```json
{
  "scripts": "NODE_OPTIONS='--max-http-header-size=100000' webpack-dev-server"
}
```

__Author(s)__

Any

__Additional information__

https://github.com/webpack/webpack-dev-server/issues/1711

[ ] I am willing to work on this issue and submit a pull request.

**Comment by jeffin143** [comment]
On it
