### ISSUE TITLE
remove all deprecated loaders from docs

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#3755]
__Feature to document__

A lot of loaders from https://webpack.js.org/loaders/ are deprecated, please fix it **ASAP**, we receive a lot of requests for helping, because people think that they still exist and are supported

+ remove any mentions of deprecated loaders from docs

Remove `script-loader` from docs due https://github.com/webpack-contrib/script-loader

__Author(s)__

Any

__Additional information__

No

[ ] I am willing to work on this issue and submit a pull request.

**Comment by snitin315** [comment]
I will take this up.
