### ISSUE TITLE
remove note about `script-loader`

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#3760]
__Feature to document__

https://webpack.js.org/guides/shimming/#other-utilities

__Author(s)__

Any

__Additional information__

`script-loader` deprecated

[ ] I am willing to work on this issue and submit a pull request.

**Comment by anshumanv** [comment]
wip

**Comment by anshumanv** [comment]
@evilebottnawi it seems it's already removed, can you verify?

**Comment by snitin315** [comment]
I remember removing it in https://github.com/webpack/webpack.js.org/commit/4ebac1057567500f6a075a32095c9b9fbea2c667 .
Unless there is another note?

**Comment by evilebottnawi** [comment]
Yes, solved
