### ISSUE TITLE
Restore documentation website

### ISSUE THREAD

**Issue by nukeop** [webpack/webpack.js.org#3762]
Currently, the documentation website has been defaced with the following message:

![ArchLabs-38-949x896](https://user-images.githubusercontent.com/12746779/83518277-c6dd6000-a4c9-11ea-86d6-5d02e0689eed.png)

Some of us have day jobs and deadlines...

In the immortal words of Professor Oak:
![ArchLabs-26-489x155](https://user-images.githubusercontent.com/12746779/83536931-6eb35780-a4e3-11ea-98e3-ad7b6d74356b.png)

**Comment by fmad89** [comment]
DOCS LIVES MATTER!

**Comment by snitin315** [comment]
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The <a href="https://twitter.com/webpack?ref_src=twsrc%5Etfw">@webpack</a> documentation will be temporarily down for today to pay respects to George Floyd and countless others who are the victims of police violence in the Black community and around the world. <a href="https://twitter.com/hashtag/blackoutday?src=hash&amp;ref_src=twsrc%5Etfw">#blackoutday</a> <a href="https://twitter.com/hashtag/BlackOutDay2020?src=hash&amp;ref_src=twsrc%5Etfw">#BlackOutDay2020</a> <a href="https://t.co/FPy0JITmjs">https://t.co/FPy0JITmjs</a> <a href="https://t.co/CgSndheO4A">pic.twitter.com/CgSndheO4A</a></p>&mdash; webpack module bundler (@webpack) <a href="https://twitter.com/webpack/status/1267770405554540545?ref_src=twsrc%5Etfw">June 2, 2020</a></blockquote>

**Comment by chenxsan** [comment]
Just open https://webpack.js.org/guides/getting-started/ or any other pages instead of homepage, you should be able to use docs as usual.

**Comment by nukeop** [comment]
Thanks for the tip

**Comment by Ispen** [comment]
You could do it normally, like put a popup or small window on the side, with blm info, but no, you prefer to hinder the work of millions of programmers, resulting the opposite effect to the intended one. Congrats webpack devs!

**Comment by evilebottnawi** [comment]
@Ispen Because it is very important for me and for others, tomorrow your family member can be killed by a psychopath policeman. How would you feel about this?

**Comment by nukeop** [comment]
> @Ispen Because it is very important for me and for others, tomorrow your family member can be killed by a psychopath policeman. How would you feel about this?

Ah, a notice on webpack's website is sure to put a stop to this. Carry on!

**Comment by Ispen** [comment]
> @Ispen Because it is very important for me and for others, tomorrow your family member can be killed by a psychopath policeman. How would you feel about this?

It is also important for me and probably for each of us. I agree that such problems should also be publicized in a programming environment, BUT not in this way! Without hindering other people's work! More understanding and empathy, less imposing your vision of the world.

**Comment by evilebottnawi** [comment]
> Ah, a notice on webpack's website is sure to put a stop to this. Carry on!

Yes, if we do it together, we can change everything

> It is also important for me and probably for each of us. I agree that such problems should also be publicized in a programming environment, BUT not in this way! Without hindering other people's work! More understanding and empathy, less imposing your vision of the world.

This was done so that we all pay attention. Most would just close the pop-ups and pass by.

**Comment by Ispen** [comment]
> Most would just close the pop-ups and pass by.
It's their choice, instead you build an army of opponents making their work more difficult. Not this way.

**Comment by nukeop** [comment]
> Most would just close the pop-ups and pass by.

Because most of us don't care about american problems when we're programming, please keep us out of them, thank you.

**Comment by devx97** [comment]
> @Ispen Because it is very important for me and for others, tomorrow your family member can be killed by a psychopath policeman. How would you feel about this?

I am 100% sure that my family will not overdose fentanyl and metamphetamine as he did :)

**Comment by kuskoman** [comment]
if you really want to make people pay attention to it there are many different ways to do it. making our(software developers) work harder by removing docs will not create ANY positive associations with actions you are _trying_ to promote.

**Comment by piotros** [comment]
@evilebottnawi have you ever wondered how this situation looks like from a European point of view?

**Comment by numb86** [comment]
> BUT not in this way! Without hindering other people's work! More understanding and empathy, less imposing your vision of the world.

Exactly so!
This way produces no attention or interest. It cause confusion and repulsion.
Coerced solidarity is not solidarity.

**Comment by anikethsaha** [comment]
People are protesting for justice even having a threat like COVID'19 around them. I guess this is the least we can do. 

You have the answer above https://github.com/webpack/webpack.js.org/issues/3762#issuecomment-637512383 .

**Comment by nierw** [comment]
The United States isn't the world. People have deadlines and jobs - confusing them in favor of implicitly coerced solidarity with something that may not even be relevant to their location in the world is disappointing.

Put up a through-link to the documentation instead of being disrespectful and assuming you _represent the globe._

**Comment by TheLarkInn** [comment]
@nukeop I've blocked you from contributing on our organization temporarily. Your vapid commentary is not welcome here. Allow this time to reflect on why this situation is not about you "having to do work" but rather focusing on more important justices, not only here, but all over the world. 

Rather, like us, use your privilege to help voice the injustices across the world and fight for change.
