### ISSUE TITLE
Restore/Allow Clickthough to Documentation

### ISSUE THREAD

**Issue by mattleong** [webpack/webpack.js.org#3763]
![Screenshot from 2020-06-02 16-40-30](https://user-images.githubusercontent.com/3721204/83580130-12a30000-a4f0-11ea-8d3d-e5ce09a615c8.png)

Although, done for what I'm sure are good and heartfelt intentions, blocking access to documentation is actually counter productive. It is preventing people (**including people of color**) from the ability to complete their job. I understand the intention is to force people to think about the state of the world and their involvement in it, however I think there are better ways to go about it that are less destructive to the community Webpack is trying to stand up for. 

A clickthough link to the actual documentation should be made, rather than completely denying access. It's not obvious at all that it's available outside of the bare domain (i.e. https://webpack.js.org/concepts/). 

Again, I appreciate the message the Webpack team is trying to convey, however, there are less destructive alternatives.

**Comment by TheLarkInn** [comment]
We hope that the destruction that you feel today conveys even fraction of a fraction of a fraction of what those who are being oppressed are feeling. This page will remain downed for now and I ask that you consider reflecting on why you feel uncomfortable inconvenienced and then use that reflection to empathize for others and rally for their support. I am closing and locking this issue.
