### ISSUE TITLE
Request for making information about repression on civilian people in Hong Kong the main page of docs

### ISSUE THREAD

**Issue by kuskoman** [webpack/webpack.js.org#3764]
For some time webpack is informing about things related internal political situation of USA. I think that it's also worthy to inform people about (in my opinion) even bigger injustice happening currently in HK, where Chinese police unlawfully restricts freedom of protesters in many ways.

**Comment by TheLarkInn** [comment]
I tried to be as inclusive with our messaging as possible to not only include the current focused Black community, but also "others around the world". 

This is not an injustice contest and they should not be compared. Both are condemnable and worth of protest. If you have links or resources that we can include for global funds for supporting injustice I welcome those contributions.

**Comment by jeanlucaslima** [comment]
Hey, @TheLarkInn, taking the risk of being publicly judged, but as a someone from around the world, but not from the US it really is hard to understand the decision. Hard to put into words, but I'm a bit conflicted given I don't even understand in details what is happening in the US. 

Racism is an issue bigger than any country, indeed. 

But it feels like people from other countries are being dragged into US political problems right now, in a bit of a forceful way. Which I never expected from an open source project. 

I'm just trying to understand, really.

**Comment by jeanlucaslima** [comment]
And if this trends goes I hope we also include other movements. HK, Uyghurs, but also problems in my country like the Amazon issues were surely overlooked in the past.

**Comment by TheLarkInn** [comment]
Appreciate your honesty. We understand that it isn't a perfect form of solidarity but just a great call to action for civil injustice anywhere right now. 

Even Brazil, struggles from deep roots of racism today and is just one of many countless examples. If you have causes you want to share. I'll leave this issue open to raise further awareness.

**Comment by jeanlucaslima** [comment]
We do have issues, yes, and each place has its own struggles. Not denying that. 

Gonna leave here the NGO I support, ISA, that fights for the people of the Amazon forest and indigenous people from Brazil in general: https://filiacao.socioambiental.org/donate/

**Comment by kagawagao** [comment]
@kuskoman it's not same thing.

to be honest, have the “protesters” in Hong Kong really suffered violent by the police?

**Comment by MrKou47** [comment]
People just believe what the had heard. No one will check the truth. It's not a good idea to include all politics

**Comment by Niefee** [comment]
香港主要是被一群香港废青搞得乌烟瘴气，甘愿做美国的走狗，也不懂做一个好好工作生活的年轻人。这种人去哪里都是祸害。

**Comment by Lyanbin** [comment]
香港是种族问题？你在说你🐴   呢？

**Comment by XGHeaven** [comment]
Please close this issue. @TheLarkInn 

香港一是中国内政，二是外部势力教唆，和颜色革命类似。跟种族歧视、人权、自由完全是两回事。

**Comment by HuShiyuFrontEnd** [comment]
what happened in HongKong，just like some New York citizen said they are English people and want to be independent。No oppression， okay? We Chinese never be afraid of our policy, they potect us but not like american policy, kill people. It's not the same problem, don't mess they up.

**Comment by HuShiyuFrontEnd** [comment]
> @kuskoman这不是一回事。
> 
> 老实说，香港的“抗议者”真的遭受过警察的暴力吗？
No， they are the violence itself

**Comment by TheLarkInn** [comment]
This is for a place to leave links to initiatives and funds for civil rights issues beyond that has been provided. I will lock discussion if continued. 大家明白吗？大哥们明白吗？

**Comment by HuShiyuFrontEnd** [comment]
> 除了提供的权利之外，这里还为与民权问题的倡议和资金保持联系的地方。如果继续，我将锁定讨论。大家明白吗？大哥们明白吗？
but you guys truely know what happened in HongKong？

**Comment by stopbeingcowards** [comment]
many companies support #blackouttuesday because popularity. do not let this be a trend.

**Comment by jinweijie** [comment]
In my opinion, this is a nasty request. Just a humble suggestion that please understand the full story before taking action. Thanks. Hope everything get better soon. Thanks.

**Comment by talktohebe** [comment]
You are strongly biased against China. Are you the most vicious dogs?

**Comment by supermariogo** [comment]
@kuskoman Open your eyes, looks at the [video](https://www.youtube.com/watch?v=JTHG1lRuYSU)  
Whoever talk about Hong Kong, please not only look at what western media said, please have a full view of HK.

**Comment by HermantNET** [comment]
So many mainlanders never respect the vast majority of Honk Kong people's opinions, only their own... Anyways, I think an OSS project taking a political stance, no matter how obviously "correct" or "moral" it may be, is like jumping into a shark tank, much like this thread. Still, I respect the decision and hope something will be done to better social divides in the USA. I do hope you're prepared for the global communities response if you stay silent on other issues though.

**Comment by kagawagao** [comment]
@HermantNET 

are you sure it was **vast majority of Hong Kong people's opinions**? is there statistic data support your opinion?

let's think this problem in another view

If Texas seeks independence from the United States, and "prosters" rob the store, burning buildings, throw petrol bomb, beating people who have different positions from them, and holding up "Chinese troops to save the people of Texas".

how do you think about this. are these poeple worthy of respect?

finnaly, I also think we should **NOT**  bring political issues into the open source community.

**Comment by HuShiyuFrontEnd** [comment]
> So many mainlanders never respect the vast majority of Honk Kong people's opinions, only their own... Anyways, I think an OSS project taking a political stance, no matter how obviously "correct" or "moral" it may be, is like jumping into a shark tank, much like this thread. Still, I respect the decision and hope something will be done to better social divides in the USA. I do hope you're prepared for the global communities response if you stay silent on other issues though.

The fact is, most mainland people do not care about anything abount HongKong. HongKong has independent finance, mainland goverment can't get one dollar tax from Hong Kong, what happened in HongKong can't influence our life. Who care about HongKong? Those people who hope HongKong prosperous and stable. Do you have a child? Will you hope your 16 years old, do not go to school everyday and become "protesters", even though they do not know what they are doing, just to be cool. If you really want to do good things, first investigate, not take conclusion.

**Comment by HuShiyuFrontEnd** [comment]
Please, words just like swords, don't hurt us time by time. I heard people in California want to be independent every year. But will I support or be against then? I will not, because I can't know what's the true need of people in California. But why you always think you guys get the truth? Open source community should be pure, if you want politics, go to your twitter or facebook. Webpack is a great tool, don't use politics to kill it.

**Comment by Pan-Bubr** [comment]
@TheLarkInn , with due respect to the solidarity gesture, could you at least let people clickthrough to the docs? You can add checkboxes like "I understand the seriousness of the situation" "I agree with the protesters' cause" or anything you like.

Because for now, you are hurting mostly inexperienced developers that are trying to figure out your tool for the first time.

Experienced people will fork your repo and self-host your page. They also either do not need the documentation or will just use another tool like https://devdocs.io/ 

Taking the page hostage does not really help the cause and may have an opposite effect of losing support for the protesters.

Maybe you will consider some positive reinforcement for the allies and not hurting random uninvolved bystanders from outside the US?

**Comment by kuskoman** [comment]
I am closing this issue. I created it to draw you attention to the fact, that human rights are not being respected in many places around the world.
I still don't think that webpack documentation, and other similiar software documentation should be a place to inform about political situation and number of these injustices in the world is just one of reasons.
Don't understand me wrong. I appreciate all kinds of fight for human rights, but making people annoyed by hiding the documentation will probably cause reverse effect.
All lives matter
