### ISSUE TITLE
All live matters

### ISSUE THREAD

**Issue by cojack** [webpack/webpack.js.org#3766]
Be speaking of Black Live Matters you show your self as a racist ignorant, farewell and be gone.

**Comment by egoist** [comment]
All lives matter, yes, because that's obvious to most people. #BlackLivesMatter is just a message to all racists who think only white lives matter.

**Comment by jamezrin** [comment]
https://twitter.com/dan_abramov/status/1267224910839066630

"It’s curious how software developers struggle with logic when applied to real world situations."

**Comment by HermantNET** [comment]
> All lives matter, yes, because that's obvious to most people. #BlackLivesMatter is just a message to all racists who think only white lives matter.

Not all racists are white, but I understand and agree with what you're saying

**Comment by EugeneHlushko** [comment]
Should be up and running

**Comment by TheLarkInn** [comment]
Thank you to all who speak up to original poster. Locking conversation.
