### ISSUE TITLE
Multi page entries and groups of vendors chunks with SplitChunksPlugin

### ISSUE THREAD

**Issue by bzioni** [webpack/webpack.js.org#3794]
I have a multi-page setup for Webpack 4 with multiple entries that works just fine.
```
entry : {
  "page-1": "./src/js/page-1.js",
  "page-2": "./src/js/page-2.js",
}
...
optimization: {
   splitChunks: {
     chunks: 'all' 
   }
}
```

The problem is with the SplitChunksPlugin that creates a group of vendors for shared imports
which makes me a problem to load them dynamically (by the name of the entry):

```
vendors~page-1.js
vendors~page-1~page-2.js
```

Is it possible to split the vendors chunks by the name of the entries to look like this?

```
vendors~page-1.js
vendors~page-2.js
```

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
