### ISSUE TITLE
update `shimming` documentation

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#3797]
Update https://webpack.js.org/guides/shimming/ page and examples for `import-loader`/`export-loader`/`expose-loader`, they all got the update and changed their options, so we need to update the examples, documentation of each loader can be found in their README

https://webpack.js.org/guides/shimming/

Don't know

[ ] I am willing to work on this issue and submit a pull request.

**Comment by snitin315** [comment]
Taking this up.

**Comment by chenxsan** [comment]
@evilebottnawi Sure, I'll update it as soon as possible.

**Comment by evilebottnawi** [comment]
Big thanks for helping
