### ISSUE TITLE
Merge is not a function

### ISSUE THREAD

**Issue by makuzaverite** [webpack/webpack.js.org#3823]
### Doc might be updated about how merge package is used on production section under guides
> I had an issue to day i was looking into webpack's doc and the face an error like this

![image](https://user-images.githubusercontent.com/53856673/86916171-7d64de00-c123-11ea-8c61-a4d346e1a70a.PNG)

This example from docs didn't work for me

![more](https://user-images.githubusercontent.com/53856673/86916252-9ff6f700-c123-11ea-9624-a31ded8f5bce.PNG)

Source: https://webpack.js.org/guides/production/#setup

I came a cross an found that webpack-merge package now is destructured during it's import

## Solution
![solution](https://user-images.githubusercontent.com/53856673/86916350-c2891000-c123-11ea-9381-5d12053f1df5.PNG)

May be documentation might be updated to remove that kind of confusion

**Comment by anshumanv** [comment]
Yep that's an issue, I'll update 👍

**Comment by makuzaverite** [comment]
I did a pull request 

here https://github.com/webpack/webpack.js.org/pull/3824

**Comment by evilebottnawi** [comment]
No need close, it will be closed after merge

**Comment by chenxsan** [comment]
Could be closed now that the pull request was merged.
