### ISSUE TITLE
[Feature] Add 'Next' and `Back` buttons to switch between section on bottom of the page ?

### ISSUE THREAD

**Issue by MenaiAla** [webpack/webpack.js.org#3830]
**Issue Description**
When I want to move forward or backward between sections ( pages ), I did not find the `Next` and `Back`  buttons on the bottom of the page.

**Current scenario**
Must select each selection on the left side.

**Featured scenario**
Two buttons that allow docs readers to switch between sections without scrolling on the top.

**Comment by chenxsan** [comment]
there's a pull request here https://github.com/webpack/webpack.js.org/pull/3793

**Comment by MenaiAla** [comment]
Yes, I check it out but why they did not approve it yet?

**Comment by chenxsan** [comment]
@MenaiAla We all do it in our free time :) So I guess it would take some time. Please be patient.

**Comment by montogeek** [comment]
Released.
