### ISSUE TITLE
Notify readers that module loaders arrangement is important.

### ISSUE THREAD

**Issue by MenaiAla** [webpack/webpack.js.org#3831]
When I was reading [Asset Arrangement](https://webpack.js.org/guides/asset-management/) I wrote the config manually like this :

 ```
module: {
        rules: [{
            test: /\.css$/,
            use: ["css-loader", "style-loader"]
        }]
    }
```

The code was invoking an error but I COULD NOT find where's the error Then I figured out that the right arrangement of modules should be : 

 ```
module: {
        rules: [{
            test: /\.css$/,
            use: ["style-loader", "css-loader"]
        }]
    }
```

But the section of [Loading CSS](https://webpack.js.org/guides/asset-management/#loading-css) did not mention that the order is matter.

**Comment by chenxsan** [comment]
I think it's mentioned somewhere like https://webpack.js.org/concepts/loaders/#loader-features:

> Loaders can be chained. Each loader in the chain applies transformations to the processed resource. **A chain is executed in reverse order**. The first loader passes its result (resource with applied transformations) to the next one, and so forth. Finally, webpack expects JavaScript to be returned by the last loader in the chain.

But I agree it's better to warn users here too.

Maybe you can submit a pull request.

**Comment by mitchell-frost** [comment]
I would like to open a pull request. Where is the repository with the documentation?

**Comment by anshumanv** [comment]
@mitchell-frost it's this repository itself.

**Comment by mitchell-frost** [comment]
> @mitchell-frost it's this repository itself.

I can't find the code folder or the documentation.

**Comment by snitin315** [comment]
> I can't find the code folder or the documentation.

You can click on the `Edit Document` button on webpack.js.org's page which you want to edit.

**Comment by mitchell-frost** [comment]
> > I can't find the code folder or the documentation.
> 
> You can click on the `Edit Document` button on webpack.js.org's page which you want to edit.

Thank you!

**Comment by mitchell-frost** [comment]
I have made a PR for this issue.

**Comment by jeffin143** [comment]
@montogeek : Let's close this
