### ISSUE TITLE
Display Problem on Chinese AssetManagement Website

### ISSUE THREAD

**Issue by Ji4ming** [webpack/webpack.js.org#3834]
https://www.webpackjs.com/guides/asset-management/

The change from main.js to bundle.js(line 35-36) is not truly highlighted on the webpage which may lead to certain misunderstandings or omissions.
This change is supposed to be highlighted as it is crucial for all the changes we will make in latter sections.

**Comment by chenxsan** [comment]
Not a problem can be fixed in this repository. You might want to create an issue on the Chinese translation site https://github.com/docschina/webpack.js.org/issues
