### ISSUE TITLE
Reference optimization.runtimeChunk in Code Splitting Guide

### ISSUE THREAD

**Issue by sokra** [webpack/webpack.js.org#3835]
__Feature to document__

On the https://webpack.js.org/guides/code-splitting/ page document that `optimization.runtimeChunk: "single"` is needed when multiple entry points are put on a single HTML page.

Similar to the note here: https://webpack.js.org/configuration/optimization/#optimizationruntimechunk

We should also add a note that using multiple entrypoints per page should be avoided when possible in favor of an entrypoint with multiple imports: `entry: { page: ["./analytics", "./app"] }`. This results in better optimization and consistent execution order when using async script tags.

Multiple entrypoints per page are still valid to use in scenarios where HTML is generated in a dynamic matter, e. g. when components on page are unknown at compile-time and HTML page is composed dynamically depending on data.

__Author(s)__

@sokra, @jakearchibald

__Additional information__

https://bundlers.tooling.report/code-splitting/multi-entry/

> This test is a "partial" pass, since runtimeChunk:"single" is required to ensure correct module instantiation, but it is disabled by default and not documented in Webpack's code splitting guide.

[ ] I am willing to work on this issue and submit a pull request.

**Comment by jeffin143** [comment]
Will take a look

**Comment by mitchell-frost** [comment]
I made a pull request. Please go through it

**Comment by jeffin143** [comment]
I was working on it and was about to raise it , and that is why I said will take a look

**Comment by mitchell-frost** [comment]
> I was working on it and was about to raise it , and that is why I said will take a look , anyways no issues if you already raised one.

Apologies. There was no pull request so, I thought maybe you got busy.

**Comment by chenxsan** [comment]
closed via https://github.com/webpack/webpack.js.org/pull/3847
