### ISSUE TITLE
Note about compiling untrusted code

### ISSUE THREAD

**Issue by sokra** [webpack/webpack.js.org#3838]
__Feature to document__

Add a note about compiling untrusted code somewhere into the documentation.

> Do not compile untrusted code with webpack. It would allow an bad actor to execute code on your machine, your CI-Server and in the web browser of the user.

__Author(s)__

@sokra

__Additional information__

[ ] I am willing to work on this issue and submit a pull request.

**Comment by anshumanv** [comment]
wip

**Comment by mitchell-frost** [comment]
I want to open a pull request. Where should this be added in the documentation?

**Comment by jeffin143** [comment]
> I want to open a pull request. Where should this be added in the documentation?

@anshumanv , is currently working on this , so you would want to take some other issues to resolve :)

**Comment by mitchell-frost** [comment]
> > I want to open a pull request. Where should this be added in the documentation?
> 
> @anshumanv , is currently working on this , so you would want to take some other issues to resolve :)

Okay! :)
