### ISSUE TITLE
Continue redesign splash page

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack.js.org#386]
In #374, @skipjack cleaned up the splash page to allow for a redesign. He added a temporary screenshot of @pastelsky's mock-up of the splash page. This screenshot is low quality, so we should preferably fix this soon.

This is a ticket to ensure that we don't forget that.

@pastelsky, do you plan on working on the splash page?

**Comment by skipjack** [comment]
@pastelsky happy to help out with this, if you're very busy this week we could always just add a higher res modules image for the time being. Didn't mean to put pressure on you to jump on this right away. 

Just for reference here's @pastelsky's design from #285:

![image](https://cloud.githubusercontent.com/assets/8988697/20487087/1a8eba8e-afd0-11e6-81d2-9052b962fb61.png)

I think we should also quickly talk out what end goal with this is... were you thinking this would be the only section displayed on this page (kind of like [Gulp's landing page](http://gulpjs.com/))? If so we should figure out what the plan for the small example and support sections is. Maybe we keep support there and move the short example to our new getting started section?

**Comment by pastelsky** [comment]
Here are the vector assets for homepage. Feel free to use them as you like —
https://www.dropbox.com/sh/fktsoaqcgt6r0mr/AADMSXL0dtzvpn1VWAi8HyGHa?dl=0

**Comment by skipjack** [comment]
Closing as @pastelsky tackled this in #510.
