### ISSUE TITLE
Added css-minimizer-webpack-plugin to official plugins

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#3883]
__Feature to document__

Need to add `css-minimizer-webpack-plugin` to official plugins https://github.com/webpack-contrib/css-minimizer-webpack-plugin

__Author(s)__
Any

__Additional information__

No

[ ] I am willing to work on this issue and submit a pull request.

**Comment by jamesgeorge007** [comment]
On it.
