### ISSUE TITLE
Tree Shaking localization in Chinese has a grammar issue

### ISSUE THREAD

**Issue by sy0uta1k0n** [webpack/webpack.js.org#3886]
__Feature to document__

tree shaking: https://webpack.docschina.org/guides/tree-shaking/

multiple '代码' provided
It should be <这样会允许去掉这
'+段'
'-代码'
代码，但仍然会有一些导入的问题需要被包括/评估，因为它们包含了副作用。>

__Additional information__
<img width="1115" alt="tree shaking" src="https://user-images.githubusercontent.com/13308844/89142828-0fbd9d80-d57b-11ea-86e3-7741d6db7aff.png">

[Y] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
Please open an issue on https://github.com/docschina/webpack.js.org/issues, it can't be fixed in this repository.

**Comment by sy0uta1k0n** [comment]
Got it and I had open a new issue in the mentioned repo
