### ISSUE TITLE
Page not scrolled to top when clicking sidebar menu

### ISSUE THREAD

**Issue by chenxsan** [webpack/webpack.js.org#3933]
When I open https://webpack.js.org/concepts/#environment and click `Concepts` menu on sidebar:

![image](https://user-images.githubusercontent.com/1091472/91187970-5b4f0b80-e723-11ea-8506-3d07521a15d5.png)

Nothing happens while I expect the page to scroll to top.

**Comment by anshumanv** [comment]
Fixed in https://github.com/webpack/webpack.js.org/pull/3971
