### ISSUE TITLE
Create and display links to webpack blog

### ISSUE THREAD

**Issue by dmitriid** [webpack/webpack.js.org#394]
Basically copying it from https://github.com/webpack/webpack.js.org/issues/327 (see [comment](https://github.com/webpack/webpack.js.org/issues/327#issuecomment-262023743) ):

Feature request:

- update webpack README, webpack 1.x doc site with a link to the [official webpack blog](https://medium.com/webpack)
- on webpack.js.org, possibly:
  - move the icons into the top header
  - add a footer with proper text links (to aid discoverability through search engines etc.)

The reason is: currently the blog is undiscoverable and a people are very surprised when they hear about it. However, it's a good source of webpack-related news.

**Comment by johnstew** [comment]
PR for this here, [#700](https://github.com/webpack/webpack.js.org/pull/700).

Added in the blog link to the top navigation only for now. The footer looks pretty balanced and wasn't sure where this should go down there. Will defer to @bebraw or @TheLarkInn on if it should be added there.

**Comment by skipjack** [comment]
Closing as #700 was merged.
