### ISSUE TITLE
make `postcss-loader` official 

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#3941]
__Feature to document__

make `postcss-loader` official (now it under webpack-contrib) https://github.com/webpack-contrib/postcss-loader

__Author(s)__

No

__Additional information__

No

[ ] I am willing to work on this issue and submit a pull request.

**Comment by anshumanv** [comment]
wip

**Comment by anshumanv** [comment]
I think already official

**Comment by evilebottnawi** [comment]
@anshumanv I think we need check url of `postcss-loader` in our docs, because it migrate to other organization

**Comment by anshumanv** [comment]
Already - https://github.com/webpack/webpack.js.org/pull/3909 😄

**Comment by evilebottnawi** [comment]
Great
