### ISSUE TITLE
[webpack 5]: adding example for toml/yaml/json5 files

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#3943]
__Feature to document__

https://github.com/webpack/webpack/tree/master/examples/custom-json-modules

__Author(s)__

Any

__Additional information__

No

[ ] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
I'll document it.

**Comment by chenxsan** [comment]
@evilebottnawi I found there was an example for `toml` here http://localhost:3000/configuration/module/#ruleparserparse, do you think it's still necessary to document them somewhere?

**Comment by evilebottnawi** [comment]
@chenxsan yes, we need to document this, because not all developers know about examples and they are poorly indexed in search systems
