### ISSUE TITLE
Dogfood webpack 5?

### ISSUE THREAD

**Issue by chenxsan** [webpack/webpack.js.org#3961]
webpack 5 was going to be released at [2020-10-10](https://github.com/webpack/webpack/issues/11406), any interest in dogfooding it in this project?

Here's some benefits I can think of now:

1. It's more convincing for people who consider upgrading to webpack 5 if webpack document site is dogfooding webpack 5
2. We can hopefully improve the performance of production site and development environment
3. We can upgrade many of the outdated dependencies as well which I think is good for the health of the project.

cc @EugeneHlushko @montogeek @evilebottnawi since you're active team members in this project.

If you're interested, I can draft a PR and let's see how far I can get before 2020-10-10.

**Comment by evilebottnawi** [comment]
@chenxsan Good idea :+1: I am for it

**Comment by EugeneHlushko** [comment]
Yes i was going to pick it up for hands on experience but since you are willing happy to review it later! Please go ahead
