### ISSUE TITLE
[outdated doc] plz remove namedModules from 5.x doc

### ISSUE THREAD

**Issue by achenwei-chwy** [webpack/webpack.js.org#3988]
__Feature to document__

namedModules for optimization config
__Author(s)__
I do not know

__Additional information__
It was traced to a doc update because a prop was not found when I was configuring webpack5 
https://github.com/webpack/webpack-cli/issues/1809

[ x ] I am willing to work on this issue and submit a pull request. (but I am not sure if its just removing it? if so I can take on)

**Comment by chenxsan** [comment]
It's removed in this commit https://github.com/webpack/webpack/commit/5e72a6505a0a91024d82fa2e9e1a7d14c61c022d. I think removing it should be enough.

**Comment by chenxsan** [comment]
PR welcomed, let us know if you need any help.

**Comment by sokra** [comment]
`namedChunks` must also be removed.

@achenwei-chwy Do you still want to do a PR? As there are only 3 days left, could you do that until tomorrow? Otherwise I will take it.
