### ISSUE TITLE
Contributors heading is included in search results

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack.js.org#399]
As you can see below, the "Contributors" heading is included in the search results. This is not a huge problem, but can be confusing when it's the first result, such as in this case:

![webpack](https://cloud.githubusercontent.com/assets/533616/20557909/e4030048-b16d-11e6-83e4-448c1625f824.png)

@dzello, is this something that can be easily fixed in our Algolia config?

**Comment by dzello** [comment]
Yes! I've fixed it by adding an entry to `selectors_exclude` in [webpack's DocSearch config](https://github.com/algolia/docsearch-configs/pull/95). I also updated the `start_urls` property to reflect the recent navigation changes. The config has been deployed and the live search reflects the changes.

**Comment by SpaceK33z** [comment]
Thanks for the quick fix!!
