### ISSUE TITLE
Popover functionality not working in few links

### ISSUE THREAD

**Issue by rahul3v** [webpack/webpack.js.org#3990]
Steps to produce 
1. go to https://webpack.js.org/configuration/
2. search (/* Advanced resolve configuration (click to show) */ on webpage, or find it as shown on image as highlighted one)
3. click on the link, the popup will not work,

tried browsers : Chrome and Mozilla  - latest
screen resolution : 1366 x 768

![popupWillNotWork](https://user-images.githubusercontent.com/24385409/93664274-18b2f180-fa8b-11ea-8fdb-b9c21affa2a3.JPG)

**Comment by anshumanv** [comment]
seems to work for me

**Comment by rahul3v** [comment]
well it will work in high screen resolution, try it in normal as specified 1366*768

**Comment by anshumanv** [comment]
Yep seems like an issue, feel free to PR
