### ISSUE TITLE
How to - Handle compatibility

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#4]
[Stub](https://github.com/webpack/webpack.io/blob/develop/content/how-to/handle-compatibility.md).

Feel free to comment here if you have ideas on what this guide should cover. Link to potential resources too.

**Comment by pksjce** [comment]
@bebraw - You mean compatibility with?

**Comment by bebraw** [comment]
The original stub had

> require.main require.cache module.loaded global process __dirname __filename module.id

That said, maybe we can close this one.

**Comment by bebraw** [comment]
Yeah, let's close. Too vague.
