### ISSUE TITLE
Make it obvious how easy it is to improve the docs

### ISSUE THREAD

**Issue by johnnyreilly** [webpack/webpack.js.org#40]
Because it's very easy indeed!

**Comment by bebraw** [comment]
The new docs will have an "edit" button as well. Instead of going through wiki, we'll be going through PRs at least at the beginning to keep it controlled.

**Comment by SpaceK33z** [comment]
Agree, issues like webpack/webpack-dev-server#553 constantly appear in all package repo's.

**Comment by SpaceK33z** [comment]
Closing since the new docs have an "edit" button now (don't know when that got implemented).
