### ISSUE TITLE
remove `eslint-loader` from list of loaders

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#4007]
__Feature to document__

Need to remove eslint-loader from official loader, because it is deprecated https://github.com/webpack-contrib/eslint-loader in favor eslint-webpack-plugin

__Author(s)__

Any

__Additional information__

Ref: https://github.com/webpack-contrib/eslint-loader
Ref: https://github.com/webpack-contrib/eslint-webpack-plugin

[ ] I am willing to work on this issue and submit a pull request.

**Comment by jamesgeorge007** [comment]
WIP

**Comment by EugeneHlushko** [comment]
closed via #4013
