### ISSUE TITLE
Documentation: Passing a Configuration page

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack.js.org#401]
https://webpack.js.org/configuration/passing-a-config/

This page is not finished yet.

**Comment by simon04** [comment]
I'm struggling to associate the content of extended configuration definitions with "Passing a Configuration". What his "passed"? Alternative suggestion: "Configuration Types" (relating to Javascript types function, array, Promise).

See also my comment: https://github.com/webpack/webpack.js.org/pull/895#issuecomment-280034635

**Comment by bebraw** [comment]
Configuration types would be better, yeah. Better rename the page, add the `env` bits there and include multi-compiler mode (return an array) too. That covers it.

**Comment by simon04** [comment]
Documenting multi-compiler mode is covered in #898.

It's just that https://webpack.js.org/configuration/environment/#using-environment-variables does not fit into the new title. Maybe keep this section on a separate page titled "environment variables"? Or keep `--env` on both pages?

**Comment by bebraw** [comment]
`Using --env` would fit the suggested page. `Using environment variables` could become a guide. It's out of place there.

**Comment by simon04** [comment]
Good idea. PR #898 is updated.
