### ISSUE TITLE
Passing ecmaVersion results in "Invalid configuration object"

### ISSUE THREAD

**Issue by Slapbox** [webpack/webpack.js.org#4012]
# Bug report

**What is the current behavior?**

v4.44.2 crashes with "Invalid configuration object" telling me that `output.ecmaVersion` is not a valid option

**If the current behavior is a bug, please provide the steps to reproduce.**

Provide `output.ecmaVersion` of any value. Tested: `5` and `6`

**What is the expected behavior?**

No crash on using documented option https://webpack.js.org/configuration/output/#outputecmaversion

**Other relevant information:**
webpack version:  4.44.2
Node.js version: 12.13.0
Operating System: Windows 7
Additional tools:

**Comment by Slapbox** [comment]
The docs for that setting specifically mention Webpack 4, so it would be good to edit the docs in that case.

> The default value of output.ecmaVersion in webpack 4 is 5

**Comment by Cronus1007** [comment]
I want to work on this issue.

**Comment by rramaa** [comment]
@evilebottnawi 
https://github.com/webpack/webpack.js.org/pull/4017
Have raised a PR for the documentation

**Comment by sokra** [comment]
This issue can be merged into #3968
