### ISSUE TITLE
Url loader default limit behavior isn't very clear

### ISSUE THREAD

**Issue by melloc01** [webpack/webpack.js.org#4014]
> The limit can be specified via loader options and defaults to no limit.

What does this actually mean? No upper limit or limit: 0?

No upper limit: will transform every file to base64
Limit 0: will fallback to file-loader

**Comment by evilebottnawi** [comment]
> Number|String
> A Number or String specifying the maximum size of a file in bytes. If the file size is equal or greater than the limit file-loader will be used (by default) and all query parameters are passed to it.

https://github.com/webpack-contrib/url-loader#limit

**Comment by evilebottnawi** [comment]
If you still want to improve it feel free to send a PR to https://github.com/webpack-contrib/url-loader#limit
