### ISSUE TITLE
Documentation: External Configurations page

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack.js.org#402]
https://webpack.js.org/configuration/external-configs/

This page is not finished yet.

**Comment by tarang9211** [comment]
@SpaceK33z @TheLarkInn im interested in helping on this. Is there some place I can read about external configurations first? That would help me put it down in easy-to-read words!

**Comment by simon04** [comment]
We got a CoffeeScript example via #778.

Reading the title "External Configurations", I would not expect to see an configuration example in an other JS language.

What is meant with the TODO "loader settings, e.g. `sassLoader`, `eslint` sections"?

cc: @bebraw

**Comment by tarang9211** [comment]
@simon04 Should we change the title of that concept/page?

**Comment by simon04** [comment]
+1 from my side, but I'd like to hear other comments. Any suggestions for the title?

**Comment by bebraw** [comment]
Yeah, feel free to change the title to match the content.

**Comment by tarang9211** [comment]
**Configurations using Javascript Supersets** ?

**Comment by bebraw** [comment]
**Configuration with JavaScript Alternatives** would work for me.

**Comment by tarang9211** [comment]
Sweet, I'll submit a PR for this

**Comment by tarang9211** [comment]
Does the file name also need to change? @bebraw @simon04

**Comment by tarang9211** [comment]
PR is here #900

**Comment by bebraw** [comment]
Yeah, the file name has to change too and we probably want a rewrite so the old link doesn't break. But Simon will give you some feedback I think. 👍

**Comment by tarang9211** [comment]
Ok, looking forward to it to get this fixed.

**Comment by simon04** [comment]
@bebraw, do you know that the TODO "loader settings, e.g. sassLoader, eslint sections" is about?

**Comment by bebraw** [comment]
@simon04 Those are likely obsolete by now and covered elsewhere. I would remove the TODO.

**Comment by simon04** [comment]
Fixed with #900.
