### ISSUE TITLE
webpack@5.0.0-rc.3: unrecognized output.ecmaVersion option

### ISSUE THREAD

**Issue by homobel** [webpack/webpack.js.org#4020]
# Bug report

Doc says(https://webpack.js.org/migrate/5/) there is _output.ecmaVersion_ option to make webpack use es5 runtime.

**What is the current behavior?**

But when I use it I got validation error:
```
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.output has an unknown property 'ecmaVersion'. These properties are valid:
```

**If the current behavior is a bug, please provide the steps to reproduce.**

`npm i webpack@next webpack-cli`

**webpack.config.js**
```
module.exports = {
	mode: 'development',
	entry: './in.js',
	output: {
		ecmaVersion: 5
	}
};
```

in.js may be empty.

`npx webpack`

**What is the expected behavior?**
No validation error expected. Build runtime has es5 version(no array functions etc).

**Other relevant information:**
webpack version:  5.0.0-rc.3
Node.js version: v14.10.1
Operating System: win10 64

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack.js.org/issues/4012
