### ISSUE TITLE
add `html-minimizer-webpack-plugin` to official plugins

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#4024]
__Feature to document__

https://github.com/webpack-contrib/html-minimizer-webpack-plugin

__Author(s)__

Any

__Additional information__

No

[ ] I am willing to work on this issue and submit a pull request.

**Comment by snitin315** [comment]
I will do this.

**Comment by snitin315** [comment]
I think now we don't need to do this manually after https://github.com/webpack/webpack.js.org/pull/4013

Only excluded plugins are - 

https://github.com/webpack/webpack.js.org/blob/46d0ed3ed5380ee1cbc27eaffcfc4744c6a78d0c/src/utilities/constants.js#L18-L25

**Comment by chenxsan** [comment]
Indeed, it's already included here https://webpack.js.org/plugins/html-minimizer-webpack-plugin/ automatically after https://github.com/webpack/webpack.js.org/pull/4013
