### ISSUE TITLE
Add `json-minimizer-webpack-plugin` to official plugins

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#4025]
__Feature to document__

https://github.com/webpack-contrib/json-minimizer-webpack-plugin

__Author(s)__

Any

__Additional information__

https://github.com/webpack-contrib/json-minimizer-webpack-plugin

[ ] I am willing to work on this issue and submit a pull request.

**Comment by anshumanv** [comment]
wip

**Comment by chenxsan** [comment]
The build stage in travis will include those plugins automatically now, you can check it here https://webpack.js.org/plugins/json-minimizer-webpack-plugin/. I think we only need to update those deprecated plugins in future.

**Comment by anshumanv** [comment]
oh nice let's close this
