### ISSUE TITLE
Documentation: Finish "Entry and Context" page

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack.js.org#403]
https://webpack.js.org/configuration/entry-context/

Needs an introduction. Also the `entry` option is only documented partially, it should have more examples.

**Comment by tarang9211** [comment]
@SpaceK33z can i help with this? im completely new to the repo, so some guidance would be great!

**Comment by TheLarkInn** [comment]
@tarang9211 https://github.com/webpack/webpack.js.org/blob/master/CONTRIBUTING.md

Start here. And then you can look in the content folder. :-D

**Comment by tarang9211** [comment]
@TheLarkInn got everything set up! I need to come up with the descriptions right?

**Comment by TheLarkInn** [comment]
Yup, really just a nice paragraph for how entry and context interact with eachother, what their purpose is etc.

**Comment by tarang9211** [comment]
**Entry and Context describe where the application must begin execution and also resolve any loaders from the configuration.**

sounds good?

**Comment by TheLarkInn** [comment]
I believe it may be any paths from the configuration

**Comment by tarang9211** [comment]
@TheLarkInn 

**The entry object provides an entry point for the application to begin execution.
The context object is an absolute path that resolves loaders and entry points.
**

That better?

**Comment by tarang9211** [comment]
@TheLarkInn or @bebraw can we close this issue since it seems to be deployed to production?
