### ISSUE TITLE
CLI: Update docs to v4

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack.js.org#4030]
__Feature to document__
New CLI

__Author(s)__
Me

__Additional information__
A lot has changed in the CLI v4 since v3 hence this issue is to track updates to the new CLI docs.

/cc @evilebottnawi 

- [x] I am willing to work on this issue and submit a pull request.

**Comment by snitin315** [comment]
Main Highlights -

- [ ] Core flags
- [ ] Negated flags
- [ ] Multiple types fir stats -> `--stats (means stats: true)` , `--stats verbose (means stats: verbose)`
- [ ] Multiple entries `--entry a.js --entry b.js`
- [ ] --env flag
- [ ] --analyze
- [ ] out of box `serve` & `info`

**Comment by anshumanv** [comment]
We've touched almost everything in the new CLI, need full rewrite 😄

**Comment by anshumanv** [comment]
@snitin315 I think I've covered most from your list, can you go over again and see what we've missed?

**Comment by snitin315** [comment]
I think only the last point is left from the list.
