### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by EugeneHlushko** [webpack/webpack.js.org#4031]
The build started to fail with missing supporters and starter kits

```
ERROR in ./components/StarterKits/StarterKitsTable.jsx
Module not found: Error: Can't resolve './_starter-kits.json' in '/home/travis/build/webpack/webpack.js.org/src/components/StarterKits'
 @ ./components/StarterKits/StarterKitsTable.jsx 11:0-40 17:5-9
 @ ./components/StarterKits/StarterKits.jsx
 @ ./components/Site/Site.jsx
 @ ./index.jsx
ERROR in ./components/Support/Support.jsx
Module not found: Error: Can't resolve './_supporters.json' in '/home/travis/build/webpack/webpack.js.org/src/components/Support'
```

Sample failure: https://travis-ci.org/github/webpack/webpack.js.org/jobs/733593393

Need to investigate why it started to occur

**Comment by EugeneHlushko** [comment]
Anyone able to pick up? i am busy cc @chenxsan @montogeek

**Comment by chenxsan** [comment]
@EugeneHlushko `yarn cypress:ci` would start the development server with the `yarn start` script, but in CI server we don't run `"fetch"` script to generate the `_supporters.json` and `_starter-kits.json` files before that.

Adding a `prestart` script should hopefully fix those warnings. Let me create a pull request to see if it will eliminate those warnings.

**Comment by chenxsan** [comment]
closed via https://github.com/webpack/webpack.js.org/pull/4032
