### ISSUE TITLE
minor: Add links to documentation

### ISSUE THREAD

**Issue by astonizer** [webpack/webpack.js.org#4034]
__Additional information__

On the [Asset Management](https://webpack.js.org/guides/asset-management/) page(third line), it would have been good to add links to the official website of the tools mentioned(grunt and gulp). Beginners having no idea of those tools can directly navigate to the website and know more about them. 
![screenshot](https://user-images.githubusercontent.com/57724542/95334876-46da6300-08cc-11eb-839b-5b27acf2cef3.png)

- [x] I am willing to work on this issue and submit a pull request.

**Comment by evilebottnawi** [comment]
We can add links on these tool, It's enough?

**Comment by astonizer** [comment]
Well I'm just a beginner in this field, so I guess it should be enough

**Comment by snitin315** [comment]
@astonizer do you want to send a PR for the same? It will be a good first contribution 😄 .

**Comment by astonizer** [comment]
@snitin315 Yes :smiley:
