### ISSUE TITLE
remove svg-inline-loader from docs

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#4052]
__Feature to document__

Remove svg-inline-loader, it is deprecated in favor `raw-loader` and `image-minimizer-webpack-plugin`

__Author(s)__

Any

__Additional information__

Ref: https://github.com/webpack-contrib/svg-inline-loader

[ ] I am willing to work on this issue and submit a pull request.

**Comment by anshumanv** [comment]
wip
