### ISSUE TITLE
[Bug] Link Conversion Error

### ISSUE THREAD

**Issue by QC-L** [webpack/webpack.js.org#4055]
![image](https://user-images.githubusercontent.com/13861040/95616781-f82ff300-0a9c-11eb-83aa-fe6caba1b80f.png)

I found a link exception and fixed it, when updating the Chinese document.

@EugeneHlushko 

Fixed #4054

**Comment by chenxsan** [comment]
Related page https://webpack.js.org/loaders/css-loader/#getting-started
