### ISSUE TITLE
Missing documentation target option.

### ISSUE THREAD

**Issue by juangl** [webpack/webpack.js.org#406]
I notice in [this commit](https://github.com/webpack/webpack.js.org/commit/ffb96199c6e0dd9706eb90310edaa24caad99112) was deleted `electron-main` from [target docs](https://github.com/webpack/webpack.js.org/blob/develop/content/configuration/target.md). I wonder if this was intentional. Sorry, I'm just curious.

**Comment by sokra** [comment]
No it wasn't intentional. You could send a PR which adds it again.

**Comment by SpaceK33z** [comment]
It was semi-intentional. I removed `electron-main` because `electron` does exactly the same it seems. @sokra, is it recommended to use `electron-main` or `electron`? We should mention one of the two.

**Comment by simon04** [comment]
How do `atom`/`electron`/`electron-main` differ from each other? According to https://github.com/webpack/webpack/blob/9380bd4/lib/WebpackOptionsApply.js#L115-L117 they are handled equally, and I cannot find any other reference to those identifiers in the source code.

**Comment by sokra** [comment]
There are equal. It has historical reasons. atom, renamed to electron, splitted into electron-main and renderer. Prefer `electron-main` and `electron-renderer`.

**Comment by simon04** [comment]
Thanks for the clarification. I submitted a PR.
