### ISSUE TITLE
WebpackManifestPlugin is no longer maintained

### ISSUE THREAD

**Issue by Bowser65** [webpack/webpack.js.org#4063]
The docs at https://webpack.js.org/guides/output-management/#the-manifest links to the [webpack-manifest-plugin](https://github.com/shellscape/webpack-manifest-plugin) plugin to extract manifest data in a JSON file, that can be used elsewhere.

I tried Webpack 5 on a project of mine and saw an error from this plugin, only to notice the maintainer put a notice on the repo 16 days ago saying the plugin is no longer maintained.

The docs should be updated to either remove the reference to this plugin, or link to a working plugin accomplishing this feature.

**Comment by madflow** [comment]
@shellscape undeprecated the repo: https://github.com/shellscape/webpack-manifest-plugin/commit/49f34a5c56db85c5076d1fae7f7be980022f932c

Let's give them a chance ;)

There are also:

* https://github.com/webdeveric/webpack-assets-manifest
* https://github.com/ztoben/assets-webpack-plugin
* https://github.com/FormidableLabs/webpack-stats-plugin

**Comment by chenxsan** [comment]
Closed as webpack-manifest-plugin 3 was out https://github.com/shellscape/webpack-manifest-plugin/releases/tag/v3.0.0 which is compatible with webpack 5.
