### ISSUE TITLE
Allow to change site theme (light <-> dark)

### ISSUE THREAD

**Issue by Jokero** [webpack/webpack.js.org#4072]
Currently theme is forced without possibility to change it. I prefer to use dark theme in MacOS, but I'm not very happy with dark theme of webpack site (it's too dark for me), so I'll be glad to use the light version (and maybe I'm not alone in this desire).

Toggle can be added next to language switch:
![image](https://user-images.githubusercontent.com/434135/96294695-74728b00-0ff5-11eb-8aae-62099d7457b2.png)

[x] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
I second this, it would be great to give user an option.

**Comment by Jokero** [comment]
@chenxsan Do you maybe know what icon can be used for that?

**Comment by chenxsan** [comment]
@Jokero I saw people use icons like below (from https://dark-mode-class-toggle.glitch.me/):

![moon](https://googlechromelabs.github.io/dark-mode-toggle/demo/moon.png)

![sun](https://googlechromelabs.github.io/dark-mode-toggle/demo/sun.png)
