### ISSUE TITLE
/loaders/html-loader/ contains invalid link

### ISSUE THREAD

**Issue by simon04** [webpack/webpack.js.org#4080]
https://webpack.js.org/loaders/html-loader/#export-into-html-files

![2020-10-18-191316](https://user-images.githubusercontent.com/782446/96374917-fd183500-1175-11eb-9438-7da8c6c94ba8.png)

https://raw.githubusercontent.com/webpack-contrib/html-loader/master/README.md uses the correct Markdown syntax.

**Comment by montogeek** [comment]
I think it will be fixed by https://github.com/webpack/webpack.js.org/pull/4054

**Comment by chenxsan** [comment]
fixed by https://github.com/webpack/webpack.js.org/pull/4054
