### ISSUE TITLE
Print link isn't working

### ISSUE THREAD

**Issue by jvmazagao** [webpack/webpack.js.org#4083]
__Feature to document__
The print section isn't open a dialog to print the section os save the section.

![After clicking the print section in documentation](https://user-images.githubusercontent.com/22477816/96721675-d8dd7380-1382-11eb-9aa2-bfa6039a3a9f.png)

__Author(s)__

__Additional information__

Steps -
1. Open [Webpack page](https://webpack.js.org/)
2. Go to the [documentation section](https://webpack.js.org/concepts/)
3. Click on the Print Section link.

What I'm as a user expect -
I expect in the concepts part or in every part to print the current section, or, to print all the documentation section.

[ ] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
Ah, I see, you mean the "Print Section" in the sidebar:

![image](https://user-images.githubusercontent.com/1091472/96809371-52da2f00-144d-11eb-91b1-694403fcd997.png)

I've misunderstood you as I thought it would be `Print Document`:

![image](https://user-images.githubusercontent.com/1091472/96809448-743b1b00-144d-11eb-8ccc-d90b79355e30.png)

Indeed, it's broken.

**Comment by chenxsan** [comment]
Hi, I've pushed a pull request to fix it, can you please try the [preview url](https://github.com/webpack/webpack.js.org/pull/4086#issuecomment-714201670) over there?

**Comment by jvmazagao** [comment]
> Hi, I've pushed a pull request to fix it, can you please try the [preview url](https://github.com/webpack/webpack.js.org/pull/4086#issuecomment-714201670) over there?

Working.
