### ISSUE TITLE
ignoreWarnings not in stats

### ISSUE THREAD

**Issue by jer-sen** [webpack/webpack.js.org#4084]
# Bug report

**What is the current behavior?**
Using option `stats.ignoreWarnings` throws an error.

**If the current behavior is a bug, please provide the steps to reproduce.**
`webpack.config.js` with `stats.ignoreWarnings` defined.

**What is the expected behavior?**
No error, cf doc https://webpack.js.org/configuration/stats/#statsignorewarnings
Instead it works well with just `ignoreWarnings` (same level as `stats`). Doc should be fixed.

**Other relevant information:**
webpack version:  5.1.3

**Comment by evilebottnawi** [comment]
@chenxsan feel free to close if it fixed

**Comment by chenxsan** [comment]
@evilebottnawi I can't as I have no authority doing it :)
