### ISSUE TITLE
[Vote] Design Vote Page

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#409]
@skipjack So it looks like our voters page got leaked and now has a crap ton of traffic. Do you think you could come up with a creative design for this as top priority for webpack.js.org?

**Comment by skipjack** [comment]
Sure I can start working on that.

**Comment by dmitriid** [comment]
Add a notice: "this as an alpha page, not complete, go away, follow our blog for announcements [here]"

Make sure it's visible on all browsers. 

It's a much more effective way to mitigate this than to frantically design the page and try to respond to everyone on twitter

**Comment by dmitriid** [comment]
Also: once the page is done, reset all counters and then open up to the public

**Comment by TheLarkInn** [comment]
Yes. I agree. I'm submitting some basic content on a branch, and then merging to develop for a deploy.

**Comment by TheLarkInn** [comment]
This can be the baseline for @skipjack to work off of.

**Comment by skipjack** [comment]
@TheLarkInn sorry for the delay on this... so I think @NejcZdovc has been working on this (see #444) so I don't want to overwrite any of his work. As mentioned in #430 I'm fairly busy this month but after I PR some current work I have locally I'll do whatever I can to help push this forward. 

@NejcZdovc maybe you want to close #444 and move that discussion over here?

**Comment by NejcZdovc** [comment]
@skipjack my issue is more focused on functionality of voting then on design. I am sadly not a designer, so I can't really help on design part, but I can help implement it if you do a quick mock. 

We can discuss my suggestion here as well, but I think this are two different things. On the other hand I agree that my issue should be done before this issue can be done.

If you guys like my suggestion I can easily start implementing it.

**Comment by sokra** [comment]
see also #447

**Comment by NejcZdovc** [comment]
I saw it, and I think that I can work off this PR

**Comment by skipjack** [comment]
> @skipjack my issue is more focused on functionality of voting then on design. I am sadly not a designer, so I can't really help on design part, but I can help implement it if you do a quick mock.

Lost track of this one, now that #474 is pretty much done I can try to help out more with the voting page. I'll start messing around with the design soon and open a PR.

**Comment by skipjack** [comment]
Ok finally got a few rough drafts together for this... interested in some feedback before I go too much further. I made three states, one for what the page would look like logged out, one logged in as a normal user, and one as an admin.

**Logged Out**

![voting_0000_logged-out](https://cloud.githubusercontent.com/assets/8988697/22856780/7dcc4716-f066-11e6-99f9-8d8f6552ec14.png)

**Logged in as a Normal User**

![voting_0001_normal-user](https://cloud.githubusercontent.com/assets/8988697/22856781/8e52477a-f066-11e6-8aa8-a4c359c066eb.png)

**Logged in as an Admin**

![voting_0002_admin-user](https://cloud.githubusercontent.com/assets/8988697/22856783/97b01888-f066-11e6-967a-645a5dbb6a36.png)

I kept it as single page interface for now, although down the road it might make sense to break it down into more pages. If people think this is heading in the right direction I'll add a comp for what the admin settings menu could look like and one for creating a new topic.

cc @sokra @TheLarkInn @NejcZdovc @pksjce (as I know you all have worked on the voting section)
cc @jhnns @pastelsky (as I figure you may have some design feedback)

P.S. I will push this to the [design repo](https://github.com/skipjack/webpack-design), even though it's deprecated, in case anyone wants to take a look at the raw PSD.

**Comment by NejcZdovc** [comment]
@pksjce I love it :+1:

**Comment by TheLarkInn** [comment]
Wow that's impressive looking. How does this look from a mobile standpoint? 

Also a fun tiny low hanging fruit feature we could open to the community is to make the little logos next to the influence could be tiny colored webpack logos. Overall it looks awesome.

**Comment by TheLarkInn** [comment]
Okay other thoughts. As much as I like showing each of the participants I worry about page loads for all the images aka extra requests. Maybe we can show the top 5 influencers along with a "total count" of people who have voted for that feature.

**Comment by skipjack** [comment]
> How does this look from a mobile standpoint?

Wanted to get some feedback first on the desktop version, I'll add a mobile comp soon.

> Also a fun tiny low hanging fruit feature we could open to the community is to make the little logos next to the influence could be tiny colored webpack logos.

Yea that could be cool, I did steal the shape for those icons from the logo.

> Maybe we can show the top 5 influencers along with a "total count" of people who have voted for that feature.

Sounds good, figured we'd have to limit it a bit. 

I'll come back with some updates soon and any other feedback/ideas in the meantime I'm all ears.

**Comment by pksjce** [comment]
I think the concern from the beginning has been that the CTA area ie. the vote button is very tiny. I could not think of a way to rectify it at all :(

**Comment by skipjack** [comment]
@pksjce 

> I think the concern from the beginning has been that the CTA area ie. the vote button is very tiny. I could not think of a way to rectify it at all :(

Yeah I see what you mean, and I was thinking we should definitely at least bump them up on mobile/smaller screens. Although maybe there is a better approach like using buttons or something too.

> What do the little gear icons lead to?

Those would be to a settings menu only available for admins. The options would include `archive`, `unarchive`, `lock`, `unlock`, and `edit`. I'll share a comp for those as well. I'm going to give this until the weekend before digging back into it, so if anybody else has other feedback please let me know before then...

Also, here were some of the things I found for inspiration on Dribbble, maybe they'll spark some other ideas too:

[Voting UI](https://dribbble.com/shots/221965-Voting-UI)
[Voteraction](https://dribbble.com/shots/1061395-Voteraction-REAL-CODED-PIXELS-animation)
[Voting Results](https://dribbble.com/shots/1022251-Voting-results)
[Mobile Comp](https://dribbble.com/shots/2752748-Voting-Screens-Dribbble-Rebound)

**Comment by sokra** [comment]
Maybe we can rename the participants to sponsors and allow everyone with high vote in golden influence to be visible in this list.

**Comment by skipjack** [comment]
@pksjce as for the admin menu, something like this:

![image](https://cloud.githubusercontent.com/assets/8988697/24886284/7ab5f44e-1e21-11e7-84a0-42e3ab136429.png)

@TheLarkInn working on a mobile version of the comp now. Should have something to share soon. Once I have that ready I think we should clean up some of the voting components, port them to another repo that can be maintained and managed separately from this one, and implement the new design. Anyone interested in maintaining that repo? @NejcZdovc @pksjce would either or both of you be?

I'd be happy to help with cleaning up and porting (I have a little bit of an obsession with refactoring/code cleanup 😆 ), but from there I probably won't have much time to tackle issues, new features etc. as there's plenty of issues that still need to be tackled here.

**Comment by NejcZdovc** [comment]
@skipjack this voting would still be part of webpack.org.js or could be used separately?

**Comment by skipjack** [comment]
@NejcZdovc we'd still integrate it as a section of this site, but it would have it's own `/src` directory, issue management, config, etc. This would...

- Take some weight off of this repo both in terms of code and issues.
- Allow us to have separate maintainers.
- Give us flexibility on where and how we deploy it (either here or elsewhere).
- Give it space to breath, add new features to, fix issues in isolation, etc.
- Allow us to version and release it in a more targeted way.

It could be consumed via an npm package or git submodule, and I think @bebraw and I would both be willing to help with the consumption and integration into this repo. There would definitely be some things to figure out but it basically already functions as a micro SPA in this site, via the `<Interactive>` component, and is already fairly isolated with it's own set of components and styling all under `/components/vote`.

There's definitely a little lifting to extract and consume it initially but I think in the long term the pros definitely outweigh the cons. It'll be nice to get started on too, as I think it'll be the first of a few things mentioned in #301 that will help keep this repo more targeted.

**Comment by NejcZdovc** [comment]
@skipjack ok let's do it :smiley:

**Comment by bebraw** [comment]
Maybe set up `webpack-contrib/voting-app` and then consume as a package? I can do the repo if you can agree on the name.

**Comment by NejcZdovc** [comment]
I would go a as a npm package, yes

**Comment by skipjack** [comment]
I'm good with that name 👍.

**Comment by bebraw** [comment]
Done. [Here](https://github.com/webpack-contrib/voting-app). You should have admin level rights to it.

**Comment by skipjack** [comment]
@NejcZdovc @pksjce I'll ping you once the designs are done and we can working on porting it. @bebraw any ideas on integration? Should we just have one wrapper component that imports the styling and top-level component, and renders the component in an antwar `<Interactive>` tag?

**Comment by NejcZdovc** [comment]
@skipjack ql, let me know when I can help

**Comment by bebraw** [comment]
@skipjack Wrapper sounds like a good starting point, yeah.

**Comment by skipjack** [comment]
Finally got a mobile comp together:

![image](https://cloud.githubusercontent.com/assets/8988697/25064142/3d19c72e-21c2-11e7-8eeb-3e3512553aef.png)

It's not perfect but I think this is a good starting point. I'm working on porting things to the new repository now, I'll create an issue for the redesign there and move over any existing vote issues from this repository.

@pksjce @NejcZdovc I created a vote-team and added you both. As soon as we finish the port I think we'd be happy for you two to take over as the core maintainers (plus anyone else from the core team like @sokra or @TheLarkInn who are interested). Then @bebraw and I will help with re-integration into this site via an npm package.

**Comment by NejcZdovc** [comment]
@skipjack so we should start porting now or will you do some more things in this repo?

**Comment by skipjack** [comment]
I have it almost ready, I'll push where I'm at in the next hour or so.
