### ISSUE TITLE
improve guides and other docs

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#4090]
__Feature to document__

There are a lot of usage `file-loader`/`url-loader`/`raw-loader` in guides (and other docs), for example https://webpack.js.org/guides/asset-management/#loading-fonts, we need to rewrite it on https://webpack.js.org/guides/asset-modules/, because these loader will be deprecated in the near future

__Author(s)__

Any

__Additional information__

I think it is high priority

[ ] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
I'll update them soon.
