### ISSUE TITLE
Webpack Dev Server command deprecated 

### ISSUE THREAD

**Issue by Kenludiaz** [webpack/webpack.js.org#4095]
Hello,
The command for running webpack dev server on the [documentation page](https://webpack.js.org/guides/development/) is outdated.
Please see https://github.com/webpack/webpack-dev-server/issues/2029#issuecomment-585207461

It should be `webpack serve`, not `webpack-dev-server --open`.

Thank you
[ X] I am willing to work on this issue and submit a pull request.

EDIT: Sorry this command (`webpack server`)compiled my bundle, but deleted my `./dist` files. Will try to find the right command before the documentation is modified.

EDIT: `./dist` files deleted, but project is still served. `webpack serve` seems to still be correct.

**Comment by chenxsan** [comment]
FYI, we did have a PR here https://github.com/webpack/webpack.js.org/pull/4091
