### ISSUE TITLE
Add CDN for static files

### ISSUE THREAD

**Issue by AntonGordei** [webpack/webpack.js.org#4105]
How can we add CDN to images, etc. But the scripts are loaded as before. 
How it was possible for example in webpack 4 and url-loader.

![image](https://user-images.githubusercontent.com/49307594/97419125-bddaa880-191a-11eb-8790-c53557964c38.png) 

How to do it using the assets module in the webpack 5?

**Other relevant information:**
webpack version:  "5.1.3"
Node.js version: v12.13.0
Operating System: Windows 10
Additional tools: yarn

**Comment by AntonGordei** [comment]
@evilebottnawi 
publicPath: (chunk)=> string
?

**Comment by AntonGordei** [comment]
@evilebottnawi 
Are there any other solutions to this problem?

**Comment by evilebottnawi** [comment]
No other solutions, you should use `publicPath`

**Comment by AntonGordei** [comment]
@evilebottnawi 
you can write an example for PublicPath as Function?

**Comment by evilebottnawi** [comment]
```js

publicPath: (pathData) => {
 // You logic
}
```

**Comment by AntonGordei** [comment]
@evilebottnawi

**Comment by AntonGordei** [comment]
@evilebottnawi 
i wrote this test function
![image](https://user-images.githubusercontent.com/49307594/97440414-7b27c900-1938-11eb-92af-6b4b47c6f0a5.png)
 and i get strange object
![image](https://user-images.githubusercontent.com/49307594/97440503-97c40100-1938-11eb-940b-4755c44582cd.png)

**Comment by AntonGordei** [comment]
@evilebottnawi

**Comment by AntonGordei** [comment]
@evilebottnawi

**Comment by AntonGordei** [comment]
@evilebottnawi I need answer. Because I have not found any information about this.

**Comment by evilebottnawi** [comment]
WIP on this, wait the new release

**Comment by FlenoryR** [comment]
@evilebottnawi

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
