### ISSUE TITLE
Randomize Open Collective sponsors and backers

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack.js.org#411]
The [current implementation](https://github.com/webpack/webpack.js.org/blob/0fe4e32067940ebd106ed73b591a56ea2d912048/components/support/support.jsx) just asks Open Collective for the first 5 sponsors and the 20 first backers. Unfortunately, the order is unclear. It's not alphabetical, it's not chronological – but it's also not random.

Although this might be a small detail, it's quite important for corporate sponsors to be visible on the page. We should randomize the occurrence.

**Comment by sokra** [comment]
It's by donation amount

**Comment by TheLarkInn** [comment]
Technically we can pull this information in via new JSON api's. If possible I'd love to just pull them all in. And if it gets too large, to then have a separate page, or something.

**Comment by jhnns** [comment]
> It's by donation amount

Oh ... that seems fair, as long as we have less then 5 sponsors with the maximum amount :)

> If possible I'd love to just pull them all in

I think we really need to be careful on the splash page to not make things slow.

---

Unfortunately, I'm biased here because my company Peerigon is a sponsor (and currently **not** visible anymore). However, I would rather have a random order instead of showing the most generous all the time while hiding the others all the time. The fairest solution would be to calculate the probability in relation to the donation amount.

**Comment by sokra** [comment]
> The fairest solution would be to calculate the probability in relation to the donation amount.

Sounds fair. This would motivate even small sponsors to donate.

Another idea: Show the top 5, and make a slideshow of the remaining ones.

**Comment by sokra** [comment]
btw. after deploy we show the top 20 sponsors, so everyone should be visible as we have 9 sponsors currently...

**Comment by rafaelrinaldi** [comment]
This might be useful to implement that: https://github.com/OpenCollective/OpenCollective/issues/271

**Comment by skipjack** [comment]
@rafaelrinaldi would you be interested in PR-ing this? The example in that issue you linked to does look like the right solution.

**Comment by rafaelrinaldi** [comment]
@skipjack Sure thing, I can give it a shot

**Comment by skipjack** [comment]
@rafaelrinaldi awesome! If you're not already aware, the related code is in [`components/support`](https://github.com/webpack/webpack.js.org/tree/master/components/support).

**Comment by rafaelrinaldi** [comment]
@skipjack Great stuff. Will try to play with it this weekend and give an update here.

**Comment by skipjack** [comment]
@rafaelrinaldi did you ever get anywhere with this? No pressure, just curious...

@sokra @jhnns @TheLarkInn is this still a priority or should we close this out? Maybe @TheLarkInn's idea of having it on a separate page ordered by donation amount would be fine. 

I've been thinking about simplifying the landing page to just the top section with quick calls to action (e.g. just the banner, visualization, headline, and a button or two like "Get Started" and "Contribute"). @pastelsky had a mock-up that kind of inspired this train of thought, at some point I may elaborate on that and create a separate issue/PR.

**Comment by skipjack** [comment]
Closed for now with #1159 in... if anyone wants to change how these are displayed feel free to use the newly fetched data to do so.
