### ISSUE TITLE
ag-grid logo is not properly visible under Dark Mode

### ISSUE THREAD

**Issue by LakinduK** [webpack/webpack.js.org#4119]
![image](https://user-images.githubusercontent.com/38062348/97865563-4365ac00-1cbf-11eb-8f52-7cfd0fd3f629.png)

**Comment by chenxsan** [comment]
I've pushed a quick fix setting background color to `white`. If you have better idea, let me know.

**Comment by anshumanv** [comment]
I think we should provide an option to toggle bw dark and light mode.

**Comment by chenxsan** [comment]
@anshumanv We do have a plan here https://github.com/webpack/webpack.js.org/issues/4072
