### ISSUE TITLE
Site does not work properly in IE11

### ISSUE THREAD

**Issue by Jokero** [webpack/webpack.js.org#4138]
Looks like it's broken after update to webpack 5 which transpiles its internals now to es2015 instead of es5. Is this an intentional decision to not support IE 11?

![image](https://user-images.githubusercontent.com/434135/98463383-ec366e80-21cb-11eb-922b-204b3d01e44a.png)

**Comment by chenxsan** [comment]
Can you check this preview https://webpack-js-org-git-feature-use-bionic.webpack-docs.vercel.app/ under IE 11? It's a preview right before the upgrade of webpack 5.

**Comment by Jokero** [comment]
Syntax error in another place
![image](https://user-images.githubusercontent.com/434135/98463741-a4651680-21ce-11eb-8944-a07157ca4ffb.png)

**Comment by chenxsan** [comment]
Then it might not function well under IE 11 for some time. Feel free to send a PR.

**Comment by Jokero** [comment]
I personally do not use IE11, just noticed it when tested theme switch. If no one complains we can close the issue

**Comment by evilebottnawi** [comment]
@chenxsan Let's use `target: ['web', 'es5']` or adding IE11 to browserslist and update webpack to latest (we have bugs)

**Comment by chenxsan** [comment]
I'll fix it soon.

**Comment by chenxsan** [comment]
I've spent some time tinkering with IE 11 support here https://github.com/webpack/webpack.js.org/pull/4247 but I don't think it will worth it. There're so many packages built without IE 11 support on npm:

```
          path.resolve(__dirname, 'node_modules/punycode'),
          path.resolve(__dirname, 'node_modules/react-banner'),
          path.resolve(__dirname, 'node_modules/react-tiny-popover')
```
And there could be more, hence I suggest dropping support for IE 11.

**Comment by chenxsan** [comment]
I'm closing this for two reasons:

1. Internet Explorer 11 desktop application will go out of support and be retired on June 15, 2022 as per https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549
2. We have 0.03% users in the last 30 days using IE

Anyway if anyone want to support it, feel free to file a pull request.
