### ISSUE TITLE
remove cache-loader from loaders list

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack.js.org#4144]
__Feature to document__

cache-loader deprecated in favor https://webpack.js.org/configuration/other-options/#cache

__Author(s)__

Any

__Additional information__

Loader: https://github.com/webpack-contrib/cache-loader

[ ] I am willing to work on this issue and submit a pull request.

**Comment by anshumanv** [comment]
wip

**Comment by chenxsan** [comment]
@anshumanv Do you need help?

**Comment by anshumanv** [comment]
ah this got misplaced in my todo, will PR today
