### ISSUE TITLE
Improve "watchOptions.ignored" documentation

### ISSUE THREAD

**Issue by birdofpreyru** [webpack/webpack.js.org#4146]
__Feature to document__

[The existing documentation of `watchOptions.ignored`](https://webpack.js.org/configuration/watch/#watchoptionsignored) should mention that cache-related options effectively affect the watching, specifically the watching of stuff inside `node_modules` folder. See discussion in https://github.com/webpack/webpack/issues/11952 for additional context.

__Author(s)__

__Additional information__

**Comment by evilebottnawi** [comment]
There is not problems in `ignore`, this is exactly how webpack works with `managedPaths`
