### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by nurpais** [webpack/webpack.js.org#4154]
## Feature request

**What is the expected behavior?**

Please light version of the site.

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by chenxsan** [comment]
We have a PR here https://github.com/webpack/webpack.js.org/pull/4137 implementing this feature , would be great if you can add your opinion there.
