### ISSUE TITLE
Code sample for guides

### ISSUE THREAD

**Issue by chenxsan** [webpack/webpack.js.org#4178]
Most Chapters in guides have strict orders, for example, you should finish https://webpack.js.org/guides/getting-started/ first before https://webpack.js.org/guides/asset-management/, otherwise you don't have that code sample to work on.

Thus I think it would be great to provide users with code sample in the beginning of every guide, with which they can download and pick up any guides they want to learn, instead of learning guides one by one in a strict order. But that means we have more things to maintain in future, I'm not sure if it will worth it.

**Comment by sagar-barapatre** [comment]
Can you please tell me Exactly what do we need to do here ?

**Comment by chenxsan** [comment]
@sagar-barapatre I haven't yet figured out what to do here.

**Comment by montogeek** [comment]
Yeah, not sure if worth it to maintain all that code.

Another solution is to explain that order at the very beginning of the guides, something like:

> Code examples in the guides use previous guides examples, please make sure to follow the guides in order or if you follow one guide in particular have all the example code from previous guides.

**Comment by chenxsan** [comment]
We've introduced some examples running on stackblitz, see https://github.com/webpack/webpack.js.org/tree/master/examples. I think this can be closed now.
