### ISSUE TITLE
Documentation: Get Started with Webpack

### ISSUE THREAD

**Issue by GeorgeAnagnostopoulos** [webpack/webpack.js.org#427]
The new docs are really awesome! 
In the getting started-mentioned index.html file with the bundle.js couldn't get it to work as it is. When I move the script tag inside the body tag everything works fine.

**Comment by SpaceK33z** [comment]
Would you be interested in doing a PR?

**Comment by GeorgeAnagnostopoulos** [comment]
If you could be kind enough to tell me how :)

**Comment by SpaceK33z** [comment]
Of course, you can find it here: https://github.com/webpack/webpack.js.org/blob/develop/content/get-started/index.md. If you click on the 'edit' button on the top-right, you can make edits. After saving the file, the GitHub UI will help you to make a PR.

**Comment by GeorgeAnagnostopoulos** [comment]
Thank you very much for your time!

**Comment by SpaceK33z** [comment]
Thank you too!

Fixed by #428
