### ISSUE TITLE
document webpack@5's support of workers

### ISSUE THREAD

**Issue by chenxsan** [webpack/webpack.js.org#4297]
> Just note - `webpack@5` support workers (web workers and Node.js worker threads) out of box, you don't need this loader, it was deprecated someday (need improve docs)
> 
> /cc @chenxsan Do we have examples/guide for web workers and etc stuff?
> 
> _Originally posted by @alexander-akait in https://github.com/webpack-contrib/worker-loader/issues/301#issuecomment-741898222_

**Comment by alexander-akait** [comment]
Let's close in favor https://github.com/webpack/webpack.js.org/issues/4341 (I think with example it will be easy to write)
