### ISSUE TITLE
Wrong path name is mentioned in repositories/README.md

### ISSUE THREAD

**Issue by gauravdas014** [webpack/webpack.js.org#4298]
The path name mentioned in repositories/README.md should be `src/utilities/fetch-package-repos.js` but currently, it's written as `src/utils/fetch-package-repos.js` which does not exist
<br/>
### Path mentioned in README.md
![Screenshot (581)_LI](https://user-images.githubusercontent.com/51530678/101793418-c7ffe180-3b2b-11eb-88e5-b0e28e3f1d24.jpg)
<br/>
### Path which actually exists
![Screenshot (582)_LI](https://user-images.githubusercontent.com/51530678/101793532-e960cd80-3b2b-11eb-8614-5000225bd6c0.jpg)

<br/>
 Would like to give a PR for fixing it.
<br/>

**Comment by snitin315** [comment]
PR Welcome

**Comment by gauravdas014** [comment]
Should I consider it as a typo and commit as a typo fix? @snitin315

**Comment by snitin315** [comment]
`docs: fix link`

**Comment by snitin315** [comment]
We can always change commit message while merging so its not a big deal here.

**Comment by gauravdas014** [comment]
Okay. Thanks. I just clarified being a new contributor to this repo.
