### ISSUE TITLE
EnvironmentPlugin handling of null/undefined for default values is inconsistent with docs

### ISSUE THREAD

**Issue by jdmnd** [webpack/webpack.js.org#4299]
# Bug report

**What is the current behavior?**
Using a `null` default value does not cause builds to fail if that environment variable is not defined. 
```js
new webpack.EnvironmentPlugin({
  ENV_TYPE: null
})
```

**If the current behavior is a bug, please provide the steps to reproduce.**
https://webpack.js.org/plugins/environment-plugin/

**What is the expected behavior?**
In the [documentation for EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/), it says this:
> To specify an unset default value, use null instead of undefined.

>If an environment variable is not found during bundling and no default value was provided, webpack will throw an error instead of a warning.

I infer that this means that using this will fail if no environment variables are provided:
```js
new webpack.EnvironmentPlugin({
  ENV_TYPE: null
})
```
Whereas this will not:
```js
new webpack.EnvironmentPlugin({
  ENV_TYPE: undefined
})
```
I expect this is an error in the documentation, or the wording is unclear.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by chenxsan** [comment]
I believe the document is right although I'm not the one wrote it.

If you have a rule without specifying an environment variable:

```
new webpack.EnvironmentPlugin(['ENV_TYPE'])
```
Then `process.env.ENV_TYPE` would be `undefined`, which is same to:

```
new webpack.EnvironmentPlugin({
  ENV_TYPE: undefined
})
```
In both cases, webpack will throw an error.

Hence the documentation recommends to use `null` to initialize ithe value if you don't care about the value of your variable at the beginning. Actually, anything other than `undefined` is ok here, e.g., `''`.

Maybe we can change it to something like:

> Do not  use `undefined` for the default value, otherwise webpack would throw an error.

**Comment by jdmnd** [comment]
Ok I see your point. 
I think the main part that was unclear to me was this sentence as it's ambiguous whether "an unset default value" means "a default value will not be set" vs "the default value shall be the unset value (ie undefined)":

> To specify an unset default value, use null instead of undefined.

The behaviour is actually the latter interpretation. 

> Maybe we can change it to something like:
> 
> >Do not use undefined for the default value, otherwise webpack would throw an error.

I'm not sure the docs should instruct people not to use it. 
In my application I need to use both to support both optional and non-optional environment variables:
```
new EnvironmentPlugin({
  APP_NAME: undefined,
  API_ROOT: null,
});
```
`APP_NAME` needs to be an error as it has not meaningful default value, but the application provides its own default if `API_ROOT` is not defined, so I don't want to treat that as an error. 

What about something like this?
> Note that `null` and `undefined` values behave differently. Use `undefined` for required environment variables, or `null` if they are optional.

**Comment by chenxsan** [comment]
@jdmnd Make sense. Would you love to file a pull request for it? Otherwise I can help.
