### ISSUE TITLE
Guides - Use ContextReplacementPlugin

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#43]
This is probably the best example on how to use this Plugin with webpack 2. (Thanks to @sokra). 

https://github.com/webpack/webpack/issues/2783

Document needs: 
- Link to "What's a ContextModule? ContextModuleFactory?"
- Explain this scenario in a generalized term, then reference the example above, (or create a new one). 
- Explain what each of the properties represent and how it relates to webpack.
- Caveats (if any)
- Interop with other Plugins, or properties in webpack config (I believe maybe the contextRegexp props under `module`?)

**Comment by skipjack** [comment]
Looks like this was addressed in #1127 and there's already a link to webpack/webpack#2783.

**Comment by skipjack** [comment]
@mover96 it seems you have a good bit of experience and knowledge on that plugin, based off reading through that issue. If you had time to review and potentially do a follow up pr to #1127, that would be awesome.
