### ISSUE TITLE
Document new performance budgets feature

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#435]
Now that most of the details are stamped out for https://github.com/webpack/webpack/pull/3350#pullrequestreview-9743611, we need to ensure that we are documenting the new configuration features, as well as specify what they represent. 

Here is the schema for the new information: 

```
    "performance": {
      "description": "Configuration for web performance recommendations.",
      "additionalProperties": false,
      "properties": {
        "hints": {
          "description": "Turn hints on or off",
          "type": "boolean"
        },
        "maxInitialChunkSize": {
          "description": "Total size of all initial chunks (in bytes)",
          "type": "number"
        },
        "maxAssetSize": {
          "description": "Filesize limit (in bytes) when exceeded, that webpack will provide performance hints",
          "type": "number"
        },
        "errorOnHint": {
          "description": "Throw errors instead of warnings when performance hints are found",
          "type": "boolean"
        }
      },
      "type": "object"
    }
```

Performance property: 
Default recommendations about web practice and performance. 

Reference https://github.com/webpack/webpack/issues/3216 for more details.

**Comment by TheLarkInn** [comment]
```
    "performance": {
      "description": "Configuration for web performance recommendations.",
      "anyOf": [
        {
          "enum": [
            false
          ]
        },
        {
          "additionalProperties": false,
          "properties": {
            "assetFilter": {
              "description": "Filter function to select assets that are checked",
              "instanceof": "Function"
            },
            "hints": {
              "description": "Sets the format of the hints: warnings, errors or nothing at all",
              "enum": [
                false,
                "warning",
                "error"
              ]
            },
            "maxEntrypointSize": {
              "description": "Total size of an entry point (in bytes)",
              "type": "number"
            },
            "maxAssetSize": {
              "description": "Filesize limit (in bytes) when exceeded, that webpack will provide performance hints",
              "type": "number"
            }
          },
          "type": "object"
        }
      ]
    },
```
this is the new schema, holding for my reference

**Comment by tarang9211** [comment]
@TheLarkInn can i help on this issue?

**Comment by TheLarkInn** [comment]
Looks like we missed this just a few days before closing this!!! Sorry I submitted and merged the PR for this feature. There are some other issues I'd be happy to assist you with. Feel free and @ mention me again next time (I should actually get it now), and I'll assist where needed.

**Comment by tarang9211** [comment]
No problem @TheLarkInn 
Could you point me to some beginner friendly issues for this repo? I'm completely new to the webpack repo and looking to help!

**Comment by TheLarkInn** [comment]
Sure well just looking at the issue list on here and finding something you are already comfortable with is a great start. Otherwise you can goto the webpack/webpack repo also and look at issues with a D* label which will tell you what the degree of difficulty will be.

**Comment by tarang9211** [comment]
D0 being the easiest contributions, right?

**Comment by TheLarkInn** [comment]
Yes :)
