### ISSUE TITLE
How to use callMemberChain？

### ISSUE THREAD

**Issue by McDaddy** [webpack/webpack.js.org#4363]
In the document，callAnyMember is in JavascriptParser Hooks. But actually I can't config callAnyMember in webpack 5. After check the source code I found new hook names callMemberChain, unfortunately, I still not find way to use it, my purpose is to listen to a callExpression. In my code below, I want to catch the `i18n.s` expression

```javascript
const i18n = {
  s: (a: string, b: string) => {
    return a + b;
  },
};
i18n.s('sss', 'fdp');
```  
so I config my plugin like this, but still no luck. 
```javascript
 apply(compiler) {
    compiler.hooks.normalModuleFactory.tap('AutoI18nPlugin', (normalModuleFactory) => {
      normalModuleFactory.hooks.parser
        .for('javascript/auto')
        .tap('AutoI18nPlugin', parser => { 
          parser.hooks.callMemberChain.for('i18n').tap('AutoI18nPlugin', (expression, members) => {
            console.log(expression, members);
          });
        });
    });
  }
```

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
