### ISSUE TITLE
webpack.js.org website doesn't load in Firefox private browsing mode (TypeError: navigator.serviceWorker is undefined)

### ISSUE THREAD

**Issue by richardxia** [webpack/webpack.js.org#4364]
__Feature to document__

When I try to view any page on https://webpack.js.org/ in Firefox's private browsing mode, I see the site content flash for a split second before it goes black. When I open up the Firefox developer console, I see the following error:

```
vendor.bundle.js:2:243873
TypeError: navigator.serviceWorker is undefined
    pl https://webpack.js.org/index.bundle.js:1
    Nu https://webpack.js.org/vendor.bundle.js:2
    unstable_runWithPriority https://webpack.js.org/vendor.bundle.js:2
    Ho https://webpack.js.org/vendor.bundle.js:2
    Pu https://webpack.js.org/vendor.bundle.js:2
    Tu https://webpack.js.org/vendor.bundle.js:2
    D https://webpack.js.org/vendor.bundle.js:2
    onmessage https://webpack.js.org/vendor.bundle.js:2
    3323 https://webpack.js.org/vendor.bundle.js:2
    s https://webpack.js.org/index.bundle.js:1
    1102 https://webpack.js.org/vendor.bundle.js:2
    s https://webpack.js.org/index.bundle.js:1
    3577 https://webpack.js.org/vendor.bundle.js:2
    s https://webpack.js.org/index.bundle.js:1
    1542 https://webpack.js.org/vendor.bundle.js:2
    s https://webpack.js.org/index.bundle.js:1
    4595 https://webpack.js.org/index.bundle.js:1
    s https://webpack.js.org/index.bundle.js:1
    o https://webpack.js.org/index.bundle.js:1
    x https://webpack.js.org/index.bundle.js:1
    <anonymous> https://webpack.js.org/index.bundle.js:1
    <anonymous> https://webpack.js.org/index.bundle.js:1
```

I don't think I had any issue loading the site yesterday, so I believe this was a recent change. Looking through the recent commits, I believe https://github.com/webpack/webpack.js.org/pull/4362 is the likely culprit.

It's not safe to attempt to access the `.serviceWorker` property without first checking that it is defined. See https://developer.mozilla.org/en-US/docs/Web/API/Navigator/serviceWorker:

> The feature may not be available in private mode.

I am running Firefox 84.0 on macOS 10.15.7 (Catalina).

__Author(s)__

@chenxsan, as he was the author of https://github.com/webpack/webpack.js.org/pull/4362.

__Additional information__

[x] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
@richardxia Wow, I didn't expect that! Thanks for heads-up, and I can confirm the problem. PR is welcomed!

**Comment by chenxsan** [comment]
And this seems to be firefox only as per https://bugzilla.mozilla.org/show_bug.cgi?id=1601916

**Comment by richardxia** [comment]
Thanks, I'll get a PR out shortly. I ran into a few issues with the development setup, but I have things working after I switched to `yarn`. I can file a separate ticket with the specific issues I ran into with `npm`.

**Comment by richardxia** [comment]
PR submitted: https://github.com/webpack/webpack.js.org/pull/4365
