### ISSUE TITLE
devServer.index documentation issue

### ISSUE THREAD

**Issue by elkhan** [webpack/webpack.js.org#4370]
https://webpack.js.org/configuration/dev-server/#devserverserveindex

It should be:

```
devServer: {
        staticOptions: {
            index: 'foo.html'
        }
    }

```
https://github.com/webpack/webpack-dev-server/issues/2540#issuecomment-627463732

**Comment by alexander-akait** [comment]
webpack-dev-server@4 in beta, docs will be updated after stable release
