### ISSUE TITLE
callAnyMember is gone but document is not updated yet

### ISSUE THREAD

**Issue by McDaddy** [webpack/webpack.js.org#4389]
# Bug report

**What is the current behavior?**
As I searched whole webpack 5 source code I didn't find keyword `callAnyMember` , but the official documentation is still there. Can you please update the  official documentation and suggest how to replace this hook?

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I guess the substitution hook should be callMemberChain, but so far I didn't try out the solution.
```
// code
myFunc.s(1)

// plugin
parser.hooks.callMemberChain.for('s').tap('MyPlugin', expression => {
      console.log(123); // never run into this
  });
```

**Other relevant information:**
webpack version:  5.9.0

**Comment by McDaddy** [comment]
> Yes that's the correct replacement.
> 
> ```js
> // code
> myFunc.s(1)
> 
> // plugin
> parser.hooks.callMemberChain.for('myFunc').tap('MyPlugin', (expression, properties) => {
>   console.log(properties); // ["s"]
> });
> ```

I have tried 
```
parser.hooks.callMemberChain.for('myFunc')
parser.hooks.callMemberChain.for('s')
parser.hooks.callMemberChain.for('myFunc.s')
```
none of them worked for me ......

**Comment by McDaddy** [comment]
for more details...

If I replace `myFunc` with `console`, it can work as expected. so I guess the difference is callee information. 
the user defined object can't be detected by this hook?

```
    apply(compiler) {
        compiler.hooks.compilation.tap('MyPlugin', (compilation, { _, normalModuleFactory }) => {
            normalModuleFactory.hooks.parser.for('javascript/auto').tap('MyPlugin', parser => {
              parser.hooks.callMemberChain.for('console').tap('MyPlugin', (expression, properties) => {
                console.log(expression); // works well
              });
              parser.hooks.callMemberChain.for('myFunc').tap('MyPlugin', (expression, properties) => {
                console.log(expression);  // never run into this
              });
            });
        });
    }
```

**Comment by chenxsan** [comment]
@McDaddy 

It seems to me that `myFunc.s` won't trigger the `callMemberChain`.

![image](https://user-images.githubusercontent.com/1091472/104113897-5046f180-5339-11eb-8ec0-74c311d3c073.png)

 But I'm not familiar with the internal of webpack so I could be wrong, could you create a reproducible repository and post it to webpack repository? The author seldom shows up here.

**Comment by McDaddy** [comment]
> @McDaddy
> 
> It seems to me that `myFunc.s` won't trigger the `callMemberChain`.
> 
> ![image](https://user-images.githubusercontent.com/1091472/104113897-5046f180-5339-11eb-8ec0-74c311d3c073.png)
> 
> But I'm not familiar with the internal of webpack so I could be wrong, could you create a reproducible repository and post it to webpack repository? The author seldom shows up here.

Yes！I've debugged into the same positon. I'm wondering whether author did it on purpose. Thank u! I'll create the reproducible repository later

**Comment by McDaddy** [comment]
@chenxsan  Sorry I realized I don't know how to create a webpack reproducible repository... could u give me a guide  about how to create a runnable webpack repository and how to post it to webpack repository

**Comment by chenxsan** [comment]
There's a guide when you file an issue using the bug template https://github.com/webpack/webpack/issues/new?assignees=&labels=&template=Bug_report.md. Or you can check any issues over there to see how other people were making it, e.g., https://github.com/webpack/webpack/issues/12293

**Comment by McDaddy** [comment]
> There's a guide when you file an issue using the bug template https://github.com/webpack/webpack/issues/new?assignees=&labels=&template=Bug_report.md. Or you can check any issues over there to see how other people were making it, e.g., [webpack/webpack#12293](https://github.com/webpack/webpack/issues/12293)

Thank u @chenxsan, I've created repository and raised an new issue [webpack/issues/12385](https://github.com/webpack/webpack/issues/12385)
