### ISSUE TITLE
Guides - Use with Docker

### ISSUE THREAD

**Issue by d3viant0ne** [webpack/webpack.js.org#44]
[Stub](https://github.com/webpack/webpack.io/blob/develop/content/how-to/use-with-docker.md).

> With the performance increases coming in the `Docker` Beta ( now public ) web development in an isolated Docker environment has not only become practical but extremely useful.

**Goal:** Guide to setup & configuration of both Docker & Webpack2 with examples covering all aspects of the development workflow using Webpack2 from dev build to prod bundling as well as dev server, watch, hmr, tree shaking & so on.

@bebraw - Assuming you like the idea, could i get a stub for `How To - Docker` and I will begin to outline the proposal in detail ( already have a whiteboard full of notes, concepts & examples ).

IMO this document, given it's scope should live outside of `How To: Use with third party tools` 74b90c400e799fb975344a5aae67f4fce49b7f8f

//cc @TheLarkInn

**Comment by bebraw** [comment]
Sounds good to me. I don't mind adding a stub.

I still have some work to do with my PR. Hopefully we get that merged soon.

**Comment by d3viant0ne** [comment]
That's fine, all the docker stuff will take a bit of time

**Comment by bebraw** [comment]
There's a stub now. So I would say it's safe to PR against the `develop` branch once you look into it.

**Comment by SpaceK33z** [comment]
@d3viant0ne, is this still something you're interested in? Otherwise I could work on this after I've finished #26. I've never used Docker before though (but this can be a good thing), so if anyone else wants to do it, that's fine.

**Comment by skipjack** [comment]
@d3viant0ne @SpaceK33z are either of you still interested in this? Imho this might make more sense as a blog post that we then link to from somewhere in the docs but I don't feel too strongly about it. In the end we may wind up with an __Integrations__ section (instead of just a single page) that contains things like this, _Typescript_, and other integrations. The main goal imo is to keep the core guides separate and more visible than any third-party integration discussions.

**Comment by d3viant0ne** [comment]
@skipjack - I have completely forgotten about this. I still have the draft docs buried on my ssd somewhere but I see your point about moving this to a different section of the documentation.

No argument from me on that point.

**Comment by skipjack** [comment]
Ah great, well if you want to PR what you have we can sort out how it's organized in #438. Or if you'd rather wait on it for now or just move it to a blog post I suggest we close for now and re-open down the road if anything.

Happy to help facilitate whatever direction you choose. I'm just trying to move some of these older issues forward.

**Comment by d3viant0ne** [comment]
Honestly, Docker anything is usually very purpose built. Even if I threw up a guide, I few it would only lead to a bunch of questions related to trying to turn a generic example into something that works in a particular CI / CD chain or local development workflow.

If the question comes up a lot in the future, I can resurrect a doc on the subject but most of what I see used now is Docker for supporting stack & webpack-dev-server on the host.

We can clean this up for now & revisit the topic in the future if there is a need.
