### ISSUE TITLE
text too narrow in firefox

### ISSUE THREAD

**Issue by SimonSiefke** [webpack/webpack.js.org#4404]
![text-too-narrow](https://user-images.githubusercontent.com/23744935/103907592-bfd29c00-5101-11eb-9052-c320503b50c4.png)

https://webpack.js.org/plugins/mini-css-extract-plugin/

![gitter](https://user-images.githubusercontent.com/23744935/103907761-f7414880-5101-11eb-8327-10fe103ddd36.png)

There is a `<div class="gitter">` which takes up lots of space

**Comment by SimonSiefke** [comment]
seems to be fixed now

**Comment by alxndrsn** [comment]
I still see this in Firefox 84.  The layout fixes if I hard-reload the page.
