### ISSUE TITLE
Using `file-loader` to load fonts doesn't work in production build.

### ISSUE THREAD

**Issue by pastelsky** [webpack/webpack.js.org#443]
With reference to #430 , we currently load font files on the site as embedded data URI's using the `url-loader`. This may not be ideal as users have to download both `woff` and `woff2` versions of the font, which is blocking in nature.

We can use `file-loader` to solve this issue, but antwar / configuration doesn't support it currently. @bebraw would have a better idea perhaps.

**Comment by SpaceK33z** [comment]
Don't know for sure, but this could be related to the hack I [had to do here](https://github.com/webpack/webpack.js.org/blob/develop/components/logo/logo.jsx#L3-L4). It seems that the `.svg` only works when you import it twice in different files. Very weird.

**Comment by bebraw** [comment]
This should be fixed now by #450. It's vanilla webpack setup now (antwar does less work).
