### ISSUE TITLE
Vote app

### ISSUE THREAD

**Issue by NejcZdovc** [webpack/webpack.js.org#444]
Based on a talk with @sokra I am creating an issue for a new vote mechanism.

Here is an [initial implementation](https://output.jsbin.com/qunevoyuhe), just to demonstrate the behaviour (it's not working on mobile yet).

What I wanted to achieve here is to reduce number of arrows for voting and to be mobile friendly. With this new system there would be only two buttons, up and down. If you click on a button you would increment your vote for 1. But if you would like to vote for a lot more, you can just hold down a button and amount for a vote will increase over time.

Current implementation (left number is your current vote, right number is increment):
1-5      =>  +1
5-10    =>  +2
10-40  =>  +5
40-70  =>  +10
70+     =>  +15

What do you think?

**Comment by SpaceK33z** [comment]
I like this. It reminds me a bit more of UserVoice (or services like that), where you get 3 points you can divide between feature requests. They also allow you to spend those 3 points on 1 feature, and have a simple up and down vote button. If you vote twice, it will say "+2" between the vote buttons.

**Comment by jhnns** [comment]
I also like this 👍

**Comment by NejcZdovc** [comment]
Great will implement it tomorrow

**Comment by NejcZdovc** [comment]
I think that I should wait for #447 to be merged and then work based on this. @pksjce already assumed in her design that we will have one button.

**Comment by NejcZdovc** [comment]
I added this vote app logic to PR #447
