### ISSUE TITLE
Proposal: remove contributors section in the web page

### ISSUE THREAD

**Issue by chenxsan** [webpack/webpack.js.org#4441]
I can understand benefits to show the `Contributors` section in the web page,

1. it might attract new contributors
2. it gives contributors credit for contributing

However, it becomes a problem when there're so many contributors on one page, for example, https://webpack.js.org/guides/code-splitting/

<img src='https://user-images.githubusercontent.com/1091472/104813385-dd131300-5843-11eb-925d-1daff1b54f08.png' width='200' />

If you're browsing that page on mobile phone:

<img src='https://user-images.githubusercontent.com/1091472/104813593-139d5d80-5845-11eb-93d2-23d67c628a86.png' width='200' />

This is sort of inconvenient if users want to scroll to the end just to make sure they don't miss something important after the `Contributors` section.

And I don't think webpack users would care about this section, it's a waste of their times and bandwidths to load contributors' avatar even though we are lazy loading them.

In addition, it will be a problem for contributors as well since they have to scroll multiple pages to see the body text:

<img src='https://user-images.githubusercontent.com/1091472/104845127-c5ed2780-590e-11eb-8106-c40c5e09e754.png' width='200' />

Thus I'm proposing to remove the whole `Contributors` section from the web page and the `contributors` field from the frontmatter of markdown files.

I don't think removing those would stop contributors from contributing, if we really want to show those contributors, we can add a link to pages like https://github.com/webpack/webpack.js.org/contributors-list/master/src/content/guides/code-splitting.md which list all contributors who had contributed.

**Comment by snitin315** [comment]
But It makes me happy to see my name there.

**Comment by snitin315** [comment]
Maybe we can limit it to recent 10-15 contributors name and display the rest with the help of a button labeled as `See more contributors`

**Comment by chenxsan** [comment]
> But It makes me happy to see my name there. 

Let's talk from the perspective of common webpack users, is it beneficial to most common webpack users?

I can understand your frustration to remove the section as I am one of the contributors listed in those pages.

And regarding the 'See More' suggestion, sure it would lessen the pain here, but it would only hide the problem as one day in the future there may be 200 contributors listed on the page, which then would become a real problem to contributors as they have to scroll down the markdown page to see the body part.

**Comment by alexander-akait** [comment]
I agree about it is unnecessary on every page, I think we can create separate page and move all contributors to there, also we can get them from github to avoid manually adding

**Comment by snitin315** [comment]
Single separate page sounds good 👌

**Comment by montogeek** [comment]
Another idea is to only show 3 (randomly picked) and put a link to the GitHub page to see the rest.
It will save:
- Space on mobile and desktop
- Load times
- Bandwidth

**Comment by alexander-akait** [comment]
I don't think anybody need to know contributors :smile: , no need unnecessary overload pages. But we should respect work of other contributors, so single page `Contributors` is maximum simple and good solution

**Comment by montogeek** [comment]
It is an open source project, potential contributors will look for it, existing contributors can link their contributions to potential employers, friends, etc.

Yeah, of course everything is in GitHub, but having it in the webpage itself helps with the spirit of the community around webpack.

**Comment by alexander-akait** [comment]
But they can use this link to potential employers, friends, etc.

**Comment by chenxsan** [comment]
> It is an open source project, potential contributors will look for it, existing contributors can link their contributions to potential employers, friends, etc.
> 
> Yeah, of course everything is in GitHub, but having it in the webpage itself helps with the spirit of the community around webpack.

If we list random contributors, it would no longer make sense for existing contributors to share that page with their potential employers, friends, etc. as the contributors listed on the page could be different for every one.

**Comment by snitin315** [comment]
I would like to implement the new `/contributors` page if we reach an agreement. 

Some pros that I can think of - 

- No need to manually update the contributor list anymore.
- Better visibility than being shown at the bottom (If anyone wants to show potential employers)
- save load time, bandwidth for actual docs conten.

**Comment by chenxsan** [comment]
Sure, I'll assign it to you. But it would be great if you can finish issues you're still working at first because the `contributors` page is not that urgent to have.

**Comment by chenxsan** [comment]
Here's what I think needs to be done:

- [ ] Add a new `contributors` page
- [ ] Remove `Contributors` section
- [ ] Clean up `contributors` field in frontmatter of markdown file

**Comment by sokra** [comment]
When the list gets long we could show only small avatars similar to github:

![image](https://user-images.githubusercontent.com/1365881/106944411-d4b54600-6726-11eb-9e9f-e5328e8732ed.png)

> * No need to manually update the contributor list anymore.

Instead of the manual list we could get the information from the git log. We can get the last 100 commits to a file and show the authors. This would also keep the list shorter as contributors vanish after some modifications. To get more user information you can use the github api and look up information for any commit from that user.

**Comment by chenxsan** [comment]
> When the list gets long we could show only small avatars similar to github:
> 
> ![image](https://user-images.githubusercontent.com/1365881/106944411-d4b54600-6726-11eb-9e9f-e5328e8732ed.png)
> 
> > * No need to manually update the contributor list anymore.
> 
> Instead of the manual list we could get the information from the git log. We can get the last 100 commits to a file and show the authors. This would also keep the list shorter as contributors vanish after some modifications. To get more user information you can use the github api and look up information for any commit from that user.

Any specific reason you want to retain the `Contributors` section? If we're referring to the benefits @montogeek listed before, then they're no longer available in your proposal version as the list would be dynamic then.

To common webpack users, `Contributors` section doesn't really benefit them. A `Last updated at 2022-2-22 2:22:22` message or `10 people have contributed to this page` would benefit them more in my opinion.

BTW, here's how it looks without the `Contributors` section https://webpack-js-org-git-fork-chenxsan-feature-remove-contributors.webpack-docs.vercel.app/api/.

**Comment by samal-rasmussen** [comment]
Can't rely on linking to a page to show off your work when the contributor list is dynamic.

As a user of the docs I would welcome the removal. They are just visual noise to me. I do sympathize with the contributors, but even so the contributions are logged in git and you can already link to the [github contributors list](https://github.com/webpack/webpack.js.org/graphs/contributors) if you need to show someone your work. And a separate contributors page in the docs would also make this info discoverable from the docs themselves.
