### ISSUE TITLE
The `webpack.ProvidePlugin` does not tree shake code as documented

### ISSUE THREAD

**Issue by zerustech** [webpack/webpack.js.org#4444]
# Steps to reproduce this issue

1.  Initialize the project structure:
```bash
$ cd <base>
$ mkdir test
$ cd test
$ yarn init
$ yarn add --dev webpack webpack-cli
$ mkdir src
```
2.  Create `src/index.js`:
```js
function component() {
    const element = document.createElement('pre');
    element.innerHTML = ['Hello', 'webpack', '5 cube is equal to ' + cube(5)].join('\n\n');
    return element;
}
document.body.appendChild(component());
```
3. Create `src/math.js`:
```js
export function square(x) {
    return x * x;
};

export function cube(x) {
    return x * x * x;
};
```

4. Create `webpack.config.js`:
```js
const path = require('path');
const webpack = require('webpack');

module.exports = {
    entry: './src/index.js',
    output: {
        filename: '[name].bundle.js',
        path: path.resolve(__dirname, 'dist'),
    },
    plugins: [
        new webpack.ProvidePlugin({
            cube: ['./math.js', 'cube'],
        }),
    ],
    mode: 'production',
    optimization: {
        runtimeChunk: true,
    },
};

```

5. Build the bundle:
```bash
$ yarn webpack
```

6. Expected Result: 
**ONLY** the `cube()` function is included in `dist/main.bundle.js`

7. Actual Result:
**BOTH** the `cube()` and the `square()` functions are included.

**Comment by chenxsan** [comment]
Could you share where the documentation stated that `ProvidePlugin` can be tree shaken?

**Comment by zerustech** [comment]
> Could you share where the documentation stated that `ProvidePlugin` can be tree shaken?

https://webpack.js.org/guides/shimming/#shimming-globals
> This would go nicely with Tree Shaking as the rest of the lodash library should get dropped.

**Comment by chenxsan** [comment]
I can't help. If you think it's a bug, please post it on https://github.com/webpack/webpack so the author can take a look.

**Comment by zerustech** [comment]
Thanks @chenxsan.

**Comment by chenxsan** [comment]
I'm closing this as this is webpack related.
