### ISSUE TITLE
[Docs] ProfilingPlugin outputPath example is incorrect

### ISSUE THREAD

**Issue by strarsis** [webpack/webpack.js.org#4448]
# Bug report

**What is the current behavior?**
In the current webpack documentation the [example for initializaing the `ProfilingPlugin`](https://webpack.js.org/plugins/profiling-plugin/#usage-custom-outputpath) is incorrect, 
as the `outputPath` is assigned a relative, non-absolute path`profiling/profileEvents.json` that causes an exception when trying to run webpack:
````
ValidationError: Invalid options object. Profiling Plugin has been initialized using an options object that does not match the API schema.
 - options.outputPath: The provided value "profiling/profileEvents.json" is not an absolute path!
   -> Path to the output file e.g. `path.resolve(__dirname, 'profiling/events.json')`. Defaults to `events.json`.
````

**If the current behavior is a bug, please provide the steps to reproduce.**
Use the example in thebpack documentation for the `ProfilingPlugin `.

**What is the expected behavior?**
The example in the documentation should use assign an absolute path, so the `ProfilingPlugin` initializes correctly.
The exception shows a suitable example: `path.resolve(__dirname, 'profiling/events.json')`

**Other relevant information:**
webpack version:  5.x
Node.js version: v14.15.3
Operating System: WSL 2 (Windows 10 x64)
Additional tools: `ProfilingPlugin`

**Comment by akgupta0777** [comment]
@strarsis I understood your issue. We should document that for better understanding.

**Comment by akgupta0777** [comment]
@strarsis do you want to work on that OR will I send a PR ?

**Comment by strarsis** [comment]
@akgupta0777: Added a fork branch with the fix: https://github.com/webpack/webpack.js.org/compare/master...strarsis:profilingplugin-outputpath-absolute
For creating a PR I have to sign a CLA and other things, I will probably do that, but currently have no time.
Could you create a PR out of that branch and merge it?

**Comment by akgupta0777** [comment]
I can't create a PR out of that branch I don't have access and also can't sign CLA because it requires GitHub user email. You have to do it yourself.
