### ISSUE TITLE
Webpack documentation completely broken on Firefox

### ISSUE THREAD

**Issue by pmrotule** [webpack/webpack.js.org#4458]
# Bug report

**What is the current behavior?**

The page layout of the documentation is completely broken on Firefox.

<img width="755" alt="image" src="https://user-images.githubusercontent.com/10983258/105140938-b3364680-5af8-11eb-9006-d07ea7ae0d76.png">

I personally added "flex: 0" to `.gitter` to fix the issue on my end.

<img width="357" alt="image" src="https://user-images.githubusercontent.com/10983258/105141240-250e9000-5af9-11eb-88d5-32f56a27a283.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

Go to https://webpack.js.org/plugins/split-chunks-plugin/ on Firefox.

**What is the expected behavior?**

Page not being broken like it is on Chrome or Safari.

**Other relevant information:**
webpack version:  Documentation of Webpack 5
Node.js version: N/A
Operating System: macOS Big Sur v11.1
Additional tools: Firefox v84.0.2

**Comment by alexander-akait** [comment]
@chenxsan Feel free to close, I think we need focus on changing cache strategy, a lot of problems with current strategy

**Comment by pmrotule** [comment]
@chenxsan It worked, thanks 🙌 
No more gitter indeed. Feel free to close the issue.

**Comment by chenxsan** [comment]
Let's keep it open until Network-first strategy is implemented.
