### ISSUE TITLE
watchOptions.ignored examples are wrong

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack.js.org#4463]
__Feature to document__

https://webpack.js.org/configuration/watch/#watchoptionsignored

__Author(s)__

Any

__Additional information__

we use `glob-to-regexp` package to convert glob to regexp and pass **absolute** path to ignore. Using:
- `node_modules/**` means `/^node_modules\/((?:[^/]*(?:\/|$))*)(?:$|\/)/` (i.e. all files starting with `node_modules`), so it should be `"**/node_modules/**"`
- `files/**/*.js` is also wrong and should be `**/files/**/*.js`
- also you can specify path using `path.posix.resolve(__dirname, './ignored-dir')` or `path.posix.resolve(__dirname, './ignored-dir/**/*.png')`

[ ] I am willing to work on this issue and submit a pull request.

**Comment by sokra** [comment]
> * "**/node_modules/**"

`"**/node_modules` would also work and is a bit shorter
