### ISSUE TITLE
Webpack 4 ignores `resolve.mainFields` in the global configuration

### ISSUE THREAD

**Issue by anseki** [webpack/webpack.js.org#4482]
Hi, thank you for the great tool.

I have a question. It might be a bug.

To import modules with `pkg.module` field (not `main` field) if possible, I wrote a `webpack.config.js` like:

```js
module.exports = {
  // ...
  resolve: {mainFields: ['module', 'jsnext:main', 'browser', 'main']},
  // ...
};
```

That worked fine in Webpack 3.
However, in Webpack 4, it seems that the specific is ignored when nested importing. That is, for example, a mod-A is imported with `module` field correctly, but a mod-B that the mod-A imports is imported with `main` field even if `module` field is given.

I added below, then that worked fine.

```js
module.exports = {
  // ...
  resolve: {mainFields: ['module', 'jsnext:main', 'browser', 'main']},
  module: {
    rules: [
      {
        test: require('path').resolve(__dirname, 'node_modules'),
        resolve: {mainFields: ['module', 'jsnext:main', 'browser', 'main']}
      }
    ]
  }
  // ...
};
```

I found this: https://github.com/webpack/webpack/wiki/Changelog-WIP

> Resolving can now be configured with `module.rules[].resolve`. It's merged with the global configuration.

It seems that the default `module.rules[].resolve` is used when that is not specified, and the global configuration is ignored.
I tried `resolve: {mainFields: []}` as the `module.rules[].resolve`, and I expected that the empty `mainFields` list is merged with the global `mainFields` list, but an error "Module not found" occurred. That is, it seems that the global `mainFields` was ignored.

Is this correct behavior of Webpack 4?
And also, to import all modules with `pkg.module` field, are both the first and the second `resolve` required?

(Sorry, my English is poor.)

**Comment by alexander-akait** [comment]
@chenxsan We need docs this https://github.com/webpack/webpack/blob/master/lib/config/defaults.js#L992, i.e. options for resolver can be configured by dependency, i.e. you can setup different options for `mjs`/`cjs`/`new URL('./file.ext', import.meta.url)`/etc. I think example with different options for `mjs` and `cjs` and `new URL()` will be enough (because popular)
