### ISSUE TITLE
`output.publicPath: "auto"`

### ISSUE THREAD

**Issue by sokra** [webpack/webpack.js.org#4491]
__Feature to document__

`output.publicPath: "auto"`

Only works for web and web worker targets.

Determines the publicPath automatically from `<script>` tag.

__Author(s)__

@sokra 

__Additional information__

Should be listed on:

* https://webpack.js.org/configuration/output/#outputpublicpath
* https://webpack.js.org/guides/public-path/

[ ] I am willing to work on this issue and submit a pull request.

**Comment by snitin315** [comment]
WIP
