### ISSUE TITLE
UseEntry function return value documented as "options object"

### ISSUE THREAD

**Issue by vvanpo** [webpack/webpack.js.org#4493]
https://webpack.js.org/configuration/module/#useentry

In the documentation for the `function(info)` `UseEntry` type, it claims (emphasis mine):

> A UseEntry can also be a function which receives the object argument describing the module being loaded, and must return *an options object.*

But it should really be a non-function `UseEntry` object, right? In the ensuing example:

```
(info) => ({
  loader: 'svgo-loader',
  options: {
    ...
```

The `options` object is a property of the return value, but not the return value itself.

**Comment by chenxsan** [comment]
Yes, I believe it should return a non-function `UseEntry` object from the function `UseEntry`. Pull request welcome.
