### ISSUE TITLE
Navigation links in sidebar have poor user experience

### ISSUE THREAD

**Issue by e-cloud** [webpack/webpack.js.org#451]
If memory serves me, this docsite is developed with React.

Obviously, it is supposed to be a SPA.

Navigating inside the SPA ought to be smooth, at least partial view update.

However, clicking on the links in sidebar will act like a traditional site. That's not what a SPA should behave.

**Comment by bebraw** [comment]
It's not SPA technically. It does progressive enhancement and a tiny bundle per each page if the pages have interactive elements in them.

It would be possible to get SPAish user experience if we wrote a routing layer (something to capture anchor clicks and update browser history).

**Comment by e-cloud** [comment]
I am sorry for my misunderstanding. Hope it would get better. I haven't learn React yet, otherwise I may give some help.

**Comment by bebraw** [comment]
The navigation problem is mostly outside of React. Literally pure JavaScript. It would be nice to tackle this, though. I might give it a quick go.

**Comment by bebraw** [comment]
Here's the high level idea: http://neugierig.org/software/blog/2014/02/single-page-app-links.html .

In addition the site generator should be able to generate fragments (json?) that contains the script references and the content so the replacement process can be done. This might mean some level of separation between navigation and the actual content to replace.

**Comment by skipjack** [comment]
Closing this in favor of #924 which already has a PR open for it (#933) that I'll be reviewing shortly.
