### ISSUE TITLE
webpack trying to parse @font-face urls

### ISSUE THREAD

**Issue by DannyMcwaves** [webpack/webpack.js.org#452]
webpack is trying to require or import the urls of the fonts in the CSS file 
and consequently raises an error on the command line indicating build error.
This excludes the build of that particular file from the rest of the files.

Any solution or similar encounters?

**Comment by dangodev** [comment]
@DannyMcwaves this might be a better issue for https://github.com/webpack/webpack. This is for the documentation. Unless you’re referring to specific doc content that needs correction?

Webpack does try to handle `@font-face` `src` files, and this behavior is intended for the most part. You can use either [file-loader](https://github.com/webpack/file-loader) if you want to simply keep that link to the file in the CSS (and have the browser manually request the font file), or you can alternately use [url-loader](https://github.com/webpack/url-loader) if your intent is to base64 embed the font file straight into the CSS. Webpack affords you both options.

**Comment by DannyMcwaves** [comment]
Thanks @dangodev. The first one is exactly what I wanted.
And sorry for the issue misappropriation.
