### ISSUE TITLE
Note about System.import

### ISSUE THREAD

**Issue by danez** [webpack/webpack.js.org#454]
I was reading through the migration guide and noticed the section about `System.import`.
When reading it it sounds like `System.import` is already a thing and the new specified way of how to do dynamic loading, but it is not and probably never will be in its current form (see whatwg/loader#149, whatwg/loader#147 and https://github.com/tc39/proposal-dynamic-import).

I see that some users probably already use `System.import` and it's nice webpack supports the current spec, BUT It would probably be good to add a note that says that this is not a final specification and that it is very early stage and will be changing in future. I think users should be aware of that so that they can decide if they take the risk of a evolving and changing spec.

I also saw some other sections that said `TODO document System.import` which maybe should add the same.

**Comment by SpaceK33z** [comment]
See https://github.com/webpack/webpack/pull/3413, support for `import()` will probably land in the next beta.

**Comment by bebraw** [comment]
Yeah, the current beta implements `import()`. `System.import()` can be considered deprecated now.

**Comment by prewk** [comment]
pull request #499 fixes the deprecated `System.import` stuff in the migration guide.

**Comment by bebraw** [comment]
Closing since #499 was merged.
