### ISSUE TITLE
Loader interface documentation fails to mention what the parameters in the loader interface do.

### ISSUE THREAD

**Issue by matyasf** [webpack/webpack.js.org#4630]
__Feature to document__

https://github.com/webpack/webpack.js.org/blob/master/src/content/api/loaders.md

__Author(s)__

@TheLarkInn | @jhnns | @tbroadley

__Additional information__

https://github.com/webpack/webpack.js.org/blob/master/src/content/api/loaders.md fails to mention what the parameters in the loader interface do. From the article it becomes quickly clear that the loader interface looks like `function (content, map, meta)`, but the reader can only guess what these parameters do (this is especially true for `map` and `meta`)

[ ] I am willing to work on this issue and submit a pull request. -- Sorry, I can only guess what they do.

**Comment by chenxsan** [comment]
There're listed here https://webpack.js.org/api/loaders/#thiscallback

**Comment by matyasf** [comment]
Isn't that the signature for the function object that is returned by `async()`? From the site:

https://webpack.js.org/api/loaders/#thisasync

and the example from the doc:

```
var callback = this.async();
...
callback(null, result, sourceMaps, meta);
```

Also as I see these interfaces need 3 parameters at most (`content`, `map`, `meta`), not 4.

**Comment by chenxsan** [comment]
Loaders are chained, the first parameter means whether to throw the error in current loader, pass `null` means there's no error, and the next loader will receive all other third data, i.e., `content`, `map`, `meta`. But yes, I agree it's not explicitly documented, users have to infer it from `this.callback`.

**Comment by chenxsan** [comment]
I've filed a pull request here https://github.com/webpack/webpack.js.org/pull/4648/files, do you think it will solve the problem here?

**Comment by matyasf** [comment]
looks good, I've added a comment
