### ISSUE TITLE
Remove usage of `clean-webpack-plugin` in favor `output.clean`

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack.js.org#4658]
__Feature to document__

Now we can use https://webpack.js.org/configuration/output/#outputclean

https://webpack.js.org/guides/output-management/

__Author(s)__

Any

__Additional information__

Maybe we have `clean-webpack-plugin` plugin in other places, need check

[ ] I am willing to work on this issue and submit a pull request.

**Comment by snitin315** [comment]
On it.

**Comment by chenxsan** [comment]
@snitin315 Do you need help?

**Comment by snitin315** [comment]
@chenxsan thanks for proposing, I have the bandwidth to work on it today. Sorry for the delay 😄.
