### ISSUE TITLE
improve description of the `output.library` option and guide for libraries

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack.js.org#4687]
__Feature to document__

https://webpack.js.org/configuration/output/#outputlibrary
https://webpack.js.org/guides/author-libraries/

__Author(s)__

Any

__Additional information__

output.library support object notation https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json#L1474, we it is very poorly described

`output.library.export` should be preferred over `output.libraryExport`
`output.library.type` should be preferred over `output.LibraryType`

`output.libraryExport` and `output.LibraryType` were keep for compatibility, but I think we will drop them in future, so we need rewrite it 

https://webpack.js.org/guides/author-libraries/ should be updated too using `output.library.type`/`output.library.export`. 

> With webpack 3.5.5, using libraryTarget: { root:'_' } doesn't work properly (as stated in issue 4824). However, you can set libraryTarget: { var: '_' } to expect the library as a global variable.

Solved and should be removed. 

Also I think will be great to add more example with different types and exports and names, because right now it is very hard to understand from docs how to generate libraries.

[ ] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
I guess you were talking about `output.libraryTarget` instead of `output.LibraryType`? `output.LibraryType` is not exposed as far as I see.

**Comment by chenxsan** [comment]
Related pull request https://github.com/webpack/webpack/pull/10448
