### ISSUE TITLE
Wrong documentation for WatchIgnorePlugin

### ISSUE THREAD

**Issue by vyobukhov** [webpack/webpack.js.org#4743]
__WatchIgnorePlugin__

WatchIgnorePlugin has wrong documentation:
```
## Options

- `paths` (`[string, RegExp]`): A list of RegExps or absolute paths to directories or files that should be ignored
```

But it actually expects an `options` object with an array property `paths` in it as stated here:
https://github.com/webpack/webpack/blob/master/lib/WatchIgnorePlugin.js#L97

P.S. type definitions are also incorrect

**Comment by chenxsan** [comment]
The type definition doesn't follow the convention of typescript but a homemade one https://webpack.js.org/contribute/writers-guide/#configuration-defaults-and-types, I agree it's confusing.
