### ISSUE TITLE
Module not found: Error: Can't resolve 'path' 

### ISSUE THREAD

**Issue by p3im4n** [webpack/webpack.js.org#4792]
hi
Im going to make a ftp client bundle for my web
I test basic-ftp and ftp from nmp 
then I got many error while compiling such as:

ERROR in ./node_modules/basic-ftp/dist/Client.js 5:15-30
Module not found: Error: Can't resolve 'path' in '/var/www/disn.ir/html/node_modules/basic-ftp/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

the question is,is that possible any way??
to use ftp client on front end?
be cause of tcp security stuff....
the other question,how do i know which npm module can use in web frontend and which not?

**Comment by alexander-akait** [comment]
Please read error message and use this, you can't use Node.js module in browser, you need polyfill or disable this module

**Comment by p3im4n** [comment]
> you can't use Node.js module in browser

this is not true, there is many example frontend web site based on node modules
but I read not all of them cant be bundled for using on frontend

if I am wrong give me a reference about that
best regards
