### ISSUE TITLE
Advise for official document page

### ISSUE THREAD

**Issue by loynoir** [webpack/webpack.js.org#4799]
# Background
Install with latest webpack, keep up to latest official document, ran into weird bug.
Dig a little into that bug, seems it is because of a documented 3rd party loader outside of webpack-contrib, is not really webpack5-able.

# Expected behavior
Any 3rd party loaders outside of community [webpack-contrib](https://github.com/webpack-contrib), should 
1. Within official document page, with **hightlight**
2. Not within official document page

# Actual behavior
Official document contains, at least one, 3rd party loader **outside** of community **without highlight**. 
Not really want to point out which one.

# Personal Opinion
Within official document [page](https://webpack.js.org/loaders) of webpack loaders, should only contains 
1. official webpack loaders
2. community supported 3rd party webpack loaders.
3. neccesary packages required by above two

Any 3rd party loaders outside of community [webpack-contrib](https://github.com/webpack-contrib), should 
1. Within official document page, with **hightlight**
2. Not within official document page

Besides, I saw keyword securiy when submit issue. 
Emm, it's also might be a security issue too.

**Comment by alexander-akait** [comment]
I think we need remove `extract-loader` from our docs, this loader is broken...

**Comment by loynoir** [comment]
@alexander-akait `babel-loader` is too essential. I dont think babel-loader would be a problem.  😆

**Comment by chenxsan** [comment]
Generally we would avoid including documentations for third-party loaders or plugins that are not from `webpack` or `webpack-contrib`, readme from their own repositories could serve more up-to-date documentation.
