### ISSUE TITLE
API - Document MultiStats

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack/webpack.js.org#480]
"By accident" I found out about [`MultiStats`](https://github.com/webpack/webpack/blob/f18989c712894bba13ebfb6dfb3f50fc44b0d12a/lib/MultiCompiler.js#L190) today. Looks like neither the old nor the new docs mention `MultiStats`.

This actually broke my code when I switched from a normal compiler config to the _multi compiler config_, because I tried to access `stats.compilation` which is `undefined` on `MultiStats` (but not a normal `Stats`).

**Comment by skipjack** [comment]
@webpack/documentation-team any idea what's involved to get this documented? It seems the [stats configuration](https://webpack.js.org/configuration/stats/) page may need to updated and something would have to be added in the [API docs](https://webpack.js.org/api/)? This is a part of webpack I'm not too familiar with but I'd be happy to help push this forward however I can.

@donaldpipowitch where do you think would be an appropriate place (or places) to add this documentation? Is there anywhere specific you were looking when you were trying to debug that issue?

**Comment by skipjack** [comment]
There's also [this small section](https://webpack.js.org/api/plugins/compiler/#multicompiler) on the `MultiCompiler`.

**Comment by kevinphelps** [comment]
The @types/webpack type definitions also need updating.

**Comment by sokra** [comment]
The Stats object interface has only these methods:

``` js
toJson(opt)
toString(opt)
hasErrors()
hasWarnings()
```

The `compilation` property is private.

webpack either returns a `Stats` or a `MultiStats` which both fulfill this interface.

**Comment by skipjack** [comment]
Ok and those are all documented [here](https://webpack.js.org/api/node/#stats-object). I'll just add a note about the `MultiStats` which I guess is returned when using the `MultiCompiler`. @donaldpipowitch so it seems the answer to your issue is really just that `compilation` is not meant to be accessed.

**Comment by donaldpipowitch** [comment]
Good to know, thank you all.

**Comment by kevinphelps** [comment]
Is the `stats` array on `MultiStats` supposed to be private also? https://github.com/webpack/webpack/blob/f18989c712894bba13ebfb6dfb3f50fc44b0d12a/lib/MultiCompiler.js#L191

**Comment by skipjack** [comment]
@kevinphelps good question, @sokra? It seems maybe the private methods should be prefixed by an `_` to prevent confusion?

**Comment by donaldpipowitch** [comment]
A `_` prefix would be awesome.
