### ISSUE TITLE
Can we follow the Contribution Guide with using pnpm?

### ISSUE THREAD

**Issue by meglio** [webpack/webpack.js.org#4810]
Following the Contribution Guide with using pnpm fails with lots of errors like he following; is this expected?

<img width="531" alt="image" src="https://user-images.githubusercontent.com/282177/113574154-b2727280-965a-11eb-905f-e248d7734977.png">

**Comment by chenxsan** [comment]
We use yarn specific feature like 'resolutions' so I don't expect pnpm to work out of the box.
