### ISSUE TITLE
Improve examples for compiler hooks

### ISSUE THREAD

**Issue by vivek1729** [webpack/webpack.js.org#4813]
**Compiler Hooks**

The compiler hooks api [doc](https://webpack.js.org/api/compiler-hooks/) has a section that points to an example usage
![image](https://user-images.githubusercontent.com/1658576/113634361-766feb00-9623-11eb-97f4-bbcab95787a9.png)

I noticed that the repo uses the deprecated `compiler.plugin` apis in its [example](https://github.com/pksjce/webpack-internal-examples/blob/master/compiler-example/compiler-example.js#L15) and also relies on a much older version of [webpack](https://github.com/pksjce/webpack-internal-examples/blob/master/package.json#L12) (ver 2.x).  I am not sure if the repo is actively maintained as I see some open issues and PRs from 3 years ago.

Having updated examples for compiler APIs would be a really useful resource for the community. I could get a head start and use the `hooks` api only because of the helpful examples linked in the `Tip` section despite them being outdated.

Is there a central repo to track examples for webpack APIs? Not sure if it's part of this repo.
I'd be happy to contribute an example for the `hooks` api with the latest versions of webpack.

[x] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
> Is there a central repo to track examples for webpack APIs? Not sure if it's part of this repo.

No, I don't think so.

---

I think we can remove the outdated tip.

**Comment by vivek1729** [comment]
Thanks for the reply @chenxsan . I can remove the outdated tip. As an alternative, I'd also be happy to scaffold a tiny repo with an example for compiler hooks. I can link to that example instead. Please let me know if that's acceptable. Happy to submit a PR for either.

**Comment by chenxsan** [comment]
Thanks for your offer but we want to avoid linking to external repository because it's a maintenance burden. Users can always find real world examples from webpack plugins' repository if they want.

**Comment by vivek1729** [comment]
Thanks @chenxsan for the quick clarification. Have submitted a PR for the minor update.

**Comment by chenxsan** [comment]
Closed via https://github.com/webpack/webpack.js.org/pull/4866
