### ISSUE TITLE
Search doesnt respect the V4 prefix

### ISSUE THREAD

**Issue by danielo515** [webpack/webpack.js.org#4824]
It is not possible to search docs for V4. You go to V4 version of the docs, search for anything and it redirects you to the v5 docs, it is very frustrating.
Please, provide a way to search on the v4 docs, thanks.

**Comment by chenxsan** [comment]
I think we need another `apiKey` from algolia https://github.com/webpack/webpack.js.org/blob/master/src/components/Navigation/Navigation.jsx#L115. Not sure know who owns the algolia account for webpack documentation. cc @webpack/documentation-team

**Comment by chenxsan** [comment]
FYI, It's live on v4.webpack.js.org now.
