### ISSUE TITLE
__webpack_require__(null)

### ISSUE THREAD

**Issue by YikaJ** [webpack/webpack.js.org#4837]
webpack@5.31.0 still get this problem

![image](https://user-images.githubusercontent.com/8725110/113966327-7b21e280-9861-11eb-8e64-e316565b33a1.png)

`concatenateModules: false ` can fix it。

@Knagis @sokra  Could you reopen this issue?

_Originally posted by @YikaJ in https://github.com/webpack/webpack/issues/11856#issuecomment-815426944_

**Comment by alexander-akait** [comment]
@chenxsan We need doc what plugins from `webpack.optimize` should be used only when `mode: 'none'`

**Comment by chenxsan** [comment]
> @chenxsan We need doc what plugins from `webpack.optimize` should be used only when `mode: 'none'`

Roger that. I'll see where to mention it.

**Comment by YikaJ** [comment]
Thanks a lot.
