### ISSUE TITLE
Switch themes in mobile view as well

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack.js.org#4892]
**Feature to document**
Currently, no way in UI to switch between light and dark themes on mobile.

**Author(s)**
Any

**Additional information**

**Comment by chenxsan** [comment]
See https://github.com/webpack/webpack.js.org/pull/4137#issuecomment-808094536. Anyway, if you have an idea, file a pull request and let's see how it works.

**Comment by hetanthakkar1** [comment]
@chenxsan Can you assign it to me!

**Comment by hetanthakkar1** [comment]
@chenxsan Can we implement this design, i.e. I will shift down the search bar button in next row and place the theme button like this https://elastic.github.io/eui/#/

![image](https://user-images.githubusercontent.com/38756320/117587689-c3704100-b13c-11eb-8354-1343abf46a6b.png)

**Comment by chenxsan** [comment]
@hetanthakkar1 I'm not sure if it's a good choice, you may have a try.
