### ISSUE TITLE
index.html in getting started tutorial is not regenerated as stated

### ISSUE THREAD

**Issue by wlnirvana** [webpack/webpack.js.org#4893]
The [getting started](https://webpack.js.org/guides/getting-started/) tutorial nicely points out that ideally `index.html` should not be in `dist/` folder, and suggests readers will be guided to programmatically generate this file later on.

https://github.com/webpack/webpack.js.org/blob/d49899f7ade166ccbd320633e8b7dcd23a39e2af/src/content/guides/getting-started.md#L147

Unfortunately, there are no further instructions on this.

**Comment by DYW972** [comment]
Hello, 

I don't understand your question. Can you give more details?

I just started the `Getting Started Guide` and from now I can automatically generate the `index.html` file in the dist folder.

Maybe I did not understand your question well or maybe I did not understand the guide well.

Best regards

**Comment by wlnirvana** [comment]
@DYW972 I'm confused as well. Are you talking about [this page](https://webpack.js.org/guides/getting-started) as well? The current version explicitly stated that\

> You may have noticed that index.html was created manually, even though it is now placed in the dist directory.

It mentions migrating to an automatic way, but does not really implement that. Did I miss anything?

**Comment by chenxsan** [comment]
It's in another guide here https://webpack.js.org/guides/output-management/#setting-up-htmlwebpackplugin, I think you are right, it's sort of confusing. Would you like to send a pull request to add a link?

**Comment by DYW972** [comment]
@wlnirvana Ok now I understand, Thanks to @chenxsan . Sorry my English is bad. You are right but in the second sentence you can read this: 

> **_**Later on in this guide, we will generate index.html rather than edit it manually**_**.

And like @chenxsan said after the **Getting Started** guide, comes **Asset Management** and **Output Management** (where you will find the automatization of the index.html)

I'm agree with @chenxsan It can be confusing. Adding a link to the **Output Management** guide will be more efficient.

Like this:

> [Later ](https://webpack.js.org/guides/output-management/#setting-up-htmlwebpackplugin) on in this guide, we will generate index.html rather than edit it manually. Once this is done, it should be safe to empty the dist directory and to regenerate all the files within it.

or like this:

> Later on in this guide, in the [Output Management](https://webpack.js.org/guides/output-management/#setting-up-htmlwebpackplugin), we will generate index.html rather than edit it manually. Once this is done, it should be safe to empty the dist directory and to regenerate all the files within it.

Thank you for you question @wlnirvana and thank you @chenxsan for your answer !

🖖
