### ISSUE TITLE
Concepts - Modules

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#49]
[Stub](https://github.com/webpack/webpack.js.org/blob/develop/content/concepts/modules.md).

Feel free to comment here if you have ideas on what this guide should cover. Link to potential resources too.

**Comment by pksjce** [comment]
Trying to understand what would go under this topic? Isn't the chapter on loaders enough to get across the point? Could you give some pointers on the expected content here?

**Comment by bebraw** [comment]
Yeah, that's a valid point. I renamed the issue to simply `Concepts - Modules`.

From webpack's point of view everything is literally a module. That's where the initial name came from.

Considering expected content, there probably isn't that much. This would be a good place to explain what type of modules webpack supports and what modules are.

**Comment by TheLarkInn** [comment]
Since we now have `concepts/modules` I'm going to close this. If anyone else disagrees we can open it back up. But I think the content that we have there get's us one step closer.
