### ISSUE TITLE
Document placeholder slice option

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#490]
I.e. `[chunkhash:8]`. This should be mentioned somewhere.

**Comment by simon04** [comment]
From my findings, there are (at least) three possibilities:
* https://github.com/webpack/webpack/blob/master/lib/TemplatedPathPlugin.js#L7-L8
* https://github.com/webpack/webpack/blob/master/lib/HashedModuleIdsPlugin.js#L30
* https://github.com/webpack/webpack/commit/44f8709fbd47cb67ac138478ff4348b9d6745d96#diff-7473dd12403a310ad8cf18d0ab9f10b9R25

**Comment by bebraw** [comment]
Sidenote: this does **not** work with `[name]`. I got bitten by that a while ago.
