### ISSUE TITLE
API - Stats JSON Schema

### ISSUE THREAD

**Issue by walfly** [webpack/webpack.js.org#491]
I'm working on some tools to help my company find areas to optimize our builds. I'm doing this primarily through traversing the stats file. There's documentation on the options I can toggle on my builds, but I haven't found any good descriptions of the structure of the json itself. For the most part it seems pretty straight forward, I imagine reasons is a list of modules that include a given module, but I'm seeing some unexpected results when I try to use moduleId and the modules array to filter reasons by chunk. It would be very helpful to have a reference for this information. Does this exist anywhere? If so, can it be made public?

**Comment by dmitriid** [comment]
+1 to that. I've been looking for a definition, and the only "documentation" is a 1.1 MB [JSON file](https://github.com/webpack/analyse/blob/master/app/pages/upload/example.json) linked from node.js API in 1.x docs

**Comment by skipjack** [comment]
@walfly By schema do you mean type definitions for each property or a page documenting and giving examples all potential properties of the JSON? I guess both would probably make sense. I'd be happy to help push this forward but I think we need more clarification from @sokra before we can really get started (and yeah it would be great if there was already a doc on this somewhere, or at least a commented example of the JSON.

Let's see though...

`errors` and `warnings` seem to be straightforward. Each is just an array of strings -- each string containing a message and stack trace.

As for the other top-level information:

`time` - Build time in milliseconds (?)
`version` - Webpack version used for the build.
`hash` - Hash of the build.
`filteredModules` - ?
`assets` - An array of objects each representing a file from the `output` of the build
`chunks` - An array of objects each representing a chunk

As for the nested objects:

### `assets` object

``` js
{
    "chunkNames": [], // The names of the chunks this asset contains ?
    "chunks": [ 10, 6 ], // The chunk IDs this asset contains ?
    "emitted": true, // Whether or not it made it to the `output` directory ?
    "name": "10.web.js", // The `output` filename
    "size": 1058 // The size of the file in bytes ?
}
```

### `chunks` object

``` js
{
    "entry": true, // Whether or not it's an entry chunk
    "files": [
        // An array of filename strings that contain this chunk (?)
    ],
    "filteredModules": 0, // ?
    "id": 0, // The ID of this chunk
    "initial": true, // ?
    "modules": [
        // An array of objects representing each module -- see below
    ],
    "names": [
        // An array of chunk names contained within this chunk (?)
    ],
    "origins": [
        // ? -- see below
    ],
    "parents": [], // Parent chunk IDs? Names?
    "rendered": true, // ?
    "size": 188057 // Chunk size in bytes (?)
}
```

`origins` object (found within `chunks` objects)

``` js
{
    "loc": "", // ?
    "module": "(webpack)\\test\\browsertest\\lib\\index.web.js", // ?
    "moduleId": 0, // ?
    "moduleIdentifier": "(webpack)\\test\\browsertest\\lib\\index.web.js", // ?
    "moduleName": "./lib/index.web.js", // ?
    "name": "main", // ?
    "reasons": [] // Same as `reasons` in the `modules` object below ?
}
```

### `modules` object

``` js
{
    "assets": [], // A list of `assets` objects (?)
    "built": true, // Maybe this mean compiled, loaded or output?
    "cacheable": true, // Whether or not this module is cacheable (?)
    "chunks": [
        // IDs of chunks that contain this module (?)
    ],
    "errors": 0, // Number of errors when resolving or processing the module (?)
    "failed": false, // Whether or not compilation failed on this module (?)
    "id": 0, // The ID of the module
    "identifier": "(webpack)\\test\\browsertest\\lib\\index.web.js", // Another ID ?
    "name": "./lib/index.web.js", // Path to the actual file
    "optional": false, // ?
    "prefetched": false, // Whether or not the module was prefetched (a build optimization)
    "profile": { // Module specific compilation stats? Corresponds with normal `stats` object?
        "building": 73,
        "dependencies": 242,
        "factory": 11
    },
    "reasons": [], // ?
    "size": 3593, // Module size in bytes?
    "source": "// Should not break it...\r\nif(typeof...", // The stringified raw source (?)
    "warnings": 0 // Number of warnings when resolving or processing the module (?)
}
```

I know this isn't perfect but maybe it'll give us a start... @bebraw @sokra can you review this and help fill in the missing bits? @walfly @dmitriid feel free to fill in any you guys may know that I don't as well.

**Comment by walfly** [comment]
@skipjack Yes both is really what I'm looking for. I've been able to figure most of it out from inspecting the object, but for properties like `module.reasons` I'd really like a clear explanation I can refer too.

**Comment by skipjack** [comment]
@walfly no problem.. I think we can use that as a general outline and hopefully get some help from the @webpack/core-team to fill in the blanks. I'll try to ping some people so we can get the ball rolling on this.

**Comment by TheLarkInn** [comment]
Yes reasons is built and collected into each module as the graph is being traversed.  Reasons provides a chain of information that shows why the current module is inside the bundle etc

**Comment by sokra** [comment]
We could create a doc page similar to the "Configuration" page, with commented and linked json data.

**Comment by skipjack** [comment]
Starting to dig into this now, expect a PR within the next day or two.

**Comment by skipjack** [comment]
@TheLarkInn @sokra @webpack/documentation-team I will need help filling in some of the blanks (e.g. `?` above) but I figure that's easier to do on PR with an outline in place.

**Comment by sokra** [comment]
> but I figure that's easier to do on a PR with an outline in place.

Yep, I'll help you once a page exist.
