### ISSUE TITLE
Change the existing code to Typescript

### ISSUE THREAD

**Issue by khushal87** [webpack/webpack.js.org#4936]
**Feature to document**
The repository currently uses JS in the codebase and I believe that if we move it to Typescript the code will be much more maintainable in the future and unlock new possibilities.

**Author(s)**
Any

**Additional information**
Adapting to Typescript will unlock strict type checking and makes the code more readable.

- [x]  I am willing to work on this issue and submit a pull request.

**Comment by khushal87** [comment]
I want feedback of the community if I can proceed on it.

**Comment by chenxsan** [comment]
Generally I think it's a good idea. But I would love to collect more inputs from other maintainers. cc @webpack/documentation-team

**Comment by khushal87** [comment]
@chenxsan Thanks, looking for the same.

**Comment by arpitBhalla** [comment]
@khushal87 Can we both work on this?, we can divide the work

**Comment by khushal87** [comment]
Sure, let's wait for approval first. @arpitBhalla

**Comment by khushal87** [comment]
Can I start on it? @chenxsan

**Comment by chenxsan** [comment]
Thanks for your patience, however there's no response from other members so far. I'll let you know when it's decided.

**Comment by todortotev** [comment]
count me in too

**Comment by chenxsan** [comment]
I'm closing this now. There's no interest from other maintainers so far, besides, I think JavaScript works quite good for this project as most of the code are markdown files, and we do have `prop-types`, e2e tests etc. to ensure the code not to break. Introducing TypeScript might improve the code quality but it would make the bar to contribute higher.

Thank you again for your interest to contribute.
