### ISSUE TITLE
Concepts - Loaders

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#50]
[Stub](https://github.com/webpack/webpack.io/blob/develop/content/concepts/loaders.md).

Feel free to comment here if you have ideas on what this guide should cover. Link to potential resources too.

**Comment by manekinekko** [comment]
Hi @bebraw can you assign this one to me?

**Comment by TheLarkInn** [comment]
Done

**Comment by TheLarkInn** [comment]
@manekinekko do you need any help with this. Let me know!!

**Comment by manekinekko** [comment]
@TheLarkInn sorry for the delay. I was preparing for some upcoming confs. 
Here is the PR https://github.com/webpack/webpack.js.org/pull/249

**Comment by TheLarkInn** [comment]
No pressure at all, just wanted to offer help if you need it.

**Comment by dangodev** [comment]
I’d love to know the preferred syntax going forward—`rules` or `loaders`? `query` or `options`? Or just understanding what to use where.

**Comment by TheLarkInn** [comment]
We have kept backwards compatibility to loaders and query but going forward you should use rules and options.

**Comment by dangodev** [comment]
@TheLarkInn thanks for clarifying. That was my assumption based off the fact they seemed like new additions to 2.x, but wasn’t totally sure.

**Comment by SpaceK33z** [comment]
I'm going to close this since #383 was merged, which covers the loader concepts good enough I think. I used huge parts of @manekinekko's content, so props to him!
