### ISSUE TITLE
Migrating Guide: Code Splitting inaccuracy?

### ISSUE THREAD

**Issue by sunyang713** [webpack/webpack.js.org#502]
Hi, I was reading over the migrating documentation, and under the section for code-splitting it says:

```javascript
function onClick() {
  import("./module").then(module => {
    module.default;
  }).catch(err => {
    console.log("Chunk loading failed");
  });
}
```

https://github.com/webpack/webpack.js.org/blob/develop/content/guides/migrating.md#code-splitting-with-es2015

Shouldn't the function inside the `.then()` return `module.default`?
```diff
  import("./module").then(module => {
-   module.default;
+   return module.default;
  }).
```

**Comment by TheLarkInn** [comment]
That is correct!!! Would love a PR for this!!!!

**Comment by sunyang713** [comment]
okay, super simple so I'm on it.

**Comment by bebraw** [comment]
Merged.
