### ISSUE TITLE
Increase accessibility for webpack newbies

### ISSUE THREAD

**Issue by aem** [webpack/webpack.js.org#505]
Webpack can be intimidating. I'm an experienced JS dev with years of experience but every time I had looked at webpack's docs before they were just a little too dense and intimidating to be useful for a beginner. Now I can attribute that to not having an understanding of basic webpack concepts. 

Speaking at least for myself, when I first navigate to a library's page I immediately click on the first "Docs" link I can find and look for a "Getting Started" guide. Unfortunately webpack's "Introduction" page assumes basic knowledge of webpack's concepts.

I'd like to propose adding a link along the lines of **New to webpack? Learn the basics [here](https://webpack.js.org/concepts/)** to the top of the Documentation page. I had been to the webpack site several times but never even thought of clicking on the Concepts link, I always went straight to Docs. This might make things a little easier for the naive, such as myself :) 

as per https://twitter.com/TheLarkInn/status/809810824990720001

**Comment by TheLarkInn** [comment]
Let's do it!!

**Comment by bebraw** [comment]
Merged.

**Comment by TheLarkInn** [comment]
Awesome!!!
