### ISSUE TITLE
Outdated documention for `NormalModuleReplacementPlugin` when using function replacement option (webpack5)

### ISSUE THREAD

**Issue by russaa** [webpack/webpack.js.org#5059]
the documentation for [NormalModuleReplacementPlugin](https://github.com/webpack/webpack.js.org/blob/2419dffba1adc6a03d49066e8acb16e3c32bb2ba/src/content/plugins/normal-module-replacement-plugin.md#advanced-example) is outdated with regard to the `Advanced Example` for `webpack5`:

The example in the documentation instructs to replace `resource.request` with the modified request, but in `webpack5`, the field `resource.createData.request` needs to be changed instead (see source code for `webpack5` [NormalModuleReplacementPlugin.js](https://github.com/webpack/webpack/blob/ff1b314d30fbf996dc0acf37b7b789eab8ca33e1/lib/NormalModuleReplacementPlugin.js#L45)).

The documentation should be updated, changing [src/content/plugins/normal-module-replacement-plugin.md](https://github.com/webpack/webpack.js.org/blob/2419dffba1adc6a03d49066e8acb16e3c32bb2ba/src/content/plugins/normal-module-replacement-plugin.md) at line 45:
```javascript
          resource.request = resource.request.replace(
```
to
```javascript
          resource.createData.request = resource.request.replace(
```

**Comment by chenxsan** [comment]
I believe you're talking about the `afterResolve` case while the example shows `beforeResolve` case:

```js
if (resourceRegExp.test(result.request)) {
  if (typeof newResource === 'function') {
    newResource(result);
  } else {
    result.request = newResource; // it's mutating the `result.request`
  }
}
```

**Comment by russaa** [comment]
yes, of course, you are correct.

Ideally the description should explain, that the plugin is used during 2 phases and so on.

However, failing that, the advanced example should instruct to modify the result in a way that would work for both phases, e.g. changing it to something like
```javascript
          resource.request = resource.request.replace(
            /-APP_TARGET/,
            `-${appTarget}`
          );
          if(resource.createData) resource.createData.request = resource.request;
```

Or, alternatively, it should explicitly state that users should look into the source code of the plugin:
otherwise it may not work sometimes, and users will have no clue why that is (thinking they did everything correctly, since they followed the documentation).
