### ISSUE TITLE
Concepts - Plugins - Index

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#51]
[Stub](https://github.com/webpack/webpack.io/blob/develop/content/concepts/plugins.md).

Feel free to comment here if you have ideas on what this guide should cover. Link to potential resources too.

**Comment by bebraw** [comment]
To quote @okbel from #42:

> ## **Situation**
> People are using Webpack because every React tutorial have Webpack as its module bundler. > Some of them are beginners, some others come from Angular with experience in browserify. 
> I've seen a lot of beginners struggle with bundle sizes. And even though everything looked fine. Something was off. Some sorting in the plugins array messes up the final size. 
> I detected this from people coming from Angular. Since most of angular tutorials/examples don't have webpack in it. Usually they try to extend the default config with the prod config and if the order is not correct, the bundle size incease and you have no clue of what's going on.
> I've seen it several times.
>
> ## **Issue**
> Documentation does not clarify about plugins load order.
>
> ## **Solution**
> Detailed explanation while handling plugins in Webpack.

**Comment by jcreamer898** [comment]
I'd be happy to help out on some of the CommonsChunkPlugin stuff. I've been doing an advanced webpack series here... http://jonathancreamer.com/advanced-webpack-part-1-the-commonschunk-plugin/

Let me know if and how you would want me to get started!

**Comment by bebraw** [comment]
@jcreamer898 Cool to hear. I have the rough ideas [here](https://github.com/webpack/webpack.io/blob/develop/content/writers-guide.md) (article structure, available custom syntax). I imagine `CommonsChunkPlugin` specific how to could work. There could be something in the existing structure already.

You could pick a stub you find interesting or create your own. Propose an outline for an article and we can go from there.

**Comment by TheLarkInn** [comment]
I was creating an issue for him to work off of. And both of you are willing to edit the "Goals" etc.

**Comment by bebraw** [comment]
@TheLarkInn Sure, that works.

**Comment by TheLarkInn** [comment]
https://github.com/webpack/webpack.io/issues/67 

Part of me wants to preserve the more higher level "List of Plugins" because its recognizable and comfortable for users, and then a single page devoted to each plugin with more understandable syntax, etc. Feel free to update

**Comment by TheLarkInn** [comment]
Fixed with #198
