### ISSUE TITLE
Keep pathname when selecting language dropdown list

### ISSUE THREAD

**Issue by cs09g** [webpack/webpack.js.org#5105]
**Feature to document**
It's better to replace hostname only when selecting a language on the dropdown list(ENGLISH, 中文, 한국어).

When you search for something on google and enter the document site then change the language. it moves to the main page of the language. Actually, the pathname is the same and the difference is the hostname.

* [x] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
Makes sense. Feel free to send a pull request.
