### ISSUE TITLE
Check lint on dev start

### ISSUE THREAD

**Issue by cs09g** [webpack/webpack.js.org#5109]
![image](https://user-images.githubusercontent.com/7428017/123160309-fb430600-d4a8-11eb-836d-33b43c5eec94.png)

There are many lint errors on the current master branch. The reason It's possible is lint checking is not strict here. If no one runs lint before commit, lint would be the thing no one use. 

It may be better to strict lint on dev-server start.

i.e, `"start": "npm run clean-dist && npm run lint && webpack serve --config webpack.dev.js --env dev --progress --node-env development",`

* [x] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
Which file? If you mean `printable.md`, it's generated automatically, there's no need to lint it. We have lint-staged to run `lint-js` on .js, .jsx, .md to make sure there is no lint issues when you're committing, so I think it wont be a problem. Besides, running lint at dev stage would introduce another overhead to the already long-running dev command.

**Comment by cs09g** [comment]
Oh, I see. It's in `printable.md` Then why is it not in .eslintignore?

**Comment by chenxsan** [comment]
It won't be generated in dev environment. Only when you run 'yarn build' will it be generated.
