### ISSUE TITLE
[Docs.] Fix the correct code sequence in the splitchunksplugin guide

### ISSUE THREAD

**Issue by Luccasoli** [webpack/webpack.js.org#5192]
**Feature to document**

In this documentation page: https://webpack.js.org/guides/code-splitting/#splitchunksplugin
I believe that should be a paragraph showing the change you should undo to keep doing the content explained in that topic

I noticed this because in this page: https://webpack.js.org/guides/code-splitting/#dynamic-imports
It expect that your code still is that code made in the last topic (code-splitting/#splitchunksplugin), but in the splitchunksplugin topic, it expect that your code it is that one created in https://webpack.js.org/guides/code-splitting/#entry-points (two topic before)

[X] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
Thank you for raise this issue, but the current version seems right to me.

At the end of [`Entry Points`](https://webpack.js.org/guides/code-splitting/#entry-points), we mentioned some pitfalls, and:

> Let's remove this duplication in next section.

And there're two ways to remove that duplication.

I.e., 

1. Entry dependencies
2. SplitChunksPlugin

Which means both are based on the configuration of `Entry Points` section:

```js
const path = require('path');

  module.exports = {
    mode: 'development',
    entry: {
      index: './src/index.js',
      another: './src/another-module.js',
    },
    output: {
      filename: '[name].bundle.js',
      path: path.resolve(__dirname, 'dist'),
    },
};
```
Hence there's no need to undo anything first in `SplitChunksPlugin` section.

**Comment by Luccasoli** [comment]
I understand, but since I did the two approaches, one after the other, I thought I could have this warning to refactor the previous code, but as these are two different ways to change the initial code, it makes sense to leave it as is

Thanks for the response! :D
