### ISSUE TITLE
React Hot MD guide app configuration won't hot reload

### ISSUE THREAD

**Issue by timurtu** [webpack/webpack.js.org#527]
After following the steps of [the React HMR guide](https://github.com/webpack/webpack.js.org/blob/develop/content/guides/hmr-react.md) I am left with an app that won't hot reload. 

What happens is on every file change of the __App.js__ the browser does reload, and it seems from the webpack-dev-server log as if the module rebundles, but nothing happens.

__[HMR] Waiting for update signal from WDS...__ does print to the browser console although no changes are seen in the browser. The only way I've been getting app changes to register with this config is if I manually run `webpack`. 

What should the __index.html__ look like?

**Comment by macbem** [comment]
I also have an issue with this guide, I'm getting an `You may need an appropriate loader to handle this file type.` error for my index.js for some reason.

**Comment by chrisVillanueva** [comment]
@timurtu @macbem 

I ran through the React HMR guide and it ran fine on my local.  I'm running:

- ubuntu 16.04 LTS
- node v6.1.0
- npm v4.0.5
- "devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.13.2",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-2": "^6.13.0",
    "css-loader": "^0.23.1",
    "postcss-loader": "^0.9.1",
    "react-hot-loader": "^3.0.0-beta.6",
    "style-loader": "^0.13.1",
    "webpack": "^2.1.0-beta.25",
    "webpack-dev-server": "^2.1.0-beta.0"
  }
-  "dependencies": {
    "react": "^15.3.0",
    "react-dom": "^15.3.0"
  }

After reading the Guide, I was able to produce this in my browser:

### Initial Load of index.html after setting up webpack+react+babel
![hmr-react-1](https://cloud.githubusercontent.com/assets/1554280/21748550/bbf30d3a-d555-11e6-96ef-16a108943ba7.png)


### index.html after changing text in /src/components/App.js
![hmr-react-2](https://cloud.githubusercontent.com/assets/1554280/21748558/d41053b4-d555-11e6-9744-cb3afa8c44f7.png)

Perhaps a couple of steps needed more clarification.  I created a PR to update the Guide.
Hopefully this helps.

**Comment by macbem** [comment]
You ran the HMR guide, because my PR with fixes has already been merged to the docs - sorry, I forgot to mention it here.

**Comment by timurtu** [comment]
What were the fixes?

**Comment by macbem** [comment]
I have changed the required Webpack version.

**Comment by timurtu** [comment]
I tried the [guide](https://webpack.js.org/guides/hmr-react/) again and ran into a small issue, and that was destructuring __resolve__ from __path__ in the __webpack.config.js__. `const { resolve } = require('path')`

I'm not sure which node version has destructuring, I'm running v4.6.1, but after changing it to a normal require statement everything seems to be working.
