### ISSUE TITLE
Guides - Integrate with Third Party Tools

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#53]
[Stub](https://github.com/webpack/webpack.io/blob/master/content/guides/integrations.md).

Feel free to comment here if you have ideas on what this guide should cover. Link to potential resources too.

**Comment by pksjce** [comment]
What does it mean to use third party tools? As webpack plugin? Or in the bundle?

**Comment by bebraw** [comment]
Grunt, Gulp, Mocha, Karma. I guess it would be better to have specific how to for each. This is more like a seed article that can be split up.

**Comment by pksjce** [comment]
Ok got it. Thanks.

**Comment by skipjack** [comment]
There's actually already a [corresponding guides page](https://webpack.js.org/guides/task-test-runner/) with `[TODO]s` for each of those tools already in case anyone is interested in pr-ing them.

**Comment by skipjack** [comment]
I may try to tackle this. I feel like a fairly simple page with links to things like [gulp-webpack](https://www.npmjs.com/package/gulp-webpack) and [grunt webpack](https://github.com/webpack-contrib/grunt-webpack) would do.
