### ISSUE TITLE
Sidebar item anchor links reloads the page

### ISSUE THREAD

**Issue by tsriram** [webpack/webpack.js.org#530]
This may be related to #451 but one thing that I thought could be fixed quickly is the links to anchors within the same page. In the current scheme of things, clicking on an anchor link reloads the entire page. Guess react-router's `Link` component is used to render the links and I couldn't find a way to fix it though the [documentation for `Link`](https://github.com/ReactTraining/react-router/blob/master/docs/API.md#link) says it is possible.

So I just tried with a quick-and-dirty fix here - https://github.com/tsriram/webpack.js.org/commit/d24781c9dde4d0dec54f5ebe3ce82c880610d838 - using plain old anchor tag and it works!

Would be great if someone can actually fix the `Link` component to stop refreshing the page for anchor tags. Else, I could send a PR with this, if it makes sense.

**Comment by bebraw** [comment]
Hi,

The generated result doesn't actually use react-router at all. The routing solution is for development only.

**Comment by bebraw** [comment]
That fix of your is sensible. Feel free to PR.
