### ISSUE TITLE
[Module Federation] collision between modules of differents remotes.

### ISSUE THREAD

**Issue by penguintree** [webpack/webpack.js.org#5308]
# Bug report

**What is the current behavior?**
A host consumes two different remotes.
Both remotes have the same file structure, i.e. both exposes `./src/main.js` under different names.

remote package 1 :
```
const moduleFederation = new ModuleFederationPlugin({
   name: 'somePackage',
   filename: 'somePackage.entrypoint.js',
   exposes: {
      './x': './src/main'
   }
});
```
remote package 2 :
```
const moduleFederation = new ModuleFederationPlugin({
   name: 'anotherPackage',
   filename: 'anotherPackage.entrypoint.js',
   exposes: {
      './y': './src/main'
   }
});
```
host :
```
const moduleFederation = new ModuleFederationPlugin({
   name: 'host',
   filename: 'host.entrypoint.js',
   remotes: {
      'firstRemote': 'somePackage@http://localhost:9001/somePackage.entrypoint.js',
      'secondRemote': 'anotherPackage@http://localhost:9002/anotherPackage.entrypoint.js'
   }
});
```

In the host app, when using both federated modules, the first one overrides the second.
```
import firstPackage from 'firstRemote/x';
import secondPackage from 'secondRemote/y'; // here object from firstRemote/x is imported, but it's not the same instance.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
[This repository](https://github.com/penguintree/webpack-module-federation-module-cache-issue) reproduces the bug.

**What is the expected behavior?**
Both modules from both remotes should be loaded independently, as the similarities in the exposed file name is merely a coincidence and is not known by the host.

**Other relevant information:**
webpack version:  5.50.0
Node.js version: 14.17.0
Operating System: Windows 10 20H2 19042.1110
Additional tools: n/a

**Comment by alexander-akait** [comment]
@chenxsan @snitin315 Let's add this problem to https://webpack.js.org/concepts/module-federation/#troubleshooting

**Comment by penguintree** [comment]
> 
> 
> > TypeError: secondRemote_y__WEBPACK_IMPORTED_MODULE_1___default(...).doSomethingWithPackage2 is not a function
> 
> Are you sure reproducible test repo works fine?

Yes the error is the symptom. The function `doSometingWithPackage2` do exists in `remote-pacakge-2` and should be available.

**Comment by alexander-akait** [comment]
Change name in `package.json` for `remote-package-1` and `remote-package-2` and all will be work fine

**Comment by penguintree** [comment]
Thanks a lot.
I would have thought that the [name provided in ModuleFederationPlugin](https://github.com/penguintree/webpack-module-federation-module-cache-issue/blob/7ea88c88d44d9890aeb59c3374e8d576b0b43b83/remote-package-1/webpack.config.js#L6) would be sufficient to make to completely independant packages. It looks like both must be unique, the name in the plugin _and_ in package.json.

**Comment by alexander-akait** [comment]
In theory you can create shared remotes between different builds, it is very exotic, but it is possible

**Comment by penguintree** [comment]
I ran in this issue while exploring how I could handle different remote packages version in a rather large federated application. I didn't found a lot of information about remote versioning apart from [a video from Jack Herrington](https://www.youtube.com/watch?v=ZFNxTy3fOO0) based on unpkg. Is there any official guidelines or documentation you are aware of about this ?

**Comment by alexander-akait** [comment]
I think better to open another issue about this and ask directly questions, so we will improve this, module federation is real big theme, so there are a lot of complex information

**Comment by Cantarella** [comment]
> На этот вопрос отвечали много раз:
> 
> [https://github.com/penguintree/webpack-module-federation-module-cache-issue/blob/main/remote-package-1/package.json#L2 ](https://github.com/penguintree/webpack-module-federation-module-cache-issue/blob/main/remote-package-1/package.json#L2) [https://github.com/penguintree/webpack-module -federation-module-cache-issue/blob/main/remote-package-2/package.json#L2](https://github.com/penguintree/webpack-module-federation-module-cache-issue/blob/main/remote-package-2/package.json#L2)
> 
> Webpack генерирует среду выполнения на основе `uniqueName`(webpack генерирует общую функцию, посмотрите исходный код `webpackChunktoolpackage_v1`), у вас есть то же самое `uniqueName`для разных пакетов, поэтому вы делитесь кодом между `remotes`, это создает коллизии, вот логика для значения по умолчанию https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L616 , поэтому у вас должны быть разные имена

despite the fact that it has been answered many times - it was this answer of yours that helped me. Thank you)
