### ISSUE TITLE
A minor mistake with 'Getting Started'

### ISSUE THREAD

**Issue by cntanglijun** [webpack/webpack.js.org#533]
![image](https://cloud.githubusercontent.com/assets/13279117/21376624/89672410-c771-11e6-8e23-01ad3ebd74d7.png)

![image](https://cloud.githubusercontent.com/assets/13279117/21376997/d04f7bb8-c774-11e6-8c08-33cf6507d0c8.png)

Use `./node_modules/.bin/webpack -h` instead?

**Comment by bebraw** [comment]
PR welcome.
