### ISSUE TITLE
Fix vert scrolling marquee on splash page for Safari Mobile

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#540]
Looks like this has issues on mobile safari. ![image](https://cloud.githubusercontent.com/assets/3408176/21407911/84740e8e-c797-11e6-86e1-6e48b74f13f4.png)

**Comment by CasperVonPfaler** [comment]
The same issue is also on desktop safari.
<img width="1141" alt="screen shot 2016-12-24 at 13 23 30" src="https://cloud.githubusercontent.com/assets/15709469/21466705/474e3fd8-c9dc-11e6-8a59-d52eb76d067a.png">
I could take a crack at fixing it over the holidays.

**Comment by skipjack** [comment]
Pretty sure this was fixed in #549 as I remember reviewing that. Feel free to re-open if anyone is still seeing this bug.
