### ISSUE TITLE
Docs for module context options mention deprecation but not alternative

### ISSUE THREAD

**Issue by scott-ln** [webpack/webpack.js.org#5404]
**Feature to document**

Whatever the replacement for [module context options](https://webpack.js.org/configuration/module/#module-contexts) will be

**Additional information**

The documentation for module context options says "Avoid using these options as they are deprecated and will soon be removed." It's hard to know what to do after reading this as no further explanation is provided - will they be replaced by something else? Will this kind of config be entirely unavailable, if so why? Cheers.

Edit: On second reading, the "Tip" below suggests using [ContextReplacementPlugin](https://webpack.js.org/plugins/context-replacement-plugin/) - if that's the correct way, then this section could do with being rewritten to prioritize that information, which would be clearer.

**Comment by chenxsan** [comment]
Can't find those deprecated texts now.
