### ISSUE TITLE
remove `commonjs-module` from documentation

### ISSUE THREAD

**Issue by sokra** [webpack/webpack.js.org#545]
It has no special effect. Replace it with `commonjs2`

**Comment by tarang9211** [comment]
@sokra could you give more info on this? I'd be glad to help out here.

**Comment by skipjack** [comment]
@tarang9211 it seems to be an option for `libraryTarget`. A quick grep revealed that there's three pages containing a reference to it:

- `/configuration/index.md`
- `/configuration/output.md`
- `/guides/author-libraries`

Would you still be interested in submitting a pr to clean those up?
