### ISSUE TITLE
Should `checkResource` have been made required? If so, https://webpack.js.org/plugins/ignore-plugin/ needs updated as well.

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack.js.org#5464]
Should `checkResource` have been made required? If so, https://webpack.js.org/plugins/ignore-plugin/ needs updated as well.

_Originally posted by @KyleAMathews in https://github.com/webpack/webpack/issues/14211#issuecomment-921122866_

**Comment by KyleAMathews** [comment]
we can close this
