### ISSUE TITLE
With module federation, submodules of shared modules are not actually shared if they are imported individually

### ISSUE THREAD

**Issue by antoinetissier** [webpack/webpack.js.org#5476]
# Bug report

**What is the current behavior?**
Importing a submodule of a shared module yields a different instance of the submodule in each `ModuleFederationPlugin`, instead of a single shared instance.

**If the current behavior is a bug, please provide the steps to reproduce.**

I created a repository to showcase the issue: [module-federation-with-shared-submodules](https://github.com/antoinetissier/module-federation-with-shared-submodules).

It is based on the [shared context](https://github.com/module-federation/module-federation-examples/tree/master/shared-context) module federation example, with the difference that on the `main` branch the different module federation plugins import the shared context from the shared library through a submodule import rather than a root import:

```diff
- import { NameContext } from "@shared-context/shared-library";
+ import { NameContext } from "@shared-context/shared-library/src/context/NameContext";
```

The problem is that when doing this, the context is not actually shared, and each module federation plugin gets its own instance: `app1` provides "Billy" as context value above the `Welcome` component taken from `app2`, but `Welcome` uses a different context instance in its call to `useContext` - the one bundled with `app2`.
=> This leads to seeing "No name provided" in `app1` instead of "Billy".

Not being able to rely on submodules imports is a problem, because importing the whole shared library might make the bundle size much bigger in real life cases.
For example, importing just the `<Button />` component from [ant-design](https://github.com/ant-design/ant-design) instead of the whole library makes a huge difference:
```diff
- import { Button } from "antd";
+ import Button from "antd/lib/button";
```

**What is the expected behavior?**
I would expect the submodules to be shared between the different module federation plugins.

**Possible workaround**
Sharing the submodule itself in the webpack configs of the module federation plugins seems to work as expected:
```diff
      shared: [
        "react",
        "react-dom",
        {
-          "@shared-context/shared-library": {
-            import: "@shared-context/shared-library",
+          "@shared-context/shared-library/src/context/NameContext": {
+            import: "@shared-context/shared-library/src/context/NameContext",
            requiredVersion: require("../shared-library/package.json").version,
         },
        },
      ]
```

You can check that on the `shared-submodule` branch of the repo. After rebuilding, "Billy" is rendered as expected in `app1`:
```
git checkout shared-submodule
yarn clean-install && yarn clean && yarn build && yarn start
```

However, having to do this for every submodule of a shared library would be painful, and not scale well.
Please let me know if there is a better to way to approach this issue.

**Other relevant information:**
webpack version:  5.52.1
Node.js version: 14.17.1
Operating System: Windows 10

**Comment by antoinetissier** [comment]
> Put a trailing / on the end of whatever your sharing.

It's working !
When you add the documentation, would you mind adding a link to it in this issue ?

In any case, thanks a lot 👍

**Comment by nkalinov** [comment]
Is that still the recommended way? It doesn't seem to work for me. On the contrary, it completely breaks shared modules.
I'm applying this to all my package.json "dependencies". Is there an issue with this?

```
shared: {
    ...Object.entries(dependencies).reduce((acc, [key, version]) => {
      // acc[key] = version;
      // Include subpaths as well. E.g. lodash/fp, @redux-saga/core/io...
      acc[`${key}/`] = { requiredVersion: version };
      return acc;
    }, {}),
            react: {
          singleton: true,
          requiredVersion: dependencies.react,
        },
        'react-dom': {
          singleton: true,
          requiredVersion: dependencies['react-dom'],
        },
        redux: {
          singleton: true,
          requiredVersion: dependencies.redux,
        },
        'react-redux': {
          singleton: true,
          requiredVersion: dependencies['react-redux'],
        },
        'react-router-dom': {
          singleton: true,
          requiredVersion: dependencies['react-router-dom'],
        },
}
```

**Comment by ScriptedAlchemy** [comment]
Someone feel free to open pr. I have no capacity but can suggest edits if someone will get the PR started

**Comment by Christian24** [comment]
@ScriptedAlchemy & @alexander-akait I just opened a PR https://github.com/webpack/webpack.js.org/pull/6519, since this took me a long time to figure out. 

Feel free to leave feedback.

**Comment by chbdetta** [comment]
Is this a regression? It seems adding `/` at the end of a shared package causes it not to be shared (including the sub path imports and index import)

**Comment by rrosenshain-sc** [comment]
@ScriptedAlchemy sorry for bumping an old thread but just ran into a similar problem.
The proposed solution of using `/` works when all the apps are using `/` but if there's a mix of root imports and nested imports then packages are not shared.

Any suggestions there? Is it possible for the runtime to be "smart" about it? like compare the key with the import itself and dedupe it?
