### ISSUE TITLE
Searching for "CLI" does not show you the CLI page

### ISSUE THREAD

**Issue by marcofugaro** [webpack/webpack.js.org#557]
Here is the page I was trying to access to: https://webpack.js.org/api/cli/

I don't know how search works, but I think just adding `(CLI)` to the page title would suffice

**Comment by dzello** [comment]
APIs, loaders and plugins weren't being picked up. That's been [fixed](https://github.com/algolia/docsearch-configs/commit/fa6c750cdd4a8673a0f5e1597dbf6f325fd3056e) and deployed.

Searching for `command line interface` works as expected now. Adding `(CLI)` to the header tag on that page should make it a top match for the short `CLI` form also.

**Comment by bebraw** [comment]
Thanks for the fix. Closing.
