### ISSUE TITLE
moduleExtensions is depracated missing in doc

### ISSUE THREAD

**Issue by mennya** [webpack/webpack.js.org#5572]
moduleExtensions is depracated but there is no infro in doc now, but it was before, see commit:

https://github.com/webpack/webpack.js.org/commit/b67859ce748d11aac988eabccd9c873741ea4b19

**Comment by mennya** [comment]
Yes but where can i find info about moduleExtensions deprecation?

**Comment by mennya** [comment]
@snitin315 should it also be here? https://webpack.js.org/blog/2020-10-10-webpack-5-release/ and here https://github.com/webpack/changelog-v5  ?

**Comment by snitin315** [comment]
Added in https://github.com/webpack/webpack.js.org/pull/5584
