### ISSUE TITLE
'Edit this page' link broken

### ISSUE THREAD

**Issue by gitanupam** [webpack/webpack.js.org#561]
It seems that 'Edit this page' link is broken throughout the documentation site (like on https://webpack.js.org/configuration/)

**Comment by bebraw** [comment]
[Here](https://github.com/webpack/webpack.js.org/blob/develop/components/page/page.jsx#L11). `page.url` should be `trimEnd(page.url, '/')`. PR welcome.

**Comment by bebraw** [comment]
The PR was merged (not deployed yet, though).
