### ISSUE TITLE
Graphic on front page depicts a CSS module depending on a TypeScript module?

### ISSUE THREAD

**Issue by pelotom** [webpack/webpack.js.org#562]
Minor detail perhaps, but kinda silly:

<img width="215" alt="screen shot 2016-12-28 at 11 55 07 pm" src="https://cloud.githubusercontent.com/assets/128019/21539240/ca7cc4c6-cd59-11e6-829f-e9a517444f6c.png">

**Comment by skipjack** [comment]
@pastelsky hey I tried fixing this one but can't open the `modules.svg` file in illustrator. I think it's because we optimized it somehow, but if you share the original file I should be able to pick this up.

**Comment by SpaceK33z** [comment]
@skipjack here is the file you can open in Illustrator: https://webduck.nl/playground/homepage-modules.svg

I opened the file from the repo in Sketch and exported it again as svg. Then tested it with Illustrator and it worked :).

**Comment by skipjack** [comment]
Awesome, thanks @SpaceK33z.. I'll tackle this soon.

**Comment by skipjack** [comment]
@SpaceK33z I was able to fix this but when using `svgo` as you suggested it throws off the module backgrounds:

![image](https://cloud.githubusercontent.com/assets/8988697/23047598/e2ee943e-f47e-11e6-8357-efe2ebcd3b56.png)

Without `svgo` it looks fine... any ideas?

**Comment by skipjack** [comment]
Nvm, figured it out using [SVGOMG](https://jakearchibald.github.io/svgomg/). The **Collapse useless groups** option was causing issues.

**Comment by skipjack** [comment]
Resolved in #907... @SpaceK33z I merged to get this out of the way (the changes were fairly minor) and close this issue but feel free to review at your leisure and ping me or re-open if you see any issues.
