### ISSUE TITLE
Wrong line highlighting in source code

### ISSUE THREAD

**Issue by kennyjacob** [webpack/webpack.js.org#563]
On https://github.com/webpack/webpack.js.org/blob/develop/content/concepts/plugins.md at the bottom there is a link to a code sample highlighting a specific section of code (https://github.com/webpack/webpack/blob/master/bin/webpack.js#L290-L292). Due to changes in that file, the highlight has become wrong.

You might need a way to link to a commit's version of the file or else update these doc links whenever the file changes.

**Comment by bebraw** [comment]
Yeah, it would be far better to link to a specific commit. GitHub allows that. PR welcome.

**Comment by bdougie** [comment]
I can PR real quick, already have a cloned version locally.
