### ISSUE TITLE
Links for plugins at v4 leftside menu are wrong for ProfilingPlugin and plugins after that

### ISSUE THREAD

**Issue by hnakamur** [webpack/webpack.js.org#5645]
# Bug report
## What is the current behavior?

The link of ProfilingPlugin at the left side menu in the v4 plugins page https://v4.webpack.js.org/plugins/
is https://v4.webpack.js.org/plugins/printable/
The link of ProgressPlugin is https://v4.webpack.js.org/plugins/profiling-plugin/
The link of ProvidePlugin is https://v4.webpack.js.org/plugins/progress-plugin/
And so on.

## What is the expected behavior?

The link of ProfilingPlugin at the left side menu in the v4 plugins page https://v4.webpack.js.org/plugins/
should be https://v4.webpack.js.org/plugins/profiling-plugin/
The link of ProgressPlugin is  https://v4.webpack.js.org/plugins/progress-plugin/
The link of ProvidePlugin is https://v4.webpack.js.org/plugins/provide-plugin/
And so on.

**Comment by chenxsan** [comment]
I believe it's fixed now, let me know if if I was wrong.
