### ISSUE TITLE
Webpack css-loader docs is uncomfortable to read

### ISSUE THREAD

**Issue by akgupta0777** [webpack/webpack.js.org#5663]
Go to this link https://webpack.js.org/loaders/css-loader/#options
I am viewing it on a 15.6 inch laptop screen fairly big but still the options table is very uncomfortable to read as the description is totally stripped out (See below image for reference)

![image](https://user-images.githubusercontent.com/51379307/140480338-a8600158-03f3-42f3-9edb-1940a1dd3405.png)

For reading any of the options I have to count the option and then scroll it all the way to right and then I can read it. It is not a great experience for someone who is reading docs.

Possible Solution:
Should be something on the table to adjust the size according to user view.

**Comment by snitin315** [comment]
The docs for loaders and plugins are fetched from their README.md in GitHub - https://github.com/webpack-contrib/css-loader

> Should be something on the table to adjust the size according to user view.

It would be nice if we can improve this behavior here.

**Comment by chenxsan** [comment]
Sort of difficult to improve for such a case, we can always have some wider tables no matter how wide the page is. But feel free to send a PR if you have a good idea.

**Comment by akgupta0777** [comment]
@chenxsan we can shift the description column in place of default column.
As default column content is short even it is stripped out the reader can see it comfortably in my opinion.

If you like this idea I can send a PR for this.🙂

**Comment by akgupta0777** [comment]
Description is kinda more important than the default values of options. Let me know what you think about this.

**Comment by chenxsan** [comment]
As @snitin315 said, the readme is fetched from https://github.com/webpack-contrib/css-loader/blob/master/README.md, if you want to make a change, file an issue over that repository to see how maintainers over there think.
