### ISSUE TITLE
General - Clarify Loader Configuration

### ISSUE THREAD

**Issue by dmitriid** [webpack/webpack.js.org#569]
Recently (during a discussion of https://github.com/webpack/webpack/issues/2797) I went to see how loaders are configured in Webpack 2. I found it in the end, but the journey was a long one:

- [Concepts -> Loaders](https://webpack.js.org/concepts/loaders/) only mentions they can accept query parameters without describing what that is
- [Guides](https://webpack.js.org/guides/)... May be there are loaders, but I don't know in which one
- [Documentation](https://webpack.js.org/configuration/). There's a spec for the documentation. And you can see the `options` param somewhere in `rules`
- Then I went like this: Documentation -> Module -> Rule.loader -> [optional: Rule.use] -> [UseEntry.loader](https://webpack.js.org/configuration/module/#useentry). 

Note: the last step of the journey:
- contradicts concepts. Concepts only mention the query. Both `UseEntry.loader` and config spec only mention `options`
- is a bit confusing (there's now `loader` and `loaders`, _and_ `Rule.use`? and all of them do the same thing?)

**Comment by skipjack** [comment]
> Correct. I think there are 4-5 ways to achieve the same thing now that use and options were added. And ExtractTextPlugin comes with an exception (won't work with use iirc).

Is the plan to remove some of these things the next major release? It seems `use` is what we want to stick with and the others were left in to prevent too many breaking changes being introduced at once?

**Comment by skipjack** [comment]
@webpack/documentation-team is there a consensus to my question above? I think if the answer is that `rules`, `use`, and `options` are what we want to stick with then we should:

- Make it clear that's what's recommended
- Note the support for old semantics with a warning for when they will be dropped
- Clean up usage throughout the site to reflect the recommended practice

@dmitriid if that is the case, do you think those steps would resolve the issue?

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack/webpack/pull/5066 `rules`, `use`, `options` is definitely the way to go as it seems :)

**Comment by skipjack** [comment]
Ah very nice, thanks!
