### ISSUE TITLE
Documentation on recordsPath

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#577]
> Quoting @nmaves:

I am looking for a bit of insight on how to use the recordsPath file.

We are using code splitting and the commons chunk plugin and we would love to have long term caching of our bundles.

What we don't know or understand is how we get this with our recordsPath file.  We would like to know when/if we should be persisting this file.  Should it change for each developer on each build?  Does the webpack-dev server use/modify it?  We have different build commands for each ENV that we support (DEV, TEST, PROD).  Should that file change after each build and should we commit that to our SCM?

**Moved from https://github.com/webpack/webpack/issues/3653**

**Comment by skipjack** [comment]
We also already have TODOs regarding this on the [other options config page](https://webpack.js.org/configuration/other-options/#recordspath). Maybe documenting those options can be tackled here as well.

**Comment by skipjack** [comment]
Starting to work on this now. I found a good description of the base `recordsPath` option from @bebraw [here](https://survivejs.com/webpack/optimizing/separating-manifest/#using-records) but I still need more info on `recordsInputPath` and `recordsOutputPath`.

@nmaves have you read that [SurviveJS article](https://survivejs.com/webpack/optimizing/separating-manifest/) before? Or the [caching guide]() on this site? I think you might actually be looking to separate the manifest though it seems they're somewhat related (tbh this is one part of webpack I'm not too familiar with yet).

Or if you already resolved your issue, I'd be interested to hear how as it could influence what we add to the docs.

**Comment by bebraw** [comment]
@skipjack `recordsPath` is equal to `recortsInputPath` and `recordsOutputPath` set to the same value. I think the design would be better if we had `records: { input, output }` but it is what it is right now. Essentially the two fields exist if you want to load records from a different source than which you are writing into.
