### ISSUE TITLE
My bundle is 500 times bigger than in tutorial?

### ISSUE THREAD

**Issue by kasperpeulen** [webpack/webpack.js.org#578]
I just followed the steps here:
https://webpack.js.org/get-started/

According to the tutorial, I should get this output:
```
webpack app/index.js dist/bundle.js

Hash: a3c861a7d42fc8944524
Version: webpack 2.2.0
Time: 90ms
   Asset     Size  Chunks             Chunk Names
index.js  1.56 kB       0  [emitted]  main
   [0] ./app/index.js 170 bytes {0} [built]
```

But the output I'm getting is:

```
./node_modules/.bin/webpack app/index.js dist/bundle.js
Hash: 9d1f20a41ecfcabb22ab
Version: webpack 2.2.0-rc.3
Time: 337ms
    Asset    Size  Chunks                    Chunk Names
bundle.js  544 kB       0  [emitted]  [big]  main
   [0] ./~/lodash/lodash.js 540 kB {0} [built]
   [1] (webpack)/buildin/global.js 506 bytes {0} [built]
   [2] (webpack)/buildin/module.js 548 bytes {0} [built]
   [3] ./app/index.js 257 bytes {0} [built]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (250 kB). 
This can impact web performance.
Assets: 
  bundle.js (544 kB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (250 kB). This can impact web performance.
Entrypoints:
  main (544 kB)
      bundle.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
```

I was a bit suprised by this.

**Comment by bebraw** [comment]
Hi,

I think that output at the page is not up to date. That lodash dependency alone explains most of the size since it appears to bundle whole lodash there.

It probably would be a better idea to import only smaller parts of lodash and update the tutorial output accordingly.

**Comment by ntrrgc** [comment]
Same issue here: https://github.com/webpack/webpack/issues/3794

**Comment by bebraw** [comment]
Yeah, let's keep this one open as that's for the main repo.

**Comment by johnstew** [comment]
**Possible solutions:**
- Take the output from the actual tutorial and display that instead of what's there.
- OR add a tip stating "Output may vary, but if build is successful you are good to go."

Thoughts?

**Comment by bebraw** [comment]
@johnstew Latter would work for me. Easier to maintain.

**Comment by johnstew** [comment]
@bebraw agree

**Comment by johnstew** [comment]
@bebraw this should be good to close now, correct?

**Comment by bebraw** [comment]
Yeah, let's do that.
