### ISSUE TITLE
Git flow and develop branch?

### ISSUE THREAD

**Issue by simon04** [webpack/webpack.js.org#587]
When reading through recent comments on PRs, such as https://github.com/webpack/webpack.js.org/pull/580#issuecomment-269969137 or https://github.com/webpack/webpack.js.org/pull/573#issuecomment-269904137, the `develop` is no longer in use.

Thus, [CONTRIBUTING.md](https://github.com/webpack/webpack.js.org/blob/master/CONTRIBUTING.md) should be adapted accordingly. The git flow branching model is no longer applicable?

**Comment by skipjack** [comment]
Yep, the whole git flow section should be removed and "Branching your Changes"/"Submitting Changes" should be tweaked as well.

**Comment by bebraw** [comment]
@skipjack I would drop the naming part to keep it simple. The focus is on content after all.

I'll tweak and merge in a bit. Thanks for the heads up.
