### ISSUE TITLE
Document usage of `import()` for code splitting

### ISSUE THREAD

**Issue by dmackerman** [webpack/webpack.js.org#589]
Instead of the deprecated `System.import`.

As requested by @TheLarkInn. 😄

**Comment by halt-hammerzeit** [comment]
A follow-up
https://github.com/webpack/webpack/issues/3777

The [migration guide](https://webpack.js.org/guides/migrating/) says:

> If you want to use import with Babel, you'll need to install/add the dynamic-import syntax plugin while it's still Stage 3 to get around the parser error. When the proposal is added to the spec this won't be necessary anymore.

At the same time, seems that it has been added recently:
https://github.com/babel/babel/issues/4944

I'm now running my project without that babel syntax plugin and it seems to work.
So maybe reflect that in the migration guide, that the syntax plugin is not needed for the newest babel (or that developers should update their babel, though I'm not sure which package exactly, I just reinstalled all `node_modules` from scratch and it worked).

**Comment by jouni-kantola** [comment]
@halt-hammerzeit: I'm doing `import()` in this branch:
https://github.com/jouni-kantola/webpack-output-by-build-type/tree/webpack2

Without `plugins: ["syntax-dynamic-import"]` options to `babel-loader` I get:
```
ERROR in ./src/index.js
Module build failed: SyntaxError: Unexpected token (10:24)

   8 | // using babel polyfill adds quite a lot of overhead
   9 | async function bootstrap() {
> 10 |     const { a } = await import('./deps/module-a.js');
     |                         ^
  11 |     a();
  12 |
  13 |     const { b } = await import('./deps/module-b.js');
```
This tells me code splitting with import doesn't work without `syntax-dynamic-import`.

**Comment by halt-hammerzeit** [comment]
@jouni-kantola Did you reinstall node_modules?

```
rm -rf node_modules
npm install
```

**Comment by jouni-kantola** [comment]
Can you give me an example of your code? If you try this in babel's REPL, it throws:
[Dynamic import](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=stage-3&code=import%20lodash%20from%20'lodash'%3B%0A%0Aconst%20module%20%3D%20import('.%2Fmodule')%3B%0A)
