### ISSUE TITLE
Headings have huge content areas, covering up interactive areas above them

### ISSUE THREAD

**Issue by rschristian** [webpack/webpack.js.org#5945]
**This is not a feature request.**

**Steps to Reproduce**

Edit: This seems to not be reproducible on Chrome/Chromium. Not sure what others, but is reproducible on Firefox.

1) Navigate to https://webpack.js.org/plugins/terser-webpack-plugin/#options
2) Scroll to the bottom of the options table
3) Try to scroll the options table horizontally
4) Notice you cannot do it, because the next heading covers it.

![Screenshot of page with dev tools](https://user-images.githubusercontent.com/33403762/152632141-e2aa47cc-82e5-46f5-b221-6e39c3a6d35b.png)

**Additional information**

This seems to be site-wide, though the issue only pops up here and there.

[] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
Unfortunately this is a workaround for the fixed navbar, otherwise when we click the header or access the header anchor, the header would be hidden under the fixed navbar.

**Comment by rschristian** [comment]
Ah, gotcha! Yep, that makes sense. However, portions of the site are unusable at the moment (usually with horizontal scrolls, so tables like this, code snippets, etc), so if there's no cross-browser solution, a different navbar setup might be needed? 

React's documentation also having poor UX doesn't really help things here.

**Comment by chenxsan** [comment]
I can confirm React doc has the same problem under firefox:

<img width="876" alt="CleanShot 2022-02-06 at 19 44 52@2x" src="https://user-images.githubusercontent.com/1091472/152679304-f0a7ce05-e24c-4267-9e60-ae68781aed5d.png">

You can try to select the text from right to left, firefox won't let you do it while other browsers like Edge has no problem.

There're two options here:

1. use [`scroll-margin-top`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top), however we can run into another problem under Safari
2. Do not use fixed header.

But I did notice that there's no problem on nextjs https://nextjs.org/docs/basic-features/font-optimization#usage. I'll see how to make it.

**Comment by chenxsan** [comment]
@rschristian Hi, can you check https://webpack-js-org-git-fork-chenxsan-bugfix-fix-467aee-webpack-docs.vercel.app/plugins/terser-webpack-plugin/#test? I've filed a pull request to workaround the problem. Will merge it once I clean up the code.
