### ISSUE TITLE
Bad loader rendering

### ISSUE THREAD

**Issue by simon04** [webpack/webpack.js.org#598]
Due to special styling of the README from https://github.com/webpack/less-loader/pull/119, the [`less-loader` documentation](https://webpack.js.org/loaders/less-loader/) rendering is rather unfortunate:
- the badges are being displatyed as `[![npm][npm]][npm-url] [![node][node]][node-url] [![deps][deps]][deps-url] [![tests][tests]][tests-url] [![coverage][cover]][cover-url] [![chat][chat]][chat-url]`
- the webpack logo seems unnecessary
- due to the centered `<h1>`/`<h2>` headings in the `README.md`, no anchors are inserted.

This should be addresses since similar modifications for other loaders are scheduled: https://github.com/webpack/webpack/issues/3195

![2017-01-04-120955_1198x948_scrot](https://cloud.githubusercontent.com/assets/782446/21640602/ceb67f24-d276-11e6-983e-4c3137de3510.png)

**Comment by SpaceK33z** [comment]
Good point. This will probably not be easy to fix though, since the readme's are auto-generated :(. Do you have any suggestions how to tackle this?

**Comment by simon04** [comment]
In [scripts/fetch_package_files.js](https://github.com/webpack/webpack.js.org/blob/3450c22/scripts/fetch_package_files.js#L72-L75), one could:
- delete all lines until encountering `<h2 align="center">Install</h2>`
- replace any `<h1 align="center">` and `</h1>` with `#` (likewise for `h2` and `##`)
