### ISSUE TITLE
.js extension file still need loaders

### ISSUE THREAD

**Issue by tcvduc** [webpack/webpack.js.org#5987]
- I'm a newbie to Webpack and I meets the problem as description below:

1. On [Loaders](https://webpack.js.org/concepts/#loaders ) section, it said Webpack understands Javascript file
<img width="401" alt="1" src="https://user-images.githubusercontent.com/44729657/155484992-b0103e36-92bc-4a5b-a580-3fb9bd85687d.png"> 
2. But when I run `npx webpack` to bundle Javascript file, it still need loaders
<img width="776" alt="2" src="https://user-images.githubusercontent.com/44729657/155485725-b6089c93-298c-4081-97ee-0d3629fb0a07.png">
- So, do we still need to add loaders when we bundle Javascript files?
- Thank you.

**Comment by chenxsan** [comment]
The problem is you're using JSX syntax in the .js file. JSX is not a standard JavaScript syntax.

**Comment by tcvduc** [comment]
Thank you, I got it.
