### ISSUE TITLE
[Bug] The vote page for v5 is blank

### ISSUE THREAD

**Issue by mhnaeem** [webpack/webpack.js.org#6002]
**Issue**

The voting page on the Webpack website is blank for the current version of documentation. Link: https://webpack.js.org/vote/

**Additional information**

Should this page possibly be removed entirely? I noticed that the page for v4 wasn't updated frequently either. 

- [X] I am new to Webpack docs but I am willing to work on this issue and submit a pull request if there is a decision made on how it should be handled

**Comment by chenxsan** [comment]
Yeah, it's broken now, see https://github.com/webpack/webpack.js.org/pull/5900. The app was built in webpack v4, maybe some compatibility problems between webpack 5 and webpack 4. Besides, the vote app isn't updated for quite a long time. So maybe we should just redirect the vote page to v4? Anyway if you want to fix it, PR is welcome.

**Comment by mhnaeem** [comment]
@chenxsan Do you think perhaps we should just remove the entire page? If the voting app is not maintained or updated it might not provide any utility to redirect or have it there anyway.

**Comment by chenxsan** [comment]
> @chenxsan Do you think perhaps we should just remove the entire page? If the voting app is not maintained or updated it might not provide any utility to redirect or have it there anyway.

Sorry I can't make the decision myself here.

**Comment by chenxsan** [comment]
Closed via https://github.com/webpack/webpack.js.org/pull/6017
