### ISSUE TITLE
optimization type definitions should match string options specified in webpak 5 docs

### ISSUE THREAD

**Issue by noahehall** [webpack/webpack.js.org#6018]
# Bug report

**What is the current behavior?**
type def for OptimizationOptions doesnt match webpack 5 docs

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
- `chunkIds?: 'natural' | 'named' | 'size' | 'total-size' | false,`
- `moduleIds?: 'natural' | 'named' | 'hashed' | 'size' | 'total-size' | false,`
- [should both include `deterministic`](https://webpack.js.org/configuration/optimization/)
- 

**Other relevant information:**
webpack version:  5.68
Node.js version:  17.6
Operating System:  ubuntu 21.10
Additional tools: pnpm, flow-typed

**Comment by alexander-akait** [comment]
We should fix docs

**Comment by noahehall** [comment]
@alexander-akait hmm you know perhaps this should be in the flow-typed repository

I checked the [typescript def here](https://github.com/webpack/webpack/blob/5a26b7c4a923c42022ca97fe9cbf46907a20d6d8/declarations/WebpackOptions.d.ts#L1619)

and **deterministic** is listed

**Comment by alexander-akait** [comment]
Can you provide package.json?

**Comment by noahehall** [comment]
@alexander-akait [created a ticket here](https://github.com/flow-typed/flow-typed/issues/4279)
