### ISSUE TITLE
Lazy load folder index

### ISSUE THREAD

**Issue by lionel-bijaoui** [webpack/webpack.js.org#6057]
- [x] Check the current issues to ensure you aren't creating a duplicate.
- [x] Consider making small typo fixes and such directly as pull requests.
- [x] For the voting application, go to https://github.com/webpack-contrib/voting-app.
- [x] For the document of Chinese translation（中文版文档), go to https://github.com/docschina/webpack.js.org.
- [x] For loader/plugin docs, consider opening an issue in the corresponding repository.
- [x] No existing issue? Go ahead and open a new one.
- **Remove these instructions from your PR as they are for your eyes only.**

Hello,

I'm using alias to point to a file (`./some/folder/index.js`).
```js
resolve.alias: {
"myAlias": "./some/folder/"
}

```
This file contain exports from all the files present in said folder. 
```js
// index.js
export * from "./modul1.js";
export * from "./modul2.js";
export * from "./modul3.js";
```
where each module is a file:
```js
// module1.js
export function someMethod(){ 
//... 
}
// module3.js
export const someProperty = "foo";
```

This setup allow me to do in my other files :
```js
import { module1, module3 } from "myAlias";

module1.someMethod();

module3.someProperty;
```
These modules are available between multiple different projects (like a library) as submodules git.
This work well, and allow easy usage of these module from everywhere.

But not all modules are used by all project, and I would like to know how to allow for some lazy loading and/or three shaking based on usage.
If I reused my example:
```js
import { module1, module3 } from "myAlias";

module1.someMethod();

module3.someProperty;
```
When I do this, module2 is also loaded, even if I don't need it. Beyond problem with possible circular dependency, it load pretty much all module when I might only need one.

Is there a solution where I can still use the syntax `import { module1, module3 } from "myAlias";`, where each module is a separate file and all module are into a single file, and where the request of one module doesn't load everything at once ?

I understand that this is a very specific problem, and I thank you for you time and help.

Have a nice day.

**Comment by chenxsan** [comment]
It's better asking on StackOverflow. Anyway, you can check the tree shaking section here https://webpack.js.org/guides/tree-shaking/#root.
