### ISSUE TITLE
Update migration v4 to v5 guide to include env variable changes

### ISSUE THREAD

**Issue by JJPell** [webpack/webpack.js.org#6064]
This isn't mentioned in the migration guide but it would be useful to know that when migrating from v4 to v5 you need to change the format of the environment variables passed to your config from the following:

```
webpack --env.FOO foo --env.BAR --env.BAZ baz
```
To this format:
```
webpack --env FOO=foo BAR BAZ=baz
```

Otherwise you get the following error:
```
Error: Unknown option '--env.foo'
```

**Comment by yadunandanbhat** [comment]
i would like to work on this, but I might need some help!

**Comment by chenxsan** [comment]
It's more like a breaking change between webpack-cli v3 and v4 as per https://github.com/webpack/webpack.js.org/pull/4051. Not in webpack itself.
