### ISSUE TITLE
more asset generator options description

### ISSUE THREAD

**Issue by vankop** [webpack/webpack.js.org#6095]
**Feature to document**
there is asset `generator.outputPath` that affects **only output path**
there is asset `generator. publicPath` that provides way to create publicPath for assets
related issues https://github.com/webpack/webpack/issues/15656 https://github.com/webpack/webpack/issues/15693

**Author(s)**

**Additional information**

[ ] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
I think they are already documented here https://webpack.js.org/configuration/module/#rulegeneratorpublicpath?
