### ISSUE TITLE
bundle file gets considered a module!

### ISSUE THREAD

**Issue by drewdeal** [webpack/webpack.js.org#612]
v 1.14 - getting error: Module not found: Error: Cannot resolve module 'dist/pixDBundleWP.js' 

Config has:
```
module.exports = {
  entry: './pixiDrew/index.js',
  output: {
    path: "dist",
    filename: 'pixDBundleWP.js'
  },
```
So on second run of `webpack --display-error-details ./pixiDrew/index.js dist/pixDBundleWP.js`
I get no error, but the bundle file grows by 1.2Mb!

Using ES6 mods, and here are the imports:
```
import {getImages, makeGridMap, makeMappedRows, mappedFocusChange} from "../helpers/modelFn";
import $ from "jquery";
import {autoDetectRenderer, Container, loader, Sprite, Text, Graphics, tweenManager, tween} from "pixi.js";
//import  "../lib/pixi.js";
import "pixi-tween";
```

Ok, I think it is because I have files as args and they are repeated in config file. 
I think there should be an override in this case, as user expects one argument to prevail.

**Comment by skipjack** [comment]
This would be a better a question for the [gitter channel](https://gitter.im/webpack/webpack) or SO but in case you haven't already resolved it...

```
module.exports = {
  entry: './pixiDrew/index.js',
  output: {
    path: "dist",
    filename: 'pixDBundleWP.js'
  },
```

Here you've already defined your entry and output so there's no need to pass any of the filenames/paths to the CLI call. That is, just running:

```
webpack --display-error-details
```

should pick up all the necessary info from your config. I'm also unsure if the `path` defined in your config is valid for v1.14 (see the [old documentation](http://webpack.github.io/docs/configuration.html#output-path)). I have a feeling doing this might resolve your issue.

I'm going to close this issue as it doesn't really relate to this repo, but definitely reach out on Gitter or SO if you're still having issues.

**Comment by skipjack** [comment]
> Ok, I think it is because I have files as args and they are repeated in config file.
I think there should be an override in this case, as user expects one argument to prevail.

Ah just noticed the end... if this is still an issue with the latest version of webpack please open a ticket on [the main repo](/webpack/webpack) to file a bug.
