### ISSUE TITLE
Document Asset Bundling (Files/Images/Fonts)

### ISSUE THREAD

**Issue by michael-ciniawsky** [webpack/webpack.js.org#615]

**Comment by skipjack** [comment]
I might be able to tackle this one, were you thinking as a guide or more as a concept page? I see it's already mentioned briefly [here](https://webpack.js.org/guides/webpack-and-typescript/#importing-non-code-assets) but that's pretty much it.

**Comment by michael-ciniawsky** [comment]
Many folks seem to have problems when it comes to including assets in their bundles correctly e.g most of them coming from task runners like Gulp || grunt, store their images etc in one separate `./assets` folder and complain about the difficult management of these assets. The list goes on when using ETWP and the paths are off etc etc. 😛 tbh I guess it will be difficult to document, but a few 101 examples to understand the difference between File Tree <=> Dependency Graph would be helpful :)

**Comment by skipjack** [comment]
So how about an "Asset Management" guide that goes through loading images, either directly via js or css, and then also discusses aliasing for for those that want to stick with an `/assets` directory? For example, if you alias, then you can do things like `import Img from 'Assets/image.png'`. I find that approach really useful for some other things (not really for assets).

> but a few 101 examples to understand the difference between File Tree <=> Dependency Graph would be helpful :)

Don't assets like images and fonts just become a part of your dependency graph? Not sure exactly what you mean here...

**Comment by michael-ciniawsky** [comment]
> Don't assets like images and fonts just become a part of your dependency graph? Not sure exactly what you mean here...

Many don't understand the Dependency Graph approach at all at the beginning :). They still think in terms of a file tree, I especially noticed that (subjective), when it comes to assets loading. They see the 101 React Tutorials and do it with the CSS but without *really* understanding why in terms of the underlying concept(s) 😛 

## General
### File Tree
```
|– assets
|  |– img.png
|  |– icons
|  |  |– icon.svg
|  |  |–  etc... and more deeply nested like per 'page'
|– styles
|– pages
|- gulpfile.js
```
### Dependency Graph
```
|– components
|  |– component
|  |  |– index.js
|  |  |– index.css
|  |  |– icon.svg
|  |  |– img.png
|  |  |– subcomponent
|  |  |  |– index.js
|  |  |  |– index.css
|  |  |  |– icon.svg
|  |  |  |– img.png
|
|
|– entry.js
|– index.html
|- webpack.config.js
```

**entry.js**
```js
import component from './components/component'
```

**components/component**
```js
import style from './index.css'

import icon from './icon.svg'
import img from './img.png'

import subcomponent from './subcomponent'

const Component = () => {...}

export default  Component
```

**components/component/sub**
```js
import style from './index.css'

import icon from './icon.svg'
import img from './img.png'

const SubComponent = () => {...}

export default  SubComponent
```

>EDIT: Ah you mean they don't get bundled with the js but are instead added to the build directory as individual files?

Yep 🙃 and this comes to the mix in additionally afterwards, most think webpack will **keep** the original src [file/folder] structure (like grunt/gulp) and not that it will get resolved && flattened in the `output` along with their `bundle.js`

**Comment by skipjack** [comment]
Ok yea I think I have enough to get started on a guide now... thanks for the details!

**Comment by michael-ciniawsky** [comment]
There're endless ways to do it and you mentioend `resolve.alias` already, so please don't understand the examples above as the non plus ultra, but when it clicked on the concept, many don't seem to have bigger problems bringing `resolve` etc into the mix 😛 , so the above should just highlight the overall difference between to two common approaches generally

**Comment by michael-ciniawsky** [comment]
Mentioning the relation between the Dependeny Graph and 'webpack walking the `import/require()` statements` also seemed to work well as a hint (from my experience) :D

**Comment by skipjack** [comment]
Yeah, I follow you 👍 ... maybe some links to concept pages throughout wouldn't hurt either. I'll ping you for a review once I have something in the works, sounds good?
