### ISSUE TITLE
yarn install error

### ISSUE THREAD

**Issue by lcxfs1991** [webpack/webpack.js.org#617]
hi there,

I clone the project and use yarn install. It has following errors:
[yarn-error.txt](https://github.com/webpack/webpack.js.org/files/692006/yarn-error.txt)

![webpacjs](https://cloud.githubusercontent.com/assets/3348398/21748705/2154faec-d5c6-11e6-9e57-5015e2c47d73.jpg)

**Comment by bebraw** [comment]
The error log seems to point at https://www.npmjs.com/package/httperrors. Beyond that it's hard to tell what's going on as the site wasn't designed to be used with yarn (no official support, pr welcome).

**Comment by lcxfs1991** [comment]
I create a pull request yesterday. Upgrade `gh-pages` to the latest version would resolve the issue.

**Comment by bebraw** [comment]
Ok, looks like it was merged already. This might be safe to close then. Please verify that yarn works and close. 👍
