### ISSUE TITLE
How to set up webpack5 + express + ejs ?

### ISSUE THREAD

**Issue by spamator12** [webpack/webpack.js.org#6183]
Ejs render loaders seems to require that you pass in your inline variables in the config file, rather than in your Express routes, which doesn't make much sense to me. I have difficulties configuring Webpack 5 to properly use EJS template files. My app structure looks like:

_webpack: 5.38.1
express": 4.17.1
ejs-render-loader: 1.0.0*_

index.js (main node.js setup file)
|
- PAGES
|     |
|     - page1.ejs
|     - page2.ejs
|     |
|     - PARTIALS (ejs partials)
|         |
|         - header.ejs
|         - menu.ejs
|         - footer.ejs
|
- ROUTES
    |
    - page1.js
    - page2.js

**INDEX.JS**

```
var express = require('express');
var app = express();
var page1 = require('./routes/page1.js');
var page2 = require('./routes/page2.js');
app.set('view engine', 'ejs');
app.set('views', __dirname + '/ejs');
var server = https.createServer(options, app).listen(port, host, function()
{
    console.log('server is running!');
}
app.use('/page1', page1);
app.use('/page2', page2);
// + bla bla bla
```

**PAGE1.JS**

router.get('/', function(req, res, next)
{
    res.render('page1', {data : data}); // here we render ejs file
    res.end();
}
router.post('/page2', function(req, res, next)
{
    // + bla bla bla
    res.render('page2', {data : data}); // here we render ejs file
    res.end();
}

**PAGE1.EJS**

```
<!DOCTYPE html>
<html>
<head>
    <title>PAGE1</title>
    <%- include ('head.ejs'); %>
</head>
<body>
    <%- include ('header.ejs'); %>
    <%- include ('menu.ejs'); %>
    <div class="errors">
        <% if (typeof errors == "undefined") { %>
        <% } else { %>
            <%- errors %>
        <% } %>
    </div>
</body>
</html>
```

**PAGE2.JS**

```
router.get('/', function(req, res, next)
{
    res.render('page1', {data : data}); // here we render ejs file
    res.end();
}
```

**PAGE2.EJS**

```
<!DOCTYPE html>
<html>
<head>
    <title>PAGE2</title>
    <%- include ('head.ejs'); %>
</head>
<body>
    <%- include ('container.ejs'); %>
</body>
</html>
```

**WEBPACK.CONFIG.JS**

```
module.exports = {
    target: "node",
    entry: {
        main: './SRC/index.js'
    },
    externalsPresets: {node: true},
    externals: [webpackNodeExternals()],
    module: {
        rules: [
            {
                test: /\.ejs$/,
                use: {
                    loader: 'ejs-render-loader'
                }
            }
        ]
    }
}
```

Can somebody who has working config, show his settings, so I can adjust mine? Thanks!

**Comment by chenxsan** [comment]
Hope you have figured it out. I'm closing it as it might be better asked on stackoverflow.

**Comment by antonpodolsky** [comment]
For anyone looking for a solution, you can use tags like `<%- include ... %>` to be processed  by webpack, and escape the rest of the `ejs` tags using `<%%`  to inject content in express:

```ejs
<%- include header %>
  <div>
    <%%= content %> 
  </div>
<%- include footer %>
```

```js
app.get('/*', (req, res) => {
  res.render('index', { content: 'My index page' });
});
```
