### ISSUE TITLE
more info needed to understand output.publicPath

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack.js.org#627]
![image](https://cloud.githubusercontent.com/assets/1060733/21894514/7515db86-d91a-11e6-9dd6-2649bc0f00fc.png)

this is from the documentation on [webpack.github.io](http://webpack.github.io/docs/configuration.html#output-publicpath)

i‘ve found that there are many people who are wondering about `output.publicPath` in the configuration file.i think to a certain degree it's because the documentation is not good enough.
there are something very important for readers to understand the usage and the purpose of `output.publicPath`:
1. WDS or webpack will do two things if `output.publicPath` is present:
    1. add the value in front of all URLs which reference to an asset(both affect in DEV and PROD mode).
     2. mapping the folder in memory to the URL set by `output.path`(only affect in DEV mode).
     3. a common misunderstanding is that if `output.publicPath` haven't been set,it will default be the same as `output.path`,but actually it's `""` instead.
2. the URL mapping is for the folder which contain the output files instead of the one which is as the content base,so we should color this in the documentation for emphasis.
3. we also need more charts to explain these relationships and procedures.

**Comment by simon04** [comment]
You are referring to the webpack 1 documentation. Please review the [webpack 2 docs on output.publicPath](https://webpack.js.org/configuration/output/#output-publicpath) since this section has already been extended.

**Comment by skipjack** [comment]
Closing this for now, as @simon04 mentioned `publicPath` is defined much better in the new docs. @zzzgit if you still think the new section is missing something feel free to re-open and highlight exactly what needs updating/adding.
