### ISSUE TITLE
Module Federation in production

### ISSUE THREAD

**Issue by Lisheri** [webpack/webpack.js.org#6322]
I now encounter a problem: in the case of two applications referencing each other, if the publicPath is not set to the corresponding absolute path, the specific module under the corresponding sub-application will not be obtained, but if it is set to the absolute path, it will be in the address The server (cdn) address is exposed on the bar. If set to auto, the refresh will initiate a request from the current route to obtain the submodule after switching the route, which also fails to obtain. How to solve it please?

I didn't find an answer for the response in the documentation.Dynamic publicPath failed.

**Comment by Lisheri** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/49238808/183484346-7be11211-dea7-418a-91e0-983e7c6ea789.png">
<img width="606" alt="image" src="https://user-images.githubusercontent.com/49238808/183484539-3f3e9073-8bf8-4aad-922a-ba7e4ab75566.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/49238808/183484581-c5bfd6d5-04d2-48d3-96db-54d3541709a4.png">
<img width="752" alt="image" src="https://user-images.githubusercontent.com/49238808/183484617-6b1931ef-7f21-4f92-b0b5-f3a9e9bbb85b.png">

**Comment by Lisheri** [comment]
ok, I resolved it by dyn publicPath!

**Comment by chenxsan** [comment]
Glad you fixed it.
