### ISSUE TITLE
resolve.resolveToContext should be removed from docs cause webpack doesn't use this prop.

### ISSUE THREAD

**Issue by stsiarzhanau** [webpack/webpack.js.org#634]
resolve.resolveToContext should be removed from docs cause webpack doesn't use this prop.

See response to [issue](https://github.com/webpack/webpack/issues/3954) opened in webpack repo.

**Comment by SpaceK33z** [comment]
Okay, would you be interested in making a PR for this?

**Comment by stsiarzhanau** [comment]
I'd be glad to contribute (not only to fix this issue, but possibly in future).
But I've never made PRs and it's not clear for me how I can do it.
Do I need to fork this repo? Next steps?
Please, give me some guideline or link to resource where I can read about how to contribute.

**Comment by TheLarkInn** [comment]
Here's a great link!!! https://github.com/webpack/webpack.js.org/blob/master/CONTRIBUTING.md

**Comment by stsiarzhanau** [comment]
PR #640
