### ISSUE TITLE
Add "resolveLoader" to Webpack's configuration reference

### ISSUE THREAD

**Issue by adriancuadrado** [webpack/webpack.js.org#6394]
In [this article](https://webpack.js.org/contribute/writing-a-loader/#setup) `resolveLoader` is mentioned, but in webpack's [configuration reference](https://webpack.js.org/configuration/) I couldn't find anything about it. I'd like to know what other properties are available in the `resolveLoader` object apart from `modules` and what the default values are.

**Comment by adriancuadrado** [comment]
My bad, the configuration is documented [here](https://webpack.js.org/configuration/resolve/#resolveloader) already. Still, I think it should be mentioned in the [configuration reference](https://webpack.js.org/configuration/).

**Comment by chenxsan** [comment]
You can use the search function to look up those configurations.
<img width="588" alt="" src="https://user-images.githubusercontent.com/1091472/203315844-ff5e157f-7f57-4254-bd88-187a171a66b6.png">
