### ISSUE TITLE
Mention somewhere in the documentation that you can also use a JSON configuration file: "webpack.config.json"

### ISSUE THREAD

**Issue by adriancuadrado** [webpack/webpack.js.org#6395]
It's not mentioned anywhere. I think [this](https://webpack.js.org/configuration/configuration-languages/) is the most appropriate place to do so.

**Comment by Akhilbisht798** [comment]
can we also use ```webpack.config.json``` to config our webpack or is it just ```webpack.config.js```?

**Comment by adriancuadrado** [comment]
> can we also use ```webpack.config.json``` to config our webpack or is it just ```webpack.config.js```?

You can currently configure webpack using the json format. That's why I am asking to have that feature documented. Otherwise this would be a feature request and feature requests should go in the webpack's repository (not this one, this one is for the website. The other one with the source code of webpack).

**Comment by chenxsan** [comment]
I don't think we're going to document every possible configuration format webpack supports. There's https://webpack.js.org/configuration/configuration-languages/ page where you can see:

> Webpack accepts configuration files written in multiple programming and data languages. The list of supported file extensions can be found in the [node-interpret](https://github.com/gulpjs/interpret) package. Using [node-interpret](https://github.com/gulpjs/interpret), webpack can handle many different types of configuration files.

So basically you can check `node-interpret` package for the exhausted list.
