### ISSUE TITLE
The BannerPlugin has no documentation in webpck 2

### ISSUE THREAD

**Issue by doberkofler** [webpack/webpack.js.org#645]
There is no documentation of the BannerPlugin on https://webpack.js.org/plugins. How would I add a new plugin page as a PR?

**Comment by simon04** [comment]
Go to https://github.com/webpack/webpack.js.org/new/master/content/plugins and input `banner-plugin.md` as filename. Make sure to include a minimal yaml header at the top of the file:
```yaml
---
title: banner-plugin
---
```

**Comment by simon04** [comment]
BannerPlugin docs have been added in #779.

**Comment by WouterVanherck** [comment]
Followed the above link and instructions. Have only found the commit for the banner-plugin.md file which actually points to older documentation of the banner-plugin? Searched it myself which resulted in the following link:  https://github.com/webpack/webpack.js.org/blob/master/src/content/plugins/banner-plugin.md

Posting this so it could help others in the future when searching for the banner-plugin docs.
