### ISSUE TITLE
Unreadable `<code>` nested inside `link` in a `tip`

### ISSUE THREAD

**Issue by mukeshgurpude** [webpack/webpack.js.org#6480]
Page: https://webpack.js.org/concepts/plugins/
Theme: dark

![image](https://user-images.githubusercontent.com/55982424/199867577-9d791d9a-bbb8-4524-9f30-1b58af536311.png)

First link in the above image(webpack-source) is unreadable in dark mode. Somehow the styles have messed up the visibility of the element.

**Comment by snitin315** [comment]
@chenxsan Could this be because of https://github.com/webpack/webpack.js.org/pull/6438? Maybe we need to improve Tip styles for the dark theme too.

**Comment by chenxsan** [comment]
Filed a pull request here https://github.com/webpack/webpack.js.org/pull/6481, let me know what you think.
