### ISSUE TITLE
code-splitting-css demo throw error

### ISSUE THREAD

**Issue by yuyang041060120** [webpack/webpack.js.org#655]
```bash
/Users/yyy/Learn/webpack2-demo/node_modules/webpack/lib/Chunk.js:59
                throw new Error("Chunk.entry was removed. Use hasRuntime()");
                ^

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.get entry [as entry] (/Users/yyy/Learn/webpack2-demo/node_modules/webpack/lib/Chunk.js:59:9)
    at /Users/yyy/Learn/webpack2-demo/node_modules/extract-text-webpack-plugin/index.js:201:13
    at Array.filter (native)
    at Compilation.<anonymous> (/Users/yyy/Learn/webpack2-demo/node_modules/extract-text-webpack-plugin/index.js:200:37)
    at Compilation.applyPlugins0 (/Users/yyy/Learn/webpack2-demo/node_modules/tapable/lib/Tapable.js:68:14)
    at Compilation.seal (/Users/yyy/Learn/webpack2-demo/node_modules/webpack/lib/Compilation.js:533:8)
    at /Users/yyy/Learn/webpack2-demo/node_modules/webpack/lib/Compiler.js:471:16
    at /Users/yyy/Learn/webpack2-demo/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/Users/yyy/Learn/webpack2-demo/node_modules/webpack/lib/Compilation.js:452:11)
    at processModuleDependencies.err (/Users/yyy/Learn/webpack2-demo/node_modules/webpack/lib/Compilation.js:423:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


```

os: macOS Sierra 10.12.2
node: 7.4.0
webpack: 2.2.0-rc.7

webpack.config.js

```javascript
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = function () {
  return {
    entry: './app/index.js',
    output: {
      path: './dist',
      filename: 'bundle.js'
    },
    module: {
      rules: [{
        test: /\.css$/,
        exclude: /node_modules/,
        loader: ExtractTextPlugin.extract({
          loader: 'css-loader?sourceMap'
        })
      }]
    },
    devtool: 'source-map',
    plugins: [
      new ExtractTextPlugin({ filename: 'bundle.css', disable: false, allChunks: true })
    ]
  }
};
```

app/index.js

```javascript
import './index.css';
console.log('index');
```

app/index.css

```css
body {
  background: red;
}
```

**Comment by simon04** [comment]
Which version of `extract-text-webpack-plugin` are you using? Make sure to install a 2.x version, e.g., via `extract-text-webpack-plugin@beta`.

**Comment by yuyang041060120** [comment]
<img width="757" alt="2017-01-17 9 18 53" src="https://cloud.githubusercontent.com/assets/6648248/22021989/f7e29d40-dcfa-11e6-99d3-64b98d4d3815.png">

Maybe update doc to npm i --save-dev extract-text-webpack-plugin@2.x.x

**Comment by Jonwheeler** [comment]
I think that a note in the docs regarding this makes sense, though it should probably be updated once ExtractTextPlugin 2.X is released. I'm happy to make PR for this if folks agree?

Seems that there are may also be plans to address this in the ExtractTextPlugin project itself. https://github.com/webpack/extract-text-webpack-plugin/issues/280

**Comment by skipjack** [comment]
@Jonwheeler I think updating the guide to reflect this would be great. Not sure on the timeline for the first official v2 release of the ExtractTextPlugin -- @bebraw do you know?.

If that release isn't coming soon (like within the next week or so) then yeah it's probably worth a quick PR.

**Comment by bebraw** [comment]
@skipjack No idea of timeline. That depends on Tobias and his schedule.

**Comment by simon04** [comment]
@bebraw, when the PR https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/409 is merged, we can close this issue. :smile:

**Comment by bebraw** [comment]
@simon04 Merged.
