### ISSUE TITLE
Add index.html to the initial project tree in output management guide

### ISSUE THREAD

**Issue by rajas2211** [webpack/webpack.js.org#6584]
**Feature to document**

dist/index.html should be present in the project folder tree for the preparation step 
https://webpack.js.org/guides/asset-management/

**Author(s)**
@snitin315 @skipjack @TheDutchCoder

**Additional information**
Following up from the end of previous tutorial (Asset Manegment) and what lies ahead in the tutorial, it seems index.html should be a child present in the dist directory

**Comment by chenxsan** [comment]
If you mean 
<img width="821" alt="" src="https://user-images.githubusercontent.com/1091472/210975720-51bf157e-8bae-4e1c-bac9-7c4d022798a7.png">

I think the main point here is to add a `print.js` file.

**Comment by rajas2211** [comment]
Yes, apoologies, I copied a wrong link there.

I agree with the rationale here, it just seemed inconsistent. While following along with the tutortial, I assumed dist/index.html was not required here and deleted it. However, it was used in the next step. Hence, the request to update it.
