### ISSUE TITLE
A more detailed explanation of default minifiers

### ISSUE THREAD

**Issue by dartess** [webpack/webpack.js.org#6586]
**Feature to document**

https://webpack.js.org/configuration/optimization/

> '...' can be used in optimization.minimizer to access the defaults.

But what are these "the defaults"? Usecase: I know that by default webpack uses Terser to compress JS. I want to change it to another minifier. But the documentation does not give me an understanding if there is something else in "the defaults" that I need to transfer to my config.

**Author(s)**

**Additional information**

[ ] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
@dartess I've filed a pull request adding some explanation to it, let me know if it helps you.
