### ISSUE TITLE
Site - Hook up the Gitter Button to Open Gitter Sidecar

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#66]
* Sidecar - https://sidecar.gitter.im/.

Probably need to handle this at template level (`Body.jsx`) and write JavaScript to open it when the Gitter button is clicked.

**Comment by ericclemmons** [comment]
This looks done already:
> https://webpack.github.io/webpack.io/

**Comment by bebraw** [comment]
@ericclemmons The site is not up to date (no automated deployment process or staging yet). The design is a bit different now.

**Comment by SpaceK33z** [comment]
Fixed in 610cf2515a4be760db1cd52a8b679f141dd7b86e

Also tested it myself and it works!

**Comment by skipjack** [comment]
Works on develop with @bebraw's 610cf2515 but doesn't isn't hooked up to the button in the Sidecar but instead adds that button at the bottom, it seems what @SpaceK33z did, using the special class, should work or using:

```html
<script>
  ((window.gitter = {}).chat = {}).options = {
      room: 'webpack/webpack',
      activationElement: '.sidecar__item--gitter'
  };
</script>
<script src="https://sidecar.gitter.im/dist/sidecar.v1.js" async defer></script>
```

Yet I tried both of these and neither did. I think it might have something to do with the fact that the element is rendered after that script runs. For some reason even though the gitter script comes at the end of `template.js`, it gets inserted into the DOM before the other script tags. Maybe we use their [api alternative](https://sidecar.gitter.im/) to get it working:

```js
var chat = new window.gitter.Chat(/* options */);
```

Not sure if any of this helps but I just thought I'd share what I saw/tried. Haven't been able to figure out a fix yet but it would be nice if we could hook this to the Sidecar as originally planned.

**Comment by bebraw** [comment]
@skipjack Can you try against the current `develop` version? Works for me if I build it (`npm run build`).

**Comment by skipjack** [comment]
@bebraw Ah you're right! so it's just an issue on the dev-server then. We should get rid of the extra "Open Chat" button at the bottom though, I believe we can do that by adding:

```js
activationElement: false
```

Not too big a deal if it doesn't work on the dev-server for now.

**Comment by bebraw** [comment]
@skipjack It actually works during development for me. But yeah, production matters the most. I'll add that flag there. Good point.
