### ISSUE TITLE
Would like to link transpile-webpack-plugin to the Plugins page

### ISSUE THREAD

**Issue by licg9999** [webpack/webpack.js.org#6614]
**Feature to document**

Hi team, months ago, I noticed an issue https://github.com/webpack/webpack/issues/5866 which initiated the use of webpack without bundling. The issue looked to be not resolved for a while. As I was also troubled by the same problem at that time, I started working on a webpack plugin for a possible solution, which is [transpile-webpack-plugin](https://github.com/licg9999/transpile-webpack-plugin).

After several release, thinking the plugin has matured, I would request to get it linked in the webpack official website now, so that more developers could use it for their problems.

If any comments for the plugin, just let me know by continuing the discussion in this issue or starting a new issue in [the plugin's issue list](https://github.com/licg9999/transpile-webpack-plugin/issues).

If no more comment, I would be happy to submit changes for linking the plugin to [the Plugins page](https://webpack.js.org/plugins/) by creating a pull request for this repo by modifying existing files as below:

* `src/content/plugins/index.mdx`
* `src/content/awesome-webpack.mdx`

and creating a new file for the detail page of the plugin  (following the way [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) did):

* `src/content/plugins/transpile-webpack-plugin.mdx`

Let me know how the team thinks of it. Any concerns or any comments. Mind my starting a pull request? Thanks.

**Author(s)**

**Additional information**

[✓] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
Hi, feel free to add a link to `src/content/awesome-webpack.mdx` which is reserved for any third-party plugins, but I don't really know if we want to include another file under `src/content/plugins/`. I think `html-webpack-plugin` is an exception because it's sort of required to use webpack. We'd rather keeping it less than more.

**Comment by licg9999** [comment]
Hi @chenxsan, cc: @snitin315, I finished preparing the pull request(https://github.com/webpack/webpack.js.org/pull/6807) as we talked above. Would you take a second to have a look? Appreciated.
