### ISSUE TITLE
Documentation incorrect or incomplete for `/plugins/split-chunks-plugin/#splitchunksname`

### ISSUE THREAD

**Issue by benjaminblack** [webpack/webpack.js.org#6646]
The documentation reads:

> If you choose to specify a function, you may find the `chunk.name` and `chunk.hash` properties (where chunk is an element of the chunks array) particularly useful in choosing a name for your chunk.

The `chunk.hash` property seems to not exist. [Minimal example demonstrating the problem](https://stackblitz.com/edit/webpack-webpack-js-org-m6dszs?file=webpack.config.js).

I.e., in `chunks.forEach(({name, hash}) => ...)`, `name` is `"main"` but `hash` is `undefined`.

**Comment by alexander-akait** [comment]
@chenxsan Feel free to close if you already fixed it
