### ISSUE TITLE
Clarification on watchOptions ignored and new webpack.WatchIgnorePlugin

### ISSUE THREAD

**Issue by zakuru** [webpack/webpack.js.org#6673]
**Feature to document**: Clarification on watchOptions ignored and new webpack.WatchIgnorePlugin

https://webpack.js.org/configuration/watch/#watchoptionsignored
https://webpack.js.org/plugins/watch-ignore-plugin/

@SpaceK33z @skipjack 

**Additional information**

Hi,
The 2 things seem to do the same work unless am I mistaking ?
Apologies if I did not understand the differences between the two.

[ X] I am willing to work on this issue and submit a pull request.

**Comment by chenxsan** [comment]
Hi, I think most webpack users don't have to worry about those internal plugins unless you're developing tools like next.js upon webpack api. We list them for users who want to use webpack through api and who might want to customize webpack plugins instead of using the default ones.

**Comment by zakuru** [comment]
@chenxsan Thanks for your answer
Looking into next.js repo there a no references to `WatchIgnorePlugin`, plus I think they moved to `turbopack` now.
If there is a clear use case where `WatchIgnorePlugin` is necessary over  could it be explained ?
https://github.com/search?q=repo%3Avercel%2Fnext.js+WatchIgnorePlugin&type=code

But actually they use the `watchOptions` element.
https://github.com/vercel/next.js/blob/a5a13fe930060058cea406ebbbb4454a480c95e5/packages/next/src/build/webpack-config.ts#L1653

**Comment by TheLarkInn** [comment]
Doing some investigation on WatchIgnorePlugin: 

* https://github.com/webpack/webpack/issues/979
* https://github.com/webpack/webpack/pull/858
* https://github.com/webpack/webpack-dev-server/issues/112

It appears that its purpose is to simply ignore files/directories from being watched. As for why this might be useful, I think perhaps thats situational. Some issues seem to reference rebuild performance, others seem to reference preventing infinite reloads. I think if you would like to document this we should agree on a terminology covers some basic scenarios. 

Hope you find this helpful!

**Comment by TheLarkInn** [comment]
I'm noticing that `WatchIgnorePlugin` doesn't map to any configuration properties (like some internal webpack plugins do). I think that if _anything_ we should make a note that `WatchIgnorePlugin` is obsolete and it is recommended to use `watchOptions`. 

Probably best official stance we can take.

**Comment by TheLarkInn** [comment]
We probably won't _get rid_ or delete the plugin as its a breaking change. (Or if we do we should slow deprecate it across a major version).

**Comment by zakuru** [comment]
Thank you @TheLarkInn for the clarification 
I can open a PR to mark it as obsolete then will tag you when ready in a few days 🙏

**Comment by chenxsan** [comment]
Closed via https://github.com/webpack/webpack.js.org/pull/6709
