### ISSUE TITLE
Usage - Plugins - Optimize - CommonsChunkPlugin

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#67]
We would ideally have a "Usage" page which contains a way for users to see a single page devoted to one plugin. (Can be accessed from List of Plugins).
- [ ] Has the same [general API usage information](https://webpack.github.io/docs/list-of-plugins.html#commonschunkplugin) 
- [ ] We expand on this with multiple ways to use CommonsChunk. 
- [ ] References Code snippets from the [examples section](https://github.com/webpack/webpack/tree/master/examples)

One of the biggest struggles for most developers (including myself sometimes) is understanding _what_ each of the properties mean in an understandable way, and understanding what happens when you combine them etc.

**Comment by TheLarkInn** [comment]
@bebraw @jcreamer898

I think that this would be a nice single page approach to these plugins, if this isn't what you imagined @bebraw for plugins usage. (This also makes documenting the individual plugins easier than having to pull in the entire `list of plugins` page IMO).

**Comment by bebraw** [comment]
Yeah, I agree having `plugins/` namespace could be sensible. Small, focused articles over big, chunky ones. There is going to be some overlap between different sections (think how tos, conceptual info), but that's ok.

**Comment by bebraw** [comment]
There's https://webpack.js.org/plugins/commons-chunk-plugin now. Time to close I think.
