### ISSUE TITLE
webpack.js.org cannot be saved with the Browser

### ISSUE THREAD

**Issue by flash-me** [webpack/webpack.js.org#6726]
**Feature to document**

As a visitor of the https://webpack.js.org/ website, I want the option to save pages locally for offline usage or in educational context when referring to webpack in scientific papers.

**Author(s)**
Not a particular person. Any page cannot be saved

**Additional information**

1. Visit any page, e.g. https://webpack.js.org/concepts/
2. Save the page with <kbd>Ctrl</kbd>+<kbd>S</kbd> (on mac <kbd>Cmd</kbd>+<kbd>S</kbd>)
3. Open the locally saved HTML File
4. cry

![image](https://user-images.githubusercontent.com/5240450/228973556-fd1f95cc-7119-4e50-b9d7-fdf4c7a58139.png)

cheers
flash ⚡

**Comment by chenxsan** [comment]
Hi, I believe you can still visit the webpack.js.org site even when offline as we cache the whole site with [workbox](https://github.com/webpack/webpack.js.org/blob/e6b4eda8c03a618513b579a65ba629253a76bcfd/src/sw.js). You don't have to save any page first to access it.

**Comment by flash-me** [comment]
It's not about what my browser chaches. The use case is to save files to local machine (HTML, JS, assets) so you can share them to others.

If the other people then try to open these local files, the page won't work.

cheers
flash ⚡
