### ISSUE TITLE
Missing documentations

### ISSUE THREAD

**Issue by lcxfs1991** [webpack/webpack.js.org#678]
hello,

We found there are several missing docs in `master` branch, however, they can be compiled in `gh-pages`branch.

Could you explain the relationship here?

![408202265117772168](https://cloud.githubusercontent.com/assets/3348398/22092816/b1d25650-de3b-11e6-8899-58b8ef89d8f0.jpg)

![694612570446993594](https://cloud.githubusercontent.com/assets/3348398/22092817/b6f75f40-de3b-11e6-9e39-20aff3fd52b4.jpg)

**Comment by bebraw** [comment]
Those are fetched from GitHub repositories below webpack organization. They are literally the README files. It also picks up some local files.

**Comment by lcxfs1991** [comment]
we are trying translate this part into Chinese. Could you tell me where I can locate the source?

**Comment by bebraw** [comment]
It picks up plugins and loaders from https://github.com/webpack .

If you write files with the same slugs to loaders/plugins directories, the setup might pick those instead (needs testing and possibly a tweak). That would work for translating.

**Comment by lcxfs1991** [comment]
We are using master for translation. Could we just copy those readme files from github and drag them into the folder?

**Comment by bebraw** [comment]
Yeah. That was the point.

**Comment by lcxfs1991** [comment]
thank u!
