### ISSUE TITLE
Document dev server overlay improvement

### ISSUE THREAD

**Issue by malcolm-kee** [webpack/webpack.js.org#6808]
**Feature to document**

There are new dev server overlay configurations with the following changes:

- https://github.com/webpack/webpack-dev-server/pull/4605
- https://github.com/webpack/webpack-dev-server/pull/4813

**Author(s)**

@malcolm-kee

**Additional information**

- [X] I am willing to work on this issue and submit a pull request.

I plan to work on this next week, but happy to let others work on this if they're interested.

**Comment by chenxsan** [comment]
Closed via https://github.com/webpack/webpack.js.org/pull/6809
