### ISSUE TITLE
Scrollbar not visible in sidebar.

### ISSUE THREAD

**Issue by Riyan911** [webpack/webpack.js.org#6838]
# Bug report

**What is the current behavior?**
Scrollbar is not visible in microsoft edge linux. 
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version:
Operating System:
Additional tools:

**Comment by chenxsan** [comment]
I believe it was designed this way https://github.com/webpack/webpack.js.org/commit/c7d70be3f00c7642c8dd4392b34315d13c35c94e. And in your screencast, I can see you scrolled sidebar successfully while reaching the end fast as `Under The Hood` is the last item in sidebar menu.

**Comment by Riyan911** [comment]
I meant to say that that the scrollbar isn't visible on the left hand side

**Comment by chenxsan** [comment]
> I meant to say that that the scrollbar isn't visible on the left hand side

Then it's designed this way. But I agree it's sacrificing accessibility for good looks.
