### ISSUE TITLE
file-loader outputPath doesn't work

### ISSUE THREAD

**Issue by yuyang041060120** [webpack/webpack.js.org#685]
file-loader: 0.9.0

<img width="342" alt="2017-01-20 10 11 24" src="https://cloud.githubusercontent.com/assets/6648248/22133045/da779e54-def8-11e6-9100-595be1e11eab.png">

I doesn't find any "outputPath" word in source code. And It doesn't work in my config.

```javascript
{
  test: /\.txt$/,
  use: 'file-loader?name=[name].[ext]&outputPath=dist/word/'
}
```

**Comment by bebraw** [comment]
What's that supposed to do? Are you sure you didn't mean to include the path to `name`?

**Comment by SpaceK33z** [comment]
That's because `outputPath` hasn't been released yet... (see [commits](https://github.com/webpack/file-loader/commits/master)).
