### ISSUE TITLE
Config - Add Missing Devtool Options

### ISSUE THREAD

**Issue by Torwori** [webpack/webpack.js.org#686]
https://webpack.js.org/configuration/devtool/

`inline-source-map` is listed under "For development", but it's missing from the summary table above it.

**Comment by Torwori** [comment]
Same with `hidden-source-map`. :smile:

**Comment by johnstew** [comment]
Also it looks like `cheap-eval-source-map` is listed in the table but missing in the `development` description beneath it.

**Comment by simon04** [comment]
Also related: #273
