### ISSUE TITLE
Upgrade Plugins in migration guide

### ISSUE THREAD

**Issue by tbrisbout** [webpack/webpack.js.org#687]
The first step in my project in order to upgrade to webpack 2 is to fix unmeet peer dependencies with already installed plugins (eg `extract-text-webpack-plugin`).

The migration guide on the website starts with API changes in configuration.
Documentation for this one is not immediately obvious.

It may be interesting to begin with installation change for each *official* plugin to use with webpack 2,
and then describe API changes.

Let me know if I can help with this, or if it is already in progress.

**Comment by bebraw** [comment]
`extract-text-webpack-plugin` is problematic as it's still running in beta, yeah.

If you don't mind crafting a little PR to amend this issue, that would help. 👍 

> It may be interesting to begin with installation change for each official plugin to use with webpack 2, and then describe API changes.

Agreed. That would be a great change too.

**Comment by simon04** [comment]
The `extract-text-webpack-plugin` is out of beta.
