### ISSUE TITLE
Issues with elastic apm rum configuration with webpack

### ISSUE THREAD

**Issue by prasadcv94** [webpack/webpack.js.org#6975]
Please find the details wrt.. issue

package.json
============

"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-scripts": "5.0.1",
"webpack": "^5.75.0"

"webpack-cli": "^5.0.1",
"webpack-dev-server": "^4.11.1"

"@elastic/apm-rum": "^5.12.0",
"@elastic/apm-rum-react": "^1.4.2",

bootstrap.js
============

import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./App";
import apm from "../rum.js";
import config from "../Config.js";

apm.setInitialPageLoadName(config.getApmServiceName());

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

rum.js
======

import { init as initApm } from "@elastic/apm-rum";
import Config from "./Config.js";

const apmServerUrl = Config.getApmServerUrl();
const apmServiceName = Config.getApmServiceName();
const apmAppEnvironment = Config.getApmAppEnvironment();

var apm = initApm({
  serviceName: apmServiceName,
  serverUrl: apmServerUrl,
  verifyServerCert: false,
  active: true,
  instrument: true,
  environment: apmAppEnvironment,
});
export default apm;

with the above configurations, while starting the application we are getting below error in the console and stopping the page load.

Error:
Uncaught (in promise) TypeError: (0 , _elastic_apm_rum_core__WEBPACK_IMPORTED_MODULE_2__.bootstrap) is not a function
    at getApmBase (index.js:21:81)
    at eval (index.js:32:15)
    at ./node_modules/@elastic/apm-rum/dist/es/index.js (vendors-node_modules_elastic_apm-rum_dist_es_index_js.js:513:1)
    at __webpack_require__ (main.js:339:33)
    at main.js:551:198
    at __webpack_require__.m.<computed> (main.js:1152:34)
    at __webpack_require__ (main.js:339:33)
    at fn (main.js:628:21)
    at eval (rum.js:2:74)
    at ./src/rum.js (node_modules_babel-loader_lib_index_js_ruleSet_1_rules_3_use_src_app_bootstrap_js.js:28:1)
	
	

Please help me on this issue.

**Comment by chenxsan** [comment]
Hi, without a reproducible repo, we can't really help. You may ask it on stackoverflow.
