### ISSUE TITLE
feature request: add Manifest Extraction Plugin to awesome-webpack page

### ISSUE THREAD

**Issue by hinell** [webpack/webpack.js.org#6999]
https://github.com/webpack/webpack.js.org/blob/49ff8629e8a4652bbfc1f5ce71de66e96180724b/src/content/guides/output-management.mdx#L218-L220

**Feature to document**
Manifest Extraction Plugin. Currently it's mentioned in guide, but not in Plugins list.

Link to Manifest Extraction Plugin: https://github.com/shellscape/webpack-manifest-plugin

**Comment by snitin315** [comment]
@hinell this is a 3rd party webpack plugin, in the plugin list we mention plugins maintained by the webpack team only. Ideally these plugins come under the [webpack](https://github.com/webpack) and [webpack-contrib](https://github.com/webpack-contrib) organisation on GitHub. But we can add this plugin on the awesome-webpack page - https://webpack.js.org/awesome-webpack/

**Comment by hinell** [comment]
Whatever. Feel free to close.
