### ISSUE TITLE
请问 第二个参数传了false，为什么还是会递归子目录呢，require.context('./', false, /\.js$/) 

### ISSUE THREAD

**Issue by JimWang-happy** [webpack/webpack.js.org#7048]
![image](https://github.com/webpack/webpack.js.org/assets/76657138/2ce8e411-c2b8-483b-b936-65d8beee7a6f)
![image](https://github.com/webpack/webpack.js.org/assets/76657138/4d189fbd-c2aa-488a-8081-184813c18c76)
![image](https://github.com/webpack/webpack.js.org/assets/76657138/526d6cd1-cd74-4fa7-9b4b-b0da622735cf)

**Comment by h7ml** [comment]
When using the `require.context` method, the second parameter determines whether to recursively search subdirectories. If you pass `false` as the second parameter, it means that subdirectories will not be searched. However, this parameter only applies to files in the current directory. If there are subdirectories in the current directory with files that meet the criteria, the `require.context` method will still recursively search them, regardless of the value of the second parameter.

Therefore, if you want to limit the `require.context` method to only search files in the current directory, you can set the first parameter to the absolute path of the current directory, like `require.context(__dirname, false, /\.js$/)`. This way, it will only search for `js` files in the current directory and will not recursively search subdirectories.

**Comment by JimWang-happy** [comment]
Thank you for your reply, but I used require.context(__dirname, false, /\.js$/) and it still didn't work.
![image](https://github.com/webpack/webpack.js.org/assets/76657138/d0f7330f-784e-4b45-a651-e104b978988d)
![image](https://github.com/webpack/webpack.js.org/assets/76657138/bb9db390-5185-44dc-b99c-691a9d24496a)

**Comment by snitin315** [comment]
Please create issues in English with proper steps to reproduce.
