### ISSUE TITLE
Splichunks.name documentation question.

### ISSUE THREAD

**Issue by pushkargupta9807** [webpack/webpack.js.org#7082]
![image](https://github.com/webpack/webpack/assets/93791633/b4e1cfa7-9dde-4192-84ec-b354d540812d)

Hello , I am using the above tip to move some modules into the main entry chunk . Specifying the `spliChunks.{cacheGroups.cacheGroup}.name : "main"` does the trick for me. 

However I am getting confused by the statement "If the splitChunks.name matches an [entry point](https://webpack.js.org/configuration/entry-context/#entry) name, the entry point will be removed."  Can anyone please elaborate on this? I dont want to introduce any side-effects with the above change only to discover later.

**Comment by chenxsan** [comment]
That sentence was first documented in https://github.com/webpack/webpack.js.org/pull/2183 to close issue https://github.com/webpack/webpack/issues/7217. But I reckon there might be misunderstanding there. Probably we should just remove that sentence if no one knows what it means.

**Comment by snitin315** [comment]
When `spliChunks.cacheGroups.{cacheGroup}.name` matches an entry-point name, the entry-point chunk & the cache group chunk will be merged. See [this example](https://stackblitz.com/edit/node-2hjcez?file=webpack.config.js), comment line 30 in `webpack.config.js` (`name: 'main'`),  and see the [file difference.](https://diffchecker.com/0xcQfCcM/)

<img width="1500" alt="Screenshot 2024-08-25 at 2 37 09 PM" src="https://github.com/user-attachments/assets/df535e73-c598-4b7b-9564-9ba794d43526">
