### ISSUE TITLE
Bug: Broken Link to CommonJS Specification

### ISSUE THREAD

**Issue by wheezyturbo** [webpack/webpack.js.org#7084]
### Bug

[CommonJS Broken Link](https://webpack.js.org/concepts/modules/#what-is-a-webpack-module)

### Additional information:
![Screenshot from 2023-12-28 10-42-21](https://github.com/webpack/webpack.js.org/assets/77047619/63e35878-5599-4c55-b56c-02e44fcc2530)
![Screenshot from 2023-12-28 10-42-44](https://github.com/webpack/webpack.js.org/assets/77047619/45c39151-4bb0-42ae-851d-61c3bd9cc7e0)

The link to the CommonJS specification on the webpack.js.org documentation is currently broken. When users click on the CommonJS link, it directs them to a "Not Found" page with the following error:

Location in Documentation: [Link location - https://webpack.js.org/concepts/modules/#what-is-a-webpack-module]
Current URL: [Broken URL - https://wiki.commonjs.org/specs/modules/1.0/]

### Steps to Reproduce:

Go to [link location](https://webpack.js.org/concepts/modules/#what-is-a-webpack-module) in the webpack.js.org documentation.
Click on the "CommonJS" link.
Additional Context:
The CommonJS specification is crucial for users to understand different module systems. A working link will improve user experience and ensure accurate information.

**Comment by alexander-akait** [comment]
Hello, do you want to send a PR?

**Comment by wheezyturbo** [comment]
> Hello, do you want to send a PR?

Yes, I would like to

**Comment by wheezyturbo** [comment]
#7086
