### ISSUE TITLE
Documentation change for clarification in asset management

### ISSUE THREAD

**Issue by tusharkashyap11** [webpack/webpack.js.org#7087]
**Description**

I was following the guide of asset management to use images in my local project where in loading images section of asset management guide the image is loaded two times if I make the changes in both js file and css file as mentioned in guide.

PR: https://github.com/webpack/webpack.js.org/pull/7090

**Additional information**

I think we only need to mention the change in js file as change in css file will load two images and there is no need or maybe a clarification for changing the css file maybe needed.

- [x] I am willing to work on this issue and submit a pull request.

**Comment by snitin315** [comment]
https://github.com/webpack/webpack.js.org/pull/7090#discussion_r1451231354
