### ISSUE TITLE
http 404 for site css

### ISSUE THREAD

**Issue by tsm91** [webpack/webpack.js.org#709]
https://webpack.js.org/048c7d20138eed316cc2.css is not found

http://imgur.com/a/s8NfX

**Comment by bebraw** [comment]
Works for me. Can anyone confirm?

**Comment by NejcZdovc** [comment]
Works for me

**Comment by montogeek** [comment]
Works here

**Comment by tsm91** [comment]
works for me too now

p.s also tried it in another browser before submitting the issue. i can confirm at that time it didnt work

**Comment by bebraw** [comment]
It must have been some temporary glitch (GitHub Pages or CDN?). It's very hard to debug, though, as we have literally zero access to the server side.

**Comment by tsm91** [comment]
It was giving me 404 for like ~10minutes

because of 404 and the filename of css i thought there was a new release and the index.html referencing the css in the old cache busted name
