### ISSUE TITLE
Better visibilty for sidecar icons on smaller screens

### ISSUE THREAD

**Issue by dmitriid** [webpack/webpack.js.org#710]
## Problem

The sidebar icons on the right-side of the screen:

![](http://dmitriid.com/i/gm2tmnrrgq2danry.png)

They are only visible on viewport sizes 1085px and up. It means that there's no way to get to the source, the blog and other links, unless you are on a desktop, with browser at at least 60% of the screen.

Additionally: they are not visible on the front page

Additionally: they are at the edge of vision, on a cluttered screen, so it's quite possible to completely dismiss them as social share icons, or ads ore somesuch. Moving them to the main menu will raise their visibility

## Suggested solution:

1. 

There is more than enough space in the top menu. Add icons in a horizontal row as they are now to the end of the menu (after "donate"). The break point for menu is 768px. Even at this size there's more than enough space to fit all four icons

2.

The top level menu (including icons) should probably be at the top of the mobile menu, and only then display itself with all the subsections

**Comment by johnstew** [comment]
I like this idea, but honestly its really more a matter of how important the webpack team considers those links. That being said, I have a PR in right now to add the [blog link to the main menu](https://github.com/webpack/webpack.js.org/pull/700). So that PR might want to be reconsidered. Either way, interested to see how the team feels.

**Comment by dmitriid** [comment]
@johnstew Awesome! Anything that increases visibility is great!

**Comment by johnstew** [comment]
Agreed!

It looks like we got the blog link in the header but I do agree with you on how those other links kind of get lost.

**Comment by dmitriid** [comment]
Closing this. Webpack communication team coudn't care less about info visibility

**Comment by TheLarkInn** [comment]
I'm sorry you got this impression but we absolutely care. I'm going to leave this open as this is a great idea.

**Comment by dmitriid** [comment]
@TheLarkInn You showed in #670 that clearly communicating what webpack is etc. is the much less of a concern than letting people know about a voting update :-\

I'm surprised you merged the blog pull request. As it took me only two months or so to even get you to get links to documentation visible.

All of a sudden this is "a great idea" etc. 

Yes, I'm bitter.

**Comment by skipjack** [comment]
Closing as we finally got #816 across the finish line. The icons should look better with #858 merged too!

**Comment by dmitriid** [comment]
Perfect!
