### ISSUE TITLE
Chinese doc translation issue.

### ISSUE THREAD

**Issue by lcxfs1991** [webpack/webpack.js.org#722]
Hi @bebraw and @TheLarkInn.

We are recently having trouble with managing our translation docs. As we know, `webpack` doc repo does not keep loader and plugin docs itself. So we have to translate docs under `generated` folder which  makes us harder to make a diff.

Would you think of keeping those docs under `content` folder ? i.e., run a program to regularly update docs from each loader and plugin.

**Comment by TheLarkInn** [comment]
There's also the possibility to doing Kron jobs on Travis. Thoughts?

**Comment by bebraw** [comment]
A cron job would have to perform sync commits against master. I'm not sure if that's a smart idea.

Would it make sense to set up an intermediate repository like that? You would generate the directory there, and whenever you want to update the translation, you would trigger the generation script against that, get a diff, and then translate. I think this might give you the information you need to keep it up to date without complicating the setup of the main site.

**Comment by lcxfs1991** [comment]
We are having this [repo](https://github.com/webpack-china/webpack.js.org) for translation. 
That would be great if we could have such an intermediate repo. Then we could run a script to update the content ourselves.  I think it would also help if other developers want to translate the doc into other languages.

**Comment by bebraw** [comment]
@lcxfs1991 Ok, I'll try to set up one below `webpack-contrib` once I find a bit of time. I'll add you to the project too so you can update it etc.

**Comment by lcxfs1991** [comment]
Thank you so much. 

Please also add `dear-lizhihua` who also leads the translation project.

**Comment by TheLarkInn** [comment]
Thanks @bebraw. 🙇

**Comment by lcxfs1991** [comment]
hey @bebraw.

We have another suggestion  that a new branch `translation` can be created under `webpack.js.org` based on branch `master`. 

In branch `translation`, we can manage a script to update docs from loaders/plugins manually. On the one hand, we can update major docs of `webpack` if `master` branch is updated. On the other hand, once there is an update from loaders/plugins doc, we can merge content from `translation` to our translation repository.

Managing another branch may be easier than another new repository.

**Comment by bebraw** [comment]
@lcxfs1991 Is it enough if I set up a branch with proper rights for you to handle then? That sounds simpler, yeah.

**Comment by lcxfs1991** [comment]
yes man.

**Comment by bebraw** [comment]
@lcxfs1991 Ok. I set up the branch and sent you an invite. You should be able to write to the branch.

**Comment by lcxfs1991** [comment]
thanks!
