### ISSUE TITLE
Why does the example for the loader use ES modules?

### ISSUE THREAD

**Issue by jrr997** [webpack/webpack.js.org#7264]
Loader runs in nodejs, but the docs example is writing in esm. I copied an example and run it with error, it took me some time to solve this  error. I think we should write [these example](https://webpack.docschina.org/contribute/writing-a-loader/#simple) to commonjs.

**Comment by chenxsan** [comment]
What kind of error? Could you share the reproducible repository? Btw, probably you need to update your node.js version? As ESM was supported in Node.js for a long time.

**Comment by jrr997** [comment]
Thanks for your help! I change .js to .mjs and it works.
