### ISSUE TITLE
Break up Guides into different parent sections 

### ISSUE THREAD

**Issue by johnstew** [webpack/webpack.js.org#749]
Breaking out the conversation from #743 into its own ticket to discuss possible parent sections and if this is a good idea. Plus need to decide the UI/UX around having a parent section.

**Parent Section Ideas:**
- Introduction
- Getting started
- Production
- Caching
- Migration
- Code Splitting
- Tree Shaking
- Contributing to Webpack
- React
- Angular
- Extras

**Comment by rouzbeh84** [comment]
So is this one a wrap?

**Comment by skipjack** [comment]
@johnstew so just to make sure I understand this correctly: you're talking about grouping the page links in sidebar and potentially creating folders within `/content/guides` (or any of the other `/content/...` directories) for each group?

For the UI/UX it would be good to tie this into #438 which, if I understand correctly, is a similar discussion.

**Comment by johnstew** [comment]
@skipjack yes exactly

Looks like #438 is talking about the same thing as well.

**Comment by skipjack** [comment]
@johnstew ok great, closing this in favor of that one and quoting you there.
