### ISSUE TITLE
not clear enough in the paragraph devtool

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack.js.org#756]
![image](https://cloud.githubusercontent.com/assets/1060733/22402327/9a7f731c-e62d-11e6-8f68-48da09bf0cb0.png)

https://webpack.github.io/docs/configuration.html#devtool

it is not clear enough for the configuration of `devtool`
what does generated code mean?
transformed code,original source as well
and i found that,no map file will be generated if you set a value which contain "eval"
it is very necessary to tell readers that

**Comment by simon04** [comment]
You link to the webpack 1 docs. The [docs for webpack 2](https://webpack.js.org/configuration/devtool/#devtool) do not define "quality" neither.

**Comment by zzzgit** [comment]
yes,thanks
but i still don't know what does `transformed code` mean

**Comment by bebraw** [comment]
* Generated - Entire code gets modified (wrapped in eval)
* Transformed - Same except this time around it generates base64 encoded source map within the source. It's like generated++, more info.
* Original - Original source does not get touched, instead a comment is added (links to source map).

I have examples of the output [here](https://survivejs.com/webpack/building/source-maps/).

**Comment by zzzgit** [comment]
![image](https://cloud.githubusercontent.com/assets/1060733/23399166/44735c30-fdda-11e6-9edd-68b5556c862e.png)

Thanks.
If your saying are true,the code generated in `cheap-source-map` mode will be wrapped in eval too?

**Comment by bebraw** [comment]
@zzzgit No, `cheap-source-map` won't be wrapped in eval as it emits a separate source map. The definitions are different based on whether they contain `eval` or not. The quality part of the table is confusing this way.

There are simply too many options and too little info to cover these adequately. To make it more complex, webpack provides two source map specific plugins where you have more control. And some of the options are broken under certain conditions  `cheap-module-source-map` is a notable example of that.

**Comment by zzzgit** [comment]
Thanks for your sharing on survivejs,but it helps me not so many.
For example,in` cheap-source-map` and `cheap-module-source-map` mode,the sourcemap shot-snaps are almost the same,how could I understand what is the difference?
What you have described is that:

> cheap-module-source-map is the same as previous except source maps from loaders are simplified to a single mapping per line.

who can understand that?They both get a map like this :`{mappings":"AAAA}`.
I am very nervous now because that I have been seeking for information about webpack sourcemap for several days,but all the documentations and blogs can not give enough.
I plan to ask questions on stackover one bye one in the future

**Comment by bebraw** [comment]
@zzzgit Yeah, the problem is that information is very sparse on this topics. It's hard to find good material. The source is likely the truth in this case.

**Comment by skipjack** [comment]
Let's move this conversation to #273. Also feel free to comment on #686 for any short-term fixes (I'll add a PR soon).
