### ISSUE TITLE
Code splitting using require.ensure improvements

### ISSUE THREAD

**Issue by agoldis** [webpack/webpack.js.org#772]
https://webpack.js.org/guides/code-splitting-require/ is great, but there're some caveats that I've discovered while following the documentation.

In the current implementation the `callback` method of `require.ensure(dependencies: String[], callback: function(require), chunkName: String)` must use 'require' method name to actually require modules. 
During the compilation phase, webpack parses the expression and replaces `require('module')` expressions with `__webpack_require__(moduleId)` (among other static replacements), thus the following code

```javascript
require.ensure(['x'], function (require) {
  require('./dependecyA.js')
}
```

becomes
```javascript
 __webpack_require__.e/* require.ensure */(0).then((function (require) {
      return __webpack_require__(242); // 242 is module id
}).bind(null, __webpack_require__)).catch(__webpack_require__.oe);
}
```

Callback function receives a single argument - function `__webpack_require__`, as appears in `__webpack_require__.e/* require.ensure */(0).then((<callbackFunction>).bind(null, __webpack_require__))`, which looks like can be used to require a module at runtime, however, this is not true - requiring a module within `require.ensure` callback __must__ be done via explicitly using `require` and cannot have other name.

For example, the code (note the argument name `request`)
```javascript
require.ensure(['./dependecyA.js'], function (request) {  request('./dependecyA.js'); })
```

becomes
```javascript
    return __webpack_require__.e/* require.ensure */(0).then((function (request) {
      return request('./dependecyA.js');
    }).bind(null, __webpack_require__)).catch(__webpack_require__.oe);
```
The code throws exception at runtime because calling `request('./dependecyA.js')` cannot allocate a module with id `./dependencyA.js` (it should have been rewritten by parser during compile time to `__webpack_require__(<moduleNumericalId>)`

The examples at https://webpack.js.org/guides/code-splitting-require/ give an impression that the argument passed to callback function should be used to import and use modules.

I've checked this functionality using webpack build `2.2.1`

Would appreciate some comments on the issue so I would get some kind of justification to create a PR for the documentation.

**Comment by skipjack** [comment]
@agoldis thanks for pointing out that issue, and I'm sorry for the delayed response. That section of the documentation has been moved around a bit as `import()` is now the recommended practice. See the [code-splitting-async guide](https://webpack.js.org/guides/code-splitting-async). If it's still an issue and you're still interested in pr-ing this, I would recommend adding a warning using our custom blockquotes -- `W> ...`.

On top of that I'm not sure if this should be categorized as a bug over at the main repository or not, so I'll defer to @simon04 and @bebraw for that. Either way though, it would be great if you could PR the warning!

**Comment by agoldis** [comment]
@skipjack thank you for response. After re-reading my original issue, I found it a bit confusing 😄 . 

So, in short, the problem is that module names in `require.ensure` callback are not replaced by their `id`s, when function name other than `require` is used.

See https://github.com/agoldis/webpack.js.org-772 for example.

I'll start to work on PR

**Comment by skipjack** [comment]
> @skipjack thank you for response. After re-reading my original issue, I found it a bit confusing 😄 .

No worries, sorry for the long delay. Yep, it took me couple reads as well but I think in the end I got it (thanks for the clarification though).

> See https://github.com/agoldis/webpack.js.org-772 for example... I'll start to work on PR

Fantastic, feel free to ping me once you submit!

**Comment by agoldis** [comment]
@skipjack here we go..
