### ISSUE TITLE
Add a bar to announce new releases/important info

### ISSUE THREAD

**Issue by dmitriid** [webpack/webpack.js.org#777]
It would be nice to have a small bar below the top menu for feature/milestone/release/etc. announcements. It may include relevant links to blog posts or to documentation.

A similar feature is implemented on http://www.typescriptlang.org:

![](http://dmitriid.com/i/gm2tknzvgu4dqmzy.png)

The reason is simple: increase visibility of certain types of announcements (especially important new releases and critical fixes).

I found myself a bit intimidated by the new site's structure, so I didn't create a pull request. Esp. because this feature probably needs design and discussion.

**Comment by skipjack** [comment]
I can PR this over the weekend if nobody does sooner.

**Comment by dmitriid** [comment]
Awesome!

**Comment by skipjack** [comment]
Started playing around with something:

![image](https://cloud.githubusercontent.com/assets/8988697/22616661/7f513d86-ea7f-11e6-8a40-8ac5c31597b2.png)

If this looks good I can open a PR. The way I implemented this for now, it would only be displayed on landing page. I could do something similar for all pages (like how TypeScript does it) but it would have to go elsewhere for the landing page as our top navigation menu blends in with the background there.

**Comment by skipjack** [comment]
P.S. the "announcement" link points to @TheLarkInn's [post](https://medium.com/webpack/webpack-2-and-beyond-40520af9067f#.ojp0x5ls1) and "install it" points to [npm](https://www.npmjs.com/package/webpack).

cc @bebraw @TheLarkInn what are your thoughts on this?

**Comment by bebraw** [comment]
The new header looks good.

Btw, we could push all the blog bits to the site itself. That would avoid the pain of linking to Medium etc. It would not be hard to add a section just for that and we could do custom things like tagging easily. A lot what's needed is in place already.

**Comment by TheLarkInn** [comment]
How about for mobile? Would this appear as dismissible top banner above toolbar or down below still. Having at the top feels like a great call to action on mobile.

**Comment by skipjack** [comment]
Yea let's do that site wide -- that is, a similar bar, at the top, mobile-friendly and dismissible. I'll create a PR soon.

**Comment by skipjack** [comment]
Closing... added in #847.
