### ISSUE TITLE
Need to document better using --env in object format and not = syntax

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#790]
I plucked the following out of a medium article https://blog.flennik.com/the-fine-art-of-the-webpack-2-config-dc4d19d7f172#.yk2bx4gum

<img width="793" alt="screen shot 2017-02-01 at 4 24 31 pm" src="https://cloud.githubusercontent.com/assets/3408176/22532274/19d73716-e89b-11e6-93da-26ee7fd0a617.png">

**Comment by johnstew** [comment]
Only mention I was able to find of this currently was in webpack issue [#2254](https://github.com/webpack/webpack/issues/2254#issuecomment-203528744).

Should this live under guides?

**Comment by TheLarkInn** [comment]
I think thats a great start. Maybe bundling for production also, but guides is a good start, what do you think @bebraw

**Comment by bebraw** [comment]
PRs welcome. It's a good default.
