### ISSUE TITLE
Dev - Speed Up Build Checks

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#793]
Currently it builds the entire site and runs all the checks against all the files. It would be far faster to perform at least some of the checks against partial data that is figured out based on the changes made by the PR (just pick the changed files). Running proselint against changed files like this would be a good starting point.

It gets trickier with link validation as those can point anywhere within the site. Solving that would require a bit more (copy the existing site from `gh-pages` + perform a partial build to overlay on top of that).

**Comment by skipjack** [comment]
Noted in #1380 -- let's track there. There's already some easy things we can do in terms of the order our checks are run I think.
