### ISSUE TITLE
strictModuleExceptionHandling missing in documentation of webpack 2

### ISSUE THREAD

**Issue by aight8** [webpack/webpack.js.org#796]
Source in master:
https://github.com/webpack/webpack/blob/master/lib/MainTemplate.js#L69

Release info:
https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.28

**Comment by TheLarkInn** [comment]
Great low hanging fruit for anyone interested!

**Comment by TheLarkInn** [comment]
Thanks for reporting!

**Comment by skipjack** [comment]
Didn't even know about this feature, that's awesome! Found a [stackoverflow post](http://stackoverflow.com/questions/40539768/webpack-throw-error-on-missing-member-import) that has a good explanation, this might be a good start?

**Comment by sokra** [comment]
Note that the stackoverflow answer is wrong. `strictModuleExceptionHandling` is about how exceptions are handled in modules. If true module is removed form cache when exception occurs while module loading. see the PR introducing it.

**Comment by skipjack** [comment]
@sokra ah good to know.

**Comment by aight8** [comment]
> Note that the stackoverflow answer is wrong. strictModuleExceptionHandling is about how exceptions are handled in modules. If true module is removed form cache when exception occurs while module loading. see the PR introducing it.

This is confusing. From which cache? An example / why someone should enable or disable this - would make more sense.

**Comment by sokra** [comment]
from `require.cache` (the module instance cache at runtime)

``` js
// module.js
throw new Error("error");
```

``` js
// with strictModuleExceptionHandling = false
require("module") // <- throws
require("module") // <- doesn't throw
```

``` js
// with strictModuleExceptionHandling = true
require("module") // <- throws
require("module") // <- also throw
```

`strictModuleExceptionHandling = true` uses `try finally` in the runtime which makes it slow. The default behavior is the more performant one, assuming `require` is not used for exception twice.
