### ISSUE TITLE
Concepts - Manifest

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#80]
It would be useful to discuss the concept of manifest a bit. It's one of those ideas that's ignored often and if you aren't aware of it you can end up in troubles when hashing. There's perhaps not that much to explain, but it's good to cover still.

The article should go below `concepts/manifest.md`. If you have ideas/references in mind, feel free to comment.

**Comment by skipjack** [comment]
This is somewhat covered at the [end of the output-management guide](https://webpack.js.org/guides/output-management/#the-manifest). Maybe just expanding on that is enough for now? If it turns into something longer then maybe we can consider moving it to it's own page under `/concepts`?

**Comment by bebraw** [comment]
A separate concept page on **manifest** would be ideal, yeah. I have something [here](https://survivejs.com/webpack/optimizing/separating-manifest/).

**Comment by skipjack** [comment]
Ah ok, so how about we take the conceptual stuff and put it in a `/concepts/manifest.md` page and the implementation parts into the manifest section of `/guides/output-management.md` and link the two appropriately?

I'd be happy to tackle this if no one beats me to it.

**Comment by bebraw** [comment]
> Ah ok, so how about we take the conceptual stuff and put it in a /concepts/manifest.md page and the implementation parts into the manifest section of /guides/output-management.md and link the two appropriately?

Yup, exactly.
