### ISSUE TITLE
More visualizations

### ISSUE THREAD

**Issue by aight8** [webpack/webpack.js.org#811]
More visualization to explain different sub architectures.

For example:
- Explain assets, bundles, modules visually
- The plugin architecture, it hooks etc.

UML like visualization:
- A class diagram for stats, compilation, compilation etc. object - even when js is not a OO language, class are made to understand the whole and how it interact together
- A flow like diagram which explains the webpack internal flow on a generic level
- I found nothing about JS tapale "pattern" or whatever it is on which webpack builds on - it were so helpfull to explain the concept of those more detailed

Keep in mind that visualization can incredible helpfull

**edit**
- I saw webpack buils on top of plugins too, internal plugins, this could be wonderfully visualized as well.

**Comment by aight8** [comment]
ps: which open source visualization tool you guys recommend for this kind of taks?

**Comment by skipjack** [comment]
Can you take a look at #469? I think that's the discussion you're looking for.

**Comment by skipjack** [comment]
@aight8 I'm going to close this as I believe #469 addresses what you're talking about. Feel free to re-open if I'm wrong but I would suggest you make some of the same comments you've made here on that thread.
