### ISSUE TITLE
i can't find "moduleTemplates" property in resolveLoader object

### ISSUE THREAD

**Issue by dear-lizhihua** [webpack/webpack.js.org#841]
```
### [Resolving Loaders](https://webpack.js.org/concepts/loaders/#resolving-loaders)
The loader name convention and precedence search order is defined by [`resolveLoader.moduleTemplates`](/configuration/resolve#resolveloader) within the webpack configuration API.
```
---
Hi, my question is:
in the last section, i can't find "moduleTemplates" property in [resolveLoader](https://webpack.js.org/configuration/resolve/#resolveloader) object.
there are three properties in resolveLoader object, they are "modules", "extensions", "packageMains"

**Comment by simon04** [comment]
This sentence has been added in #383 and originates from the [webpack 1 docs](https://webpack.github.io/docs/using-loaders.html#resolving-loaders). In [webpack/enhanced-resolve](https://github.com/webpack/enhanced-resolve) `moduleTemplates` is not listed. Is this an outdated content?

**Comment by skipjack** [comment]
I don't see any mention of `moduleTemplates` in `resolve` or `resolveLoader` currently. However it is still mentioned in `content/concepts/loaders.md`, which links to [here](https://webpack.js.org/concepts/loaders/#resolving-loaders) for the `moduleTemplates` documentation.

It seems we either need to add `moduleTemplates` to the `resolveLoader` docs in the configuration section. Or remove the mention of it from `content/concepts/loaders.md` and possibly add its dissapearance to the migration guide. @simon04 any idea if that feature still exists?

**Comment by skipjack** [comment]
@bebraw do you know if `moduleTemplates` still exists? If so, I'd be happy to add it to the `resolveLoader` docs.

**Comment by bebraw** [comment]
@skipjack There's no mention to it in webpack source at least.

**Comment by skipjack** [comment]
Ok, so maybe we just remove all mention of it in the documentation.
