### ISSUE TITLE
404 CSS not loading for https://webpack.js.org/

### ISSUE THREAD

**Issue by Graham42** [webpack/webpack.js.org#845]

**Comment by SpaceK33z** [comment]
I can't reproduce this, can you give some more info?

**Comment by jadekler** [comment]
I'm seeing this too

**Comment by jadekler** [comment]
![screen shot 2017-02-07 at 9 35 34 am](https://cloud.githubusercontent.com/assets/3584893/22700729/cce5c972-ed18-11e6-9853-6dfd0d60abbe.png)

**Comment by jadekler** [comment]
![screen shot 2017-02-07 at 9 36 07 am](https://cloud.githubusercontent.com/assets/3584893/22700749/ddb64768-ed18-11e6-871d-0aa6ca2b444a.png)

**Comment by Graham42** [comment]
This looks to be fixed now

**Comment by garmjs** [comment]
This has been fixed, i also push #844 fixed on loading resources in pages
