### ISSUE TITLE
webpack.js.org domain with www cannot resolve

### ISSUE THREAD

**Issue by garmjs** [webpack/webpack.js.org#856]
Add CNAME www to point to domain
```
➜  webpack.js.org git:(master) ✗ ping webpack.js.org
PING webpack.js.org (104.27.139.230): 56 data bytes
64 bytes from 104.27.139.230: icmp_seq=0 ttl=54 time=38.251 ms
64 bytes from 104.27.139.230: icmp_seq=1 ttl=54 time=42.337 ms
^C
--- webpack.js.org ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 38.251/40.294/42.337/2.043 ms
➜  webpack.js.org git:(master) ✗ ping www.webpack.js.org
ping: cannot resolve www.webpack.js.org: Unknown host
➜  webpack.js.org git:(master) ✗ 
```

**Comment by bebraw** [comment]
There's not much we can do about that as we don't manage the domain.

@indus Any thoughts on this?

**Comment by simon04** [comment]
In my opinion it's uncommon to have `www.[subdomain].[domain].org`. https://www.webpack.github.io/ (GitHub pages, webpack 1 docs) does not work neither.

**Comment by bebraw** [comment]
Yeah. I think @indus might need to do custom config to enable the `www` prefix. Or we would have to get a domain (discussed earlier, but it didn't go through).

I think I'll close this as `wontfix` as there's not much we can do about it here.
