### ISSUE TITLE
API - Hot Module Reloading

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#86]
Describe the hot module reloading interface and how it works in this article.

**Comment by SpaceK33z** [comment]
Also note that we need to be very clear on the differences in the CLI and the Node.js API. `--hot` automatically adds the HMR plugin, while `hot: true` in the API does not.

Ultimately, there shouldn't be [any differences](https://github.com/webpack/webpack-dev-server/issues/616). But meanwhile, we need to make this very clear.

**Comment by bebraw** [comment]
Yeah, problems like that become obvious with documentation. webpack 1 documentation actually covers these quite a bit, but I have a feeling we can be clearer on that. There are some related technical docs that should be ported over.

**Comment by skipjack** [comment]
So currently there is a [concepts page for hmr](https://webpack.js.org/concepts/hot-module-replacement) and a [hmr-react guide](https://webpack.js.org/guides/hmr-react/#components/sidebar/sidebar.jsx). It seems this issue is for creating a page documenting how to interact with hmr via node. 

Maybe a short section on [this page](https://webpack.js.org/api/node/) or creating a separate one would make sense? It is [mentioned on the CLI page](https://webpack.js.org/api/cli/#advanced-options) already.

**Comment by skipjack** [comment]
Also, @SpaceK33z a warning was [added](https://webpack.js.org/configuration/dev-server/#devserver-hot) to the devserver configuration page 🎉 . Definitely tripped me up in the past, so I'm happy that's there now.

**Comment by jiyinyiyong** [comment]
I ran into this issue too https://github.com/thheller/shadow-cljs/issues/12#issuecomment-302519511

From my side I think a minimal HMR example(and without React) would help a lot. I just find it problematic to make it really work correctly, but don't know what happened in my case.

**Comment by skipjack** [comment]
> From my side I think a minimal HMR example(and without React) would help a lot. I just find it problematic to make it really work correctly, but don't know what happened in my case.

I completely agree and after finally getting react-hot-loader to work, I realized some of the things in the current [HMR w/ React Guide]() aren't even necessary. I might take a stab at some of this though I'll probably need some help from others who have more experience with the NodeJS interface for it.

**Comment by jiyinyiyong** [comment]
I made one https://github.com/mvc-works/minimal-webpack-hmr but it does NOT work yet... Anyone please help fix it...?

**Comment by skipjack** [comment]
@jiyinyiyong your repository worked fine for me:

![image](https://cloud.githubusercontent.com/assets/8988697/26378989/e9866220-3fe4-11e7-8cf0-a640703de81f.png)

If it's not obvious, I kept changing `console.log(...)` statement from "lib 6" to "lib 5" to "lib 4" and it re-ran the module every time.

**Comment by skipjack** [comment]
Started working on this, will be submitting a PR soon (likely tomorrow).

**Comment by skipjack** [comment]
@jiyinyiyong ping! Did you ever resolve that issue? Also would it be ok if I linked to that repo as an example in the new page I'm adding in #1251?

**Comment by jiyinyiyong** [comment]
@skipjack sorry I didn't read the notifications. Going though bad time for me. What was the problem? I thought it should "rerun"?

**Comment by skipjack** [comment]
@jiyinyiyong no worries. It does but that log message get's a bit lost, note the "loading lib 4" and "accepting lib" above it:

![image](https://user-images.githubusercontent.com/8988697/27145410-b6aee7d4-5103-11e7-8325-03179ae202ee.png)

See the updated [HMR guide](https://webpack.js.org/guides/hot-module-replacement/) -- I used your repo for inspiration.

**Comment by jiyinyiyong** [comment]
Glad it helped.

I was confuse about this sentence:

> Maybe you had an outdated dependency or something?

Then I recalled that I was told on Twitter that for `import`/`export` it's different, ES modules does not need a `require()` while ES5 does, a little difference:

https://github.com/minimal-xyz/minimal-webpack-hmr/blob/master/src/index.js
https://github.com/minimal-xyz/minimal-webpack-esm-hmr/blob/master/src/index.js

so... that explaines "outdated" here?

**Comment by skipjack** [comment]
I was actually referring to your npm packages -- maybe one was outdated (e.g. webpack or some child dep) that was causing you not to see it work. Because I didn't really have to make any changes to your repo to get it working.

Your point about the difference between `import` vs `require` with HMR is correct though, at least from my understanding. They mention the same thing in the react-hot-loader documentation.

**Comment by jiyinyiyong** [comment]
Oh, someone fixed it for me. https://github.com/minimal-xyz/minimal-webpack-hmr/pull/1/files
