### ISSUE TITLE
Clamp table width to page width?

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#865]
Tables like the one [here](https://webpack.js.org/configuration/target/#target) don't read that well as there's overflow. It might be better if the table scaled to the content width and grew vertically instead.

**Comment by skipjack** [comment]
Yea I believe this is what @pastelsky's PR #440 would do, however it would also cause tables on mobile to look a bit funky (as grow a huge amount and become unreadable). We could maybe fix that with a `@include break {...}` and only scale them vertically on larger screens.

This might be a better fix after #246 is addressed by @NejcZdovc. However, as multiple people have mentioned in all these places, I think the most important thing for us to consider is whether tables are really the best solution in a lot of places.

With all that said I think tables do make sense in certain instances and some combination of #440 and #246 would be the right way to go. I want to give @NejcZdovc some time to get something going for #246 and then I can review both and add any necessary bits to combine them.

**Comment by bebraw** [comment]
Ok, cool. Mobile tables come with problems of their own, yeah. Maybe a media query or two would be in order.

**Comment by skipjack** [comment]
#875 removed the `white-space: nowrap` which fixes this issue.
