### ISSUE TITLE
Guides - Using Middleware w/ Express, Koa, Hapi

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#866]
After speaking with @pdjota at ngVikings, it turns out we don't have any documentation for using webpack-dev-middleware with express. 

@SpaceK33z Do you have any docs hidden anywhere already? Otherwise, we can leave this as low hanging fruit for a first time contributor.

**Comment by SpaceK33z** [comment]
There are docs on the repo, https://github.com/webpack/webpack-dev-middleware/

**Comment by kbariotis** [comment]
I could get my hands on it. Usually, I am using it like this: https://github.com/kbariotis/gityeller/blob/master/server.js#L26. Would that be a good example?

**Comment by skipjack** [comment]
Closing for a few reasons...

- Inactive for a while now.
- Hasn't seen too much activity/popularity.
- Keep the focus on #1258 and review other top-level sections before jumping into more guides.
- Another instance of third-party docs before our core docs our fully ironed out.

With all that said...

- I'm marking this with a new `Reconsider` label, so in the event that someone wants to dig this back up they (or anything else marked `Reconsider`), we can.
- If someone wants to pick this up and has the time to really follow through with a PR, please feel free to re-open.

I think a better start for this may be adding some examples to the `webpack-dev-middleware` README if they don't already exist. At some point maybe we can create a __Utilities__ section similar to __Loaders__ and __Plugins__ that contains packages like this that don't really fit into the latter two. For example:

- `webpack-dev-server`
- `webpack-dev-middleware`
- `enhanced-resolve`
- and there's definitely a whole bunch of others I've seen...
