### ISSUE TITLE
API - Trouble w/ Parser

### ISSUE THREAD

**Issue by tschaub** [webpack/webpack.js.org#872]
I'm putting together a plugin that extracts strings for localization (assuming I should use a plugin since one new "dictionary" file will be emitted based on call expressions in many modules).  I'd like to visit call expressions on a subset of the modules in a dependency tree.

Seeing the docs for plugging into the parser, I was hopeful I could provide a callback that would get called for call expressions where the callee matched the supplied identifier.

Specifically, [these docs](https://webpack.js.org/api/plugins/#call-identifier-expr-expression-bailing):
```
call <identifier>(expr: Expression) bailing
abc(1) => call abc

a.b.c(1) => call a.b.c
```

made me think I could do this:
```js
parser.plugin('call this.context.localize', function(expr) {
  // called for this.context.localize() expressions
});
```

But this callback is not getting called.  I can successfully provide a callback for `'call require'`.  Am I misinterpreting the docs thinking that this works for other identifiers (and member expressions)?

**Comment by skipjack** [comment]
Hmmm sorry for the delay on this... I'm not seeing the code you mentioned on [that page](https://webpack.js.org/api/plugins/#call-identifier-expr-expression-bailing) anymore. Is this still relevant or should we close it out?

**Comment by skipjack** [comment]
Ah nevermind, it's [here](https://webpack.js.org/api/plugins/parser/#call-expr-expression-bailing) now.

**Comment by sokra** [comment]
Most parser hooks only react to **free var**. i. e. for `call a.b.c`:

``` js
a.b.c(1); // triggered
function test(a) {
  a.b.c(1); // not triggered
}
```

`call this.context.localize` won't work, because `this` is not free (and can't be).

You can try `call localize` which will trigger for not defined `localize` calls.

**Comment by skipjack** [comment]
@tschaub please refer to @sokra's comment above. I'm going to close as this has been inactive for a while now and I'm not sure how we can change the current documentation in the short term to improve this description. The good news is our cleanup of the _Guides_ section (#1258) is pretty much done and now I (and hopefully others) will start going through the _Concepts_ and _API_ sections next better organize and review the content there.

If you think something can be tweaked sooner to make it more readable please submit a PR or comment here.
