### ISSUE TITLE
require.ensure chunkName example does not seem to illustrate usage of chunkName

### ISSUE THREAD

**Issue by davidtheclark** [webpack/webpack.js.org#873]
https://webpack.js.org/guides/code-splitting-require/#chunkname is supposed to document the `chunkName` argument. But the usage of `require.ensure` in the example does not actually seem to include a `chunkName` argument:

```js
require.ensure([], function(require){
    require('b');
}/*, wouldn't a chunkName go here? */);
```

It also says "we can make sure all the dependencies are collectively put in the same bundle" — but does not illustrate the usage of any dependencies.

The end result is that I'm not sure what the `chunkName` argument does, so don't know how to contribute the right fix.

**Comment by bebraw** [comment]
The basic rule is that chunks that have the same name are bundled together. That's what the sentence is trying to say.

**Comment by simon04** [comment]
See https://github.com/webpack/webpack/tree/master/examples/named-chunks for an example regarding `chunkName`. I'll submit a PR to link to a few examples.

**Comment by davidtheclark** [comment]
Thanks for the hints. I submitted a PR in which I tried to clarify some points as best I could.
