### ISSUE TITLE
Dev - Bundles Contain Duplicate Code

### ISSUE THREAD

**Issue by pastelsky** [webpack/webpack.js.org#877]
The output of `npm run build` generates a bunch of `.js` split points, and each of them seem to have a copy of `preact` and other npm libs. 

I tried introducing `CommonsChunkPlugin` in `webpack.config`, but don't find any commons file being generated. This is pretty inefficient and perhaps loading a single commons bundle upfront would be better.

@bebraw Any clue if this config comes from antwar side of things?

**Comment by bebraw** [comment]
It generates a build per each page (the interactive bits). To fix this, you would have to dig into Antwar around [here](https://github.com/antwarjs/antwar/blob/cdcb81571a180498cdae988d4d41d77c3cadac17/packages/antwar/src/build/build_worker.js#L47). PRs welcome. 👍

**Comment by bebraw** [comment]
I think I know how to handle this now. Basically the interactive build has to treat preact/preact-dom as externals (cuts most of the size). preact/preact-dom have to be bundled separately by the main config and then wired to the template (`HtmlWebpackPlugin` might do this automatically). That would solve it.

**Comment by pastelsky** [comment]
Great. However it's not just preact. Around 95% of the code between these split points is the same. The only thing that differs is the rendering of the items in the sidebar and top nav depending on page.

**Comment by bebraw** [comment]
That would need a different approach entirely.

**Comment by pastelsky** [comment]
Yeah, I guess. I tried looking at the code you linked, but I'm not sure I
entirely understand what's going on there.

Was looking to add PWA support to the site, but the caching of all of these
bundles might exceed the cache storage quota.

**Comment by skipjack** [comment]
@bebraw is this something specific to this site, or more just related to how antwar's `<Interactive>` component behaves? If it's not specific to this site maybe we can close and push to this issue over to the antwarjs repo (unless you are saying this is already a "won't fix")?

**Comment by bebraw** [comment]
@skipjack It's a difficult one to fix but we can leave this open for now. I have a feeling treating Preact and its dependencies as **externals** at webpack configuration would solve most of this.

**Comment by TheLarkInn** [comment]
I'm definitely interested in converting docs into a PWA, so keep me looped in or tagged if this ends up in another issue.

**Comment by skipjack** [comment]
Closing in favor of #1380 -- I think a port or major antwar update like #980 may address this.
