### ISSUE TITLE
Guides - Set Up HMR with Redux

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#88]
Redux specific HMR setup.

**Comment by pksjce** [comment]
Isn't this covered by https://webpack.js.org/guides/hmr-react/?
Or is there more to be done?

**Comment by bebraw** [comment]
Yeah. You can implement the interface for reducers like I have done [here](http://survivejs.com/webpack/advanced-techniques/configuring-react/#configuring-redux).

**Comment by skipjack** [comment]
@bebraw I don't see anything in the article you linked to that cover HMR for redux. If you can point me to right places I might be able to tackle this either as a follow up or part of #1251. I'm actually somewhat interested in this anyway as I've used redux in multiple projects but changing reducers has always required a full browser refresh.

**Comment by bebraw** [comment]
Hi, the info went to [this article](https://survivejs.com/webpack/appendices/hmr-with-react/) as I split it up. You have to scroll down a bit.
