### ISSUE TITLE
Undocumented Stats options

### ISSUE THREAD

**Issue by aight8** [webpack/webpack.js.org#899]
usedExports
providedExports
maxModules
depth
entrypoints

Those are options can be set trough the CLI.
See: https://github.com/webpack/webpack/blob/master/bin/webpack.js#L234

**Comment by simon04** [comment]
Good catch! Do you plan to do a PR for https://webpack.js.org/configuration/stats/?

**Comment by kbariotis** [comment]
Ref: https://github.com/webpack/webpack/blob/master/lib/Stats.js#L51

@simon04 I will, unless @aight8 wants to take it. :)
