### ISSUE TITLE
Contribute - Debugging with V8 Inspector

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#90]
**I'm submitting a feature request**

**Webpack version:**
1.10.x/2.x

**Current behavior:**
We don't have any documentation on how to use the new `node-nightly --inspect --debug-brk` feature with webpack. There are a few little details to implement so it is worth having documentation on it. 

**Expected/desired behavior:**
Having a small section in documentation explaining how to leverage the power of `node-nightly` which contains the --inspect flag letting you use the full chrome dev tools to profile, find memory leaks, and debug your webpack builds. 
- **What is the motivation / use case for changing the behavior?**
  There are small leaky abstractions from miss use of certain webpack features. Mine being one of them. A useful profiler that people are familiar with like ChromeDevTools can be invaluable 

> Moved from https://github.com/webpack/webpack/issues/2724 .

**Comment by pksjce** [comment]
@bebraw - So, now in node 7 this is available. I have used 

`node --inspect=8888 --debug-brk ./node_modules/.bin/webpack`

But, I don't understand what I could profile and how it could be useful to me?

**Comment by bebraw** [comment]
@TheLarkInn Any thoughts on this?

**Comment by TheLarkInn** [comment]
Yeah so when builds are slow you can use the profile tab and record to find out what functions are taking up the most time from there. Should allow you to diagnose long running our use heap snapshots to capture memory allocations and see where leaks might be occurring.

**Comment by skipjack** [comment]
@TheLarkInn should we just port [this article](https://medium.com/webpack/webpack-bits-learn-and-debug-webpack-with-chrome-dev-tools-da1c5b19554) you wrote to a guide?

**Comment by skipjack** [comment]
I may try to pick this up. Been working with node scripts more recently so I'd be interested to read through @TheLarkInn's article and flesh it out into a guide/article. I think it might actually fit in the __Development__ or __Contribute__ section better though.

That said, if anyone else finds this and wants to pick it up, just ping me and we can figure something out (i.e. I'm fine with passing it along as well).

**Comment by skipjack** [comment]
I do think this makes more sense in the new _Contribute_ section. Will start working on a PR soon.
