### ISSUE TITLE
source map comparison missing some (inline-source-map)

### ISSUE THREAD

**Issue by vvo** [webpack/webpack.js.org#904]
In the sourcemap documentation, we are missing `inline-source-map` in the comparison table:

https://github.com/webpack/webpack.js.org/blob/332fa9f5ba8ba704cd100b1878437a8ed0694d13/content/configuration/devtool.md#devtool

![image](https://cloud.githubusercontent.com/assets/123822/23044969/78f10872-f457-11e6-9dc5-90fd25e14952.png)

While the `For development` paragraph speaks about `inline-source-map`.

So I was reading the development part and trying to find it in the comparison table, then I was lost.

I believe in the production part we are also talking about other types of sourcemaps that are not documented in the comparison table.

Missing a bit of consistency in here, sorry I can only report it, I do not master all the sourcemaps styles.

On a side note I always felt like this sourcemap situation is too much and seems overcomplicated (so many options)

**Comment by simon04** [comment]
Thanks for reporting. I'm closing this one since we already have #686 for missing devtool modes. Also related is #273.
