### ISSUE TITLE
Integrate proselint with Travis

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#91]
[proselint](https://github.com/amperser/proselint/) can catch quite a few issues. It's not fool proof and it will give false positives, but it could be nice to set up regardless as it would save some effort.

**Comment by TheLarkInn** [comment]
Awesome! Yeah definitely.

**Comment by bebraw** [comment]
If someone wants to give it a go, steps:

1. Figure out which rules to disable and set up proselint configuration accordingly.
2. Set up Travis to install and run proselint. You can install proselint through **pip**.

That's it.

I guess we can't expect contributors to have Python installed. At least PRs will get feedback from Travis, though, so there's that.

**Comment by pksjce** [comment]
Can you check #96 ? I'm not really sure how to integrate with Travis properly. Ideally I want it to show the warnings on Travis but not fail there.

**Comment by bebraw** [comment]
Merged so closing.
