### ISSUE TITLE
Loader not working with npm linked package

### ISSUE THREAD

**Issue by alvaro9210** [webpack/webpack.js.org#910]
How can I make the `angular-router-loader` work with an `npm link`ed dependency?

I have two projects `Project A`and `Project B`.
`Project B` is linked with `npm link` and it provides modules to `project A`.
The loader works fine when I lazy load on app.routing.ts of `Project A`:

```typescript
...
{
    path: "my-apps",
    loadChildren: "project-b/my-apps/my-apps.module#MyAppsModule",
},
...
```
This correctly produces the instruction to lazy load the Module from `Project B`:
```typescript
...
{
    path: "my-apps",
    loadChildren: function () { return new Promise(function (resolve) { __webpack_require__.e/* require.ensure */(0).then((function (require) { resolve(__webpack_require__(1554)['MyAppsModule']); }).bind(null, __webpack_require__)).catch(__webpack_require__.oe); }); },
...
},
```

But...
On MyAppsModule (from Project B) I also have a lazy loaded child with the following instruction:

```typescript
{
    path: ":slug",
    loadChildren: "./app-content/app-content.module#AppContentModule"
}
```

The thing is that the loader doesn't change the import of the module of`Project B`, it keeps the result intact, it produces the following:
```typescript
{
    path: ":slug",
    loadChildren: "./app-content/app-content.module#AppContentModule"
}
```

Which ends up breaking my app with the message: 
```
EXCEPTION: Uncaught (in promise): Error: Cannot find module './app-content/app-content.module'.
```

For now I am "lazy loading" the module by doing the manual import of the module and using it in the `loadChildren` option, but as far as I know, that's not lazy loading a module per se. (Correct me if I am wrong)

Do you guys know how can I make this loader work with an `npm link`ed dependency?
Thanks in advance.

Webpack@2.2.1
angular-router-loader@0.5.0

**Comment by simon04** [comment]
Issues here are not meant for Q&A. For questions use https://gitter.im/webpack/webpack or https://stackoverflow.com/questions/tagged/webpack. Or also refer to the angular-router-loader project.
