### ISSUE TITLE
number in vote app to big for styling

### ISSUE THREAD

**Issue by sokra** [webpack/webpack.js.org#918]
![image](https://cloud.githubusercontent.com/assets/1365881/23115739/20617d8e-f747-11e6-83fa-900dc55b5295.png)

**Comment by sokra** [comment]
maybe we can go with `112k` and `67k` if the number is higher than `1k`

**Comment by Dajust** [comment]
I think that would make the voting not transparent enough, which I think is the main purpose of voting.

**Comment by skipjack** [comment]
This issue was moved to webpack-contrib/voting-app#1
