### ISSUE TITLE
Proposal: Make Sidebar anchor links not reload/refresh page.

### ISSUE THREAD

**Issue by Dajust** [webpack/webpack.js.org#924]
All Sidebar links pointing to anchors in the **current** page should only have URL fragments in their `href` attribute `<a href="#example">`.

 For example, when I'm in _https://webpack.js.org/concepts/loaders/_, clicking **Example**, under **Loaders**, on the Sidebar, should not reload the page because I'm already on the page. It should simply take me to **Example** section of the page

### Solution

In the `sidebar-item.jsx`, line 21 - 30, utilizing the title props, the `sidebar-item` component should be able to determine when to render the full anchor URL or only the `anchor.id`. 
Render either this 
`<a href={ anchorUrl + anchor.id }>{ anchor.title}</a>`, 
or  this 
`<a href={anchor.id }>{ anchor.title}</a>`

Can I help? :hand:

**Comment by skipjack** [comment]
I think there's an existing issue re this: #530. I think @bebraw was talking about doing this at the `antwar` level so you might want to talk to him. With that said though, what you propose seems like how it would be fixed.

**Comment by Dajust** [comment]
@bebraw Can I PR this solution?

**Comment by bebraw** [comment]
@Dajust Sure.
