### ISSUE TITLE
Be able to sort articles inside of a folder (indexing system, etc.)

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#93]
As a documentation writer, I should have the ability to change the sorting display on the sidebar, so that articles that flow together can be adjacent to each other.  cc @bebraw

**Comment by bebraw** [comment]
Yeah, we should agree on a way to approach this. A linked list would work. If you could add `next` field to meta and point to slug through that, that would be enough for sorting. Other ideas are welcome.

**Comment by gregvenech** [comment]
Yeah I noticed this issue too when working on the Sidebar component. `next` might work or maybe an `order` field with the `title` in each article with a number determining the position. I can update #79 with a fix for this once the `pages` array is updated.
