### ISSUE TITLE
Port webpack wiki content to the site and close the wiki

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#935]
See https://github.com/webpack/webpack/wiki . There are some old, but potentially articles there. That information should be moved to the site and the wiki should be closed.

**Comment by skipjack** [comment]
Just went through those and it seems most have already been moved, are deprecated, or don't contain much useful. The only ones I saw that may be of interest were the one on [localization](https://github.com/webpack/webpack/wiki/Recipe-Localization) and the [loader spec](https://github.com/webpack/webpack/wiki/Loader-Specification) though that one appears to be deprecated as well?

Did you have any particular ones in mind?

**Comment by bebraw** [comment]
Yeah, let's close this. I think we've reached more or less parity with the old content.

I suppose we should look into closing the old wiki at some point but there's no rush with that.
