### ISSUE TITLE
Guides - Load Polyfills on Demand

### ISSUE THREAD

**Issue by yurlovm** [webpack/webpack.js.org#938]
It would be great if there was an article in documentation which explained main strategies how to load polyfills for ES2016 only when browser not supported it and skip them for evergreen browsers.

**Comment by TheLarkInn** [comment]
I think we can use some of the material @hzoo has written up for babel and babel-preset-env. This could be a nice article.

**Comment by hzoo** [comment]
Yeah can check out the readme: https://github.com/babel/babel-preset-env#usebuiltins

http://www.2ality.com/2017/02/babel-preset-env.html just got published based on that too

**Comment by skipjack** [comment]
If it's not a huge amount of content maybe a nice little section in the [shimming guide](https://webpack.js.org/guides/shimming) would do? If not, let's create a new guide and maybe create a "shimming and polyfilling" group within the __Guides__ section (grouping would be tackled separately in #438).

**Comment by jeremenichelli** [comment]
Has someone taken this? I think is a pretty simple guide to add and I already did that in some projects in my current job so it won't be hard for me.

**Comment by skipjack** [comment]
No one's claimed it, please feel free to pick it up!

**Comment by jeremenichelli** [comment]
Good, I'm going to get into this next week probably.

**Comment by jeremenichelli** [comment]
Everyone, I'm gonna give it a try and add it to the shimming section since I think _it belongs there_. I'll try to keep it small, if I fail we can always move it to its own section and add more content and references.

PR coming soon!
