### ISSUE TITLE
Ability to tie related articles via metadata or md metadata.

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#94]
As a content author, I would like to tie relevant API documentation, and further readings on pages. so that they show up in a consistent manner simply by updating markdown metadata.

**Comment by skipjack** [comment]
Hmmm, I know this is old but kind similarly the `contributors` metadata? I think I could probably tackle this one, I know there's already a few sections manually following this paradigm (e.g. a `# Related Articles` section at the bottom).

**Comment by skipjack** [comment]
@TheLarkInn I can work on this one this week. Let me know if I have the right idea here:

__article.md__

``` md
---
title: Article
contributors:
  - skipjack
links:
  - Typechecking with PropTypes | https://facebook.github.io/react/docs/typechecking-with-proptypes.html
---
```

__browser__

> # Article
> ...
> ## Further Reading
> - [Type checking with PropTypes](https://facebook.github.io/react/docs/typechecking-with-proptypes.html)
> ## Contributors
> ...

Something like that work? Any ideas for a easier delimiting each link/title pair aside from the `|`? I'm not too well versed in front-matter so if there's an easier built-in trick to do this, pls let me know.
