### ISSUE TITLE
Guides - Managing Built Files

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack.js.org#949]
> aka "intro to why you should use html-webpack-plugin"

Based on feedback from [twitter](https://twitter.com/karljakoblind/status/834820883415961600):

> the new docs. Main confusion for me was i included generated files in wrong order and got not helpful error msg

Few brainstorming options but I think that we should essentially recommend heavily the use of html-webpack-plugin and why. (Explain the whole managing new build files that are hashed every time, ensuring they are output in correct order, etc)

**Comment by skipjack** [comment]
@TheLarkInn I agree completely, the `html-webpack-plugin` and things like `copy-webpack-plugin` both help in not having any manually managed files in your `/dist` or `/build` folder. Definitely makes managing and including auto-generated files easier, a simpler `.gitignore`, and I also think it's much easier to explain a project when you can just say:

> All work is done in this or these `/src` directory, you never have to touch anything in `/dist`.

When I first started using webpack I definitely saw a lot of examples using manually-managed `index.html` (and other) files within the build directory which is the initial approach I took as well. Only within the last few months did I stumble upon the `html-webpack-plugin` and `html-webpack-template` projects which have definitely made things much easier, and, when it comes to using hashes in the filenames, you pretty much have to use some automated solution.

**Comment by skipjack** [comment]
@TheLarkInn mind if I take a stab at this? I've used the html-webpack-plugin and html-webpack-template a fair amount at this point. I might need someone to help explain the manifest and give some examples but I could probably get something started.

**Comment by TheLarkInn** [comment]
This would be great! Feel free and take it!

**Comment by skipjack** [comment]
Ah cool, wasn't aware of that plugin.
