### ISSUE TITLE
source-map-loader as loader for tsx files should be ts-loader

### ISSUE THREAD

**Issue by ricksecretin** [webpack/webpack.js.org#965]
While following this tutorial: https://webpack.js.org/guides/webpack-and-typescript/ I noticed there is something wrong in the webpack.config.js file in the docs. 

The loader for tsx files should be 'ts-loader', not 'source-map-loader'.

Regards,

Rick

**Comment by simon04** [comment]
See https://github.com/webpack/webpack.js.org/pull/969#issuecomment-283576288 and https://github.com/webpack/webpack.js.org/pull/969#issuecomment-283579388.
