### ISSUE TITLE
Typescript + Tree shaking configuration

### ISSUE THREAD

**Issue by dmitriid** [webpack/webpack.js.org#995]
Relevant page: https://webpack.js.org/guides/webpack-and-typescript/

If I understand this correctly, this setup will not trigger webpack's tree shaking algorithm, because the loader will produce a CommonJS-stye `require`, not static `import`s required by [tree shaking](https://webpack.js.org/guides/tree-shaking/).

If I'm correct, something like this should be used for tree shaking:

----

1. `npm install babel-core babel-preset-es2015`
2. Add `.babelrc` with 

```
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ]
  ]
}
```

3. `tsconfig.json` should be set to `es6`

```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "es6",
    "target": "es6",
    "jsx": "react",
    "allowJs": true
  }
}
```

4. webpack.config should invoke both loaders:

```
module.exports = {
 entry: './index.ts',
 output: {
   filename: 'bundle.js',
   path: __dirname
 },
 module: {
   rules: [
     {
       test: /\.tsx?$/,
       use: ['babel-loader', 'ts-loader']
       exclude: /node_modules/,
     },
   ]
 },
 resolve: {
   extensions: [".tsx", ".ts", ".js"]
 },
};
```

(Note, `loaders` should be replaced by `use`)

**Comment by skipjack** [comment]
@webpack/documentation-team can anyone familiar with typescript environments confirm this?

@dmitriid maybe we add a note or warning regarding typescript in the main tree-shaking guide, and change the example in the webpack and typescript guide if your proposed solution is confirmed?

**Comment by bebraw** [comment]
Yeah, if you lose ES6 module definitions, there's no way tree shaking can work. That's correct.

**Comment by skipjack** [comment]
Ok great, @dmitriid would you be interested in pr-ing these changes?

**Comment by dmitriid** [comment]
@skipjack 

I'll try to do this today

**Comment by dmitriid** [comment]
As usual, life interfered :) And it only took me 5 days :)

**Comment by slashhuang** [comment]
@skipjack  came across the same problem, hope @dmitriid's merge request solved this tree shaking issue for ts project using webpack

**Comment by JounQin** [comment]
What about working with `webpack.config.ts`?
It seems that it will throw an error about `import` syntax in `webpack.config.ts` if `module` is `es6` in `tsconfig.json`.

**Comment by geirsagberg** [comment]
@JounQin yeah you have to use node-style requires if you have `module` set to `es6` or `es2015`. No way around it as long as your `webpack.config.ts` is using the same `tsconfig.json` as your app code.

**Comment by JounQin** [comment]
@geirsagberg I found a workaroud: move `tsconfig.json` into my `src` folder rather than cwd directly. That works for me😃.

**Comment by dmitriid** [comment]
For anyone still watching this issue, the config I provided no longer works. I have no idea what's broken and how to fix it, but you *will* end up with `error TS2307: Cannot find module 'react'`.

**Comment by kadishmal** [comment]
The link at the top is broken. The new link is https://webpack.js.org/guides/typescript/.

**Comment by Crisfole** [comment]
This content is no longer present on the Webpack.js website. Is it out of date, or just accidentally dropped?

**Comment by dmitriid** [comment]
@Crisfole It's quite possible that the current setup instructions (including those on TS site) are enough. Can't verify this, unfortunately, as I no longer have a TypeScript setup

**Comment by MadhuvanthG** [comment]
> This content is no longer present on the Webpack.js website. Is it out of date, or just accidentally dropped?

I'm too late, but might help someone landing here. I think, the page has just been modified a bit over time. This I believe, is the page you're looking for.
https://webpack.js.org/guides/typescript/#basic-setup
