### ISSUE TITLE
hmr-react.md  index.js: Module build failed: SyntaxError, Unexpected token

### ISSUE THREAD

**Issue by juan-urtazun** [webpack/webpack.js.org#996]
Hi, I'm start a example project based on hmr-react.md  guide, but on run npm start, i'm getting error:
/src/index.js: Unexpected token (11:4)
   9 | const render = (Component) => {
  10 |   ReactDOM.render(
> 11 |     <AppContainer>
     |     ^
  12 |       <Component/>
  13 |     </AppContainer>,
  14 |     document.getElementById('root')

I can't figure out what is happening.

Someone can help me?
Thanks

**Comment by scottdj92** [comment]
Are you having issues running your project, or this repo? This repo contains documentation for webpack.

**Comment by juan-urtazun** [comment]
I've been experiencing those issues while following this guide to set up my own project.
My project has the same structure and files that propose this guide and nothing else.

**Comment by scottdj92** [comment]
Can you share your repo, so I can give it a look-see?

**Comment by juan-urtazun** [comment]
Hi, thanks for your help. 
The problem was a typo in .babelrc config.
If anyone wants to try or experiment,  this is the repo https://github.com/juan-urtazun/react-webpack-hmr/tree/master

**Comment by scottdj92** [comment]
@juan-urtazun, I cloned your repo and was able to run it.

Glad to hear that you fixed it :D
